DataDog/system-tests

tests/appsec/waf/test_addresses.py
GRPC threat tests should be in the grpc threat management feature only
remove them from the appsec_request_blocking feature (which is http only)
=> feature update

utils/build/docker/dotnet/poc.Dockerfile, utils/build/docker/dotnet/uds.Dockerfile
The binaries folder wasn't properly copied (only files and not folders) when testing locally with imported built binaries (monitoring home).
Change the way how the binaries folder is copied in the dockerfile.
=> [dotnet] Fix binaries copy folder

manifests/java.yml, tests/appsec/iast/sink/test_weak_hash.py, tests/appsec/test_asm_standalone.py
Remove xpassed IAST and ASM standalone billing tests 
=> Remove IAST and ASM standalone billing java xpassed tests

manifests/dotnet.yml, manifests/golang.yml, manifests/java.yml, manifests/nodejs.yml, manifests/php.yml, manifests/python.yml, manifests/ruby.yml, tests/appsec/waf/test_addresses.py
`Test_ClientIP ` and `Test_Method` are already covered by `tests/appsec/test_blocking_addresses.py`
`Test_Lambda` is deprecated
`test_raw_body` is currently irrelevant but it is planned to use it in another not started initiative.
Remove deprecated test class
put irrelevant class in irrelevant mode.
🛟 …
=> remove outdated tests

.github/workflows/run-end-to-end.yml
Better CI output. When a scenario fails, the replay mode will fail also. But on a click on the job, the link goes to the replay mode, which is very dense, and not easy to read (and also, possibly, not the same error message).
When a scenario fails, do not execute replay mode
🛟 …
=> Do not execute replay if a scenario failed

utils/properties_serialization.py
When `replay` mode fails to find `setup_properties.json` (either because the scenario did not run, or because there is an INTERNALERROR  in the process that generate the log, stdout looks like : 
It's totally cryptic.
Now, it looks like : 
=> Better error message when replay mode fails to find setup_properties.json

manifests/dotnet.yml, manifests/golang.yml, manifests/java.yml, manifests/nodejs.yml, manifests/php.yml, manifests/python.yml, manifests/ruby.yml
To avoid missing feature report on non existing features, we should put the test in irrelevant mode.
mark `Test_API_Security_RC_ASM_processor_overrides_and_custom_scanner` as irrelevant. (no custom scanners for now)
=> irrelevant test: no custom scanners

run.sh
`run.sh` fails in bash 3 with the following error:
```
/run.sh: line 236: scenario_args[@]: unbound variable
```
bash 3 considers `${arr[@]}` as unbound rather than empty. 
This happens in macOS, which ships old bash. Users can get a newer bash with `brew install bash` (and I would recommend this), but we can fix the script by checking array length first.
Checks array length to avoid unbound variable error in bash 3.
* ~[ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change~
=> Fix run.sh for bash 3 (macOS)

tests/appsec/api_security/test_schemas.py
The dev version artifact of the PHP lib got a invalid version, so skipping this test for all version
=> [php] full skip for APPSEC-53993

docs/weblog/README.md, tests/appsec/iast/source/test_cookie_name.py, utils/build/docker/java/akka-http/src/main/scala/com/datadoghq/akka_http/IastRoutes.scala, utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/IastSourceResource.java, utils/build/docker/java/resteasy-netty3/src/main/java/com/datadoghq/resteasy/IastSourceResource.java, utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/AppSecIastSource.java, utils/build/docker/java/vertx3/src/main/java/com/datadoghq/vertx3/iast/routes/IastSourceRouteProvider.java, utils/build/docker/java/vertx4/src/main/java/com/datadoghq/vertx4/iast/routes/IastSourceRouteProvider.java, utils/build/docker/python/django/app/urls.py, utils/build/docker/python/fastapi/main.py, utils/build/docker/python/flask/app.py
With the [latest changes](https://github.com/DataDog/experimental/pull/3483), it has been decided to redact IAST keys of the vulnerabilitjies, such as "user" or "username". This would affect the existing system tests that use these keys. In particular the test that checks the tainting of the cookie names had to change the key of the cookie to, table, which is not redacted. …
=> Change user to table in cookie IAST name tests

manifests/cpp.yml, manifests/java.yml, manifests/php.yml, manifests/ruby.yml, tests/stats/test_miscs.py, utils/_context/_scenarios/__init__.py, utils/interfaces/_core.py, utils/interfaces/schemas/miscs/telemetry/v2/objects/configuration.json, utils/proxy/_deserializer.py
Test client side stats computation
* activate stats computation on default scenario
* add `object` in valid types for configuration value in telemetry request (to be validated)
*  deserialize payload for `/v0.6/stats` requests
* add a basic check on header on the above request (currently failing on go)
🛟 …
=> Client stats test skeleton

utils/_context/containers.py
Fix SQL Server healthcheck in systems with IPv6.  In CircleCI we are getting this error:
```
2024/07/11 13:35:18 [launchpadd] WARNING: Failed to connect to SQL because: dial tcp [::1]:1431: getsockopt: connection refused, will reattempt connection.
```
Using `127.0.0.1` instead of `localhost` to fix the issue where IPv6 loopback interface exists. …
=> Fix SQL Server healthcheck in systems with IPv6

utils/build/virtual_machine/provisions/auto-inject/auto-inject-prepare_repos.yml, utils/build/virtual_machine/provisions/auto-inject/repositories/rpm/datadog-stable.aarch64.repo, utils/build/virtual_machine/provisions/auto-inject/repositories/rpm/datadog-stable.x86_64.repo, utils/build/virtual_machine/provisions/auto-inject/repositories/rpm/datadog-staging.aarch64.repo, utils/build/virtual_machine/provisions/auto-inject/repositories/rpm/datadog-staging.x86_64.repo
Tests failing
Add previous current (now old) GPG keys to be able to install older deb/rpm packages
=> fix(injection): Add old GPG keys

.github/actions/pull_images/action.yml
The cleanup step takes most of the time of the job and is not needed when using larger runners which have more disk space ([600GB](https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners#specifications-for-general-larger-runners) vs [14GB](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories)).
With the cleanup, the `pull_images` job takes 5-15 minutes for `INTEGRATIONS`. Without the cleanup, it takes ~30 seconds.
Make disk cleanup optional when pulling images.
3. Mark it as ready …
=> make disk cleanup optional when pulling images

utils/build/docker/nodejs/nextjs/.babelrc, utils/build/docker/nodejs/nextjs/next.config.js
SWC is much faster and is the default since Next 13, no reason to keep using the slower legacy tooling.
Switch to SWC instead of Babel and Terser for bundling.
=> [nodejs] switch nextjs to swc instead of babel+terser for bundling

tests/parametric/conftest.py, tests/parametric/test_trace_sampling.py, utils/_context/_scenarios/parametric.py
=> Reduce flakyness of parametric tests

tests/stats/test_miscs.py, utils/build/docker/set-system-tests-weblog-env.Dockerfile
=> Do not activate stats by default on weblogs

manifests/java.yml, tests/appsec/test_automated_login_events.py, utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/security/AppSecSdkToken.java
The version was badly formatted causing the test to XPASS instead of PASS
=> [java] Fix wrong version schema in header related tests

.github/workflows/ci.yml, .github/workflows/run-parametric.yml, conftest.py, docs/execute/troubleshooting.md, manifests/ruby.yml, requirements.txt, run.sh, tests/parametric/conftest.py, tests/parametric/test_dynamic_configuration.py, utils/_context/_scenarios/parametric.py, utils/parametric/_library_client.py
Fixes #2734
Parametric tests needs two port for each test that being executed. The current solution open a socket, get the port, closes the socket, run the test. Be between the moment we close the socket, and we start the test, the port can be allocated to anything else.
The issue is that, as we use `xdist` to run tests in parallel, and as we use 16-cores machine, the probability of having a port picked by two `xdist` runner is close to 1.
Let docker pick an available port.
* Framework is modified, or non …
=> Let docker choose an host port 

tests/appsec/rasp/test_stack_traces.py
DataDog/dd-trace-dotnet#5779 moved appsec data from json to meta_struct
Adapt the RASP test to look for appsec data in both locations.
=> Fix RASP test : look for AppSec data in meta_struct

utils/build/docker/nodejs/express4-typescript/iast.ts, utils/build/docker/nodejs/express4/iast/sources.js
kafka flaky tests
When tests fail, there are errors like 
```json
{"level":"ERROR","timestamp":"2024-07-12T08:42:13.796Z","logger":"kafkajs","message":"[Connection] Response Heartbeat(key: 12, version: 3)","broker":"kafka:9092","clientId":"my-app-iast","error":"The group is rebalancing, so a rejoin is needed","correlationId":9,"size":10}
```
so try configuring a heartbeat for the consumers …
=> [nodejs] try fix iast kafka flaky tests

utils/build/virtual_machine/provisions/auto-inject/auto-inject-environment.yml, utils/build/virtual_machine/provisions/auto-inject/auto-inject_init_vm_config.yml, utils/build/virtual_machine/provisions/auto-inject/docker/auto-inject_prepare_docker.yml, utils/build/virtual_machine/provisions/auto-inject/repositories/autoinstall/execute_install_script.sh, utils/build/virtual_machine/provisions/host-auto-inject-install-script/auto-inject_host_script.yml, utils/build/virtual_machine/provisions/host-auto-inject-install-script/provision.yml, utils/build/virtual_machine/weblogs/common/create_and_run_app_container.sh, utils/build/virtual_machine/weblogs/dotnet/provision_test-app-dotnet-container.yml, utils/build/virtual_machine/weblogs/java/provision_test-app-java-alpine-jdk15.yml, utils/build/virtual_machine/weblogs/java/provision_test-app-java-alpine-jdk21.yml, utils/build/virtual_machine/weblogs/java/provision_test-app-java-alpine-libgcc.yml, utils/build/virtual_machine/weblogs/java/provision_test-app-java-alpine.yml, utils/build/virtual_machine/weblogs/java/provision_test-app-java-buildpack.yml, utils/build/virtual_machine/weblogs/java/provision_test-app-java-container-jdk15.yml, utils/build/virtual_machine/weblogs/java/provision_test-app-java-container.yml, utils/build/virtual_machine/weblogs/java/provision_test-app-java.yml, utils/build/virtual_machine/weblogs/java/provision_test-shell-script.yml, utils/build/virtual_machine/weblogs/nodejs/provision_test-app-nodejs-alpine-libgcc.yml, utils/build/virtual_machine/weblogs/nodejs/provision_test-app-nodejs-alpine.yml, utils/build/virtual_machine/weblogs/nodejs/provision_test-app-nodejs-container.yml, utils/build/virtual_machine/weblogs/nodejs/provision_test-shell-script.yml, utils/build/virtual_machine/weblogs/python/provision_test-app-python-alpine-libgcc.yml, utils/build/virtual_machine/weblogs/python/provision_test-app-python-alpine.yml, utils/build/virtual_machine/weblogs/python/provision_test-app-python-container.yml, utils/build/virtual_machine/weblogs/python/provision_test-app-python.yml, utils/build/virtual_machine/weblogs/python/provision_test-shell-script.yml, utils/build/virtual_machine/weblogs/ruby/provision_test-app-ruby-container.yml, utils/build/virtual_machine/weblogs/ruby/provision_test-app-ruby.yml, utils/build/virtual_machine/weblogs/ruby/provision_test-shell-script.yml
Re-enabling CentOS and AmazonLinux where possible
Example pipeline: https://gitlab.ddbuild.io/DataDog/system-tests/-/pipelines/39523619
- Fixed CentOS mirrors issues
- Fixed docker by starting it right before it's needed
- Remove dependency on the "apm" apt / yum repo as it's not needed anymore and prevented the installer from being installed. This was breaking CentOS because of compatibility issues with the latest deb
- Cleanup …
=> chore(injection): Re-enable disabled weblogs

.github/CODEOWNERS
@DataDog/apm-sdk-api is a frequent maintainer of parametric tests and is responsible for many of the features that parametric tests are meant to exercise
Updates CODEOWNERS to include @DataDog/apm-sdk-api for parametric tests
=> Add APM SDK API team as CODEOWNERS for parametric tests

tests/parametric/conftest.py, utils/parametric/_library_client.py, utils/scripts/compute_impacted_scenario.py
libraries that use legacy gRPC interface for parametric tests are very flaky. We don't know why the gRPC server did not respond
Add container logs when gRPC interface fails to respond
Also a small revamp of get-impacted-scenario
=> Better output for PARAMETRIC gRPC timeouts

utils/_context/_scenarios/parametric.py
=> [python] Give mor time for dd-trace-py to build

tests/appsec/api_security/test_schemas.py
=> [php] Remove flaky flag from schema extraction tests on php

manifests/dotnet.yml, utils/build/docker/dotnet/weblog/Endpoints/RequestDownStreamEndpoint.cs, utils/build/docker/dotnet/weblog/Endpoints/ReturnHeadersEndpoint.cs
Enable ASM Standalone tests for the dotnet tracer.
=> [.NET][ASM] Enable tests for ASM Standalone Billing for dotnet

utils/_context/_scenarios/core.py, utils/_context/containers.py, utils/proxy/core.py
The agent sent in its configuration a boolean linked to the `span_meta_structs` to advertise its compatibility to meta struct.
In part of the [RFC Security events in meta struct](https://docs.google.com/document/d/1iWQsOfT6Lg_IFyvQeqry9wVmXOE2Yav0X4MgOTk7mks/edit#heading=h.o5gstqo08gu5), we want a way to test when this meta struct compatibility is not available from the agent.
Added a new environment variable `SYSTEM_TESTS_AGENT_SPAN_META_STRUCTS_DISABLED` for the system tests internals.
Add this env var to the config of ProxyContainer and bubble it up to the configuration of the scenario (`meta_structs_disabled` argument)
When it's value is set to `true`, the [`/info`](https://datadoghq.atlassian.net/wiki/spaces/SAAL/pages/2420244556/Trace+Agent+Discovery+mechanisms) endpoint will not …
=> Ability to change the support state of meta struct of the agent

tests/appsec/test_asm_standalone.py
=> [python] Skip failing test in appsec_standalone scenario

tests/appsec/waf/test_reports.py
=> [nodejs] skip failing test for nodejs@5.18.0

tests/debugger/test_debugger_expression_language.py
It was decided to return error, when isEmpty operator is applied on null entity.
This PR removes redundant test.
=> [Debugger] Remove expression language isEmpty test for null

tests/appsec/waf/test_reports.py, utils/build/docker/nodejs/express4-typescript/app.ts, utils/build/docker/nodejs/express4/app.js
Try whether increasing the tracer flushing interval mitigates the `Maximum number of active requests reached` error.
=> [nodejs] Increase flush interval

tests/test_the_test/test_docker_scenario.py, utils/_context/_scenarios/core.py, utils/_context/containers.py
Following #2732, the output when a container fails to start is messy
Check for health only in main thread, and exit if one of them is not healthy, whit convenient infos and no noise in stdout.
=> Better output when some container fails to start

utils/_context/_scenarios/parametric.py
I'm done downloading the Java tracer 1.35.2 as the "latest". It's definitely not the latest since... June 27th.
add --no-cache to the wget command we use to download the lastest java tracer 
=> [Java] Get the real latest java tracer (--no-cache)

manifests/java.yml
To extend test coverage we need to enable SQLi tests for Exploit Prevention
Enabled SQLi tests for Java tracer v1.38.0
=> [java] Enabled Exploit Prevention SQLi

tests/parametric/test_dynamic_configuration.py
Another test is failing, very probably linked to APMAPI-179
Also flagging them as flaky, as the failure is not systematic
=> [dotnet] Another failing test for APMAPI-179

tests/appsec/test_runtime_activation.py
Remote Configuration tests should be in the Remote Configuration Rule Changes Feature.
APPSEC-54105
=> move RC tests to RC feature

tests/parametric/test_telemetry.py
The [RFC](https://docs.google.com/document/d/1gtdjhsMSIvuTnM9E4EreI7oZ-bAUoAxkhXX0-fBvdDY/edit?usp=sharing) has been revised since these tests were written
Note: these tests are currently marked with `@missing_feature` for all languages.
Updates the expected telemetry tags when reporting OTel env-var mapping issues:
```
config.datadog       -> config_datadog
config.opentelemetry -> config_opentelemetry
```
The expected tag values should also be lower-case.
* Framework is modified, or non obvious usage of it …
=> Update the expected telemetry tags for OTel env-var mapping

utils/_context/_scenarios/__init__.py
Waiting 100 seconds seems like a lot, especially since it should be possible to get the remote config from client libraries in milliseconds.
Lower library interface timeout for remote config tests.
=> lower library interface timeout for remote config tests

manifests/python.yml, tests/appsec/test_asm_standalone.py
asm standalone test are not enabled
- fix a typo to enable them
- remove bug decorator
=> [python] fix typo in version for python manifest 

tests/auto_inject/test_auto_inject_install.py, utils/build/virtual_machine/provisions/auto-inject-ld-preload/main.c
The previous test was replacing "puts" with a fake function that always outputted the same result. Obviously this broke things.
=> Unskip manual ld preload test

run.sh, utils/build/build.sh
Fix broken dd-trace-py ci and unblock us from merging PRs. 
system-tests steps were failing as `venv/bin` folder contained symlinks to python binary. Passing `--copies` to `venv` will copy instead of symlink. 
Tested on https://github.com/DataDog/dd-trace-py/pull/10062
🛟 …
=> [python] Fix broken dd-trace-py actions CI

utils/build/docker/php/apache-mod/build.sh, utils/build/docker/php/apache-mod/entrypoint.sh, utils/build/docker/php/common/php.ini
dd-trace-php now runs in the helper inside sidecar. This changes a logging setting.
=> [php] Support changes in dd-trace-php/master

.gitlab-ci.yml
Jobs schedules right now are manual (see https://gitlab.ddbuild.io/DataDog/system-tests/-/pipelines/40967293), this PR fixes it (see https://gitlab.ddbuild.io/DataDog/system-tests/-/pipelines/40997565)
Reorder the job rules
=> fix(schedules): Fix job schedules to make them automatic

manifests/python.yml, tests/appsec/rasp/test_shi.py, utils/build/docker/python/django/app/urls.py, utils/build/docker/python/fastapi/main.py, utils/build/docker/python/flask/app.py, utils/interfaces/_library/core.py
Following https://github.com/DataDog/dd-trace-py/pull/10073 and https://github.com/DataDog/dd-trace-py/pull/10098, this PR updates weblogs and enables the new RASP tests for python.
APPSEC-54439
=> Add support for rasp command injection

manifests/java.yml, tests/appsec/test_suspicious_attacker_blocking.py
According to the [RFC](https://docs.google.com/document/d/123wRO_ha5aZMzIXXJlGHobZrK8F4w5YuzyINncIQVLw/edit#heading=h.88xvn2cvs9dt) we have to use ASM_DATA to update exclusion_data via RC.
Update the payloads in the tests to ensure we use ASM_DATA. …
=> fix: suspicious attacker blocking RC payload

tests/appsec/rasp/test_sqli.py, tests/appsec/waf/test_reports.py
Annotate as flaky test_sqli.Test_Sqli_UrlQuery in tests/appsec/rasp/test_sqli.py
Remove flaky annotation from tests/appsec/waf/test_reports.py as was introduced by error in 
https://github.com/DataDog/system-tests/pull/2856/files and https://github.com/DataDog/system-tests/pull/2864
add flaky to tests/appsec/rasp/test_sqli.py and remove it from tests/appsec/waf/test_reports.py …
=> Set @flaky to APPSEC_RASP java vertx

tests/test_semantic_conventions.py
In node we have 2 release lines, v5.x and v4.x, test were failing in v4.x release line blocking the release.
Change node version in `@bug` decorator.
=> [nodejs] Set bug version to lower release line

tests/integrations/test_db_integrations_sql.py
Failing system test [flask-poc](https://github.com/DataDog/dd-trace-py/actions/runs/10324812052/job/28588236676?pr=10064#step:9:134) is blocking [PR](https://github.com/DataDog/dd-trace-py/pull/10064) to add `server.address` tag to database spans.
This one-line PR adds `server.address` as a valid tag in the span, for sql integration tests. …
=> [python] Add server.address tag to db span

.github/workflows/run-end-to-end.yml, tests/appsec/test_ip_blocking_full_denylist.py, tests/appsec/test_remote_config_rule_changes.py, tests/appsec/test_user_blocking_full_denylist.py, tests/remote_config/test_remote_configuration.py
Reenable remote configuration tests on PHP after fixing the bug recently introduced in the main branch.
Related Jira: [APPSEC-54528]
[APPSEC-54528]: https://datadoghq.atlassian.net/browse/APPSEC-54528?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDl …
=> [PHP] Reenable remote configuration tests

tests/appsec/waf/test_blocking.py
=> [java] Enable Test_CustomBlockingResponse in all variants

manifests/php.yml
SCI Tagging was added in the recent 1.2.0 release of the PHP tracer ([Impl](https://github.com/DataDog/dd-trace-php/pull/2731)).
Enable the tests for the now-implemented SCI feature in the PHP traer.
=> tests(php): Enable Test_TracerSCITagging

utils/build/docker/golang/chi.Dockerfile, utils/build/docker/golang/echo.Dockerfile, utils/build/docker/golang/gin.Dockerfile, utils/build/docker/golang/gqlgen.Dockerfile, utils/build/docker/golang/graph-gophers.Dockerfile, utils/build/docker/golang/graphql-go.Dockerfile, utils/build/docker/golang/net-http.Dockerfile, utils/build/docker/golang/uds-echo.Dockerfile
I'm working on importing some datadog agent code in dd-trace-go, this upgrade will bring dd-trace-go to using 1.22. According to the published support policy in the README this should be OK as 1.23 has already been released (meaning 1.21 is no longer supported)
🛟 …
=> [go] Bump golang to 1.22

tests/test_telemetry.py
=> [nodejs] Skip failing test for APMAPI-213

tests/parametric/test_otel_span_methods.py
[AIDM-162](https://datadoghq.atlassian.net/browse/AIDM-162)
The [1.2.0 release](https://github.com/DataDog/dd-trace-php/releases/tag/1.2.0) of the PHP tracer was made, which now includes the [required mapping changes](https://github.com/DataDog/dd-trace-php/pull/2717). This PR enables the test.
Additionally, it also enables an OTel test that should have been enabled at the beginning. …
=> tests: Enable some OTel PHP tests

tests/appsec/iast/source/test_kafka_key.py, tests/appsec/iast/source/test_kafka_value.py, utils/build/docker/nodejs/express4-typescript/iast.ts, utils/build/docker/nodejs/express4/iast/sources.js
flaky iast kafka tests are still with us.
Let's see if this is the definitive one 🤞
- use different consumer groups
- consume messages from the beginning
=> [nodejs] Iast kafka flaky tests again

tests/k8s_lib_injection/conftest.py
Sometimes when we shutdown the tests, errors arise trying to destroy the k8s cluster. Ignore errors and continue...
=> K8s Lib Injection. Ignore errors on destroy

manifests/dotnet.yml, tests/parametric/test_crashtracking.py
Enable all crashtracking tests for .NET
=> Enable all crashtracking tests for .NET

utils/_context/_scenarios/__init__.py, utils/_context/_scenarios/k8s_lib_injection.py
Extract K8s lib injection scenarios to separate file
=> K8s Lib Injection: Extract scenario

tests/test_telemetry.py
This test was checking each delay between all heartbeat. There are lot of reason in an uncontrolled environment for having one delay not respecting the spec. 
Check the average delay, rather each individual delay, to reduce flakiness 
=> Check average heartbeat delay for telemetry (APMAPI-224 and AIT-9176)

tests/test_telemetry.py
Following #2908 , improve heartbeat tests, and reskip it for node.
=> AIT-9176 split heartbeat test in two separated tests

tests/appsec/iast/source/test_parameter_value.py
IAST parameter value test was marked as bug long time ago but it's irrelevant for some python frameworks
Related to: https://github.com/DataDog/dd-trace-py/pull/10331
=> [Python] mark iast parameter value test as irrelevant

utils/_context/containers.py
When the postgres container fail to start, the error is cryptic. With this change, the output will make the error obvious
Per title. Not related with golang, it's only here to save some CI time
=> [golang] Add an healthcheck to postgres container

.github/workflows/ci.yml, .github/workflows/run-end-to-end.yml, .github/workflows/run-graphql.yml, .github/workflows/run-parametric.yml, conftest.py, docs/CI/github-actions.md, utils/_context/_scenarios/parametric.py
DevX, and export to feature parity dashbaord
* set a weblog variant name for parametric scenarios
* Add `-L` option as an alternative for env var `TEST_LIBRARY`
=> Small improvments on parametric tests

manifests/java.yml, tests/debugger/test_debugger_exception_replay.py
Fix java exception replay inconsistency by adding `wait for snapshot` functionality.
=> [Debugger] Fix java exception replay inconsistency

tests/debugger/test_debugger_exception_replay.py
https://github.com/DataDog/system-tests/actions/runs/10581964322/job/29320956211?pr=2933#step:59:98
The current function assumes that `method` always exists in `probe.location`, which is not always true
Do no assumes that `method` exists. Even checks its type.
🛟 …
=> More resilient logic for _wait_for_snapshot_received

.github/CODEOWNERS
=> Add DataDog/libdatadog-telemetry as owner for telemetry test file

format.sh
The format script could not fix the trailing whitespaces.
Example:
```
Checking tailing whitespaces...
./format.sh: line 76: [: ./utils/build/docker/nodejs/express4-typescript/app.ts: unary operator expected
./format.sh: line 76: [: ./utils/build/docker/nodejs/express4-typescript/app.ts: unary operator expected
All good, the system-tests CI will be happy! ✨ 🍰 ✨
```
Add quote to the variable. …
=> Fix format script when trailing white spaces 

manifests/java.yml, tests/appsec/rasp/test_sqli.py
[APPSEC-54578](https://datadoghq.atlassian.net/browse/APPSEC-54578)
* Set RASP SQLi tests to v1.39.0. This was released in v1.38.0, disabled by default, but was flaky. Effectively, we'll want to consider v1.39.0 the first release with RASP SQLi support.
* Enable all tests for RASP SQLi in Java.
🛟 …
=> [java] enable RASP SQLi tests

utils/build/docker/python/uwsgi-poc.Dockerfile
ddtrace-run have known incompatibilities with uwsgi
replace it with importing boostrap from tracer.
=> [python] drop ddtrace-run on uwsgi

.github/workflows/run-end-to-end.yml, utils/_context/containers.py
CI was freezing
* [Add a max time of 2s to curl healthcheck commands](https://github.com/DataDog/system-tests/commit/d781ec210842ee91314d8bb1f886f82366c6f5b6) : if for some reason the webserver does not reject the request, but freezes, the default timeout for curl is 15mn. the healtheck tries 60 times -> 15 hours before failure.
* [skip APPSEC_MISSING_RULES for ruby (APPSEC-54708)](https://github.com/DataDog/system-tests/commit/8087741aec3fe36c49bf7025b23c8e84d8fd1593)
* Framework is modified, or non …
=> Skip APPSEC_MISSING_RULE for ruby APPSEC-54708

.gitlab-ci.yml, tests/auto_inject/test_auto_inject_blocklist.py, utils/build/virtual_machine/weblogs/php/provision_test-shell-script.yml
Enable more PHP tests.
They are passing: https://gitlab.ddbuild.io/DataDog/system-tests/-/pipelines/43353183
=> Enable more PHP onboarding tests

manifests/php.yml, tests/parametric/test_crashtracking.py, utils/build/docker/php/parametric/server.php
Enable one more test
:warning: CI failures seem unrelated
=> PHP: Enable test Test_Crashtracking::test_report_crash

utils/build/docker/java/parametric/install_ddtrace.sh
Moving away from gRPC server to Spring Boot web server slowed Java parametric tests
This PR improves parametric Java client app startup by 
* Extracting application to improve class lookup
* Creating CDS archive for faster warmup
=> [java] Improve parametric Java client app start

manifests/java.yml
We found a context propagation bug in case if tracer is running in async frameworks (vertx)
RASP SQLi tests for vertx marked as bug
=> [java] RASP SQLi tests for vertx marked as bug

utils/build/docker/java/parametric/run.sh
We got random failures:
```
FAILED tests/parametric/test_dynamic_configuration.py::TestDynamicConfigSamplingRules::test_trace_sampling_rules_with_tags[library_env0]
= 1 failed, 306 passed, 16 skipped, 72 xfailed, 12 xpassed in 558.37s (0:09:18) =
```
AppSec process monitoring was unexpected creating span when Crash Tracking sets up as it runs a JPS command.
I disabled the AppSec process monitoring integration. …
=> [java] Fix Java parametric test flakiness

utils/_context/_scenarios/parametric.py
Enabled in https://github.com/DataDog/system-tests/pull/2961, but is flaky:
- https://github.com/DataDog/system-tests/actions/runs/10686189202/job/29620824384
- https://app.circleci.com/pipelines/github/DataDog/dd-trace-php/17340/workflows/ee976c13-0e1e-4606-a0e3-b8ce4f811486/jobs/5088330/steps
My guess (since I can't reproduce the issue locally), is that when the PHP process (PID 1) is killed by a SIGSEGV signal, the Docker container is almost immediately stopped. This abrupt shutdown likely terminates the 'sidecar' process before it can upload the report. Adding a delay seems to fix the issue
* Test logic is modified? …
=> [php] Fix flaky test Test_Crashtracking::test_report_crash

manifests/java.yml
Enabled RASP SQLi tests for vertx
=> Enabled RASP SQLi tests for vertx

tests/integrations/test_dbm.py
This is the PR that will fix system tests after https://github.com/DataDog/dd-trace-dotnet/pull/5859 is merged
We're adding support for full injection for MS SQL queries in dotnet. Thus, we need to assert that it's done in the system test.
=> add condition in DBM MSSQL to check full mode + temp disable

utils/build/docker/python/django-poc.base.Dockerfile, utils/build/docker/python/fastapi.base.Dockerfile, utils/build/docker/python/flask-poc.base.Dockerfile, utils/build/docker/python/uwsgi-poc.base.Dockerfile
Python 3.9 will reach end of life in 2025. Also Python 3.9 did not get bugfixes since 2021.
This is also an experiment to check if it improves intermittent test failures we may have on nightlies.
Change python version for weblogs
- Flask from 3.9 to 3.11
- Django from 3.9 to 3.11
- FastAPI from 3.10 to 3.11
🛟 …
=> [python] move to python 3.11 for python weblogs

manifests/dotnet.yml
Since this feature is supported from version 3.2, we have enabled the system tests.
=> [dotnet] Enable suspicious attacker blocking system tests

manifests/java.yml
Original Java Dynamic Config `DD_TRACE_ENABLE` tests were XPass and needed to be enabled for full testing.
Enables the tests in the following class for Java:
`tests/parametric/test_dynamic_configuration.py::TestDynamicConfigTracingEnabled`
Ticket Link: [APMAPI-654](https://datadoghq.atlassian.net/browse/APMAPI-654)
🛟 …
=> [Java] Setting version for Dynamic Config Tests

manifests/java.yml
A bug is present in v1.39.0 java lib
Follow up on #2977 , set the version in manifest
=> [java] Set manifest to v1.40.0 for RASP/vertx

tests/test_sampling_rates.py
Enable test_sample_rate_function for C++.
Expend the coverage of `test_sample_rate_function` to C++.
That PR has been a draft for a year (oopsy) and was also enabling the test for .NET. Enabling the test for .NET has been done since then in https://github.com/DataDog/system-tests/pull/1575
🛟 …
=> [cpp] Enable test_sample_rate_function for cpp

manifests/nodejs.yml, utils/build/docker/nodejs/express4-typescript/iast.ts, utils/build/docker/nodejs/express4/iast/sources.js
Run IAST path parameter sources tests for Node.js in `express4` and `express4-typescript` variants.
Implement endpoints in `express4` and `express4-typescript` for path parameters IAST source test.
Path parameter IAST source is not supported for `Nextjs`
Add some `try-catch` in `express4-typescript` application to not pollute stderr weblog logs with expected errors (they are trying to read a non-existing file, it is ok since they are not testing that the reading is working, we are testing that the vulnerability is in the request, an the result of the operation does not matter) See: #1886 
* Test logic is modified? -> …
=> [nodejs] Support for Node.js iast source path paramters tests

utils/_context/_scenarios/k8s_lib_injection.py, utils/_context/containers.py
When the agent or weblog image is not built in E2e scenarios, here is the error message : 
```
<huge cryptic stack tace>
INTERNALERROR>   File "/Users/charles.debeauchesne/repos/system-tests/venv/lib/python3.12/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
INTERNALERROR>     raise cls(e, response=response, explanation=explanation) from e
INTERNALERROR> docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.43/images/create?tag=latest&fromImage=system_tests%2Fagent: Not Found ("pull access denied for system_tests/agent, repository does not exist or may require 'docker login': denied: requested access to the resource is denied")
```
It's not a login error, and it's too big => crap
Here is the error now : 
```
(venv) …
```
=> Better error message when agent/weblog is not built

requirements.txt
Here is the warning in stdout : 
```
/home/runner/work/system-tests-dashboard/system-tests-dashboard/venv/lib/python3.12/site-packages/paramiko/pkey.py:82: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
"cipher": algorithms.TripleDES,
/home/runner/work/system-tests-dashboard/system-tests-dashboard/venv/lib/python3.12/site-packages/paramiko/transport.py:256: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from this module in 48.0.0.
"class": algorithms.TripleDES,
```
Update paramiko to `3.4.1`
2. Work on you PR until the CI passes (if something not …
=> Fix paramiko warning

.github/workflows/run-end-to-end.yml
This reverts commit 8087741aec3fe36c49bf7025b23c8e84d8fd1593.
Resolved by: https://github.com/DataDog/dd-trace-rb/pull/3886
=> Revert "skip APPSEC_MISSING_RULES for ruby (APPSEC-54708)"

.github/workflows/run-end-to-end.yml, .vscode/launch.json, manifests/cpp.yml, manifests/dotnet.yml, manifests/golang.yml, manifests/java.yml, manifests/nodejs.yml, manifests/php.yml, manifests/python.yml, manifests/ruby.yml, requirements.txt, scenario_groups.yml, tests/test_config_consistency.py, utils/_context/_scenarios/__init__.py, utils/_features.py
We are systematically adding tests for tracing configurations, ensuring that they are implemented consistently across all languages.
- Adds one new scenario `TRACING_CONFIG_NONDEFAULT` in `utils/_context/_scenarios/_init_.py` to cover standardization of tracing feature flags and adds it to the TRACER_RELEASE_SCENARIOS and TRACER_ESSENTIAL_SCENARIOS scenario groups
- Adds a new test file tests/test_config_consistency.py to group all new tracing config consistency test classes/methods
- Adds test cases for when `DD_TRACE_HTTP_SERVER_ERROR_STATUSES` is unset and when it is customized
- Updates the manifest files for the new test cases
3. Mark it as …
=> [Tracing] Add feature/scenarios for tracing configuration consistency and implement tests for DD_TRACE_HTTP_SERVER_ERROR_STATUSES

.github/workflows/run-graphql.yml, utils/scripts/get_github_parameters.py
The GraphQL tests results are not reported to the feature parity dashboard
Add graphql-ruby 2.3 weblog in get_github_parameters
Add Ruby in the run-graphql workflow
=> [ruby] Add graphql-ruby 2.3 weblog in get_github_parameters

tests/k8s_lib_injection/test_k8s_manual_inject.py
Enable all python tests for k8s lib injection.
The tests were marked as flaky due to a problems on the python lib init images.
If the problem are solved, the tests should work smoothly.
=> k8s: Enable all python tests

docs/execute/troubleshooting.md
There is no need to permit world-write on the file. It only needs to be world-readable/executable.
Augment the explanation with the reason for the bad permissions as well.
World-writable files are a security weakness.
Change mode from 0777 to 0755, add an explanation of umask.
🛟 …
=> Improve security of postgres init-db.sh permission fix

manifests/nodejs.yml, utils/build/docker/nodejs/express4-typescript/rasp.ts, utils/build/docker/nodejs/express4/rasp.js, utils/build/docker/nodejs/nextjs/package-lock.json, utils/build/docker/nodejs/nextjs/package.json, utils/build/docker/nodejs/nextjs/src/app/rasp/sqli/route.js
SQLi exploit prevention is merged in dd-trace-js, we should enable the system tests.
Add endpoints for sqli in weblog variants and enable the tests for the next tracer versions.
=> [nodejs] Add and enable rasp sqli tests in nodejs

utils/build/docker/runner.Dockerfile
The comment in the docker file was saying : `basically everything except utils/build`. But, `utils/build` was copied two lines after.
-> Unecessaray docker build steps
-> Unecessaray pain when we add a subfolder
Rather than a list of subfolders with everything, copy the entire folder.
🛟 …
=> [ruby] Fix the (unsupported) docker mode

.github/workflows/run-lib-injection.yml, utils/scripts/compute_impacted_scenario.py
Fix the k8s lib injection tests pipeline in order to process the results from system-tests-dashboard and pushing the results to FPD
Change the result artifacts adding the suffix "dev" or "prod"
=> Fix K8s Lib Injection push FPD

manifests/python.yml
New PRs were merged on ddtrace-py, fixing that feature.
enable iast path parameters tests for flask
=> [python] update manifest for easy wins in iast path parameters

manifests/ruby.yml, tests/appsec/test_blocking_addresses.py
I am working on a [bugfix for Ruby GraphQL instrumentation](https://github.com/DataDog/dd-trace-rb/pull/3887) and changed our implementation to use resolver names as a key for arguments instead of the query name (since one query might have multiple resolvers). 
The PR that is linked above has to be merged for this test to pass.
This PR removes an extra check for Ruby for the test that asserts that GraphQL arguments were extracted correctly.
* Framework is modified, or non obvious usage of it -> get a review …
=> [Ruby] Remove extra condition for ruby for GraphQL blocking test

manifests/python.yml
this PR https://github.com/DataDog/dd-trace-py/pull/10482 fix Flask path, but it wasn't released in ddtrace-py 2.12 yet
=> fix(python): flask path tests

utils/build/virtual_machine/provisions/auto-inject/auto-inject_installer_manual.yml, utils/build/virtual_machine/provisions/auto-inject/repositories/autoinstall/execute_install_script.sh
[APMON-1459]
Uses dev versions of OCI packages when running the onboarding tests with the "dev" vm-env
Pipeline all green: https://gitlab.ddbuild.io/DataDog/system-tests/-/pipelines/44168834
Staging versions: https://gitlab.ddbuild.io/DataDog/system-tests/-/jobs/636991553#L557
🛟 …
=> fix(onboarding): Make onboarding "dev" tests use staging versions of OCI packages

tests/debugger/test_debugger_probe_status.py
Desire for proper spelling
Spelling fix in one message
=> Another spelling fix in debugger tests

manifests/cpp.yml, manifests/dotnet.yml, manifests/golang.yml, manifests/java.yml, manifests/nodejs.yml, manifests/php.yml, manifests/python.yml, manifests/ruby.yml, tests/parametric/test_config_consistency.py, utils/build/docker/python/parametric/apm_test_client/server.py
Adding tests for tracing configs to make sure implementation across all languages are consistent, based upon the following [RFC](https://docs.google.com/document/d/1kI-gTAKghfcwI7YzKhqRv2ExUstcHqADIWA4-TZ387o/edit#heading=h.o9qoojeu3llz).
- Add test cases for when `DD_SERVICE` and `DD_VERSION` are specified, as well as when neither are included.
- Included in existing `tracing_configuration_consistency` feature.
- All tests are currently marked as `missing_feature` in the manifest files
- Small change made to pass in `None` instead of `""` in testing handler call to the python tracer library
- Ticket Link: [APMAPI-347](https://datadoghq.atlassian.net/browse/APMAPI-347)
This PR is stacked on top of #2976 
2. Work on you PR until the CI passes (if something …
=> Add config consistency tests for DD_VERSION

tests/appsec/test_automated_login_events.py
Tests related to request headers in login events started to fail for the Java tracer due to a wrong `Content-Type` header.
Use a proper form content type header in the login event requests.
=> Use a proper Content-Type header in the login events tests

manifests/python.yml
=> [python] Enable Test_AppSecStandalone_UpstreamPropagation for dev only

tests/parametric/test_config_consistency.py
Adding tests for tracing configs to make sure implementation across all languages are consistent, based upon the following [RFC](https://docs.google.com/document/d/1kI-gTAKghfcwI7YzKhqRv2ExUstcHqADIWA4-TZ387o/edit#heading=h.m7pxr7de8n4j).
- Add test cases for when `DD_ENV` is specified and not specified.
- Included in existing `tracing_configuration_consistency` feature.
- All tests are currently marked as `missing_feature` in the manifest files
- Ticket Link: [APMAPI-659](https://datadoghq.atlassian.net/browse/APMAPI-658)
* Test logic is modified? -> Get a review from RFC owner. We're working on refining the …
=> Add config consistency tests for DD_ENV (Parametric)

manifests/cpp.yml, manifests/dotnet.yml, manifests/golang.yml, manifests/java.yml, manifests/nodejs.yml, manifests/php.yml, manifests/python.yml, manifests/ruby.yml, tests/test_config_consistency.py, utils/_context/_scenarios/__init__.py
Adding tests for tracing configs to make sure implementation across all languages are consistent, based upon the following [RFC](https://docs.google.com/document/d/1kI-gTAKghfcwI7YzKhqRv2ExUstcHqADIWA4-TZ387o/edit#heading=h.u523jef6b4yp).
- Add test cases for when `DD_SERVICE` is specified, as well as when it is not included.
- Included in existing `tracing_configuration_consistency` feature.
- All tests are currently marked as `missing_feature` in the manifest files
- Ticket Link: [APMAPI-657](https://datadoghq.atlassian.net/browse/APMAPI-657) …
=> Add config consistency tests for DD_SERVICE

utils/_context/containers.py
`mcr.microsoft.com/azure-sql-edge:latest` is very flaky at startup. the output is quite painfull because it contains tons of `*` for a reason I ignore. Once the ouput cleaned, it says : 
```
2024/09/18 05:20:17 [launchpadd] INFO: Extensibility Log Header: <timestamp> <process> <sandboxId> <sessionId> <message>
2024/09/18 05:20:17 [launchpadd] WARNING: Failed to load /var/opt/mssql/mssql.conf ini file with error open /var/opt/mssql/mssql.conf: no such file or directory
2024/09/18 05:20:17 [launchpadd] ERROR: RevoScaleR installation was not found. RevoScaleR is required to be installed in order to use R scripts.
2024/09/18 05:20:17 [launchpadd] ERROR: revoscalepy installation was not found. revoscalepy is required to be installed in order to use Python scripts.
2024/09/18 05:20:17 …
```
=> Fix MsSql flakiness

docs/weblog/README.md, manifests/dotnet.yml, manifests/golang.yml, manifests/java.yml, manifests/nodejs.yml, manifests/php.yml, manifests/python.yml, manifests/ruby.yml, tests/appsec/test_fingerprinting.py, utils/_weblog.py, utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/App.java
Include new session fingeprints in the tests.
Adds a new test to validate the generation of session fingerprints, it also updates the java springboot weblog with the new endpoint.
=> [asm] add tests for session fingerprints

pyproject.toml, tests/integrations/test_db_integrations_sql.py, tests/integrations/test_dbm.py, tests/integrations/test_dsm.py
he probable cause is that some dsm endpoints hangs randomly hangs for more than 5s. When the scenario does not fails, those endpoints takes few ms, but I didn’t succed to figure out what’s happening
* skip those test
* also, activate two easy wins. …
=> [python] skip flaky tests (APMAPI-724)

manifests/cpp.yml, manifests/dotnet.yml, manifests/golang.yml, manifests/java.yml, manifests/nodejs.yml, manifests/php.yml, manifests/python.yml, manifests/ruby.yml, tests/test_config_consistency.py, utils/_context/_scenarios/__init__.py
- Introduces a test that validates that the `DD_TRACE_CLIENT_IP_HEADER` configuration is supported across client libraries
- Enables this test for the following libraries:  python, ... 
=> config_consistency: test ClientIPHeader

manifests/java.yml, tests/parametric/test_otel_env_vars.py, utils/build/docker/java/parametric/src/main/java/com/datadoghq/trace/controller/TraceController.java, utils/build/docker/java/parametric/src/main/java/com/datadoghq/trace/dto/GetTraceConfigResult.java, utils/build/docker/java/parametric/src/main/java/com/datadoghq/trace/metrics/controller/MetricsController.java, utils/build/docker/java/parametric/src/main/java/com/datadoghq/trace/opentelemetry/controller/OpenTelemetryController.java, utils/build/docker/java/parametric/src/main/java/com/datadoghq/trace/opentracing/controller/OpenTracingController.java
Ensures that all languages that have implemented the OpenTelemetry environment variable mapping feature are running the corresponding system-tests.
Enables test cases in `parametric/test_otel_env_vars.py` for Java. This required adding special mappings for propagation style names and setting DD_TRACE_OTEL_ENABLED=true in all test cases to run the Java code.
Since the tests require a new GetTraceConfig endpoint, this was implemented as part of this commit. Note that there's an obscene amount of reflection to get the required tracer settings from the internal config object. Any and all feedback is welcome to improve the maintainability of this endpoint.
2. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore …
=> [parametric] Enable OTEL Env parametric tests for Java

manifests/java.yml, tests/appsec/rasp/test_lfi.py, utils/build/docker/java/akka-http/src/main/scala/com/datadoghq/akka_http/RaspRoutes.scala, utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/RaspResource.java, utils/build/docker/java/play/app/controllers/RaspController.scala, utils/build/docker/java/play/conf/routes, utils/build/docker/java/ratpack/src/main/java/com/datadoghq/ratpack/RaspHandlers.java, utils/build/docker/java/resteasy-netty3/src/main/java/com/datadoghq/resteasy/RaspResource.java, utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/rasp/RaspController.java, utils/build/docker/java/vertx3/src/main/java/com/datadoghq/vertx3/rasp/RaspRouteProvider.java, utils/build/docker/java/vertx4/src/main/java/com/datadoghq/vertx4/rasp/RaspRouteProvider.java
- Add java endpoint for RASP LFI
=> [java] Add java endpoint for RASP LFI

tests/test_telemetry.py
=> [dotnet] App-started event is not sent (APMAPI-728)

utils/_context/_scenarios/endtoend.py, utils/_context/containers.py
The MsSql image `mcr.microsoft.com/azure-sql-edge:latest` is very flaky at startuo, probably because of this issue : microsoft/mssql-docker#868
This image may not support kernel 6.7 and above, and we're using 6.8 kernel on github action large runners.
Use `mcr.microsoft.com/mssql/server:2022-latest` image
🛟 …
=> Use mssql/server:2022-latest for MsSql container

tests/parametric/test_telemetry.py
Noticed something not matching as expected when trying to run the test locally for .NET to test that `DD_SERVICE` was returned as expected.
Instead of using existing data and helper methods, updated the test to look directly for the env var by name as expected in the telemetry based on the new consistency efforts, i.e. `DD_TRACE_HTTP_SERVER_ERROR_STATUSES` instead of `DD_HTTP_SERVER_ERROR_STATUSES` which we should change in both Env Var customers can use and returned `config name` in the respective SDK language config norm file before being able to completely pass the test.
* Test logic is modified? -> Get a review from …
=> Updating Config Consistency Telemetry Test

.gitlab-ci.yml, conftest.py, utils/_context/_scenarios/auto_injection.py, utils/_context/virtual_machines.py, utils/build/virtual_machine/provisions/auto-inject/auto-inject_init_vm_config.yml, utils/build/virtual_machine/provisions/auto-inject/docker/auto-inject_prepare_docker.yml, utils/build/virtual_machine/weblogs/dotnet/provision_test-app-dotnet.yml, utils/build/virtual_machine/weblogs/nodejs/provision_test-app-nodejs.yml, utils/build/virtual_machine/weblogs/php/provision_test-app-php.yml, utils/build/virtual_machine/weblogs/php/test-app-php/php_install.sh, utils/build/virtual_machine/weblogs/python/provision_test-app-python.yml, utils/build/virtual_machine/weblogs/ruby/provision_test-app-ruby.yml, utils/virtual_machine/aws_provider.py, utils/virtual_machine/virtual_machine_provisioner.py
=> OnBoarding tests: add OracleLinux

utils/_context/virtual_machines.py
Disable run Centos 7 as default vm.
Centos 7 tests as nightly build on system-tests only
=> Onboarding: Set Centos7 as not default vm

.gitlab-ci.yml, utils/virtual_machine/aws_provider.py
We need a way to force the updating of the cached AMIs of system-tests.
The cached AMIs are the AMIs that we create from EC2 instances caching some of the installation steps (configuraton, install docker, install runtime....)
=> OnBoarding:Force update AMIs manually

manifests/nodejs.yml
- Updates the nodejs manifest file to specify minimum support version for the `http.client_ip` tag: https://github.com/DataDog/dd-trace-js/commit/989b0d3498feb652ab15e5af32be73403a4c4ccc
=> [nodejs] Test_Config_ClientIPHeader_Configured : specify minimum supported version

manifests/dotnet.yml
Enable the system tests related to RASP with features that we already support.
=> [dotnet] Enable supported RASP features

.gitlab-ci.yml, utils/_context/_scenarios/auto_injection.py, utils/_context/virtual_machines.py, utils/build/virtual_machine/provisions/auto-inject/auto-inject_init_vm_config.yml, utils/build/virtual_machine/weblogs/dotnet/provision_test-app-dotnet.yml, utils/build/virtual_machine/weblogs/ruby/provision_test-app-ruby.yml
Add ubuntu 24 machines to onboarding tests
=> OnBoarding: add ubuntu24

manifests/dotnet.yml
This feature was declared as bug in dotnet in [this PR ](https://github.com/DataDog/system-tests/commit/7dd6a44e900e8454b1b376195d92b20b01c4cc91)
It seems that in this test, we are enabling ASM and RASP by remote config. While RASP supports RC changes regarding rules or actions, we still don't support enabling RASP at runtime if ASM was initially disabled. We will add this feature but, in the meantime, this should be marked as missing feature instead of bug.
* Framework is modified, or non obvious usage of …
=> [dotnet] RASP: Declare not supported feature

tests/parametric/test_crashtracking.py
`is_crash_report` doesn't behave correctly when it receives telemetry logs that are not a crash report.
Assertions were added in https://github.com/DataDog/system-tests/pull/3080. Instead, the `is_crash_report` function should just return false.
🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X …
=> Fix crashtracking tests

manifests/dotnet.yml
Fixed a bug in the dotnet tracer with some of the new RC tests that was added.
=> [dotnet] Enable fixed RC tests

tests/parametric/test_config_consistency.py
The `test_trace_rate_limit_without_trace_sample_rate` tests that rules sampling is not applied when just DD_TRACE_RATE_LIMIT is set without any sampling rules, however, the test was previously looking for a value of `2` on the spans' `_sampling_priority_v1` tag, which was incorrect because `2` represents a form of "user keep."
Change assert statements to expect value of `1` on spans' `_sampling_priority_v1` tag. …
=> Change RateLimit test to assert value of 1 for sampling priority

tests/appsec/iast/sink/test_unvalidated_redirect.py, tests/appsec/iast/sink/test_weak_hash.py, tests/appsec/iast/sink/test_weak_randomness.py, tests/appsec/iast/sink/test_xpath_injection.py
After fix https://github.com/DataDog/system-tests/pull/3149, if a P0 trace expected without appsec/vuln is dropped because stats computation is activated on default scenario, then the assert still passes (no trace or a trace with sec events is fine)
Just reactivate them by removing attributes
=> [dotnet][IAST] Reactivate flaky tests after fix 

docs/execute/binaries.md, docs/scenarios/parametric.md
Since the Ruby Tracer gem has been [renamed from `ddtrace` to `datadog`](https://github.com/DataDog/dd-trace-rb/pull/3490), the testing documentation has become stale, recommending uses to point system-tests to an invalid gem name.
=> Ruby:Update docs for 2.0 gem rename

utils/build/docker/java/parametric/src/main/java/com/datadoghq/trace/controller/TraceController.java
The parametric app for Java currently does not support the key `dd_trace_agent_url` as a key in the return value for the endpoint `/trace/config/`. This is a key that is necessary in order to properly test the [`DD_TRACE_AGENT_URL`](https://datadoghq.atlassian.net/browse/APMAPI-474) configuration as part of the configuration consistency effort. 
Added support for `dd_trace_agent_url` by using the Config::getAgentUrl method and returning it as part of the response to the client-side.
[APMAPI-474](https://datadoghq.atlassian.net/browse/APMAPI-474) …
=> [APMAPM-474] Adding tracerConfig support for `dd_trace_agent_url`

conftest.py, docs/execute/dd-trace-debug.md, tests/appsec/test_logs.py, utils/_context/_scenarios/__init__.py, utils/_context/_scenarios/endtoend.py, utils/_context/containers.py, utils/build/docker/golang/app/internal/common/common.go, utils/build/docker/nodejs/nextjs.Dockerfile, utils/build/docker/set-system-tests-weblog-env.Dockerfile
End-to-end test **must** be as close as possible to real condition.
Having DD_TRACE_DEBUG=true by default does not achieve that. And for some tracers, it causes flakiness that does not happen on prod, and so, decreasing the signal/noise ratio. 
Do not set `DD_TRACE_DEBUG`. If it's needed, it must be activated ponctualy on a separated branch, not on `main`.
:rocket: Once …
=> Do not use DD_TRACE_DEBUG=true by default

utils/build/docker/java/parametric/src/main/java/com/datadoghq/trace/controller/TraceController.java
The parametric app for Java currently does not support the key `dd_trace_rate_limit` as a key in the return value for the endpoint /trace/config/. This is a key that is necessary in order to properly test the [DD_TRACE_RATE_LIMIT](https://datadoghq.atlassian.net/browse/APMAPI-468) configuration as part of the configuration consistency effort.
Added support for `dd_trace_rate_limit` by using the Config::getAgentUrl method and returning it as part of the response to the client-side.
[APMAPI-468](https://datadoghq.atlassian.net/browse/APMAPI-468) …
=> Adding functionality for `dd_trace_rate_limit` for get_tracer_config()

tests/remote_config/test_remote_configuration.py
=> [php] Mark test_agent_provide_config_endpoint as irrelevant

tests/appsec/test_alpha.py, tests/appsec/test_traces.py, tests/appsec/waf/test_addresses.py, tests/appsec/waf/test_rules.py
* Clean test code base
* Open the way of removing the `appsec_rules_version` proeprty, as it's tighed to library version.
Remove test that are not relevant for `appsec_rules_version >= 1.2.7`.
=> Remove unused tests

tests/appsec/test_alpha.py, tests/appsec/test_reports.py, tests/appsec/waf/test_rules.py
=> Remove legacy mention of libddwaf_version

tests/appsec/waf/test_reports.py
Small test improvments
Remove test on the rules file version value : the regex already check it's a version ,and apart from someone putting hardcoded value, we almost check that 1==1 here. By utself, it's not harmful. But this allow to remove all reference to `appsec_rules_version`, that is a value that causes some complexity, and is hard to get. Furthermore, this is a dependancy tied to the library, and so have no reason to be tested separatly. 
* Framework is modified, or non obvious usage of it -> get a …
=> Clean Test_Monitoring

docs/weblog/README.md, manifests/dotnet.yml, manifests/golang.yml, manifests/java.yml, manifests/nodejs.yml, manifests/php.yml, manifests/python.yml, manifests/ruby.yml, tests/appsec/iast/sink/test_insecure_cookie.py, tests/appsec/iast/sink/test_no_httponly_cookie.py, tests/appsec/iast/sink/test_no_samesite_cookie.py, tests/appsec/iast/utils.py, utils/build/docker/nodejs/express4-typescript/iast.ts, utils/build/docker/nodejs/express4/iast/index.js
We are implementing an improvement to prevent having thousands of vulnerabilities when the cookie name is generated.
- Add system tests to check that cookies with different superlong name are not generating two different vulnerabilities.
- Endpoints for nodejs express4 and express4-typescript. 
🛟 …
=> Add tests to long cookie name vulnerabilities

utils/_context/_scenarios/auto_injection.py
Better error message
Previously, the error message was `INTERNALERROR> AssertionError: Weblog Provision file not found.`
It now shows the expected file name.
=> Give more info in error message

utils/_context/containers.py, utils/build/docker/dotnet/install_ddtrace.sh, utils/build/docker/php/apache-mod/php.conf, utils/build/docker/php/common/healthcheck.php, utils/build/docker/php/php-fpm/php-fpm.conf
=> [php] Use healthcheck to get version

utils/build/docker/python/fastapi/main.py, utils/build/docker/python/flask/app.py
`POST /iast/source/parametername/test` requires a JSON body. The current code does not set the `content-type` headers, and this is not liked by some framworks (fastapi)
Set the content-type (by using the `json` parameter)
=> [python] Fix weblog code to removes exception in stdout

utils/_context/containers.py, utils/build/docker/java/akka-http/pom.xml, utils/build/docker/java/akka-http/src/main/scala/com/datadoghq/akka_http/HealthcheckRoutes.scala, utils/build/docker/java/akka-http/src/main/scala/com/datadoghq/akka_http/Main.scala, utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/MyResource.java, utils/build/docker/java/play/app/controllers/AppSecController.scala, utils/build/docker/java/play/conf/routes, utils/build/docker/java/ratpack/src/main/java/com/datadoghq/ratpack/Main.java, utils/build/docker/java/resteasy-netty3/src/main/java/com/datadoghq/resteasy/MyResource.java, utils/build/docker/java/spring-boot-3-native/src/main/java/com/datadoghq/springbootnative/WebController.java, utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/App.java, utils/build/docker/java/vertx3/pom.xml, utils/build/docker/java/vertx3/src/main/java/com/datadoghq/vertx3/Main.java, utils/build/docker/java/vertx4/pom.xml, utils/build/docker/java/vertx4/src/main/java/com/datadoghq/vertx4/Main.java
=> [java] Implements healthcheck endpoint for all weblogs

.gitlab-ci.yml, utils/build/virtual_machine/provisions/auto-inject-ld-preload/provision.yml, utils/build/virtual_machine/provisions/auto-inject/docker/patch-docker-daemon.yml, utils/build/virtual_machine/provisions/container-auto-inject-install-script/provision.yml, utils/build/virtual_machine/provisions/installer-auto-inject/provision.yml
=> Patch docker daemon to not use ddbuild runner IP range

tests/appsec/rasp/utils.py
Rulesets are sent through ASM_DD product, not ASM
Change RC config product name 
=> Fix RC product name in `Test_Lfi_RC_CustomAction`

manifests/cpp.yml
Enables running and passing system-tests for dd-trace-cpp to meet the requirements of the config consistency effort (only for existing configurations implemented in the tracer)
Unskips config consistency tests for cpp, such that it will run on the next release of dd-trace-cpp. Note: This will only run once dd-trace-cpp has a version increase and/or gets released, but this works locally when tested against the latest DataDog/dd-trace-cpp@89426d570c378fe4eaec7502d53dfb937a80d326 commit, which has the required changes.
* Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file …
=> [cpp] Enable Config Consistency tests

.github/CODEOWNERS
- @Kyle-Verhoog  is no longer a member of APM Ecosystem, ownership of parametric tests should move to the apm-sdk-api team.
- @mabdinur is driving various parametric test improvements in 2024Q4 (re-writing documentation, updating helpers, migrating endpoints from grpc to http, adding helpers to abstract tracer internals, etc.). He would would like to be aware of all changes to parametric tests to avoid conflicts and regressions. …
=> codeowners(parametric): replace kyle with munir

tests/parametric/test_telemetry.py
This change to shared tests will unblock this PR: https://github.com/DataDog/dd-trace-py/pull/10987
- Updates python telemetry name to match it's corresponding environment variable: https://github.com/DataDog/dd-trace-py/pull/10987
=> [python] update telemetry configuration names

manifests/golang.yml
Test is not ok
Partial revert of #3050
=> [golang] Flag Test_HeaderTags_Colon_Trailing failing for AIT-8571

tests/parametric/test_telemetry.py
The following PR broke golang and java and parametric tests and was reverted: https://github.com/DataDog/system-tests/pull/3221. This PR reverts the revert and fixes the failing assertions.
=> parametric: update python telemetry configuration names 

tests/appsec/test_traces.py
[APPSEC-54498](https://datadoghq.atlassian.net/browse/APPSEC-54498)
Enable XPASS test.
[APPSEC-54498]: https://datadoghq.atlassian.net/browse/APPSEC-54498?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [java] Enable new AppSec obfuscation test

utils/build/docker/nodejs/express4-typescript/auth.ts
Fix missing dd-trace module error from TypeScript.
Add TypeScript ignore rule to dd-trace since it may be installed at runtime.
=> [nodejs] fix missing dd-trace module error from typescript

tests/appsec/iast/source/test_parameter_name.py
See https://github.com/DataDog/dd-trace-java/pull/7619
[APPSEC-55387](https://datadoghq.atlassian.net/browse/APPSEC-55387)
[APPSEC-54879]: …
=> [java] Enable test for fixed issue in jersey-grizzly2

utils/build/docker/ruby/graphql23/app/controllers/system_test_controller.rb, utils/build/docker/ruby/parametric/server.rb, utils/build/docker/ruby/rack/config.ru, utils/build/docker/ruby/rails42/app/controllers/system_test_controller.rb, utils/build/docker/ruby/rails50/app/controllers/system_test_controller.rb, utils/build/docker/ruby/rails51/app/controllers/system_test_controller.rb, utils/build/docker/ruby/rails52/app/controllers/system_test_controller.rb, utils/build/docker/ruby/rails60/app/controllers/system_test_controller.rb, utils/build/docker/ruby/rails61/app/controllers/system_test_controller.rb, utils/build/docker/ruby/rails70/app/controllers/system_test_controller.rb, utils/build/docker/ruby/rails71/app/controllers/system_test_controller.rb, utils/build/docker/ruby/sinatra14/app.rb, utils/build/docker/ruby/sinatra20/app.rb, utils/build/docker/ruby/sinatra21/app.rb, utils/build/docker/ruby/sinatra22/app.rb, utils/build/docker/ruby/sinatra30/app.rb, utils/build/docker/ruby/sinatra31/app.rb, utils/build/docker/ruby/sinatra32/app.rb, utils/build/docker/ruby/sinatra40/app.rb
I wanted to enable easy wins, but also wanted to add the version since it works in the manifest. Trying to run system-tests on 1.x branch was not working. 1.x branch is still active and should still be tested against system-tests
Both auto instrumentation and healthcheck endpoints were using `Datadog` namespace, but 1.x is using `DDTrace`. I applied what has been done in Sinatra weblogs and parametric weblog for auto-instrumentation (require in begin/rescue block), and added a condition for getting the version in healthcheck endpoints (`defined?(Datadog::VERSION)`)
=> [ruby] Add 1.x support in Ruby weblogs

tests/integrations/test_dsm.py, utils/build/docker/nodejs/express4/integrations/messaging/aws/kinesis.js, utils/build/docker/nodejs/express4/integrations/messaging/aws/sns.js, utils/build/docker/nodejs/express4/integrations/messaging/aws/sqs.js
Changes nodejs weblog tests for SQS / SNS / Kinesis to loop faster between messages. Previously looping was too slow and was causing requests to time out before finding the correct message in the queue.
=> nodejs: fix AWS bug where messages aren't being consumed

tests/integrations/test_dsm.py, utils/_context/containers.py
This PR updates Kafka DSM tests to include the new kafka cluster id. It also disables the test for now for all languages where cluster id is being added, and will be re-enabled in different PR's for each language once the implementation work is done. …
=> kafka cluster id test update

utils/build/docker/set-system-tests-weblog-env.Dockerfile
Resolve the `Malformed tag in tag pair ':' from tag string 'key***:val***, key2 : val2'` error that is raised when running  weblog apps.
- Removes whitespace from comma delimited tags. DD_TAGS should be delimited by commas or whitespace NOT both. 
🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ …
=> chore: fix formatting for DD_TAGS

manifests/ruby.yml, tests/appsec/test_blocking_addresses.py
We have a lot of easy-wins
Add version declaration in manifest (Test_AppSecStandalone_UpstreamPropagation: v2.4.1-dev will work once #3295 is merged in main)
=> [ruby] Enables a bunch of easy wins

utils/build/docker/ruby/graphql23/app/controllers/system_test_controller.rb, utils/build/docker/ruby/rack/config.ru, utils/build/docker/ruby/rails42/app/controllers/system_test_controller.rb, utils/build/docker/ruby/rails50/app/controllers/system_test_controller.rb, utils/build/docker/ruby/rails51/app/controllers/system_test_controller.rb, utils/build/docker/ruby/rails52/app/controllers/system_test_controller.rb, utils/build/docker/ruby/rails60/app/controllers/system_test_controller.rb, utils/build/docker/ruby/rails61/app/controllers/system_test_controller.rb, utils/build/docker/ruby/rails70/app/controllers/system_test_controller.rb, utils/build/docker/ruby/rails71/app/controllers/system_test_controller.rb, utils/build/docker/ruby/sinatra14/app.rb, utils/build/docker/ruby/sinatra20/app.rb, utils/build/docker/ruby/sinatra21/app.rb, utils/build/docker/ruby/sinatra22/app.rb, utils/build/docker/ruby/sinatra30/app.rb, utils/build/docker/ruby/sinatra31/app.rb, utils/build/docker/ruby/sinatra32/app.rb, utils/build/docker/ruby/sinatra40/app.rb
This will enable the activation of system-tests on ruby dev environment for the upcoming version (e.g.: current version is 2.4.0, healthcheck will return 2.4.0-dev and system-tests will increment the patch number, so tests can be activated by declaring 2.4.1-dev in the manifest)
This adds -dev to the version given by healthchecks when not using datadog/ddtrace gem from Rubygems by verifying that the source of a Rubygems is a Bundler::Source::Rubygems object
=> [ruby] Add -dev to healthcheck when not using gem from Rubygems

utils/_context/virtual_machines.py, utils/virtual_machine/aws_provider.py
If there are many instances running the network interfaces raises error.
We restrict the number os instances running and wait for clean process.
https://datadoghq.atlassian.net/browse/INPLAT-116
=> OnBoarding: Limit ec2 instances

manifests/dotnet.yml, utils/build/docker/dotnet/weblog/Controllers/RaspController.cs, utils/build/docker/dotnet/weblog/Controllers/SessionController.cs
This PR enables the FP and suspicious attacker system tests that are supported in the latest version of the tracer.
=> [dotnet] Enable FP and Suspicious attacker tests

tests/test_the_test/test_version.py, utils/_context/_scenarios/parametric.py, utils/_context/library_version.py, utils/build/docker/ruby/graphql23/app/controllers/system_test_controller.rb, utils/build/docker/ruby/install_ddtrace.sh, utils/build/docker/ruby/parametric/Gemfile, utils/build/docker/ruby/parametric/system_tests_library_version.sh, utils/build/docker/ruby/rack/config.ru, utils/build/docker/ruby/rails42/app/controllers/system_test_controller.rb, utils/build/docker/ruby/rails50/app/controllers/system_test_controller.rb, utils/build/docker/ruby/rails51/app/controllers/system_test_controller.rb, utils/build/docker/ruby/rails52/app/controllers/system_test_controller.rb, utils/build/docker/ruby/rails60/app/controllers/system_test_controller.rb, utils/build/docker/ruby/rails61/app/controllers/system_test_controller.rb, utils/build/docker/ruby/rails70/app/controllers/system_test_controller.rb, utils/build/docker/ruby/rails71/app/controllers/system_test_controller.rb, utils/build/docker/ruby/sinatra14/app.rb, utils/build/docker/ruby/sinatra20/app.rb, utils/build/docker/ruby/sinatra21/app.rb, utils/build/docker/ruby/sinatra22/app.rb, utils/build/docker/ruby/sinatra30/app.rb, utils/build/docker/ruby/sinatra31/app.rb, utils/build/docker/ruby/sinatra32/app.rb, utils/build/docker/ruby/sinatra40/app.rb
We get ruby version from pure ruby threw healthcheck, so we don't need anymore all the clean done in library version
=> [ruby] Remove hacks on ruby bundle info output

manifests/python.yml
I had a mistake in my [previous PR](https://github.com/DataDog/system-tests/pull/3310) replacing `v2.4.0.dev1` by `v2.4.01`
=> [python] semver format. fix a search and replace error

manifests/java.yml
=> [java] Enable RASP SSRF tests for some variants

tests/integrations/crossed_integrations/test_kinesis.py, tests/integrations/crossed_integrations/test_sns_to_sqs.py, tests/integrations/crossed_integrations/test_sqs.py, tests/integrations/test_dsm.py
disable AWS tests until flakiness / other errors are resolved.
=> disable aws tests for now

tests/appsec/blocking_rule.json, tests/appsec/test_blocking_addresses.py
Rack does not send anything to the path_params address (Rails and Sinatra does) but we still want to test blocking on multiple request addresses
On the advice of @christophe-papazian I wrote a similar test without path-params. All the weblogs that passes these tests with path_params should also pass them without, but it will also enable testing that feature on a pure Rack app
=> Add Suspicious Request Blocking test without path_params

manifests/nodejs.yml, manifests/python.yml, tests/integrations/test_dsm.py
Enables Kafka DSM test that includes Cluster ID in DSM tags. 
=> enable Python & NodeJS Kafka DSM test with new Cluster ID tag

tests/parametric/conftest.py, utils/parametric/_library_client.py, utils/tools.py
When container failed to start in parametric tests, the output is too verbose
* remove debug and info logs from requests/urllib3 modules
* remove warning from chained exception
* print container logs in stdout
=> Improve parametric scenario output

manifests/golang.yml
Handling trailing colons in header_tags will be fixed in next dd-trace-go release, due to this change: https://github.com/DataDog/dd-trace-go/pull/2913 
Enables Test_HeaderTags_Colon_Trailing for Go in v1.70.0
=> Enable Test_HeaderTags_Colon_Trailing for Go

docs/execute/binaries.md
Cleaning up clutter and clarifying how to run golang binaries in the System-Tests repo.
=> Updating how to run binaries for Golang

.github/workflows/run-docker-ssi.yml, tests/docker_ssi/test_docker_ssi.py, utils/build/ssi/base/install_os_deps.sh, utils/build/ssi/base/php_install_runtimes.sh, utils/build/ssi/php/php-app.Dockerfile, utils/docker_ssi/docker_ssi_definitions.py, utils/docker_ssi/docker_ssi_matrix_builder.py, utils/docker_ssi/docker_ssi_matrix_utils.py, utils/interfaces/_test_agent.py
Init docker SSI tests for PHP
+ test that the library_entrypoint send the `library_entrypoint.complete` telemetry metric
Same as @emmettbutler [PR for Python](https://github.com/DataDog/system-tests/pull/3284) (thanks for paving the way!)
https://datadoghq.atlassian.net/browse/INPLAT-48 and https://datadoghq.atlassian.net/browse/INPLAT-11 …
=> Init docker SSI tests for PHP

manifests/dotnet.yml, utils/_context/_scenarios/parametric.py, utils/build/docker/dotnet/parametric/Endpoints/ApmTestApi.cs
Enable config consistency tests for dotnet
makes updates to dotnet.yml to enable certain config consistency tests
=> enable config consistency system tests dotnet

tests/integrations/test_dsm.py
NodeJS in rabbitMQ was not getting the queue name correctly. It was using the routing key instead.
Update the tests to match the other languages.
=> Update DSM nodeJS tests for RabbitMQ

manifests/cpp.yml, manifests/dotnet.yml, manifests/golang.yml, manifests/nodejs.yml, tests/parametric/conftest.py, tests/parametric/test_crashtracking.py, utils/_context/_scenarios/parametric.py, utils/_context/containers.py, utils/build/docker/ruby/parametric/server.rb
Add a test to verify that crashtracking properly times out when the telemetry endpoint takes too much time to reply.
Added a new test that sets an artificial delay on the telemetry endpoint, crashes the application, then verifies the container exits within 10 seconds.
🛟 …
=> Add a test to verify that crashtracking properly times out

docs/execute/binaries.md
Add info to java binaries for running custom tracer from CI.
=> Updating how to run binaries for Java

docs/weblog/README.md, manifests/cpp.yml, manifests/dotnet.yml, manifests/golang.yml, manifests/java.yml, manifests/nodejs.yml, manifests/php.yml, manifests/python.yml, manifests/ruby.yml, tests/serverless/span_pointers/aws/test_s3_span_pointers.py, tests/serverless/span_pointers/utils.py, utils/build/docker/python/django/app/urls.py, utils/build/docker/python/flask/app.py
Now that span pointers for s3 and dynamodb are going to be released and we're starting work on the javascript tracer, let's add more tests.
Adding system tests for s3: copy object and complete multipart upload; and dynamod: put item, update item, delete item, batch write item, and transact write items.
🛟 …
=> chore: more span pointer tests

manifests/nodejs.yml, utils/_context/_scenarios/__init__.py, utils/build/docker/nodejs/express4-typescript/app.ts, utils/build/docker/nodejs/express4/app.js, utils/build/docker/nodejs/nextjs/src/app/vulnerablerequestdownstream/route.js
Test IAST vulnerability detection with standalone mode ON
- Implement `/vulnerablerequestdownstream`
- Add two new env var to the `IAST_STANDALONE` scenario for disabling vulnerability deduplication and enabling the IAST for all requests
- `DD_IAST_DEDUPLICATION_ENABLED=false`
- `DD_IAST_REQUEST_SAMPLING=100`
🛟 …
=> Enable Test_IastStandalone_UpstreamPropagation in nodejs

tests/debugger/test_debugger_pii.py, tests/debugger/test_debugger_probe_status.py
[dd-trace-py 2.16](https://github.com/DataDog/dd-trace-py/releases/tag/v2.16.0) release may have introduced bugs on debugger feature.
Skip failing test. As the bug is not on the main branch, probably nothing to fix (appart maybe the release process ? TBD), so I set the "cold case" ticket as reason. 
🛟 …
=> [python] Skip bugs for 2.16.0 release

utils/build/docker/ruby/parametric/system_tests_library_version.sh
=> Add -dev on dev version for ruby in parametric scenario

utils/_context/_scenarios/auto_injection.py
We want to remove the lang sufix from the datadog-apm-library, in order to simplify the components view from FPD
=> Onboarding: format datadog-apm-library dep

tests/parametric/test_headers_precedence.py
Updating system-tests to reflect current behavior for distributed tracing
[APMAPI-873](https://datadoghq.atlassian.net/browse/APMAPI-873)
Enabling XPassing tests for Header Precedence system-tests
[APMAPI-873]: …
=> Enabling xPassing tests for Header Precedence

.github/workflows/run-end-to-end.yml
No flakes !
https://datadoghq.atlassian.net/browse/APMAPI-879
Skip CROSSED_TRACING_LIBRARIES for python 3.12, as the crash at startup happens too aften, and as all test are skipped on this scenario.
=> [python] Do not run CROSSED_TRACING_LIBRARIES for python 3.12

utils/build/docker/python/parametric/apm_test_client/server.py
For scenarios which need to segfault, it is better and more realistic to create an actual segfault rather than hacking the behavior.
We noticed with a change to crashtracking that `os.kill(os.getpid(), SIGSEGV)` behaved differently, and the application would not actually crash. This is expected behavior with how linux and signal handling is meant to work when the process is PID 1.
Cause a crash by actually segfaulting instead of using external signals.
* Framework is modified, or non obvious usage of it -> …
=> [python] replace os.kill(os.getpid()) with ctypes.string_at(0)

manifests/ruby.yml, tests/appsec/test_conf.py, tests/parametric/test_headers_b3multi.py, tests/parametric/test_headers_none.py, tests/parametric/test_otel_tracer.py, tests/remote_config/test_remote_configuration.py
Enables every classes that are entirely ok as of 7th of November 2024
=> [ruby] Enable more easy wins

tests/remote_config/test_remote_configuration.py
This test was an easy win for Ruby but there was no manifest declaration. When talking about it with Charles, it was clarified that this test is testing nothing, except the /info endpoint but it should be rewritten somewhere else.
It removes Test_Agent from test_remote_configuration.py
=> Remove Test_Agent from test_remote_configuration.py

manifests/dotnet.yml
Effort to make sure .NET configuration is consistent and kept like that: [APMAPI-473](https://datadoghq.atlassian.net/browse/APMAPI-473)
[APMAPI-473]: https://datadoghq.atlassian.net/browse/APMAPI-473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDl …
=> Enabling .NET Consistent Configs

manifests/dotnet.yml
This feature is supported in the latest .Net tracer release.
=> [dotnet] Enable RC tests

tests/parametric/test_headers_precedence.py
Followup from #3253 and adding sampling header tag to verify consistency of flag values in Span Links. Also enabling Java tests that are fixed to be consistent.
Adding sampling header tag and enabling TraceContext Span Link system tests for java.
🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8 …
=> Adding sampling header tag for trace_context_precedence test

manifests/nodejs.yml, tests/appsec/test_asm_standalone.py
We thought that it should be working automatically, but not, there is work to do, so it is not a `bug`, it is a missing_feature.
Remove `@bug` from test methods and add a `missing_feature` in nodejs.yml file.
=> [nodejs] Missing feature for IastStandalone

tests/test_config_consistency.py, tests/test_standard_tags.py
We removed `X-Forwarded` from client IP resolution (but not header collection for AppSec), since its correct format is unclear, and its usage in the wild in doubt.
=> Remove X-Forwarded from client IP resolution

format.sh
Having a large number of non-git files within the system-tests directory, if not covered by the exclude patterns, leads to slower format.sh, and possibly unexpected results.
* Use `git ls-files` instead of `find` to check the files to be formatted for trailing spaces.
* To simplify the change, I removed the additional excludes/includes args that were introduced by https://github.com/DataDog/system-tests/pull/2579 since it seems they are not used within the repo. But I can add them back if they are actually in use.
* Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file …
=> Exclude files not tracked by git from format.sh

.gitlab-ci.yml, utils/_context/_scenarios/auto_injection.py
Reverts DataDog/system-tests#3432 as its failing python injection tests, the syntax needs to be changed 
```
raphael_gavache_datadoghq_com@raphael-debian12:~$ DD_APM_INSTRUMENTATION_DEBUG=true DD_TRACE_DEBUG=true DD_TRACE_SAMPLING_RULES=[{'sample_rate':1}]  python3
...
[2024-11-12 16:36:04] [ERROR] datadog.autoinstrumentation(pid: 943923): failed to load ddtrace module: cannot access local variable 'json_rules' where it is not associated with a value
raphael_gavache_datadoghq_com@raphael-debian12:~$ DD_APM_INSTRUMENTATION_DEBUG=true DD_TRACE_DEBUG=true DD_TRACE_SAMPLING_RULES="[{'sample_rate':1}]"  python3
...
[2024-11-12 16:36:04] [ERROR] datadog.autoinstrumentation(pid: 943923): failed to load ddtrace module: cannot access local variable 'json_rules' where it is not associated with a …
```
=> Revert "OnBoarding: Force full tracing without limits"

conftest.py
=> Slightly better error message for an edge case

utils/build/virtual_machine/provisions/auto-inject/auto-inject_installer_manual.yml, utils/build/virtual_machine/provisions/auto-inject/auto-inject_pre_installer_manual.yml, utils/build/virtual_machine/provisions/auto-inject/repositories/autoinstall/execute_install_script.sh, utils/build/virtual_machine/provisions/local-auto-inject-install-script/provision.yml
Often we lose the connection to S3 and the installation fails.
replace https://s3.amazonaws.com/dd-agent/scripts/install_script_agent7.sh  to https://install.datadoghq.com/scripts/install_script_agent7.sh
=> Onboarding: change install_script_agent7 url

manifests/cpp.yml, manifests/dotnet.yml, manifests/golang.yml, manifests/java.yml, manifests/nodejs.yml, manifests/php.yml, manifests/python.yml, manifests/ruby.yml, tests/appsec/rasp/test_lfi.py, tests/appsec/rasp/test_libddwaf.py, tests/appsec/rasp/test_shi.py, tests/appsec/rasp/test_sqli.py, tests/appsec/rasp/test_ssrf.py, tests/appsec/rasp/utils.py
Check that the rules and libddwaf versions are the expected for the GA.
Adds a test checking that the libddwaf version is the expected, and one check by exploit checking that the rules version in the tracer is bigger than the min supported version. …
=> Add tests to check libddwaf and rules versions in waf.init metric

manifests/java.yml, utils/build/docker/java/akka-http/src/main/scala/com/datadoghq/akka_http/RaspRoutes.scala, utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/RaspResource.java, utils/build/docker/java/play/app/controllers/RaspController.scala, utils/build/docker/java/play/conf/routes, utils/build/docker/java/ratpack/src/main/java/com/datadoghq/ratpack/RaspHandlers.java, utils/build/docker/java/resteasy-netty3/src/main/java/com/datadoghq/resteasy/RaspResource.java, utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/rasp/RaspController.java, utils/build/docker/java/vertx3/src/main/java/com/datadoghq/vertx3/rasp/RaspRouteProvider.java
Implemented missing endpoints for SSRF in:
- akka-http
- jersey-grizzly2
- play
- ratpack
- resteasy-netty3
- vertx3
[APPSEC-55650](https://datadoghq.atlassian.net/browse/APPSEC-55650)
[APPSEC-55781](https://datadoghq.atlassian.net/browse/APPSEC-55781)
🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025 …
=> [Java] Implemented missing endpoints for SSRF

tests/docker_ssi/test_docker_ssi.py, utils/_context/_scenarios/docker_ssi.py, utils/build/ssi/base/php_install_runtimes.sh, utils/build/ssi/base/tested_components.sh, utils/docker_ssi/docker_ssi_definitions.py
https://datadoghq.atlassian.net/browse/INPLAT-38
=> Enable docker_ssi telemetry test for Python, Ruby and Java

utils/build/docker/nodejs/parametric/server.js
Update Node parametric app `start_span` in order to support adding span links that have been extracted from distributed tracing propagation extractions. This will allow parametric apps to properly test for the expected behavior for span links with distributed tracing headers.
Take the span links from the extracted context and add it to the created span with `span.addLink`. 
[APMAPI-889](https://datadoghq.atlassian.net/browse/APMAPI-889)
* Framework is modified, or non obvious usage of it -> get a review …
=> Support adding span links from extracted context in startSpan

tests/docker_ssi/test_docker_ssi_crash.py
=> Disable irrelevant Python 3.6 test_crash test

.github/workflows/compute-workflow-parameters.yml, utils/_context/_scenarios/__init__.py, utils/_context/_scenarios/core.py
Instead of adding one by one the scenarios related with the rasp in the dd-trace-js ci, it's better if we run the scenarios group for the rasp.
Working CI run in dd-trace-js: https://github.com/DataDog/dd-trace-js/actions/runs/11839366667/job/32990627845?pr=4883
Create new  scenario group and link related scenarios with the new group.
:rocket: Once your PR is reviewed, …
=> Create appsec rasp scenario group

manifests/dotnet.yml
Enable some new .net RASP tests that should pass.
=> [dotnet] Enable RASP ruleset and WAF version tests

.github/workflows/python-temporary-test.yml
PRs based off latest `main` show linting warning
Ran `./format.sh` and committed changed files.
=> Fix linting warning (trailing whitespace)

.shellcheck, docs/execute/binaries.md, manifests/cpp.yml, manifests/dotnet.yml, manifests/golang.yml, manifests/java.yml, manifests/nodejs.yml, manifests/php.yml, manifests/python.yml, manifests/ruby.yml, tests/integrations/test_otel_drop_in.py, utils/_context/_scenarios/endtoend.py, utils/_context/_scenarios/integrations.py, utils/build/docker/java/app.sh, utils/build/docker/java/install_drop_in.sh, utils/build/docker/java/spring-boot.Dockerfile, utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/App.java, utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/integrations/db/ReactiveCRUDOperation.java, utils/build/docker/java_otel/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/integrations/db/ReactiveCRUDOperation.java
Add a new integration test for "Custom Instrumentation Telemetry RFC"
Tests the following changes from the "Custom Instrumentation Telemetry RFC" on Java:
* OpenTelemetry drop-in libraries have integration names starting with 'otel.'
* Spans created by drop-in libraries are tagged with names starting with 'otel.'
Also includes some fixes due to R2DBC syntax differing slightly from JDBC …
=> Add a new integration test for "Custom Instrumentation Telemetry RFC"

utils/parametric/_library_client.py
- Clean up
- Delete `_OtelSpan.get_attribute()`
=> parametric: remove unused method

tests/parametric/test_headers_b3.py, tests/parametric/test_headers_b3multi.py
Updates the test skip annotations for Ruby and C++ b3 trace context propagation header tests, including unskipping tests for Ruby on new tracer versions.
Keeps the parametric test skip reasons up-to-date so we have a better understanding of why they are currently being skipped.
=> [parametric] Update parametric tests for b3 trace context propagation headers

tests/parametric/test_headers_precedence.py
Updates test skips in `tests/parametric/test_headers_precedence.py` with more accurate versions for test skips. This is to help improve the version tracking for our tracer's propagation behaviors.
Improve version tracking for each tracing library's implementation of propagation behaviors
=> [parametric] Update test skips in test_headers_precedence.py for language tracers

docs/execute/binaries.md
[A previous PR](https://github.com/DataDog/system-tests/commit/eff4b2bb85aec0110b964d9626e2fb803543c4b6) overwrote the Golang instructions under binaries.md; this PR reverts those changes after coming to the following conclusions: 
1. The instructions did not work for neither weblog nor parametric apps in the repo's current state
3. We want one set of instructions for both parametric and weblog app and the "old way" with golang-load-from-go-get achieves that
Revert binaries.md#Golang instructions to the old " golang-load-from-go-get" way.
Closes https://github.com/DataDog/system-tests/pull/3454 
* Test logic is …
=> [golang] update binaries.md

tests/auto_inject/test_auto_inject_install.py
The `TestContainerAutoInjectInstallScriptCrashTracking_NoZombieProcess.test_crash_no_zombie` test randomly fails for Python, leaving a zombie process behind: https://gitlab.ddbuild.io/DataDog/system-tests/-/jobs/711560396
Tracked in https://datadoghq.atlassian.net/browse/APMLP-313
🛟 …
=> Mark the onboarding zombies test as flaky for python

tests/appsec/api_security/test_apisec_sampling.py, tests/parametric/test_headers_precedence.py, tests/test_schemas.py
The versions that were used focused only on the latest release line and ignored v4.x.
Fix wrong Node.js bug versions for skipping tests.
=> [nodejs] fix wrong nodejs bug versions for skipping tests

utils/_context/_scenarios/parametric.py
- Ensures (most) python weblog and parametric apps use the same python version. This will allow us to use the same CI artifacts (ddtrace wheels) in weblog and parametric tests.
Next step: Upgrade all apps to python3.12
=> [python] parametric: upgrade app to python3.11

tests/test_schemas.py
=> [python] Skip failing test for 2.16.3 release

manifests/java.yml
Enabled xpassed tests for Java
=> Enabled xpassed tests for Java

manifests/php.yml, utils/build/docker/php/parametric/server.php
- Update the php parametric to pass the `Test_Parametric_DDTrace_Flush`.
- Implement the `/trace/stats/flush` endpoint to resolve 404 errors.
- Use the `seconds` parameter in the `/trace/otel/flush` endpoint. Previously this argument was ignored.
🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8 …
=> [php] parametric: update dd and otel flush endpoints

utils/virtual_machine/virtual_machine_provider.py, utils/virtual_machine/virtual_machine_provisioner.py
we are only using the CI_COMMIT_BRANCH variable to use the git system-tests sources instead of copy remotely all the weblog files. When we are creating a tag the CI_COMMIT_BRANCH is emptly and we are not using the git (we are copying the files remotely, and this is taking time).
Use GITLAB_CI variable instead CI_COMMIT_BRANCH
:rocket: Once your PR is reviewed, you can …
=> OnBoardin: Fix git sources when gitlab tag

manifests/nodejs.yml, tests/parametric/test_crashtracking.py, utils/_context/_scenarios/parametric.py, utils/build/docker/nodejs/parametric/server.js
Crashtracking has now been released for Node.js
Enable crashtracking tests for Node.js (only in SSI for now).
=> [nodejs] enable crashtracking tests

utils/_context/containers.py
Before
```
~/repos/system-tests: ./run.sh 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/charles.debeauchesne/repos/system-tests/venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 716, in urlopen
INTERNALERROR>     httplib_response = self._make_request(
INTERNALERROR>                        ^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/Users/charles.debeauchesne/repos/system-tests/venv/lib/python3.12/site-packages/urllib3/connectionpool.py", line 416, in _make_request
INTERNALERROR>     conn.request(method, url, **httplib_request_kw)
INTERNALERROR>   File "/usr/local/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/http/client.py", line 1336, in request
INTERNALERROR>     self._send_request(method, url, …
```
=> Print a pretty error message if docker daemon is not running

utils/parametric/_library_client.py
The following debug log is generated every 0.01 while parametric test run wait for a parametric app to start. This log is not very actionable and it could be generated thousands of times in one test run. I think we are better off without it.
[Example](https://github.com/DataDog/system-tests/actions/runs/11978009034/job/33397503747?pr=3497):
```
18:35:03.655 DEBUG    Wait for 0.01s for the HTTP library to be ready
18:35:03.667 DEBUG    Wait for 0.01s for the HTTP library to be ready
18:35:03.679 DEBUG    Wait for 0.01s for the HTTP library to be ready
18:35:03.691 DEBUG    Wait for 0.01s for the HTTP library to be ready
18:35:03.703 DEBUG    Wait for 0.01s for the HTTP library to be ready
18:35:03.714 DEBUG    Wait for 0.01s for the HTTP library to be ready
18:35:03.726 DEBUG    Wait for …
```
=> parametric: remove noisy debug log

pyproject.toml, tests/parametric/conftest.py, tests/parametric/test_config_consistency.py, tests/parametric/test_headers_baggage.py, tests/parametric/test_library_tracestats.py, tests/parametric/test_otel_api_interoperability.py, tests/parametric/test_telemetry.py, tests/parametric/test_tracer_flare.py, utils/parametric/spec/tracecontext.py
=> Fix mypy warning

utils/build/docker/nodejs/parametric/server.js, utils/parametric/_library_client.py
- Improve the reliability of opentelemetry tests. This change should reduce the wait time for retrieving spans from the testagent.
- Calls `APMLibrary.otel_flush` in `APMLibrary.__exit__()` for all libraries except cpp (which does not support the otel api).
🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives …
=> parametric: flush finished otel spans when APMLibrary contextmanager exits

.github/workflows/run-end-to-end.yml, tests/test_distributed.py
this scenario was skipped for python because it was causing a segfault. It's now fixed
=> [python] Re-enable trace_propagation_style_w3c scenario

manifests/nodejs.yml, tests/appsec/test_asm_standalone.py
=> [nodejs] Enable test_telemetry_sca_enabled_propagated for nextjs

tests/docker_ssi/test_docker_ssi.py
https://github.com/DataDog/dd-trace-js/blob/d6d23d6a359d7ac757e36d6210948658d1ccb133/init.js#L9-L16
=> [nodejs] skip docker_ssi telemetry_abort test for unsupported node.js versions

requirements.txt, tests/parametric/test_otel_api_interoperability.py, tests/parametric/test_otel_span_methods.py, tests/parametric/test_parametric_endpoints.py, utils/build/docker/dotnet/parametric/Endpoints/ApmTestApiOtel.cs, utils/build/docker/golang/parametric/otel.go, utils/build/docker/java/parametric/src/main/java/com/datadoghq/trace/opentelemetry/controller/OpenTelemetryController.java, utils/build/docker/nodejs/parametric/server.js, utils/build/docker/php/parametric/server.php, utils/build/docker/python/parametric/apm_test_client/server.py, utils/build/docker/ruby/parametric/server.rb, utils/dd_constants.py, utils/parametric/_library_client.py
- Use the definitions of SpanKind and Status Code provided by the opentelemetry-api ([link](https://opentelemetry-python.readthedocs.io/en/latest/_modules/opentelemetry/trace.html#SpanKind)).
- Removes SpanKind and StatusCode enums from dd_constants
- Replaces all references to  `dd_constants.SpanKind` and `dd_constants.StatusCode` with `opentelemetry.trace.SpanKind` and `opentelemetry.trace.StatusCode`.
- Updates all parametric apps to support the enum values returned by the python [SpanKind](https://opentelemetry-python.readthedocs.io/en/latest/_modules/opentelemetry/trace.html#SpanKind) enum (the main change here is that otel SpanKind values start at 0 instead of 1).
2. Work on you PR until the CI passes (if something not related to your task is …
=> parametric: avoid redefining otel SpanKind and StatusCode 

tests/appsec/test_automated_login_events.py, tests/appsec/test_event_tracking.py
Dotnet was missing the collection of headers on login manual /auto events
cf https://github.com/DataDog/dd-trace-dotnet/pull/6225
=> [ASM][ASTO] Acitvate some tests: headers are now collected on login events

utils/build/docker/python/parametric/apm_test_client/server.py
- Clean up duplicate class definition
- Renames duplicate SpanInjectArgs to SpanExtractArgs.
=> [python] fix extract headers arg

utils/docker_ssi/docker_ssi_matrix_builder.py
Docker ssi parse results and push dato to FPD should allow failures on CI 
=> Docker SSI allow failures

.gitlab-ci.yml
Right now the nightly pipeline waits for all the `DOCKER_SSI` tests/child_pipelines to complete before running the `onboarding_*` jobs.
We cannot run all of the `onboarding_*` jobs in parallel, but we can kick them off and run them at the same time as the `child_pipelines` job.
Set the first `onboarding_*` stage (`onboarding_ruby`) to define `needs: []` so it doesn't wait for any previous stages before starting.
The remaining stages will run in serial as expected after `onboarding_ruby` and `child_pipelines` has finished.
* Test logic is modified? -> Get a review from RFC owner. We're working on refining the …
=> Improve runtime by running onboarding_ruby parallel to child_pipelines

manifests/nodejs.yml
Test IAST Standalone Upstream propagation once the feature has been implemented correctly.
Enable tests in the Node.js manifest
[APPSEC-55778](https://datadoghq.atlassian.net/browse/APPSEC-55778)
[APPSEC-55778]: …
=> [nodejs] Enable Node.js tests for IAST Standalone Upstream propagation

utils/_context/containers.py
When the key is not length 32, the agent can stops itself : 
https://github.com/DataDog/datadog-agent/blob/90535e90a71d31df934738c8b5738c806ffea8eb/pkg/api/security/security.go#L166
https://github.com/DataDog/system-tests-dashboard/actions/runs/12044074813/job/33580719639#step:49:86
https://datadoghq.atlassian.net/browse/APMSP-1600
Use a fake key with a length of 32 characters …
=> Use a fake API key of length 32

tests/appsec/waf/test_blocking.py
=> [ruby] skip failing tests for APPSEC-56056

.gitlab-ci.yml, lib-injection/build/docker/nodejs/sample-app/child.js, lib-injection/build/docker/nodejs/sample-app/index.js, utils/build/virtual_machine/weblogs/nodejs/provision_test-app-nodejs-08.yml
We found an issue a while back that Node 10 would crash when dd-trace-js was injected. Even though that version has not been supported for a while, it's possible to encounter it in some environments where SSI would be applied. We initially added a complete bailout for versions 0.8 to 10, but now we've added proper bailout with telemetry and logging, so we can now safely run that test on those older versions.
Add Node 0.8 test for installer not supported.
* Framework is modified, or non obvious usage of it …
=> add node 0.8 test for installer not supported

docs/edit/skip-tests.md, tests/test_the_test/test_force_skip.py, utils/_decorators.py
`missing_feature` and `bug` actually execute the test, and ignore failures.
But it may happens that a test triggers a bug in the app that entirely break a payload, preventing other tests to execute. In that case, we don't want those tests to be executed (and yes, we'll loose the easy win feature).
Adds a `force_skip` argument to `@missing_feature` and `@bug`
:rocket: Once …
=> Add force_skip option

tests/appsec/waf/test_blocking.py
Those tests were disabled as a temporary fix:
https://github.com/DataDog/system-tests/pull/3584
This PR should **have** fix those tests:
https://github.com/DataDog/dd-trace-rb/pull/4173
Another thing that needs to be fixed after the update to 1.17.0.0.0:
https://github.com/DataDog/dd-trace-rb/pull/4175
WAF blocking tests are enabled again for ruby. …
=> Ruby: Unskip WAF blocking tests for ruby

tests/appsec/test_automated_login_events.py
To be able to merge: 
https://github.com/DataDog/dd-trace-dotnet/pull/6302/
as per rfc 
https://docs.google.com/document/d/1RT38U6dTTcB-8muiYV4-aVDCsT_XrliyakjtAPyjUpw/
Deactivate old tests, and when new ones exist, activate them
=> [ASM][ATO] deactivate old login to be able to merge 

tests/test_data_integrity.py
Having a correct missing feature decorators in test.
`library=nodejs and weblog_variant=spring-boot-3-native` condition can never be met.
Fix `missing_feature` decorator for `test_trace_header_container_tags`
=> [java] Fix missing feature decorator in data integrity test for java

tests/auto_inject/test_blocklist_auto_inject.py, utils/_features.py
The feature tested "user deny list" is deprecated, and will be removed from the injector.
=> Remove user deny list testing since the feature is deprecated

tests/appsec/test_asm_standalone.py
The meta struct key for iast event wasn't the right one.
[RFC](https://docs.google.com/document/d/1iWQsOfT6Lg_IFyvQeqry9wVmXOE2Yav0X4MgOTk7mks/edit?pli=1&tab=t.0#heading=h.o5gstqo08gu5)
Change from `vulnerability` to `iast`.
=> Fix meta struct key for iast events

manifests/dotnet.yml
Enable dotnet tests for security events in meta struct (both meta struct + fall back to json).
=> [dotnet] Enable tests for metastruct

tests/test_config_consistency.py
Easier to understand the error by looking stdout
More useful logs
=> Better stdout for TRACING_CONFIG_NONDEFAULT test

utils/_context/containers.py
=> Add a warning when DD_API-KEY is not 32 char long

manifests/golang.yml, manifests/nodejs.yml, tests/test_distributed.py
[To connect Synthetics to APM traces](https://docs.datadoghq.com/tracing/other_telemetry/synthetics/?tab=datadog#how-are-traces-linked-to-tests), the following Datadog headers are set:
- `x-datadog-trace-id`
- `x-datadog-parent-id: 0`
- `x-datadog-origin: synthetics` or `x-datadog-origin: synthetics-browser`
- `x-datadog-sampling-priority: 1`
This weblog test asserts that library tracers continue the trace when they receive this set of headers.
Adds new tests:
- `tests/test_distributed.py::Test_Synthetics_APM_Datadog::test_synthetics`
- `tests/test_distributed.py::Test_Synthetics_APM_Datadog::test_synthetics_browser`
* …
=> [weblog] Add test for Datadog distributed tracing headers where x-datadog parent-id is set to 0

manifests/ruby.yml
=> Fix typo in ruby manifest

manifests/golang.yml
We're disabling DD_TRACE_HTTP_CLIENT_TAG_QUERY_STRING by default in this dd-trace-go PR: https://github.com/DataDog/dd-trace-go/pull/3010, because the http client instrumentation does not have an option to obfuscate the collected query string, which poses a privacy risk to customers.
Test_Config_ClientTagQueryString_Empty is disabled for golang with marker "bug" and a link to a jira card. …
=> [golang] Disable Test_Config_ClientTagQueryString_Empty test

.vscode/settings.json, format.sh, pyproject.toml, requirements.txt
ruff is 
1. faster (be several order of magnitude) 
2. easier to configure
3. offer a formatter
Replace pylint by ruff, and configure it to be a inplace replacment. Later PR will remove all ignored rules that should not be ignored
=> Replace pylint by ruff for lint

tests/test_config_consistency.py
As of this [open PR](https://github.com/DataDog/dd-trace-go/pull/3010), dd-trace-go disables query tag collection on http.client spans by default, and there is not support for obfuscating the query string tag on the http client side.
Disables test_query_string_obfuscation_empty_client for golang with `missing_feature`
🛟 …
=> [golang] Disable test_query_string_obfuscation_empty_client test

utils/_features.py
The feature id of RASP command command injection should be corrected. The right feature value is 345.
=> Fix feature id

tests/test_profiling.py
[PROF-11018](https://datadoghq.atlassian.net/browse/PROF-11018)
[PROF-11018]: https://datadoghq.atlassian.net/browse/PROF-11018?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [python] Skip profiling for main branch PROF-11018

tests/debugger/test_debugger_exception_replay.py, tests/debugger/test_debugger_expression_language.py, tests/debugger/test_debugger_pii.py, tests/debugger/test_debugger_probe_snapshot.py, tests/debugger/utils.py, utils/build/docker/python/flask/debugger_controller.py
Remove inconsistency in EL tests
Disable exception replay tests
After sending requests, wait for all probes have "EMITTING" status
=> [Debugger] Wait for probe to be EMITTING + temporary disable exception replay

docs/scenarios/k8s_lib_injection.md
Fix the lint failures on the k8s documentation
=> k8s documentation fix lint

manifests/nodejs.yml
we need this to merge our new feature PR in our repo, we'll activate the new tests after :+1:
=> [nodejs] put old login events tests as irrelevant for now

manifests/cpp.yml, manifests/dotnet.yml, manifests/golang.yml, manifests/java.yml, manifests/nodejs.yml, manifests/php.yml, manifests/python.yml, manifests/ruby.yml, tests/parametric/test_config_consistency.py, tests/parametric/test_parametric_endpoints.py, utils/build/docker/java/parametric/src/main/java/com/datadoghq/trace/controller/TraceController.java, utils/build/docker/nodejs/parametric/server.js, utils/build/docker/python/parametric/apm_test_client/server.py, utils/parametric/_library_client.py
Adding tests for tracing configs to make sure implementation across all languages are consistent, based upon the following [RFC](https://docs.google.com/document/d/1kI-gTAKghfcwI7YzKhqRv2ExUstcHqADIWA4-TZ387o/edit?tab=t.bkepxflevyzs#heading=h.1j9ifwq5at9y).
- Add test cases for when `DD_DOGSTATSD_HOST` and `DD_DOGSTATSD_PORT` are specified, as well as when neither are included.
- Updated `test_library` `tracing/config` endpoint helper to include these fields for parametric apps
- Updated Java, Python, and NodeJS `tracing/config` endpoint in parametric apps to support the behavior
- Updated all manifest files in order to reflect the current expected behavior of the tests
[APMAPI-948](https://datadoghq.atlassian.net/browse/APMAPI-948) …
=> Adding Parametric tests for DOGSTATSD Configurations

.github/workflows/run-parametric.yml
=> Disable parametric scenario on dev/.NET

manifests/nodejs.yml, tests/appsec/iast/sink/test_nosql_mongodb_injection.py
=> [nodejs] Fix some easy wins

docs/weblog/README.md, manifests/cpp.yml, manifests/dotnet.yml, manifests/golang.yml, manifests/java.yml, manifests/nodejs.yml, manifests/php.yml, manifests/python.yml, manifests/ruby.yml, tests/appsec/test_automated_user_and_session_tracking.py
Add tests to validate the user and session tracking/blocking functionality as described in the [RFC](https://docs.google.com/document/d/1RT38U6dTTcB-8muiYV4-aVDCsT_XrliyakjtAPyjUpw)
=> Add tests for user and session tracking/blocking

utils/interfaces/schemas/library/debugger/v1/diagnostics-request.json
Update the diagnostics schema to match the [RFC](https://docs.google.com/document/d/1mAyR2LHKE8W89BoLZ5qFpQNTJ6l6t9QQiDPC-YoGD4Y/edit).
The root `message` property is not expected.
=> [Debugger] Remove message field from diagnostics schema

utils/build/virtual_machine/provisions/auto-inject/auto-inject_installer_manual.yml, utils/build/virtual_machine/provisions/auto-inject/repositories/autoinstall/execute_install_script.sh
We want to remove the dependency on the aws ecr creds helper in the installer
changes the registries to use public ones:
- install.datadoghq.com (default)
- install.datad0g.com
- installtesting.datad0g.com
=> upgrade(onboarding): Stop using QA registry, use install{testing}.datad0g.com

manifests/python.yml, tests/debugger/test_debugger_expression_language.py, tests/debugger/test_debugger_probe_snapshot.py, tests/test_schemas.py, utils/build/docker/dotnet/weblog/Controllers/DebuggerController.cs, utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/debugger/DebuggerController.java, utils/build/docker/python/flask/debugger_controller.py
The `python` bugs have been resolved, so this PR restores the relevant system tests
Removed all Python test decorators marked with `bug`.
Split hash tests into a separate group, as this feature is still under discussion.
Adjusted tests and controller to ensure consistent behavior across all libraries.
=> [Debugger] Enable python tests

.github/workflows/run-parametric.yml, utils/build/docker/dotnet/parametric/Endpoints/ApmTestApi.cs
The .NET parametric app stopped working after https://github.com/DataDog/dd-trace-dotnet/pull/6415 was merged, breaking the parametric tests. This PR fixes that issue and re-enabled the parametric scenario for .NET.
- Use reflection to access `TracerSettings` instead of `ImmutableTracerSettings`, since the latter was removed.
- Revert https://github.com/DataDog/system-tests/pull/3674 to re-enabled .NET parametric scenario …
=> [.NET][parametric] Fix reflection issue in .NET parametric app 

utils/build/docker/java/akka-http.Dockerfile, utils/build/docker/java/play.Dockerfile, utils/build/docker/java/vertx4.Dockerfile
Avoid installing libarchive-tools, not needed anymore (it was previously used to extract jars, but we now use java). This avoids apt-get flakiness, and a superfluous setup step.
=> [java] Avoid apt-get for libarchive-tools

utils/_context/_scenarios/__init__.py, utils/_context/_scenarios/endtoend.py
- Having IAST enabled can lead to appsec_runtime_activation scenario behaving incorrectly, masking actual issues.
- Example:
- When running `tests/appsec/rasp/test_lfi.py` and IAST enabled, the test passes incorrectly.
- This happens due to a limitation in the current Java tracer implementation, which doesn't support hot instrumentation for LFI exploit prevention.
- With IAST enabled, instrumentation for LFI prevention occurs at startup (shared with RASP), creating a false impression that the functionality works as expected when it does not.
Jira ticket: [APPSEC-55649]
- **Disables IAST in appsec_runtime_activation** 
* …
=> Disable IAST in appsec_runtime_activation scenario

utils/build/docker/dotnet/parametric/Endpoints/ApmTestApi.cs
Improve reliability and readability. Follow-up from #3680.
- remove unused reflection (reduce chance of #3680 happening again)
- add null annotations and null checks (reduce change of null reference exceptions)
- make members `private` where possible
- general clean-up of C# code syntax and style
🛟 …
=> [.NET][parametric] code clean up in .NET parametric app 

utils/build/docker/java/spring-boot-3-native.Dockerfile
Avoid apt-get update/install, which leads to flakiness on mirror sync.
=> [java] Avoid apt-get in spring-boot-3-native

manifests/ruby.yml, tests/debugger/test_debugger_pii.py, tests/debugger/test_debugger_probe_snapshot.py, tests/debugger/test_debugger_probe_status.py, tests/debugger/utils.py
Initial implementation of dynamic instrumentation in Ruby.
https://github.com/DataDog/system-tests/pull/3516 added the needed controller implementation for dynamic instrumentation system tests and adjusted the tests to work with the feature as implemented in Ruby. However, that PR did not turn on the tests for any tracer version.
Now that https://github.com/DataDog/dd-trace-rb/pull/4098 is merged, DI is usable in Ruby once the environment variable to enable it is set, and the feature will be shipped with the next tracer version (2.8.0).
This PR enables the dynamic instrumentation tests for Ruby tracer 2.8.0 or higher.
The companion PR to this one is https://github.com/DataDog/dd-trace-rb/pull/4146 which adds the scenarios to the list of scenarios to be executed in the Ruby tracer CI.
This …
=> DEBUG-3180 enable Ruby dynamic instrumentation tests

.github/CODEOWNERS, tests/telemetry_intake/update.sh
Simplifies the review cycle for updating these files by making it so that anyone can approve
These should only be copy-pasta from dd-go so it should be non-impactful
Just updates CODEOWNERS
=> [skipci] apm-ecosystems as CODEOWNERS for static files

manifests/nodejs.yml
Update manifest file to reflect minimum nodejs version for #3657
=> [nodejs] Specify minimum version for Test_Config_ClientIPHeaderEnabled_False

docs/edit/runbook.md, tests/test_telemetry.py
Added a runbook for a new test that is likely to fail
Just adds a runbook 😄 
=> Add runbook for config telemetry completeness

utils/build/docker/dotnet/weblog/Controllers/IastController.cs
The test test_command_injection.test_secure has been reported as flaky. This test just executed a not tainted command. so IAST should not be involved, and tests that there is no IAST trace in the span.
The error that happens from time to time is that the controller cannot execute the command "ls" and returns an error code. While it is not clear why that happens, it does not seem to be related to IAST. Anyway, the command injection code that is used in RASP has been brought to IAST. The twin command injection RASP controller methods are not flaky, they handle better the error situations and are more legible.
With this change, we expect the flaky test to stop being flaky while we improve the quality of the code.
2. Work on you PR until the CI passes (if …
=> [dotnet] Refactor IAST command injection tests

tests/debugger/test_debugger_expression_language.py, tests/debugger/test_debugger_pii.py, tests/debugger/test_debugger_probe_snapshot.py, tests/debugger/test_debugger_probe_status.py, tests/debugger/utils.py
Check for EMITTING status instead of INSTALLED
Recently, I introduced a feature to wait for probes to reach the emitting status, but I never actually checked if the status was emitting. This PR adds the missing check.
=> [Debugger] Check EMITTING probe status

utils/_context/_scenarios/parametric.py, utils/build/docker/dotnet/GetAssemblyVersion/GetAssemblyVersion.csproj, utils/build/docker/dotnet/GetAssemblyVersion/Program.cs, utils/build/docker/dotnet/install_ddtrace.sh, utils/build/docker/dotnet/parametric/system_tests_library_version.sh, utils/build/docker/dotnet/poc.Dockerfile, utils/build/docker/dotnet/uds.Dockerfile, utils/build/docker/dotnet/weblog/Endpoints/HealthcheckEndpoint.cs, utils/build/docker/dotnet/weblog/app.csproj
We had an issue in .NET where we reported the wrong library version (or it was in an invalid format, unclear). I couldn't reproduce this issue, but while we were all looking into it, we noticed we could make several improvements to how we detect and report the library version to prevent this from happening and making everything less brittle.
The main issue is that we currently use the `strings` tool from the `binutils` package and a regular expression to extract the first `a.b.c.d` version string from `Datadog.Trace.dll`. This is not great since a string in that format could be found multiple times all over the file and we have no guarantee that we are using the correct one. Also, we were saving this string into a file and reading it from several places, even though in .NET we can access …
=> [dotnet] change how we get library version

manifests/python.yml, utils/build/docker/python/parametric/apm_test_client/server.py
Enabled baggage tests in manifests. Also, updated extract endpoint to consider case where only baggage is being propagated with no span id. 
=> [Python] Enable baggage tests and fix extract endpoint

docs/RFCs/manifest.md, manifests/cpp.yml, manifests/dotnet.yml, manifests/golang.yml, manifests/java.yml, manifests/nodejs.yml, manifests/parser/schema.json, manifests/php.yml, manifests/python.yml, manifests/ruby.yml
Follow up to: https://github.com/DataDog/system-tests/pull/3551.
Use incomplete_test_app to document scenarios where test apps are not up to spec. 
Note: `incomplete_test_app` does not mean a feature is supported. It only documents the state where test apps have clear gaps.
🛟 …
=> add incomplete_test_app to manifest files

conftest.py
=> Fix scenario determinism

manifests/java.yml
In preparation for enabling V3 we have to disable V2 tests first, this is the first PR part of a three way merge:
1. First disable automated login events V2 tests (this PR)
2. Add support for for the V3 in the java tracer ([PR](https://github.com/DataDog/dd-trace-java/pull/8108))
3. Enable automated login events V3 tests ([PR](https://github.com/DataDog/system-tests/pull/3730))
Disables automated login events V2 test suite. …
=> [Java] Disable automated login events V2 tests in preparation for V3

.github/workflows/ci.yml, .github/workflows/run-end-to-end.yml, .github/workflows/run-graphql.yml, .github/workflows/run-open-telemetry.yml, .github/workflows/system-tests.yml, conftest.py, docs/edit/scenarios.md, docs/execute/skip-empty-scenario.md, utils/_context/_scenarios/core.py, utils/_context/_scenarios/docker_ssi.py, utils/_context/_scenarios/endtoend.py, utils/_context/_scenarios/external_processing.py, utils/_context/_scenarios/open_telemetry.py
=> Add an option that skip all tests if scenario contains only xfail/skip

tests/appsec/test_automated_user_and_session_tracking.py
ASM_DD is not really supposed to support the `rules_data` field.
Move the `rules_data` WAF blacklists in appsec RC tests, from the `ASM_DD` RC product to the `ASM_DATA` one.
=> use ASM_DATA instead of ASM_DD for blacklists

tests/debugger/test_debugger_exception_replay.py
hoisting is disabled waiting for make it safer
=> [java] Disable exception replay inner scenario

tests/debugger/probes/expression_probe_base.json, tests/debugger/probes/pii.json, tests/debugger/probes/pii_line.json, tests/debugger/probes/probe_snapshot_log_line.json, tests/debugger/probes/probe_snapshot_log_method.json, tests/debugger/probes/probe_snapshot_log_mixed.json, tests/debugger/probes/probe_snapshot_span_decoration_line.json, tests/debugger/probes/probe_snapshot_span_decoration_method.json, tests/debugger/probes/probe_snapshot_span_method.json, tests/debugger/probes/probe_status_log.json, tests/debugger/probes/probe_status_metric.json, tests/debugger/probes/probe_status_span.json, tests/debugger/probes/probe_status_spandecoration.json, utils/_context/_scenarios/endtoend.py
All probes sent via Remote Config should have a root `version` property. For some reason, one was not present in our mocked probe configs located in `tests/debugger/probes`. I'm not sure why this hasn't resulted in system test errors previously since the diagnostics schema expects that a version is reported. However, without this, at least the Node.js tracer, would set `version: undefined` in the object before it was serialized to JSON, which would completely remove the `version` property from the JSON output.
Maybe they other tracers fall back to `0` if there's no `version` property in the probe config?
This is a re-creation of #3581 which had to be reverted because of changes to `tests/remote_config/rc_mocked_responses_live_debugging.json` and …
=> [Debugger] Ensure all probes have a version property

pyproject.toml, utils/_context/virtual_machines.py, utils/_decorators.py, utils/cgroup_info.py, utils/onboarding/injection_log_parser.py, utils/parametric/spec/tracecontext.py, utils/proxy/core.py, utils/scripts/markdown_logs.py, utils/tools.py
=> Activate ANN002, ANN206, PTH102, PTH119

manifests/cpp.yml, manifests/dotnet.yml, manifests/golang.yml, manifests/java.yml, manifests/nodejs.yml, manifests/php.yml, manifests/python.yml, manifests/ruby.yml, tests/parametric/test_dynamic_configuration.py
Some tracing libraries added checks for matching `service` and `env` in remote config payloads. For example, https://github.com/DataDog/dd-trace-java/pull/6636/. This causes issues in scenarios like SSI where the `env` (aka `DD_ENV`) is configured in the agent, but not on the tracer. The Java tracer is rejecting remote sampling rules in SSI, which prevents Adaptive Sampling from working correctly.
See also [APM_TRACING matching & SSI](https://docs.google.com/document/d/1lcrWRvd3n7Yxa-GiFq7GV1le2a43nfAvw5Iah1ACHzI/) 🔒
Add a new test that asserts that the tracing library accepts a remote config payload without checking for matching `service` or `env`, since that is already handled by the agent.
2. Work on you PR until the CI passes (if something not related …
=> [parametric] add remote config tests with empty `DD_SERVICE` or `DD_ENV`

docs/edit/runbook.md, tests/test_telemetry.py
The runbook was missed, so drawing more attention to it
Update the text for the test failure
=> Improve docs for telemetry completeness tests

manifests/python.yml, tests/appsec/rasp/test_cmdi.py, utils/build/docker/python/django/app/urls.py, utils/build/docker/python/fastapi/main.py, utils/build/docker/python/flask/app.py, utils/interfaces/_library/core.py
APPSEC-56275
Once https://github.com/DataDog/dd-trace-py/pull/11870 merged, this PR will enable all missing tests for Exploit Prevention for python
=> [python] add support for SHi and CMDi tests for python

utils/proxy/_deserializer.py
Surround decompression with try..catch + strip ".gz" from filename
=> Surround decompression with try..catch + strip ".gz" from filename

.github/CODEOWNERS
I think the old CODEOWNERS is a legacy setting and that it actually should be the guild(?)
Change the Node.js CODEOWNERS from @DataDog/apm-js and @DataDog/asm-js to @DataDog/dd-trace-js
=> Change Node.js CODEOWNERS to the Node.js guild

tests/appsec/iast/source/test_parameter_name.py
fix APPSEC-55689. Update test from bug to missing feature
=> [python] update test from bug to missing feature

docs/weblog/README.md, manifests/cpp.yml, manifests/dotnet.yml, manifests/golang.yml, manifests/java.yml, manifests/nodejs.yml, manifests/php.yml, manifests/python.yml, manifests/ruby.yml, tests/appsec/iast/test_security_controls.py, utils/_context/_scenarios/default.py, utils/_features.py, utils/build/docker/java/akka-http/src/main/scala/com/datadoghq/akka_http/IastRoutes.scala, utils/build/docker/java/iast-common/src/main/java/com/datadoghq/system_tests/iast/utils/SecurityControlUtil.java, utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/IastSinkResource.java, utils/build/docker/java/resteasy-netty3/src/main/java/com/datadoghq/resteasy/IastSinkResource.java, utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/AppSecIast.java, utils/build/docker/java/vertx3/src/main/java/com/datadoghq/vertx3/iast/routes/IastSinkRouteProvider.java, utils/build/docker/java/vertx4/src/main/java/com/datadoghq/vertx4/iast/routes/IastSinkRouteProvider.java
Add Iast security controls system tests for Milestone 0 ([RFC](https://docs.google.com/document/d/1j1hp87-2wJnXUGADZxzLnvKJmaF_Gd6ZR1hPS3LVguQ/edit?pli=1&tab=t.0))
New test_security_controls.py that covers all the RFC test cases
`DD_IAST_SECURITY_CONTROLS_CONFIGURATION` variable will differ for each tracer, as it represents the configuration of the security controls. For instance, in Java, a possible value could be:
`INPUT_VALIDATOR:COMMAND_INJECTION:bar.foo.CustomInputValidator:validate`,
whereas for Node.js it might be:
`INPUT_VALIDATOR:COMMAND_INJECTION:bar/foo/custom_input_validator.js:validate`.
* Test logic is …
=> Add IAST Security Control tests for java springboot

utils/virtual_machine/utils.py
Push onboarding results to fpd using the ci_job_url instead of ci_pipieline_url
=> Onboarding: FPD use job url instead of pipeline url

manifests/python.yml
Support for V3 (last RFC) will be merged soon in dd-trace-py.
As those changes are incompatible with V2 tests, V2 tests need to be disabled first.
V3 tests will be enabled after that.
APPPSEC-56315
=> [python] deactivate v2 ATO tests

manifests/java.yml, tests/appsec/test_asm_standalone.py
We want to increase our percentage of easy wins in Java.
We have activated some easy wins for the following tests:
- `tests/appsec/test_asm_standalone.py::Test_SCAStandalone_Telemetry`
- `tests/appsec/test_automated_login_events.py::Test_V3_Login_Events`
- `tests/appsec/test_automated_login_events.py::Test_V3_Login_Events_Anon`
- `tests/appsec/test_automated_login_events.py::Test_V3_Login_Events_Blocking`
- `tests/appsec/test_automated_login_events.py::Test_V3_Login_Events_RC`
- `tests/appsec/test_automated_user_and_session_tracking.py::Test_Automated_User_Blocking`
- `tests/appsec/test_automated_user_and_session_tracking.py::Test_Automated_User_Tracking`
2. Work on you PR until the CI passes (if something not related to your task is failing, you can …
=> [java] Activate new batch of easy wins

manifests/java.yml, utils/build/docker/java/vertx3/src/main/java/com/datadoghq/vertx3/Main.java, utils/build/docker/java/vertx4/src/main/java/com/datadoghq/vertx4/Main.java
Test session tracking support in Vert.x 3.x and 4.x
Add required endpoints to weblogs and enable tests in the manifest.
=> [Java] Enable session fingerprinting tests in vertx

docs/architecture/test_template.py
The `@irrelevant` example in the test template uses a single `=` for comparison, where it should should two (`==`) - at least that's what I think. Please correct me if I'm wrong 😅 
=> Fix @irrelevant example in test template

tests/test_span_events.py
I copied and pasted the method name, and named it `setup` instead of `test` 😢.
=> Fix typo in test method name

tests/parametric/test_dynamic_configuration.py
This dd-trace-java [PR](https://github.com/DataDog/dd-trace-java/pull/8176) reverts filtering of `DD_SERVICE` and `DD_ENV`. In order for the PR to continue, the tests expecting the removed behavior must be first disabled.
=> [Java] Disable remote-config tests for setting `DD_ENV` and `DD_SERVICE`

utils/proxy/_deserializer.py
When the content of a payload is a multipart, each part is exported  to a separated file. Though, this file may be a `json` file. In that situation, having the content directly inside the data will allow to : 
* make schema validations
* directly make assertion on the content, without the need to read and load another file
Before : 
```json
{
"headers": {
"Content-Type": "application/gzip",
"Content-Disposition": "form-data; name=\"file\"; filename=\"symbols_34.json.gz\""
},
"system-tests-information": "File exported to a separated file",
"system-tests-file-path": "logs_debugger_symdb/interfaces/library/files/aa69f5aba727cfc64324b3956098f242_symbols_34.json"
}
```
After : 
```json
{
"headers": {
"Content-Type": "application/gzip",
"Content-Disposition": "form-data; name=\"file\"; …
```
=> Deserialize JSON in multipart

tests/appsec/test_automated_login_events.py
Although they are marked as easy wins, is irrelevant as blocking by user ID not available in java
Mark as irrelevant tests/appsec/test_automated_login_events.py::Test_V3_Login_Events_Blocking::test_login_event_blocking_auto_id
=> [JAVA] Mark as irrelevant test_login_event_blocking_auto_id

utils/build/docker/nodejs/nextjs.Dockerfile
https://github.com/DataDog/dd-trace-js/pull/5012 will start using esm loader, which is executed in a different worker and makes some test failures because there are more RC calls than expected.
With this change that behaviour will be fixed.
use `--import` instead of `--require` to initialize the tracer.
🛟 …
=> [nodejs] Use --import instead of --require in nextjs app

manifests/nodejs.yml, tests/debugger/test_debugger_probe_snapshot.py
More test coverage.
Enable the `express4` Node.js tests for `Test_Debugger_Probe_Snaphots` (Dynamic Instrumentation)
=> [nodejs] Enable DI line probe snapshot tests

docs/weblog/README.md, tests/appsec/test_automated_user_and_session_tracking.py, utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/security/AppSecAuthenticationFilter.java, utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/security/AppSecAuthenticationProvider.java, utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/security/AppSecToken.java
Customers can initiate login events via the SDK at any moment. Given that SDK-generated events should be prioritized over automated ones, we need to ensure that everything functions correctly when the SDK event occurs both first and last.
Introduces a new optional parameter to the login endpoint, allowing tests to select when to generate the SDK event.
:rocket: Once your …
=> Add a parameter to define when to trigger SDK events

tests/appsec/test_blocking_addresses.py
We are changing the way we are doing blocking for GraphQL in Ruby:
https://github.com/DataDog/dd-trace-rb/pull/4300
https://datadoghq.atlassian.net/browse/APPSEC-56464
This PR removes special case for response status code assertion for Ruby when GraphQL response is being blocked.
🛟 …
=> [ruby] Remove special handling of GraphQL response status code

manifests/java.yml
Fix easy wins for tests/appsec/test_blocking_addresses.py::Test_Blocking_response_status
=> [JAVA] Enable Test_Blocking_response_status for xpassed variants

utils/build/docker/dotnet/weblog/Models/Debugger/Pii.cs, utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/debugger/Pii.java, utils/build/docker/java_otel/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/debugger/Pii.java, utils/build/docker/python/flask/debugger/pii.py, utils/build/docker/ruby/rails70/app/models/pii.rb
Align the individual test apps for the different programming languages with the main test file.
This has already been removed in the PII test file in the following PR: https://github.com/DataDog/system-tests/pull/3827
Remove `env` from the following language apps:
- Python
- Ruby
- .NET
- Java
🛟 …
=> Remove env token from DI PII lists in each tracer app

manifests/python.yml, tests/appsec/test_asm_standalone.py
As we need more data to understand when it's failing, moving the appsec standalone tests for python from flaky (skipped) to bug (that will still be runned)
APPSEC-56162
=> [python] appsec standalone from flaky to bug

.github/workflows/run-end-to-end.yml, manifests/dotnet.yml, manifests/golang.yml, manifests/java.yml, manifests/nodejs.yml, manifests/php.yml, manifests/python.yml, manifests/ruby.yml, tests/appsec/test_asm_standalone.py, utils/_context/_scenarios/__init__.py, utils/_features.py
A new [RFC](https://docs.google.com/document/d/18JZdOS5fmnYomRn6OGer0ViS1I6zzT6xl5HMtjDtFn4) defines a new method to disable APM tracing while enabling other products. This PR defines the new scenarios, features and tests for those cases.
=> [ASM] Added Standalone Billing V2 tests

tests/appsec/test_conf.py, utils/_context/_scenarios/__init__.py, utils/_context/_scenarios/appsec_low_waf_timeout.py, utils/build/docker/java/play/conf/routes, utils/scripts/compute_impacted_scenario.py
Fix easy wins in tests/appsec/test_conf.py:
- test_disabled
- test_waf_timeout
The tests were unreliable as they only checked for the absence of an AppSec event, this is not enough as an unimplemented endpoint or a bad request pass the test
For instance the intention in test_waf_timeout is to verify that there is no event because of a timeout in the WAF. Instead, the requests were malformed, leading to errors (various 400s) and not being processed correctly.
- test_disabled
- Added a status check for the response to ensure the request is valid and the endpoint is implemented. 
- Excluded Sinatra variants in Ruby, which were causing 404 errors. 
- test_waf_timeout
- Added a status check for the response to ensure the request is valid and the endpoint is implemented.
- Excluded Sinatra …
=> Fix tests/appsec/test_conf.py

tests/parametric/conftest.py, tests/parametric/test_dynamic_configuration.py, tests/parametric/test_tracer_flare.py, utils/parametric/spec/remoteconfig.py
=> Improve RC code for parametric scenario, clarify APMAPI-1003

tests/parametric/test_dynamic_configuration.py
This is not a bug.
Fix the annotation for this test. This test was disabled in #2962 (Jira ticket was added in #3371). The test broke with the update to .NET tracing library 3.x, but this change was intentional.
```
tests/parametric/test_dynamic_configuration.py::TestDynamicConfigTracingEnabled::test_tracing_client_tracing_disable_one_way
``` …
=> [dotnet] fix annotation for `DD_TRACE_ENABLED` remote config test

manifests/golang.yml
As of v1.72.0-dev, dd-trace-go passes the Test_Config_ClientTagQueryString_Empty test, thanks to this [PR](https://github.com/DataDog/dd-trace-go/pull/3071).
Enables Test_Config_ClientTagQueryString_Empty test for dd-trace-go v1.72.0-dev.
=> [Golang] Enable Test_Config_ClientTagQueryString tests

utils/onboarding/backend_interface.py
#3847 unfortunately breaks profiling tests as they need to keep retrying even when they receive a HTTP 200 response, dependent on what's in the response body. 
We introduce a content validator parameter for `_make_request` and have `_query_for_profile` pass in a suitable one that validates profiling API responses.
🛟 …
=> Fix retry logic for profiling tests by introducing a content validator

utils/build/docker/python/django/app/urls.py, utils/build/docker/python/fastapi/main.py, utils/build/docker/python/flask/app.py, utils/build/docker/python/flask/integrations/messaging/rabbitmq.py, utils/build/docker/python/parametric/apm_test_client/server.py, utils/build/docker/python/pylons/app/app/config/middleware.py, utils/build/docker/python/pylons/app/app/controllers/identify.py, utils/build/docker/python/pylons/app/app/controllers/waf.py
Prep for ddtrace v3.0
Import tracing attributes from `ddtrace.trace` instead of `ddtrace`
=> [python] remove deprecated imports

tests/k8s_lib_injection/test_k8s_lib_injection.py
There are failures in the nightly build:
- We are calling to profiling endpoint when we shouldn't
- A bug for python and cluster agent 7.56.2
=> K8s Lib Injection: Profiling fixes and bugs

utils/build/docker/python/parametric/apm_test_client/server.py
`ddtrace/context.py` will be removed in v3.0. This change ensures parametric tests do not rely on deprecated logic.
- Import Context from `ddtrace.trace.Context`
=> [python] remove deprecated module from parametric app

.github/workflows/ci.yml
Get back the language aggregation in github action
Before : all langs are aggregated on a single "System Tests" job
After : each lang + dev/prod got it single group : 
Small  revert on job name from #3675 
=> Fix job name

utils/onboarding/backend_interface.py
There was a bug in #3901 that used the query interval that was okay with the old retry strategy (where we'd construct a new 2 minute interval up to current time on every request). Now, however, we only construct one query and pass it to the retrying method, so the query interval needs to cover the entirety of the retry period to be able to observe profiles arriving later.
Instead of `[now - 2 minutes, now]` the query period is now `[now - 6 minutes, now + 6 minutes]` for good measure. Technically, `[now, now + 5 minutes]` should be sufficient, but let's be conservative, event platform doesn't break a sweat querying a 12 minute interval instead of 5. …
=> Fix query time interval for validating profiler tests

manifests/golang.yml
Initially planned for 1.72.0, standalone ASM v1 was able to make it into v1.71.0.
Updates the manifest to enable the Standalone ASM propagation v1 test on v1.71.0.
=> [golang] standalone appsec propagation (v1) was released in v1.71.0

tests/auto_inject/test_auto_inject_install.py
Marking it as a known failure will restore green tests.
JIRA: [PROF-11264]
[PROF-11264]: https://datadoghq.atlassian.net/browse/PROF-11264?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Mark Node.js webapp as failing on Ubuntu 24 for host profiling scenario

pyproject.toml, run.sh, utils/build/build.sh, utils/build/docker/runner.Dockerfile
#3918
* `build.sh` : copy `requirements.txt` to `venv/`
* `run.sh` : compare `requirements.txt` and `venv/requirements.txt`. If they differ, or if the second is missing, call `./build.sh -i runner`
(not if docker mode or nix mode)
=> Automate runner install/update #3918

tests/auto_inject/test_auto_inject_install.py
This reverts commit 16451bf95c8a52655cf7971e3fe607b32252b692.
#3936 was a red herring based on January 29 nightly run, and those failures were fixed later that day with #3915.
Undoes the addition of bug specifications for `simple_auto_injection_profiling`, they are not needed.
🛟 …
=> Revert "Onboarding: nodejs profiling bug decorators (#3936)"

manifests/cpp.yml, manifests/dotnet.yml, manifests/golang.yml, manifests/java.yml, manifests/nodejs.yml, manifests/php.yml, manifests/python.yml, manifests/ruby.yml, tests/integrations/test_otel_drop_in.py, tests/otel/test_context_propagation.py, utils/_features.py, utils/build/docker/dotnet/weblog/Endpoints/OtelDropInEndpoint.cs, utils/build/docker/dotnet/weblog/OpenTelemetryInstrumentation.cs, utils/build/docker/dotnet/weblog/Startup.cs, utils/build/docker/dotnet/weblog/app.csproj, utils/build/docker/golang/app/net-http/main.go, utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/App.java, utils/build/docker/nodejs/express/app.js, utils/build/docker/nodejs/express/package-lock.json, utils/build/docker/nodejs/express/package.json, utils/build/docker/python/flask/app.py, utils/build/docker/ruby/rails70/Gemfile, utils/build/docker/ruby/rails70/Gemfile.lock, utils/build/docker/ruby/rails70/app/controllers/system_test_controller.rb, utils/build/docker/ruby/rails70/config/initializers/datadog.rb, utils/build/docker/ruby/rails70/config/routes.rb
We learned that there was an issue with this support in the .NET tracing library, so this new test/endpoint will identify whether other tracers have the same class of issue.
In the .NET scenario, the customer can use the OpenTelemetry Propagators API (implemented in the OpenTelemetry API package) to manually propagate context. When the OpenTelemetry SDK is configured (using the OpenTelemetry SDK package) in the application, the default propagator provided by the OpenTelemetry Propagators API is provided a default implementation, so propagation works as expected. However, when the OpenTelemetry SDK is removed and the user relies on the .NET tracer's OTEL Drop-In Support, the default propagator provided by the OpenTelemetry Propagators API is a no-op, resulting in no propagation happening. …
=> [Tracing] Add test and endpoints to test OTEL Drop-In Support of the OpenTelemetry Propagators API

manifests/php.yml, utils/build/docker/php/common/php.ini, utils/build/docker/php/common/rasp/ssrf.php
=> [PHP] Enable SSRF tests 

.github/workflows/ci.yml, .github/workflows/compute-workflow-parameters.yml, .github/workflows/run-parametric.yml, .github/workflows/system-tests.yml, utils/_context/_scenarios/core.py, utils/_context/_scenarios/parametric.py, utils/scripts/compute-workflow-parameters.py, utils/scripts/compute_impacted_scenario.py
=> Clean compute-workflow-parameters, makes job_count an official parameter for parametric scenario

tests/parametric/test_128_bit_traceids.py, tests/parametric/test_headers_b3.py
ddtrace v3.0 drops support for the deprecated `B3 single header` propagation style. `b3` should be used instead.
- Skips tests and unblocks: https://github.com/DataDog/dd-trace-py/pull/12167
=> [python] skip tests for deprecated b3 envvar

tests/appsec/iast/sink/test_code_injection.py
Enable Telemetry metric instrumented test for Node.js 
=> Enable Nodejs telemetry metric for code injection

manifests/cpp.yml, manifests/dotnet.yml, manifests/golang.yml, manifests/java.yml, manifests/nodejs.yml, manifests/php.yml, manifests/python.yml, manifests/ruby.yml, tests/test_config_consistency.py, utils/_context/_scenarios/__init__.py, utils/build/docker/agent.Dockerfile, utils/build/docker/java/spring-boot-openliberty.Dockerfile, utils/build/docker/java/spring-boot-wildfly.Dockerfile, utils/interfaces/_agent.py
"dogstatsd_non_local_traffic: true" to the agent image and start testing runtime metrics by observing what metrics the agent is sending to the backend
We need to assert some basic functionalities of the Runtime Metrics feature across various tracing libraries.
- Adds the config `dogstatsd_non_local_traffic: true` to the Datadog agent container
- Adds a method in the Agent interface to get the metrics it submits to the `/api/v2/series` backend API
- Implements new tests in classes `Test_Config_RuntimeMetrics_Enabled` and `Test_Config_RuntimeMetrics_Enabled_WithRuntimeId`. Each test case hits an endpoint, waits 10s (that is the default interval for submitting runtime metrics), and asserts properties of the submitted metrics
The end result is that the .NET Tracer and the Java Tracer are …
=> [Tracing] Implement initial weblog tests for the runtime metrics feature

.github/workflows/run-end-to-end.yml, manifests/java.yml, manifests/python.yml, tests/debugger/test_debugger_symdb.py, utils/interfaces/schemas/library/symdb/v1/input-request.json
Make `source_file` optional + make sure debugger controller exists in symbols
=> [Debugger] Make `source_file` optional + make sure debugger controller exists in symbols

tests/appsec/test_asm_standalone.py
=> Fix Standalone Billing values

pyproject.toml, tests/appsec/waf/test_addresses.py, tests/debugger/test_debugger_pii.py, tests/debugger/test_debugger_symdb.py, tests/fuzzer/core.py, tests/integrations/utils.py, tests/parametric/conftest.py, tests/parametric/test_128_bit_traceids.py, tests/parametric/test_dynamic_configuration.py, tests/parametric/test_library_tracestats.py, tests/parametric/test_sampling_span_tags.py, tests/parametric/test_trace_sampling.py, tests/perfs/process.py, tests/remote_config/test_remote_configuration.py, tests/stats/test_stats.py, tests/test_config_consistency.py, tests/test_standard_tags.py, tests/test_the_test/test_scrubber.py
=> Enable ruff rules on tests folder

utils/_features.py
Context Propagation: Extraction has the same feature_id as Security Controls and therefore
FPD is marking as bug a lot of tests not related with Security Controls :sweat_smile:
cc: @zacharycmontoya 
=> fix Context Propagation: Extraction feature_id

manifests/dotnet.yml
Enable Custom Blocking tests for dotnet.
[A fix](https://github.com/DataDog/dd-trace-dotnet/pull/6619) has been deployed in the dotnet tracer for the `test_custom_redirect_wrong_status_code` test that wasn't passing.
=> [dotnet] Enable Custom Blocking Response tests

utils/build/build_python_base_images.sh, utils/build/docker/python/flask-poc.Dockerfile, utils/build/docker/python/flask-poc.base.Dockerfile, utils/build/docker/python/uds-flask.Dockerfile
For some unknown reason `wheel` was missing in v7. As it's required by the new python default dev branch, rebuild the base image 
=> [python] update flask base image

manifests/java.yml, tests/appsec/test_user_blocking_full_denylist.py, utils/scripts/check_version.sh
Fix easy wins in following tests:
- `tests/appsec/waf/test_addresses.py::Test_PathParams`
- `tests/appsec/test_fingerprinting.py::Test_Fingerprinting_Session`
- `tests/appsec/test_metastruct.py::Test_SecurityEvents_Appsec_Metastruct_Disabled`
- `tests/test_standard_tags.py::Test_StandardTagsRoute` …
=> [java] Enabled xpass tests

tests/parametric/test_config_consistency.py
The tracing libraries are expected to parse `DD_TAGS` and assign them as span tags. Since this is both an agent setting and a tracer setting, the parsing logic is not trivial.
This PR refactors the test cases to indicate what the single `DD_TAGS` environment variable is and the resulting pairs of tags set on the spans. …
=> [Tracing] Refactor DD_TAGS test cases for clarity

tests/parametric/test_telemetry.py, utils/_context/_scenarios/__init__.py, utils/_context/containers.py
- Resolve the following test failure: https://github.com/DataDog/dd-trace-py/actions/runs/13144020351/job/36678122864?pr=12176
- Fix telemetry version introduced in an earlier sampling PR
=> update weblog sampling_test use sampling rules instead of deprecated envvar

manifests/python.yml
Metastruct reports for appsec were enabled for the next 3.0 release of python.
=> [python] enable metastruct tests

.gitlab-ci.yml, tests/auto_inject/test_auto_inject_install.py
Python APM library suports DD_PROFILING_ENABLED=auto since 1.37.0, see https://github.com/DataDog/dd-trace-py/pull/9904
Adds the three standard onboarding `_PROFILING` scenarios to the Python test matrix.
=> PROF-10509: Add profiling scenarios to Python onboarding tests

utils/build/docker/python/django/app/urls.py, utils/build/docker/python/fastapi/main.py, utils/build/docker/python/flask/app.py, utils/build/docker/python/flask/integrations/messaging/rabbitmq.py
https://github.com/DataDog/dd-trace-py/pull/12219 removes the tracer parameter from `Pin.override(...)`. In ddtrace>=3.0, the Pin object will always use the global tracer.
=> [python] Avoid passing global tracer to pin in weblog apps

pyproject.toml, tests/apm_tracing_e2e/test_single_span.py, tests/apm_tracing_e2e/test_smoke.py, tests/otel_tracing_e2e/test_e2e.py, tests/parametric/test_span_links.py, tests/parametric/test_tracer.py, tests/perfs/test_performances.py, tests/test_the_test/test_features.py, utils/_features.py
=> All classes must declare feature ids

pyproject.toml, tests/test_profiling.py, utils/_context/_scenarios/endtoend.py, utils/_context/containers.py, utils/scripts/compute_impacted_scenario.py
=> Extend mypy scope

manifests/ruby.yml, tests/appsec/test_ip_blocking_full_denylist.py, tests/appsec/test_user_blocking_full_denylist.py, utils/_context/_scenarios/__init__.py
We are now supporting IP Blocking in ruby with the full denylist.
This PR enables IP Blocking tests for Ruby.
=> [ruby] Enable IP blocking tests for Ruby

.github/workflows/run-end-to-end.yml, manifests/php.yml, tests/appsec/test_asm_standalone.py, utils/_context/_scenarios/__init__.py
The added test is a regression test which caused a incident on PHP. When ASM Standalone was implemented, it was required to send the header `Datadog-Client-Computed-Stats` as `yes` when it was a ASM Standalone request. However the way it was implemented in PHP was to add the header `Datadog-Client-Computed-Stats` always. Then the value  of the header was `yes` when it was a ASM Standalone request and `no` when not. This was generating the agent to never compute stats as it was interpreting the value `no` as if it was `yes`.
* Test logic is modified? -> Get a review from RFC owner. We're working on refining the …
=> Add test to check absence of client computed stats

.github/workflows/ci.yml
=> Use prod agent, dev agent broke lot  of tracers

tests/parametric/test_headers_baggage.py
Made [this temporary change](https://github.com/DataDog/dd-trace-js/pull/5209) to avoid [crashes](https://github.com/DataDog/dd-trace-js/issues/5111), as a result, some baggage functionalities are not working (i.e. we do not support having `baggage` as the only propagation style, or extracting headers which only include baggage).
The disabled tests will be enabled shortly following a later PR creating a different implementation of baggage propagation, which will avoid crashes without compromising on functionality.
* Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file …
=> [NodeJS] skip failing baggage tests

pyproject.toml, tests/apm_tracing_e2e/test_single_span.py, tests/appsec/iast/sink/test_hardcoded_passwords.py, tests/appsec/iast/sink/test_hardcoded_secrets.py, tests/appsec/iast/utils.py, tests/appsec/rasp/utils.py, tests/auto_inject/test_blocklist_auto_inject.py, tests/debugger/test_debugger_expression_language.py, tests/debugger/utils.py, tests/docker_ssi/test_docker_ssi.py, tests/fuzzer/corpus.py, tests/integrations/utils.py, tests/parametric/conftest.py, tests/parametric/test_config_consistency.py, tests/parametric/test_headers_baggage.py, tests/parametric/test_span_sampling.py, tests/parametric/test_telemetry.py, tests/test_config_consistency.py, tests/test_telemetry.py, tests/test_the_test/test_conventions.py
=> Activate ruff rules on tests/ folder

manifests/nodejs.yml, tests/appsec/iast/sink/test_untrusted_deserialization.py
Easy win for Node.js untrusted deserialization stack trace system test
1. Change test URL
2. Change dd-trace-js version 
=> [Nodejs] Enable untrusted deserialization stack trace test for Node.js

.github/workflows/ci.yml, .github/workflows/run-end-to-end.yml, tests/test_data_integrity.py, utils/interfaces/_core.py, utils/interfaces/_library/core.py
=> Revert agent dev fix

tests/parametric/test_headers_baggage.py
Skip tests that were not skipped by this [PR](https://github.com/DataDog/system-tests/pull/4015)
Did not realize `dd_make_child_span_and_get_headers` calls `dd_extract_headers_and_make_child_span`, which is made temporarily not working by this [PR](https://github.com/DataDog/dd-trace-js/pull/5209)
🛟 …
=> [NodeJS] skip more failing baggage tests

tests/appsec/waf/test_telemetry.py
Avoid false XPASS on APPSEC_WAF_TELEMETRY, as observed in spring-boot-3-native.
[APPSEC-54879]: https://datadoghq.atlassian.net/browse/APPSEC-54879?atlOrigin=eyJpIjoiNWRkNTlj …
=> Avoid false XPASS on APPSEC_WAF_TELEMETRY

utils/build/build_python_base_images.sh, utils/build/docker/python/django-py3.13.Dockerfile, utils/build/docker/python/django-py3.13.base.Dockerfile, utils/build/docker/python/python3.12.Dockerfile, utils/build/docker/python/python3.12.base.Dockerfile
Use the last patch version of python in the Django weblogs to benefits from the bug fixes.
Also related to APPSEC-56375
=> [python] use last patch version of python for django weblogs

utils/_context/_scenarios/auto_injection.py, utils/_context/virtual_machines.py
Ubuntu 24.04.01 LTS unfortunately has a packaging bug for Node.js (see #4032), so in order to properly test Node.js apps we introduce the latest Ubuntu 24.10.
Adds both an amd64 and arm64 Ubuntu 24.10 VM.
JIRA: [PROF-11264]
[PROF-11264]: …
=> Add Ubuntu 24.10 VMs

utils/build/virtual_machine/weblogs/nodejs/provision_test-app-nodejs-unsupported-defaults.yml, utils/build/virtual_machine/weblogs/nodejs/provision_test-app-nodejs.yml
Do not run `test-app-nodejs` on Ubuntu24 (really, 24.04.01 LTS) because… its packaged version of Node reports wrong ABI version.
Profiling tests are failing on Ubuntu24. Turns out this is a [known bug with](https://bugs.launchpad.net/ubuntu/+source/nodejs/+bug/2085804) Ubuntu 24.04.01 LTS. It reports wrong ABI version so we can't load the profiler native library (or native metrics, or IAST, etc.)
Adds Ubuntu24 VMs to the exclusion list for `test-app-nodejs`. We'll soon follow up by also adding VMs for Ubuntu 24.10, which fix the problem.
JIRA: [PROF-11264]
* Test logic is modified? -> Get a review from RFC owner. We're …
=> Do not run test-app-nodejs on Ubuntu24

.github/workflows/ci.yml, utils/scripts/get-workflow-summary.py
=> [cpp] Fix all-jobs-are-green-job

tests/auto_inject/test_auto_inject_chaos.py, tests/auto_inject/test_auto_inject_install.py, tests/auto_inject/test_blocklist_auto_inject.py
Fix the ubuntu 24.10 naming on decorators
=> Onboarding: ubuntu 24_10 fixes

manifests/ruby.yml, tests/appsec/waf/test_exclusions.py
as observed in spring-boot-3-native.
Skip on sinatra, since the endpoint is not implemented
[APPSEC-54879]: https://datadoghq.atlassian.net/browse/APPSEC-54879?atlOrigin=eyJp …
=> Avoid false xpass on test_exclusions.py

manifests/python.yml
After the underlying problem was fixed, test must be enabled again.
APPSEC-56142
=> [python] restore test after bug fixed

tests/telemetry_intake/static/config_norm_rules.json
adds config norm rule for auto span linking
dd-go pr https://github.com/DataDog/dd-go/pull/170061
want to make this test pass: https://github.com/DataDog/system-tests/blob/main/docs/edit/runbook.md#test_config_telemetry_completeness
=> [python][mlob] config norm rule for auto span linking

.github/actions/lint_code/action.yaml, .yamlfmt, .yamllint, format.sh, manifests/agent.yml, manifests/cpp.yml, manifests/dd_apm_inject.yml, manifests/dotnet.yml, manifests/golang.yml, manifests/java.yml, manifests/k8s_cluster_agent.yml, manifests/nodejs.yml, manifests/php.yml, manifests/python.yml, manifests/python_otel.yml, manifests/ruby.yml, requirements.txt, utils/scripts/compute_impacted_scenario.py
Address #1722
This adds `yamlfmt` and `yamllint` to add automatic formatting and linting to our yaml files
The reason we need both is because `yamlfmt` cannot check for key ordering while `yamllint` is only a linter so it cannot automatically re-format the files
After this is approved and merged, a follow-up should be done to update `.yamllint` to set `key-ordering` from `disabled` to `enabled` and the existing issues with key ordering should be resolved
* Framework is modified, or non obvious usage of it …
=> Add yamlfmt + yamllint

utils/build/docker/python/django/app/urls.py, utils/build/docker/python/fastapi/main.py, utils/build/docker/python/flask/app.py, utils/build/docker/python/parametric/apm_test_client/server.py, utils/build/docker/python/pylons/app/app/config/middleware.py, utils/build/docker/python/pylons/app/app/controllers/identify.py, utils/build/docker/python/pylons/app/app/controllers/waf.py
Required to test ddtrace<2.20
uses try/except to import ddtrace from the new place fallback to the old place
=> [python] use backwards compatible imports for ddtrace-py

tests/appsec/test_automated_login_events.py
The SDK should take priority over automated login events, this PR ensures that we test both when the SDK event is triggered before and after the automated one.
9 tests are modified:
2 (success/failure) * 2 (local/basic auth) * 2 (identification/anonymous mode) + 1 RC test
🛟 …
=> Add before/after to login tests

manifests/python.yml, utils/build/build_python_base_images.sh, utils/build/docker/python/flask-poc.Dockerfile, utils/build/docker/python/flask-poc.base.Dockerfile, utils/build/docker/python/flask/app.py, utils/build/docker/python/flask/integrations/graphql.py, utils/build/docker/python/uds-flask.Dockerfile, utils/build/docker/python/uwsgi-poc.Dockerfile, utils/build/docker/python/uwsgi-poc.base.Dockerfile
- Adds a `/graphql` endpoint to the flask-poc weblog app
- Enables testing graphql error spans
- Update `flask-poc` and `uwsgi-poc` base images
=> python graphql error spans testing

utils/build/docker/python/parametric/apm_test_client/server.py
These failures when running system-tests on dd-trace-py 2.19 branch:
https://github.com/DataDog/dd-trace-py/actions/runs/13303603625/job/37159774564?pr=12306#step:5:48817
=> [python] backwards compatible imports for dd-trace-py 2.19

manifests/dotnet.yml, manifests/java.yml, manifests/nodejs.yml, manifests/python.yml, tests/appsec/iast/utils.py
The RFC specifies that `stackId` should be placed into the vulnerability location and not into the vulnerability itself, so the test are wrong implemented.
A bug was found in java, nodejs and python tracers related with that so they should be disabled
In addition dotNet is the only one that implements this feature properly so we want to enable for those test to double check 
- Modify test to check the `stackId` into the vulnerability location
- Make test compatible with dotnet
- Disable test for java, python and nodejs
- Enable test for dotnet …
=> Fix IAST vulnerabilities StackTrace tests

manifests/python.yml
=> [python] re-enable Python 3.12 for http.parameter.name

tests/appsec/waf/test_telemetry.py
This adds new tags to the `appsec.waf.requests` test which is necessary for the consolidation of ASM Span Tags, Metrics, and Logs across all supported languages.
Add to the `valid_tag_prefixes` the new tags.
=> Update test_metric_waf_requests with new valid tags

manifests/java.yml
=> [JAVA] enable AppSec Standalone V2 tests

utils/_context/_scenarios/parametric.py, utils/build/docker/golang/app/go.mod, utils/build/docker/golang/app/go.sum, utils/build/docker/golang/chi.Dockerfile, utils/build/docker/golang/echo.Dockerfile, utils/build/docker/golang/gin.Dockerfile, utils/build/docker/golang/go.work, utils/build/docker/golang/gqlgen.Dockerfile, utils/build/docker/golang/graph-gophers.Dockerfile, utils/build/docker/golang/graphql-go.Dockerfile, utils/build/docker/golang/net-http-orchestrion.Dockerfile, utils/build/docker/golang/net-http.Dockerfile, utils/build/docker/golang/parametric/go.mod, utils/build/docker/golang/uds-echo.Dockerfile
Go 1.24 was released last week. As per the dd-trace-go Go version support policy, our Minimum Support Version is now go 1.23
=> [golang] rollout go 1.22 in favor of go 1.23

.github/workflows/system-tests.yml
=> Remove one failure annotation in CI

tests/debugger/utils.py
=> Fix DEBUGGER_SYMDB scenario

tests/test_telemetry.py
=> Exclude 'tracers' from product checked in "everything disabled" scenario

utils/build/docker/nodejs/parametric/server.js
I tested the stable config suite with https://github.com/DataDog/dd-trace-js/pull/5126 & it failed because some parameters were not returned by the config endpoint in NodeJS
Adds the required config params in the NodeJS parametric app.
=> upgrade(nodejs): Fix stable config suite for nodejs

manifests/python.yml
Disabling `[appsec|iast|sca]standalone` (v1) tests in preparation for https://github.com/DataDog/dd-trace-py/pull/12432
=> feat(asm): disable asm_v1 tests

tests/appsec/rasp/test_shi.py, tests/appsec/rasp/test_sqli.py, tests/appsec/rasp/test_ssrf.py
Some of the RASP tests were using an incorrect feature, specifically some of the ruleset version tests for each of the different vulnerabilities were all claiming to be part of the local file inclusion feature.
=> [ASM] Fix inconsistent feature on RASP tests

utils/build/docker/java/spring-boot/pom.xml, utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/App.java
Previously, the `make_distant_call` endpoint in the Springboot weblog app used `HttpUrlConnection` to fetch request headers that are being sent to the downstream request. This does not allow for injected headers from the tracer (such as through tracecontext or baggage propagation) to be added.
Migrated from using `HttpUrlConnection` to `okhttp` and using a Network Interceptor to get the request headers for the downstream request after the injection is done. 
* Framework is modified, or non obvious usage of …
=> [Java] Migrating `HttpUrlConnection` to `okhttp` for Springboot `make_distant_call`

manifests/dotnet.yml, utils/build/docker/dotnet/weblog/Controllers/SessionController.cs
Activate session blocking test, as we now collect session id every time
Adapt weblog as per documentation
```
Once a session has been established, a new call to `/session/user` must be made in order to generate a session fingerprint with the session id provided by the web client (e.g. cookie) and the user id provided as a parameter.
Query parameters required in the `GET` method:
- `sdk_user`: user id used in the WAF login event triggered during the execution of the request.
```
* Framework is modified, or …
=> [ASM][ATO][dotnet] Activate session blocking test

manifests/java.yml, utils/build/docker/java/akka-http/src/main/scala/com/datadoghq/akka_http/AppSecRoutes.scala, utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/MyResource.java, utils/build/docker/java/play/conf/routes, utils/build/docker/java/ratpack/src/main/java/com/datadoghq/ratpack/Main.java, utils/build/docker/java/resteasy-netty3/src/main/java/com/datadoghq/resteasy/MyResource.java, utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/App.java, utils/build/docker/java/vertx3/src/main/java/com/datadoghq/vertx3/Main.java, utils/build/docker/java/vertx4/src/main/java/com/datadoghq/vertx4/Main.java
* Enable tests for API Security schema extraction for path parameters.
* Modified the `tag_value` endpoints in all weblogs to conform to the tests (path params must be named `tag_value` and `status_code`, respectively.
* Mark resteasy-netty3 and jersey-grizzly2 as bugged ([APPSEC-56846](https://datadoghq.atlassian.net/browse/APPSEC-56846)), because all path params are inferred as strings, which will make the test fail. …
=> [java] Enable API Security tests for path parameters

tests/parametric/test_telemetry.py
Some non passing tests were unlocked on main after 3.1 release. They should not.
=> [python] disable non passing tests

docs/execute/binaries.md
I found the existing documentation confusing. It looks like I need to perform both actions - add `ruby-load-from-bundle-add` and clone the library repo to `binaries` folder.
The documentation on how to run tests against non-released Ruby tracer library locally are updated.
🛟 …
=> [Ruby] Update docs on testing against non-released library version

utils/_context/_scenarios/__init__.py
This PR fixes a typo I found while enabling some system-tests about telemetry following the instrumentation telemetry client full revamp in dd-trace-go. Here are the places that mention the env var without a S:
* The instrumentation telemetry api docs: https://github.com/DataDog/instrumentation-telemetry-api-docs/blob/main/GeneratedDocumentation/ApiDocs/v2/development.md#telemetry-environment-variables
* dd-trace-rb docs: https://datadoghq.dev/dd-trace-rb/Datadog/Core/Configuration/Settings/DSL/Telemetry.html
* dd-trace-js config: https://github.com/DataDog/dd-trace-js/blob/fd425151b56f41cc71a2b39ba088b72491283ae8/packages/dd-trace/test/config.spec.js#L1729
No tracer has the only test running in this scenario enabled. …
=> Typo in telemetry logs disablement scenario env var

manifests/java.yml
=> [JAVA]Enable TestCommandInjection_StackTrace

manifests/python.yml
[APPSEC-56429](https://datadoghq.atlassian.net/browse/APPSEC-56429)
Enables `standalone_v2` tests following https://github.com/DataDog/dd-trace-py/pull/12432
[APPSEC-56429]: https://datadoghq.atlassian.net/browse/APPSEC-56429?atlOrigin=eyJpIj …
=> [python] Onboarding: enable v2 tests

.github/workflows/ci.yml, utils/scripts/load-binary.sh
* use the same build method as dd-trace-py CI (the `pip install git+https` method can produce different ddtrace version) 
* open the way to have a build that will be the same as what customer would use (building wheel from sources)
"dev" use local folder, rather than `pip install git+https`
🛟 …
=> [python] Use local folder for "dev"

tests/debugger/test_debugger_probe_snapshot.py, tests/debugger/utils.py, utils/build/docker/dotnet/weblog/Controllers/DebuggerController.cs
This pull request includes several changes to enhance the support for probe snapshot budgets and add new functionality to the `DebuggerController` in the dotnet weblog. The most important changes include the addition of a new endpoint in `DebuggerController`, updating the method-to-line number mapping, and removing a missing feature decorator for dotnet.
Enhancements to probe snapshot budgets and debugger functionality:
* [`utils/build/docker/dotnet/weblog/Controllers/DebuggerController.cs`](diffhunk://#diff-8730c1c3eaa537de2a49726bd572c01f72363ae0bd1fcba9bb949412b46bab93R129-R139): Added a new endpoint `Budgets` that accepts an integer parameter `loops` and returns a content response after performing a no-operation loop.
* [`tests/debugger/utils.py`](diffhunk://#diff-5aa50041bb3e8e68ee5b4 …
=> Enable dotnet for probe budget tests

manifests/java.yml, tests/appsec/iast/sink/test_trust_boundary_violation.py
The test_extended_location_data tests are reporting XPASS for vulnerabilities where is_expected_location_required=False.
It needs to be enabled for the same versions as the original vulnerability test, since for these vulnerabilities, location is not relevant, and the test only verifies the presence of that vulnerability type.
[APPSEC-54879]
- Enable Test_XContentSniffing_ExtendedLocation, Test_HstsMissingHeader_ExtendedLocation 
- TrustBoundaryViolation produce a vulnerability with location so Test_TrustBoundaryViolation_ExtendedLocation is_expected_location_required should be True
* Test logic is modified? -> Get a …
=> [JAVA]Enable XPASSED test_extended_location_data for some vulnerabilities

manifests/java.yml
APPSEC-55785 was fixed so those test ara passing
[APPSEC-54879]
Enable test with missing_feature (APPSEC-55785)
[APPSEC-54879]: https://datadoghq.atlassian.net/browse/APPSEC-54879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUi …
=> [JAVA]Enable XPASSED rasp BodyJson tests for vertx4.

tests/appsec/api_security/test_schemas.py, tests/appsec/iast/utils.py, tests/appsec/rasp/utils.py, tests/appsec/test_blocking_addresses.py, tests/appsec/test_metastruct.py, tests/appsec/test_user_blocking_full_denylist.py, tests/external_processing/test_apm.py, tests/test_span_events.py, tests/test_standard_tags.py, utils/interfaces/_library/core.py
Most of the time, when get check for the root span for a request, we're assuming the following:
* There is a request.
* There is one, and only one, root span.
So created a `get_root_span` to be used for the common case, properly asserting these preconditions, and avoiding redundant boilerplate with iterators. Special cases can still use the more general `get_root_spans` and `get_spans`. …
=> Add get_root_span helper

docs/weblog/README.md, utils/build/docker/java/akka-http/src/main/scala/com/datadoghq/akka_http/AppSecRoutes.scala, utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/MyResource.java, utils/build/docker/java/play/app/controllers/AppSecController.scala, utils/build/docker/java/play/conf/routes, utils/build/docker/java/ratpack/src/main/java/com/datadoghq/ratpack/Main.java, utils/build/docker/java/resteasy-netty3/src/main/java/com/datadoghq/resteasy/MyResource.java, utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/App.java, utils/build/docker/java/vertx3/src/main/java/com/datadoghq/vertx3/Main.java, utils/build/docker/java/vertx4/src/main/java/com/datadoghq/vertx4/Main.java
Addding missing weblog endpoints for API Security sampling endpoints.
I'll enable tests as needed in separate PR at https://github.com/DataDog/system-tests/pull/4195. For now, I want to get the endpoints merged, to avoid the other PRs for the manifest automatically triggering all scenarios in CI on every push.
[APPSEC-54874](https://datadoghq.atlassian.net/browse/APPSEC-54874) …
=> [java] API Security sampling endpoints

manifests/java.yml, utils/build/docker/java/akka-http/src/main/scala/com/datadoghq/akka_http/AppSecRoutes.scala, utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/MyResource.java, utils/build/docker/java/play/app/controllers/AppSecController.scala, utils/build/docker/java/resteasy-netty3/src/main/java/com/datadoghq/resteasy/MyResource.java, utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/App.java
The `tag_value` endpoint must accept urlencoded forms and JSON. In spring-boot and akka-http it did not support JSON, which broke the corresponding API Security tests.
akka-http still does not pass the test, but spring-boot does.
=> [java] Fix tag_value endpoint in for JSON body

utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/App.java
This endpoint for `/shell_execution` in Spring Boot is sometimes throwing exceptions because `args` can be a String or an array, and we supported only String. No test failing because these are skipped for other reasons. Fixed the endpoint, so we should have a proper XPASS when the time comes.
🛟 …
=> [java] Fix /shell_execution endpoint in Spring Boot when args is an array

tests/appsec/test_blocking_addresses.py
Fix Xpassed tests [APPSEC-54879]
=> [java] Enable Xpassed tests in Test_Blocking_response_status

tests/appsec/test_traces.py
Make Test_CollectDefaultRequestHeader stricter:
* Test that the status code is 200 (avoids hiding issues with incorrect weblog implementations or bugs).
* Use legal values for headers. Some frameworks (e.g. Spring) will fail on invalid Content-Type (e.g. not containing a slash).
* Check the values of the tags, not just the keys.
* Check root spans only explicitly, since that's where these tags are expcted.
* Make assertions more explicit (e.g. no spans vs no matching span).
* See [APPSEC-56898](https://datadoghq.atlassian.net/browse/APPSEC-56898) for the golang exception.
* Test logic is modified? -> Get a review from …
=> Make Test_CollectDefaultRequestHeader stricter

tests/parametric/test_dynamic_configuration.py
Fix RemoteConfig supported capabilities for Java
=> Fix supported capabilities for Java

manifests/golang.yml
Egg-Chicken problem as I'm upgrading from experimental to V2. This PR will disable the test and another one will enable the V2
Mark Test_AppSecStandalone_UpstreamPropagation as irrelevant for Go
=> [golang] disable Test_AppSecStandalone_UpstreamPropagation 

tests/appsec/test_automated_login_events.py, utils/build/docker/python/django/app/urls.py
Enable signup tests for auto instrumentation on Django
Add corresponding endpoint for django weblogs.
APPSEC-56662
To be merged after https://github.com/DataDog/dd-trace-py/pull/12547
=> [python] signup events on django

docs/execute/run.md, docs/scenarios/k8s_lib_injection.md, manifests/golang.yml, tests/appsec/test_asm_standalone.py
[APPSEC-56328](https://datadoghq.atlassian.net/browse/APPSEC-56328?atlOrigin=eyJpIjoiOTUzOGQyYTBhYTMxNDU1N2I2MzlhYWJmMTc0ZTBjZDgiLCJwIjoiaiJ9)
- Enable `Test_AppSecStandalone_UpstreamPropagation_V2` for Go 
- Mark `Test_AppSecStandalone_UpstreamPropagation` as irrelevant for Go `> 1.72.1`
🛟 …
=> [golang] enable go system test for asm standalone v2

tests/appsec/api_security/utils.py, utils/_context/_scenarios/__init__.py
Remove testing sampling rate via RC. This mechanism was never in production. Making it compatible with both old and new API Security algorithms, but without RC.
=> Remove testing of RC request_sample_rate for API Security

manifests/java.yml, tests/test_config_consistency.py, utils/build/docker/java/spring-boot-3-native/pom.xml, utils/build/docker/java/spring-boot-3-native/src/main/java/com/datadoghq/springbootnative/WebController.java, utils/build/docker/java/spring-boot-3-native/src/main/resources/logback.xml
=> Updating log injection tests and creating `logs/library` weblog endpoint for Java 

tests/test_scrubbing.py
Do not use `.*` for `assert_absence`. The log assertions use `re.search` which already looks for a substring rather than a full match, so they are both functional equivalent. However, on a run with debug logs and ~60MB worth of logs, using `.*` will lead to a lot of backtracking and this test can take even minutes just for these 3 assertions. …
=> Improve performance of log checks

tests/test_library_logs.py
We've been getting this flaky test:
```
E       AssertionError: assert not ['2025-03-05 07:44:22.641  INFO 41 --- [     s5-admin-0] c.d.oss.driver.internal.core.time.Clock  : Using native clock...                                   com.ibm.ws.webcontainer.webapp.WebAppErrorReport: SRVE0295E: Error reported: 500\n']
```
This happens when this log line gets printed in the middle of an unrelated multi-line error, producing false positives in matches.
* Framework is modified, or non obvious usage of it -> get a …
=> [java] Fix flaky test on openliberty log check

manifests/java.yml, tests/parametric/test_config_consistency.py, tests/test_config_consistency.py
Update 128bit logging enabled tests to consider the Java edge case. Update and disable stable config Java tests to allow CI to pass on the following dd-trace-java [PR](https://github.com/DataDog/dd-trace-java/pull/8489) that updates the default value of `DD_LOGS_INJECTION`. Stable Config tests will be enabled in a future PR following the merge of the above dd-trace-java PR. …
=> Update 128 bit logging enabled tests and disable stable config tests

tests/parametric/test_dynamic_configuration.py
First part of the test switch needed to for [APMAPI-1005](https://datadoghq.atlassian.net/browse/APMAPI-1005)
We need to disable `test_not_match_service_target ` so the CI is green on [dd-trace-go/3261](https://github.com/DataDog/dd-trace-go/pull/3261) and then enable the new test `TestDynamicConfigV1_EmptyServiceTargets` after the merge.
- Mark `test_not_match_service_target` as irrelevant  …
=> [golang] disable test_not_match_service_target

tests/telemetry_intake/static/config_norm_rules.json
These changes are in sync with changes made to `dd-go` in https://github.com/DataDog/dd-go/pull/173755
Related PR for `dd-trace-js`: https://github.com/DataDog/dd-trace-js/pull/5369
`config_norm_rules.json` for config telemetry test(s)
=> Update config_norm_rules.json for vertexai config

utils/build/docker/java/spring-boot-3-native/pom.xml
In relenv, we want to compare the accuracy of native profilers to the in process java profiler.
Add debug flags to ensure we can unwind and symbolicate the application using otel / ddprof profilers.
=> [Java] Graal native image update - debug flags

tests/telemetry_intake/static/config_norm_rules.json
Unblocks the following PR: https://github.com/DataDog/dd-trace-py/pull/12662
Fix failing telemetry completeness test by add `DD_DOGSTATSD_HOST` to the telemetry configuration allowlist.
=> [python] telemetry_completeness: add config used by the python tracer

utils/build/docker/python/parametric/apm_test_client/server.py
config._stats_agent_hostname and config._stats_agent_port are not used by the agent. They will be removed in a future ddtrace version. 
- get statsd configs from the tracer instead of the global config object
=> [python] remove internal configs from parametric app

.gitlab-ci.yml
=> Gitlab: temporary disable check_pipeline_status

.gitlab/ssi_gitlab-ci.yml
Restore onboarding tests job timeout (gitlab)
=> SSI: restore timeout

manifests/java.yml, tests/test_identify.py
=> [java] Enable identify easy wins

utils/proxy/_deserializer.py
=> Do not raise an internal error on deserialization error on 500 responses

tests/appsec/waf/test_truncation.py
Check if the `waf.requests` telemetry metric includes `input_truncated:true` when a truncation occurs, in addition to the previous checks
=> check waf request input truncated tag

manifests/golang.yml, tests/test_config_consistency.py
=> Config Consistency: Enable XPassing tests

tests/parametric/conftest.py, tests/parametric/test_dynamic_configuration.py, tests/parametric/test_telemetry.py
Currently many tests expect configurations to be sent in the `app-started` telemetry payload. This isn't always the case. Configurations can be queued after application start and be sent in the app-configurations-change event.
=> telemetry: fix flaky configuration tests

tests/appsec/iast/sink/test_command_injection.py, tests/appsec/iast/sink/test_email_html_injection.py, tests/appsec/iast/sink/test_header_injection.py, tests/appsec/iast/sink/test_insecure_auth_protocol.py, tests/appsec/iast/sink/test_insecure_cookie.py, tests/appsec/iast/sink/test_ldap_injection.py, tests/appsec/iast/sink/test_no_httponly_cookie.py, tests/appsec/iast/sink/test_no_samesite_cookie.py, tests/appsec/iast/sink/test_reflection_injection.py, tests/appsec/iast/sink/test_sql_injection.py, tests/appsec/iast/sink/test_ssrf.py, tests/appsec/iast/sink/test_trust_boundary_violation.py, tests/appsec/iast/sink/test_unvalidated_redirect.py, tests/appsec/iast/sink/test_weak_cipher.py, tests/appsec/iast/sink/test_weak_hash.py, tests/appsec/iast/sink/test_xpath_injection.py, tests/integrations/test_dbm.py
=> [dotnet] reactivate tests on default scenario

utils/virtual_machine/aws_infra_exceptions.json
Flaky error loading the pulumi aws plugin. Apply to retry policy
=> SSI tests: catch pulumi plugin error

.github/workflows/compute-impacted-libraries.yml
otel scenario relies on staging backend, but this backend is not stable enough to have usable results.
Turns out that those scenarios are ran manually, which leads to unecessary friction on system-tests CI, with failures with no actionnables.
=> Remove then from the CI until they are included in the CI owned by the team owning this product. …
=> Exclude otel from system-tests CI

tests/appsec/api_security/test_api_security_rc.py, tests/appsec/api_security/test_schemas.py, utils/build/docker/php/common/php.ini, utils/build/docker/php/common/tag_value.php
Otherwise nothing is collected for the appsec api security.
If other php files are hit during these tests, then similar code needs to be added to them.
This suffices for the APPSEC_API_SECURITY and APPSEC_API_SECURITY_RC.
=> [php] add http.route to tag_value

manifests/python.yml, utils/build/docker/python/django/app/urls.py
After the merge of https://github.com/DataDog/dd-trace-py/pull/12760
- update relevant endpoint of Django
- enable relevant test for all Django weblogs
APPSEC-57027
=> [python] enable session blocking tests for Django

.gitlab-ci.yml, utils/scripts/ssi_wizards/aws_onboarding_wizard.sh
The gitlab api is paginated. The current check_pipeline_status job has a bug, it's not paginating the results. We are only checking the first 20 jobs.
Fix the job
=> SSI gitlab fix check_pipeline_status

manifests/dotnet.yml, manifests/golang.yml, manifests/java.yml, manifests/nodejs.yml, manifests/php.yml, manifests/python.yml, manifests/ruby.yml, tests/appsec/appsec_corrupted_rules.json, tests/appsec/test_customconf.py, tests/appsec/test_remote_config_rule_changes.py, tests/appsec/utils.py, tests/appsec/waf/test_truncation.py, utils/_context/_scenarios/__init__.py
Adding checks for `waf.init` and `waf.config_errors` during WAF initialization failure for the new telemetry [RFC](https://docs.google.com/document/d/1D4hkC0jwwUyeo0hEQgyKP54kM1LZU98GL8MaP60tQrA/edit?pli=1&tab=t.0)
=> Add new test for waf init failure telemetry tag

tests/test_config_consistency.py
Test_Config_HttpClientErrorStatuses_FeatureFlagCustom tests were incorrectly disabled with `reason=APMAPI-1196`.
Removes the `@bug` annotation for Golang on Test_Config_HttpClientErrorStatuses_FeatureFlagCustom tests.
=> [Go] Re-enable Test_Config_HttpClientErrorStatuses_FeatureFlagCustom tests

manifests/golang.yml, tests/test_config_consistency.py
The v1.69.0 release contains support for the relevant feature flag DD_TRACE_HTTP_CLIENT_ERROR_STATUSES: https://github.com/DataDog/dd-trace-go/releases/tag/v1.69.0
=> [Go] Change minimum version for Test_Config_HttpClientErrorStatuses_FeatureFlagCustom to v1.69.0

manifests/dotnet.yml, tests/parametric/test_config_consistency.py
As part of our tracing configuration consistency effort, we've established updated requirements for parsing `DD_TAGS` and the latest .NET Tracer now implements those behaviors.
Runs the `tests/parametric/test_config_consistency.py::Test_Config_Tags` tests cases for .NET and adds the `DD_TRACE_EXPERIMENTAL_FEATURES_ENABLED=all` configuration to allow tracers to pass this when they opt-in to the potential breaking change. …
=> Enable updated DD_TAGS test cases for .NET tracing library

.github/workflows/run-end-to-end.yml, tests/appsec/test_automated_login_events.py, utils/_context/_scenarios/__init__.py
In the current setup in the request blocking for automated user events we use runtime activation scenario which requires 1-click activation. First of all, it's a mix of two tests - 1-click activation and request blocking. Second - in Ruby we don't support yet 1-click activation.
Change runtime activation scenario to request blocking
=> Change request blocking scenario for ATO

manifests/nodejs.yml, utils/build/docker/nodejs/parametric/server.js
added endpoint to enable otel baggage test
=> [NodeJS] Enable baggage otel support drop in test

tests/appsec/waf/test_telemetry.py
Add new mandatory tags for waf requests telemetry metric
=> Add new waf requests mandatory tags

tests/docker_ssi/test_docker_ssi_crash.py
The python 3.2 branch is failing due to this issue: https://datadoghq.atlassian.net/browse/INPLAT-448?atlOrigin=eyJpIjoiN2NjYzM5ZTkxM2U1NDcyYWFmMjgzNzA2ZDA2NzE5MWEiLCJwIjoiamlyYS1zbGFjay1pbnQifQ
Add a bug marker
=> Docker SSI: Bug marker python3.2

tests/parametric/test_128_bit_traceids.py
- Ensures the FPD reports that the cpp tracer has the expected value for the 128bit trace id generation.
- Update test annotations from missing_feature to `irrelevant`. We don't need to test 128bit trace id support for b3 headers if b3 headers are not supported.
🛟 …
=> parametric: update reporting for 128bit traceid cpp tests [cpp]

tests/auto_inject/test_auto_inject_install.py
In theory the issue(s) that caused the flakiness have been fixed.
Remove the flaky attribute on `test_crash_no_zombie`.
[ APMLP-313](https://datadoghq.atlassian.net/browse/APMLP-313?atlOrigin=eyJpIjoiOTgzOGQ2ZmVhNDEyNDliMDhkYjAxMmIyZGJlZmZkNm …
=> Remove flaky attribute on test_crash_no_zombie

tests/appsec/waf/test_truncation.py
Support for libraries that will actually try to check the actual depth of the object passed as parameter
Broaden assert statement of the object depth span metric
=> Fix appsec truncation object_depth test

manifests/java.yml, tests/test_config_consistency.py, utils/_context/_scenarios/__init__.py
All changes for Round 2 of Config Consistency have been merged. This PR aims to enable all of the previously disabled tests.
[APMAPI-1043](https://datadoghq.atlassian.net/browse/APMAPI-1043)
[APMAPI-1043]: …
=> [Java] Enable Round 2 Config Consistency system-tests

.github/workflows/ci.yml
=> Reduce CI time to 30 minutes

tests/appsec/test_only_python.py
=> [python] Skip circular import check for 3.2.1

manifests/java.yml, utils/telemetry/intake/static/config_norm_rules.json
Tests will pass after merging this one: https://github.com/DataDog/dd-trace-java/pull/8178
(needs to be done in lock-step).
[APPSEC-54874](https://datadoghq.atlassian.net/browse/APPSEC-54874)
[APPSEC-54874]: …
=> [java] Enable new API Security sampling tests

utils/scripts/ci_orchestrators/gitlab_exporter.py
Docker runners are deprecated on gitlab. Migrate to docker_in_docker runner
Apply only to docker ssi
=> Docker SSI: Migrate to docker_in_docker gitlab runners

tests/appsec/iast/source/test_parameter_value.py
New Easy win in a test that is testing nothing. 
Mark the empty test as irrelevant.
Failing tests seem are not related with the PR, this PR is only adding a `@irrelevant`
=> Skip empty test with `@irrelevant` decorator

utils/_context/_scenarios/parametric.py, utils/build/docker/nodejs/express4-typescript.Dockerfile, utils/build/docker/nodejs/express4.Dockerfile, utils/build/docker/nodejs/express5.Dockerfile, utils/build/docker/nodejs/install_ddtrace.sh, utils/build/docker/nodejs/nextjs.Dockerfile, utils/build/docker/nodejs/uds-express4.Dockerfile, utils/build/docker/nodejs_otel/express4-otel.Dockerfile
This is a common cause of flakiness, often with a random 500 error from npm or from an ECONNRESET. Rerunning it reduces the flakiness pretty much to 0 (or as close as we can realistically expect without rerunning many times).
Retry `npm install` when it fails.
🛟 …
=> retry npm install when it fails

manifests/php.yml
Since https://github.com/DataDog/dd-trace-php/pull/3116 has been merged with a release of 1.8.0, I'm updating the system tests.
=> [php][API Gateway] Add tracer version to the API Gateway test

tests/docker_ssi/test_docker_ssi.py
Similar to https://github.com/DataDog/system-tests/pull/4362. We need to skip this due to a known bug in order to unblock our CI.
Expanding the known bug skip scoping for python's [DOCKER_SSI]:TestDockerSSIFeatures.test_telemetry from 3.2 to 3.0.0.dev while we investigate.
🛟 …
=> [python] expand skip from 3.2 to 3.0.0.dev for `TestDockerSSIFeatures.test_telemetry`

manifests/ruby.yml
=> [ruby] Skip failing tests for APPSEC-57124

utils/telemetry/intake/static/jvm_config_rules.json
Fixing system tests for https://github.com/DataDog/dd-trace-java/pull/8541
https://github.com/DataDog/system-tests/blob/main/docs/edit/runbook.md#test_config_telemetry_completeness
Following up from https://github.com/DataDog/dd-go/pull/177088
Running `./utils/telemetry/intake/update.sh` as suggested by runbook ⬆️ resulted in changes - mostly removals - for all the rules files... 
```
modified:   utils/telemetry/intake/static/config_norm_rules.json
modified:   utils/telemetry/intake/static/config_prefix_block_list.json
modified:   utils/telemetry/intake/static/dotnet_config_rules.json
modified:   utils/telemetry/intake/static/go_config_rules.json
modified:   utils/telemetry/intake/static/jvm_config_rules.json
modified:   utils/telemetry/intake/static/nodejs_config_rules.json
modified: …
```
=> add data_jobs_openlineage_enabled to telemetry config rules

tests/test_config_consistency.py
This dd-trace-java [PR](https://github.com/DataDog/dd-trace-java/pull/8535) caused the following tests to fail in system-tests. This system-tests [PR](https://github.com/DataDog/system-tests/pull/4355/files) disabled these tests. A fix has been merged [here](https://github.com/DataDog/dd-trace-java/pull/8604), and this PR re-enables the tests. …
=> [Java] Re-enabling tests from #4355

tests/parametric/test_process_discovery.py
`test_library.lang` evaluates to `golang` for Go, which does not align with the language reported by the Go tracer. This fix resolves the issue by matching against `go` instead of `golang`.
=> [golang] fix(process-discovery): Go tracer reports `go` instead of `golang`

tests/auto_inject/test_auto_inject_install.py
There is a flakiness on the crashtracking zombie test.
There is a race condition, the app can take time to crash. We retry reading the system process
=> Onboarding: crash zombie wait for crash

manifests/python.yml, tests/test_span_events.py
https://datadoghq.atlassian.net/browse/APMAPI-1283
* mark failing test as bug
* also changed two declarations in manifest (when an endpoint is missing in weblog, we must use `missing_feature`)
=> [python] Skip test for APMAPI-1283

tests/test_sampling_rates.py
=> [nodejs] Add express4-typescript in weblog impacted by APMAPI-1252

utils/telemetry/intake/static/jvm_config_rules.json
Fixing system tests for https://github.com/DataDog/dd-trace-java/pull/8650 and following up on https://github.com/DataDog/dd-go/pull/177450
Changes obtained by running `./utils/telemetry/intake/update.sh`. Some other files where also modified (mainly removals) but only kept the relevant change for this PR.
```
modified:   utils/telemetry/intake/static/config_norm_rules.json
modified:   utils/telemetry/intake/static/config_prefix_block_list.json
modified:   utils/telemetry/intake/static/dotnet_config_rules.json
modified:   utils/telemetry/intake/static/go_config_rules.json
modified:   utils/telemetry/intake/static/jvm_config_rules.json
modified:   utils/telemetry/intake/static/nodejs_config_rules.json
modified:   utils/telemetry/intake/static/php_config_rules.json
modified: …
```
=> Add surefire tracer telemetry config rule

tests/debugger/test_debugger_exception_replay.py
=> [Debugger] Mark multi frame exception replay test as flakey

utils/build/docker/nodejs/express/app.js, utils/build/docker/nodejs/express4-typescript/app.ts, utils/build/docker/nodejs/nextjs/src/app/make_distant_call/route.js
Previously, the `make_distant_call` endpoint in the weblog apps used `Axios` to fetch request headers that are being sent to the downstream request. This does not allow for injected headers from the tracer (such as through tracecontext or baggage propagation) to be added. This PR aims to do the same thing that #4069 does, but for the NodeJS weblog apps.
Migrated from using `Axios` to `http` to get the request headers for the downstream request after the injection is done. 
* Framework is modified, or non …
=> [NodeJS] Update `make_distant_call` to allow injecting of request headers

tests/test_span_events.py
There is a discrepancy in span events between what the RFC states and the current system test implementation for when `DD_TRACE_NATIVE_SPAN_EVENTS` is enabled for `v0.5`. The RFC states that setting `DD_TRACE_NATIVE_SPAN_EVENTS` should override the v0.5 protocol and switch to v0.4/v0.7; the system test expects that v0.5 is respected even when the environment variable is set. …
=> [python] update decorator with reason for skipping span event test

utils/virtual_machine/virtual_machines.json
The debian 12 is failing on the agent qa account (not in the new account).
Let's disable the debian 12 again, until we migrate all the repositories to the new aws account
=> Onboarding: disabled debian 12 again

.vscode/launch.json, tests/parametric/conftest.py, utils/_context/_scenarios/parametric.py, utils/build/docker/java/parametric/run.sh, utils/build/docker/nodejs/parametric/app.sh
Allow to add arbitary argument to library container command in parametric scenario
Add `library_extra_command_arguments` parameter. 
```python
import pytest
from utils import scenarios
class Test_stuff:
@scenarios.parametric
@pytest.mark.parametrize(
"library_extra_command_arguments",
[
["--arg1"]
["--arg2=12"]
],
)
def test_stuff(self, test_agent, test_library):
pass
``` …
=> Introduce a way to add extra argument to library cmd on parametric scenario

manifests/ruby.yml
I tested it locally but forgot to activate the system-test
Activate the test that ensures that Datadog-Client-Computed-Stats is not present when APM Disablement/ASM Standalone is not activated
=> [ruby][APPSEC-56357] Activate Datadog-Client-Computed-Stats test

utils/build/docker/python/parametric/apm_test_client/server.py
Unblocks this refactor: https://github.com/DataDog/dd-trace-py/pull/12749. 
Agent configurations will no longer be stored on the Tracer. The global config object will be the source of truth. 
=> [python] Use agent_config in parametric config endpoint

manifests/cpp.yml
Fix a known issue where remote config payloads get rejected by the C++ tracer
Runs the associated test, the feature work is implemented in https://github.com/DataDog/dd-trace-cpp/pull/177
=> [cpp] Enable test_dynamic_configuration.py::TestDynamicConfigV1_EmptyServiceTargets test cases

tests/test_data_integrity.py
This is a fix for https://datadoghq.atlassian.net/browse/APMSP-1811
This tests was marked as flaky, and noticed that the sampling priority was somewhat flawed. Only sampling priorities > 0 will be considered as _sampled_, and lack of a sampling priority (`None`) will be treated as a P0, which is the same behavior the Agent has.
:rocket: Once your PR is reviewed, you can …
=> [APM] Do not consider None priority as sampled

utils/build/docker/java/spring-boot/src/main/resources/application.properties
Springboot defaults the max http header sizes of all combined headers to be 8192 bytes. Since we by default support a maximum size of 8192 bytes for baggage headers alone, we need to increase this limit in the weblog app to receive baggage headers in the tracer.
Update Springboot weblog app `max-http-header-size`.
🛟 …
=> [Java] Spring-boot Increase Default Max Http Header Size

utils/scripts/load-binary.sh
As `v2-dev` was merged in `dd-trace-go`, `system-tests`'s `main` branch is failing because it pulls the latest commit of `main` from `dd-trace-go`.
=> [golang] workaround: update load-binary.sh to set default TARGET_BRANCH to v1-maintenance

manifests/php.yml, tests/debugger/probes/probe_status_metric.json, tests/debugger/probes/probe_status_metric_line.json, tests/debugger/probes/probe_status_spandecoration.json, tests/debugger/probes/probe_status_spandecoration_line.json, tests/debugger/test_debugger_probe_status.py, tests/debugger/utils.py, utils/build/docker/php/common/debugger.php, utils/build/docker/php/php-fpm/php-fpm.conf
This pull request enables PHP for the `Test_Debugger_Probe_Statuses` scenario only. This is the minimal number of changes required to get PHP passing, and in future PRs we'll enable it for more scenarios including Exception Replay (@shurivich), telemetry, and the expression language.
* [`manifests/php.yml`](diffhunk://#diff-164e30a9609b478cdace674ea20d1ae01e3872dc0d69e2da602f6acb450c4e85L389-R389): Updated the version for `Test_Debugger_Probe_Statuses` to `v1.7.3`.
* [`tests/debugger/test_debugger_probe_status.py`](diffhunk://#diff-67081901be029daaca4be54be8a1da76625549618ce0ebeeadaa82ecf079f984R93-R103): Added new test cases for `probe_status_metric_line` and `probe_status_spandecoration_line`, including the necessary setup methods and missing feature annotations. …
=> feat(debugger): Add PHP debugger endpoint & config

utils/build/docker/python/parametric/apm_test_client/server.py
=> [python] Remove useless and problematic import for parametric scenario

tests/parametric/test_sampling_delegation.py
One of the parametric test is using an env var that is not used anymore by the python client. `DD_TRACE_SAMPLE_RATE` has been dropped and replaced by `DD_TRACE_SAMPLING_RULES`
The test is currently passing due to an hardcoded sampling decision `USER_KEEP` in the http header extractor that is being reworked [dd-trace-py#12950](https://github.com/DataDog/dd-trace-py/pull/12950)
* add DD_TRACE_SAMPLING_RULES env var to Test_Decisionless_Extraction
* Framework is modified, or non obvious usage of it -> get a …
=> fix(sampling): update sample rate env var in parametric test

utils/build/docker/ruby/parametric/README.md
I had to test my changes on dd-trace-rb with an unreleased version of libdatadog. But to validate my changes before moving to something else, I had to test them using system-tests. Running (parametric) system-tests with an unreleased version of was painful to figure out, so I'm documenting it for future usage, or to look for improvements in the process.
Update docs. …
=> [ruby] Add doc for running parametric tests with an unreleased version of libdatadog

manifests/php.yml, utils/scripts/ssi_wizards/k8s_ssi_wizard.sh
Enable K8s profiling scenarios for PHP 1.9.0
=> SSI tests: Enable k8s profiling for php 1.9.0

manifests/java.yml, manifests/python.yml, tests/test_telemetry.py
During #incident-36407 we discovered that a tracer library had dynamic instrumentation enabled by default. This pull request lays the groundwork to ensure for all tracers that the defaults match our expectations.
* [`manifests/python.yml`](diffhunk://#diff-6e0ee0ad398e4fe9a7f833e48406fd4ff99eff4ac88e92ec0e0b2e58eb6e3889L1078-R1078): Updated the `Test_ProductsDisabled` to use version `v2.8.0` instead of `missing_feature`.
* [`tests/test_telemetry.py`](diffhunk://#diff-6ab9dd4d058d45bd9344fb44a8b55b5c358f9e2648bf50bbdedcbfe2dd50220cR689): Added a `@missing_feature` decorator to the `test_app_started_product_disabled` method to indicate that the feature is not implemented for the Python library.
* [`tests/test_telemetry.py`](diffhunk://#diff-6ab9dd4d058d45bd9344fb44a8b55b5c358f9e2648bf50bbded …
=> test(debugger): Ensure debugger features are disabled by default

manifests/nodejs.yml, tests/debugger/test_debugger_expression_language.py, tests/debugger/utils.py, utils/build/docker/nodejs/express/debugger/index.js
Support for this feature was just merged to `master` in the Node.js tracer and now we need to enable the corresponding system tests.
1. Add new test related endpoints to the Express 4 test app
2. Enable the tests in `tests/debugger/test_debugger_expression_language.py` to run for Node.js
3. Modify the tests in `tests/debugger/test_debugger_expression_language.py` slightly, so they fit some small quirks with Node.js …
=> [Node.js] Enable Debugger Expression Language tests for Node.js

.gitlab-ci.yml, manifests/php.yml
Skip onboarding profiling tests for PHP and version < 1.9.0
=> Onboarding: PHP profiling markers

utils/scripts/ci_orchestrators/gitlab_exporter.py
Activate the auto_inject repository to start using the new aws account
=> SSI tests: activate auto_inject new aws account

tests/test_the_test/test_version.py, utils/_context/component_version.py
Follow up of #4533
The version from PHP may be like `1.9.0-7ab1806dec09cbf6e7079ac59453b79fc5e9c91f`
The `-` tells that `7ab1806dec09cbf6e7079ac59453b79fc5e9c91f` is a prerelease info, where it's a commit sha, and should be placed in built info in the version scheme.
#4533 always replaced the `-` by a `+` to fix that, though, it can cause trouble for real pre-release info.
-> change the `-` into a `+` only if the info "looks like" a commit sha.
I also deleted two hacks that removed the pre-release info in php and java
* Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` …
=> Replace the built info in version if and only if it's a SHA

tests/debugger/test_debugger_probe_snapshot.py
requires https://github.com/DataDog/dd-trace-java/pull/8416 to be merged first
Enable code origin tests for java.  Requires that https://github.com/DataDog/dd-trace-java/pull/8416 be merged first.
=> [java] Enable code origin test for java

utils/telemetry/intake/static/config_norm_rules.json
- Adding DD_TRACE_BAGGAGE_TAG_KEYS configuration to support auto adding baggage to span tags
=> Adding DD_TRACE_BAGGAGE_TAG_KEYS config

manifests/dotnet.yml, manifests/golang.yml, manifests/java.yml, manifests/nodejs.yml, manifests/php.yml, manifests/python.yml, manifests/ruby.yml, tests/appsec/test_asm_standalone.py
Test that user events propagate asm events with `_dd.p.ts`
=> Generate user event on standalone mode

manifests/ruby.yml
We released fix which allows us to enable those checks
Just turn on some fingerprinting and more coming
=> [Ruby] Enable endpoint, header, network fingerprinting

utils/telemetry/intake/static/config_norm_rules.json
Resolve errors from this job: https://github.com/DataDog/dd-trace-py/actions/runs/14535339749/job/40782814596?pr=13214
Update error tracking env variables in telemetry intake config norms.
=> chore: update config_norm for error tracking env variables

manifests/php.yml, utils/build/docker/php/common/php.ini
This scenario was disabled because it was suspected as the root cause making the nightly build to fail, but it continued to fail after it was disabled
Charles has fixed this with https://github.com/DataDog/system-tests/pull/4516
Reverts https://github.com/DataDog/system-tests/pull/4511
* [`tests/manifests/php.yml`](diffhunk://#diff-164e30a9609b478cdace674ea20d1ae01e3872dc0d69e2da602f6acb450c4e85L403-R405): Modified the `Test_Debugger_Probe_Snaphots` entry to `Test_Debugger_Probe_Statuses` and added specific versioning for `apache-mod-8.0`. …
=> Fix(PHP): Enable probe statuses again

manifests/java.yml, manifests/python.yml, tests/debugger/test_debugger_inproduct_enablement.py
Enable tests for java and pythin in-product enablement
=> [Debugger] Enable tests for java and python in-product enablement

utils/build/docker/golang/app/internal/rasp/rasp.go
Don't crash the APP when an unknown error happens when testing out RASP.
=> [golang] fix APPSEC_RASP crash

tests/test_telemetry.py
This pull request updates the `test_debugger_products_disabled` test in `tests/test_telemetry.py` to include validation for a new configuration setting, `code_origin_for_spans_enabled`. The changes ensure that this new setting is properly tested alongside existing configurations.
* [`tests/test_telemetry.py`](diffhunk://#diff-6ab9dd4d058d45bd9344fb44a8b55b5c358f9e2648bf50bbdedcbfe2dd50220cL740-R740): Added a new variable, `co_config`, to track the `code_origin_for_spans_enabled` setting. Updated the test logic to check if this setting is present in the telemetry data and assert that it is disabled by default. [[1]](diffhunk://#diff-6ab9dd4d058d45bd9344fb44a8b55b5c358f9e2648bf50bbdedcbfe2dd50220cL740-R740) [[2]](diffhunk://#diff-6ab9dd4d058d45bd9344fb44a8b55b5c358f9e2648bf50bbdedcbfe2dd5022 …
=> test(debugger): ensure code origins is disabled by default

manifests/nodejs.yml, tests/appsec/iast/utils.py
Since cookie name is not used anymore as hash key, cookie vulnerability hashes are computed in the same way that the others. So cookie name filtering has been deprecated from `v5.50.0`.
Set the correct version in Node.js manifest for cookie name filter tests.
🛟 …
=> [nodejs] Disable IAST deduplication cookie name filter tests for future tracers versions

docs/edit/runbook.md, utils/telemetry/intake/update.sh
the http urls weren't working for me
see title
=> allow for an SSH url to be used for github in update script for telemetry

tests/appsec/iast/utils.py
Check stackId for IAST extended location tests:
* If there are two vulnerabilities, the code did not ensure we selected the correct stacktrace.
* If `stackId` was not correctly set, we could still be incorrectly matching a stacktrace.
=> Check stackId for IAST extended location tests

manifests/cpp_nginx.yml, manifests/golang.yml, manifests/java.yml, manifests/nodejs.yml, manifests/php.yml, manifests/python.yml, manifests/ruby.yml, tests/appsec/iast/test_vulnerability_schema.py, tests/appsec/iast/vulnerability_schema.json, utils/_features.py
We used to host the IAST vulnerability schema in a separate internal repository. Implementations have often deviated. So moving the schema to system-tests as source of truth, and check that all IAST payloads conform to it.
=> Add IAST schema validation

tests/appsec/iast/utils.py
Python currently signals absent fields in location with empty strings rather than absent fields. Make matching in IAST location tests a bit more lenient.
This will be fixed in Python anyway: https://github.com/DataDog/dd-trace-py/pull/13333
but it's not necessary that the code to match location in stackframe is strict to this level.
Required for https://github.com/DataDog/dd-trace-py/pull/13272 to pass system-tests. …
=> Lenient location matching for missing fields in IAST location

.github/workflows/ci.yml
Guinea pig for DataDog/ensure-ci-success v2
* Add a initial delay of 300s (5mn), no jobs is shorter than this
* set 120 retries * 60s interval -> 2 hours CI 😨  
=> Uses v2 of DataDog/ensure-ci-success

tests/debugger/test_debugger_expression_language.py, tests/debugger/test_debugger_inproduct_enablement.py, tests/debugger/test_debugger_pii.py, tests/debugger/test_debugger_probe_budgets.py, tests/debugger/test_debugger_probe_snapshot.py, tests/debugger/test_debugger_probe_status.py, tests/debugger/utils.py
This pull request attempts to fix the [flakey PHP test](https://github.com/DataDog/system-tests-dashboard/actions/runs/14796928693/job/41553463399) by polling for statuses before asserts. It also refactors the probe status-checking functionality in the debugger test suite to improve flexibility and maintainability. The key change is the replacement of multiple specialized methods (`wait_for_all_probes_installed`, `wait_for_all_probes_emitting`) with a single generalized method (`wait_for_all_probes`) that accepts a list of statuses to wait for. This update simplifies the codebase and allows for more versatile status checks.
- Replaced `wait_for_all_probes_installed` and `wait_for_all_probes_emitting` with a single `wait_for_all_probes` method that accepts a `statuses` parameter. This …
=> debugger(php): Wait for probe statuses for PHP

tests/appsec/iast/sink/test_header_injection.py, tests/appsec/iast/utils.py
Test was failing on python/dev 
Test was flaky, because it allows to have to reported vulns, and checked only the first one. As the order is not stable, the test randomly fails.
skip test
allow only one reported vuln
=> fix failing test for APPSEC-57552

tests/parametric/test_headers_tracecontext.py
We learned that Java fails to do a correct propagation of the parent_id `p` when the scenarios is:
- Incoming tracestate has a `p` value
- A local span is generated that is a child span of the remote trace context
- The local span is injected into downstream headers
This new test asserts that the correct `p` value is injected downstream, which is the span-id of the local span.
Adds a new test `tests/parametric/test_headers_tracecontext.py::test_tracestate_w3c_p_extract_and_inject` that executes for all languages, except for Java where it is skipped due to nonconformance.
* Test logic is modified? -> Get a review from …
=> Add a regression test for extracting and injecting the parent_id under the p tracestate key

utils/telemetry/intake/static/config_norm_rules.json
Following the runbook after a change in an unreleased env variable name
Changed `DD_ERROR_TRACKING_HANDLED_ERRORS_MODULES` to `DD_ERROR_TRACKING_HANDLED_ERRORS_INCLUDE` for consistency between languages
=> fix: error_tracking unreleased env variable changed name

manifests/java.yml, manifests/nodejs.yml, tests/appsec/iast/vulnerability_schema.json
Update schema with a few changes from RFCs and other discussions:
* A source may lack `value` (e.g. a bytestream for HTTP body, which is not captured) or `name` (cannot determine which part of the body is being used). So the only required field for source is `origin`. This is the case in Java when tainting an InputStream representing a body.
* Evidence may be empty. This is the case in Node.js with weak randomness.
* The field `redacted` can be `true` or absent, but not `false`. It is omitted in that case.
* Added validation for `truncated` field.
* When evidence is redacted, there is no `value` field, but there is a `pattern` field instead.
* In location, `line` may be `-1` (representing an unknown line). This is the case in Java, for example, in native code.
* In location, `spanId` may …
=> Update IAST vulnerability schema

.gitlab/ssi_gitlab-ci.yml, tests/docker_ssi/test_docker_ssi_crash.py, tests/test_the_test/test_group_rules.py, utils/_context/_scenarios/__init__.py, utils/scripts/ci_orchestrators/docker_ssi.json, utils/scripts/ci_orchestrators/gitlab_exporter.py
Crashtracking tests kill the app container. Better to have a dedicated scenario
=> Docker ssi: crashtracking dedicated scenario

utils/_context/_scenarios/parametric.py
https://github.com/DataDog/dd-trace-py/actions/runs/14916384361/job/41910185409?pr=12690
Noticed that PARAMETRIC scenario for python is using an outdated test runner image, keep it sync with what's used in dd-trace-py.
=> [python] update testrunner image for parametric scenario

.github/workflows/run-end-to-end.yml, manifests/dotnet.yml, manifests/golang.yml, manifests/java.yml, manifests/nodejs.yml, manifests/php.yml, manifests/python.yml, manifests/ruby.yml, tests/appsec/test_asm_standalone.py, utils/_context/_scenarios/__init__.py
APPSEC-57332: When APM tracing is disabled (AppSec Standalone is enabled) we currently do not retain spans with api security schemas, therefore not populating the security api catalog.
Adding system tests to ensure that when in AppSec Standalone mode, when schemas are added to spans (according to the [api sampling algorithm](https://docs.google.com/document/d/1PYoHms9PPXR8V_5_T5-KXAhoFDKQYA8mTnmS12xkGOE/edit?tab=t.0)) the span is marked as `USER_KEEP`.
* Framework is modified, or non obvious usage of it -> …
=> chore(standalone): add api security tests

tests/appsec/test_asm_standalone.py
Separate api sec standalone scenario from asm standalone
=> Separate api sec standalone scenario from asm standalone

tests/parametric/test_config_consistency.py
Avoid using a non-existent host, as this fails under `dd-trace-go` v2 (and therefore, in `v1 transitional` wrapper/shim).
Replace `randomname` with `127.0.0.1` to ensure it works in all versions, including Go `v1` and any other tracer.
=> fix(tests/parametric): update test_dogstatsd_custom_hostname to use 127.0.0.1 hostname

tests/parametric/test_config_consistency.py, utils/build/docker/ruby/parametric/server.rb
Ruby don't have data streams, and have logs injection enabled by default, so we have to tweak the stable config tests a bit
Add more config to the handle_trace_config endpoint (profiling, logs_injection)
Tweak the test for ruby (invert logs_injection tests, disable data stream tests)
Note: The test is not enabled yet, but you can run it locally by doing weird stuff documented [here](https://github.com/DataDog/system-tests/blob/main/utils/build/docker/ruby/parametric/README.md#locally-run-parametric-system-tests-with-an-unreleased-version-of-libdatadog)
* Test logic is modified? -> Get a review from RFC owner. We're …
=> [ruby] Add support for stable config

.gitlab-ci.yml, .gitlab/ssi_gitlab-ci.yml, utils/scripts/ci_orchestrators/gitlab_exporter.py
After the migration to the new aws is completed, we can now clean the leftovers and old references to the "agent qa" account
=> AWS SSI: clean lestovers after new aws account

utils/virtual_machine/aws_infra_exceptions.json
Added new errors to aws ssi retry policy
=> aws ssi: added new errors to retry policy

tests/debugger/test_debugger_telemetry.py
With DEBUG-3587, we can remove the `@missing_feature` decorators for python and dotnet for the exception replay telemetry debugger test.
* In the `test_telemetry_er` method, removed `@missing_feature` decorators for the Python and .NET libraries for ER, indicating these tests are no longer being skipped for these libraries.
:rocket: Once your PR is reviewed, you can merge …
=> Enable exception replay telemetry test for python & dotnet

docs/edit/runbook.md, tests/test_telemetry.py
This test causes too many friction. Adding a new key requires to 
1. A PR on dd-go
2. A PR on system-tests
3. A PR in the final repo
And there is no easy way to entirely remove step 2.
So we'll try another approach, based on alerts in slack channels. …
=> Remove tests on telemetry keys

manifests/ruby.yml
Completing the fingerprinting for rails/device cotribs
Enable the last bits of session fingerprinting for current Ruby implementation
=> [ruby] [APPSEC-57237] Enable session fingerprinting tests

utils/onboarding/injection_log_parser.py
While working on https://github.com/DataDog/auto_inject/pull/646, I encountered an issue with the system-tests because the "skipping" message is not the last line of the log anymore.
Instead, last log is a "telemetry" log (`{"level":"debug","ts":1747139945.1628187,"caller":"telemetry/submitter.go:74","msg":"request json","request":"{\"api_versio...`) …
=> [SSI] Add a new pattern to exclude telemetry logs

.github/workflows/run-parametric.yml
We'd like to force-execute parametric tests in dd-trace-rb CI, but we're directly using system-tests run-parametric.yml workflow
This PR adds two new inputs to run-parametric.yml:
- branch: Tells GHA to checkout another branch than the main one
- forced_tests: An array of tests to force-execute
🛟 …
=> [NO-TICKET] Add forced_tests and branch inputs to parametric GHA workflow

tests/debugger/test_debugger_telemetry.py
Updates the `tests/debugger/test_debugger_telemetry.py` file removing redundant conditional logic, adding a `@flaky` decorator for the dotnet `exception_replay_enabled` telemetry until the order of initialization is updated as part of in-product enablement.
* [`tests/debugger/test_debugger_telemetry.py`](diffhunk://#diff-c5ae7f71aecbbc23f76d9b4c50a11168c79b21efa14955cade1b8013a7461351L6-R6): Added the `flaky` utility to the imports for use in test annotations.
* [`tests/debugger/test_debugger_telemetry.py`](diffhunk://#diff-c5ae7f71aecbbc23f76d9b4c50a11168c79b21efa14955cade1b8013a7461351L27-L30): Removed redundant conditional logic in the `_setup` method, simplifying the determination of the telemetry type.
* [`tests/debugger/test_debugger_telemetry.py`](diffhunk://#diff-c5ae7f71aecbbc23f7 …
=> fix(er): mark ER telemetry for dotnet as flaky

tests/parametric/test_headers_tracecontext.py
I fixed an issue in the Java client library about last parent ID as part of https://github.com/DataDog/dd-trace-java/pull/8719
@zacharycmontoya introduced a test to check all other client libs behave as expected: https://github.com/DataDog/system-tests/pull/4595
This PR enables this new test for the coming version of the Java client library. …
=> [java] Enable last parent id in tracestate test

manifests/ruby.yml, tests/debugger/test_debugger_telemetry.py
=> DEBUG-3573 enable Ruby debugger telemetry tests

manifests/dotnet.yml, manifests/golang.yml, manifests/java.yml, manifests/nodejs.yml, manifests/php.yml, manifests/python.yml, manifests/ruby.yml, tests/test_standard_tags.py, utils/_features.py
A new feature has currently been released both in [Python](https://github.com/DataDog/dd-trace-py/pull/12778) and [PHP](https://github.com/DataDog/dd-trace-php/pull/3196). It parses referrer hostname from http header when it exists and adds it to span tags as `http.referrer_hostname`.
Add tests for this feature.
🛟 …
=> Verify correct extraction of http.referrer_hostname

utils/build/docker/nodejs/express4-typescript.Dockerfile, utils/build/docker/nodejs/express4.Dockerfile, utils/build/docker/nodejs/express5.Dockerfile, utils/build/docker/nodejs/uds-express4.Dockerfile
New vulnerabilities sampling algorithm works in a different way when the max vulnerabilities per request is reached, and to be able to detect the same vulnerability twice needs to have free budget in the first request.
That is why some ST are failing in the new algorithm PR: https://github.com/DataDog/dd-trace-js/pull/5697
Update the env var where the max vulnerabilities per request are defined …
=> [nodejs] Set the max context operations in 10

tests/debugger/test_debugger_pii.py
This pull request includes a minor update to the `tests/debugger/test_debugger_pii.py` file. The change removes a `@bug` decorator for the Java library (`DEBUG-3745`) in the `test_pii_redaction_excluded_identifiers` method, because the related issue has been resolved.
- Remove `@bug` decorator for Java library (`DEBUG-3745`) in the `test_pii_redaction_excluded_identifiers` method …
=> fix(java): Enable debug PII excluded test for v1.49

manifests/dotnet.yml, manifests/golang.yml, manifests/java.yml, manifests/nodejs.yml, manifests/php.yml, manifests/python.yml, manifests/ruby.yml, tests/appsec/test_asm_standalone.py
Test SDK v1 and v2 function when `DD_APM_TRACING_ENABLED` is set to `false`
=> Test sdk functions on standalone mode

manifests/nodejs.yml, tests/appsec/test_asm_standalone.py
Node.js do not send `appsec.events.users.login.failure.usr.exists` meta so instead of asserting this tag check that  `_dd.appsec.usr.login` is an `INVALID_USER`
- `test_user_signup_event_generates_asm_event` is irrelevant for Node.js
- Change `test_user_login_failure_event_generates_asm_event` 
🛟 …
=> User events standalone for Node.js

utils/virtual_machine/aws_infra_exceptions.json
New errors added to the retry policy for the aws ssi tests. All errors are related to build containerized apps
=> AWS SSI: new errors for retry policy

manifests/java.yml, tests/debugger/approvals/exception_replay_inner_java_snapshots_expected.json, tests/debugger/approvals/exception_replay_multiframe_java_snapshots_expected.json, tests/debugger/approvals/exception_replay_recursion_20_java_snapshots_expected.json, tests/debugger/approvals/exception_replay_recursion_3_java_snapshots_expected.json, tests/debugger/approvals/exception_replay_recursion_5_java_snapshots_expected.json, tests/debugger/approvals/exception_replay_rockpaperscissors_java_snapshots_expected.json, tests/debugger/approvals/exception_replay_simple_java_snapshots_expected.json
Changes made to `spring-webmvc-3.1` in this [PR](https://github.com/DataDog/dd-trace-java/pull/8820) has now changed the lines where Live Debugger tests expect the errors to be thrown. This PR updates the lines that the tests expect the lines to be at.
🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025 …
=> Updating Live Debugger Exception Lines `spring-webmvc-3.1`

.github/workflows/run-parametric.yml
=> Fix system-test CI on parametric test

.github/workflows/run-parametric.yml
=> Allow parametric tests to run against an arbitrary system-tests ref

tests/appsec/test_remote_config_rule_changes.py
=> small fix of appsec waf metrics

utils/scripts/add-system-tests-label-on-known-tickets.py, utils/scripts/compute_impacted_scenario.py, utils/tools.py
=> add a script that adds a label on tickets referenced in system-tests

manifests/dotnet.yml, manifests/golang.yml, manifests/java.yml, manifests/nodejs.yml, manifests/php.yml, manifests/python.yml, manifests/ruby.yml, tests/appsec/test_conf.py
libddwaf 1.25.0 has an improved obfuscation mechanism.
- add a new test class to test for the improved feature
- update manifest. In particular add a missing file in several manifests!
=> new system tests for value obfuscation

utils/build/docker/java/akka-http.Dockerfile, utils/build/docker/java/play.Dockerfile, utils/build/docker/java/ratpack.Dockerfile, utils/build/docker/java/resteasy-netty3.Dockerfile, utils/build/docker/java/spring-boot-3-native.Dockerfile, utils/build/docker/java/spring-boot-jetty.Dockerfile, utils/build/docker/java/spring-boot-openliberty.Dockerfile, utils/build/docker/java/spring-boot-payara.Dockerfile, utils/build/docker/java/spring-boot-undertow.Dockerfile, utils/build/docker/java/spring-boot-wildfly.Dockerfile, utils/build/docker/java/spring-boot.Dockerfile, utils/build/docker/java/uds-spring-boot.Dockerfile, utils/build/docker/java/vertx3.Dockerfile, utils/build/docker/java/vertx4.Dockerfile
The new IAST detection algorithm defined in [RFC-1029](https://docs.google.com/document/d/1CfGFm2Ouz5vxOhibNyLCZjGzLbDI3F0fO9irKWqxhVI/edit?tab=t.0#heading=h.vmqy3j71slqi) causes some existing IAST-related tests to fail, as the default limit of 2 vulnerabilities per request is no longer sufficient under the new implementation.
Increase number of vulnerabilities detected by request to 10 …
=> [Java] Increase max number of IAST vulnerabilities per request

manifests/python.yml, utils/build/docker/python/django/app/urls.py
* We forgot to include the deactivation of the "extended" and "stacktrace" tests for header injection in the pull request
* Changed the order of `response.headers` to maintain backward compatibility,  the previous order caused a failure because it triggered the validators first, marking the entire string as valid
Related to: 
https://github.com/DataDog/dd-trace-py/pull/13546
https://github.com/DataDog/system-tests/pull/4711 …
=> [python] finer-grained header injection

manifests/cpp_nginx.yml, manifests/dotnet.yml, manifests/golang.yml, manifests/java.yml, manifests/nodejs.yml, manifests/php.yml, manifests/python.yml, manifests/ruby.yml, tests/appsec/test_service_activation_metric.py, utils/_features.py
Add tests for new feature
New tests, checking the origin in configurations by env variable and remote config.
=> Tests for appsec service activation origin metric

.gitlab-ci.yml
Fix check_pipeline_status: If there is a failure parsing the gitlab api response, fail the job
=> gitlab ci: fix check_pipeline_status

manifests/nodejs.yml, tests/parametric/test_headers_baggage.py
We are switching to the [weblog tests](https://github.com/DataDog/system-tests/blob/main/tests/test_baggage.py) for nodejs baggage after this [PR](https://github.com/DataDog/dd-trace-js/pull/5815) is released
=> [NodeJs] disable parametric tests for nodejs baggage

manifests/python.yml, tests/parametric/test_config_consistency.py
Unblocks: https://github.com/DataDog/dd-trace-py/pull/13570
- Allows the default value of log_injection_enabled to be `None`.
=> parametric: update stable config default value for log injection

utils/build/docker/php/php-fpm-7.0.Dockerfile, utils/build/docker/php/php-fpm-7.1.Dockerfile, utils/build/docker/php/php-fpm-7.2.Dockerfile, utils/build/docker/php/php-fpm-7.3.Dockerfile, utils/build/docker/php/php-fpm-7.4.Dockerfile, utils/build/docker/php/php-fpm-8.0.Dockerfile, utils/build/docker/php/php-fpm-8.1.Dockerfile, utils/build/docker/php/php-fpm-8.2.Dockerfile
ubuntu 20.04 is EOS may 2025, I strongly presume it causes atp-get failures
Per title
=> [php] use ubuntu24.04 for PHP-FPM

manifests/golang.yml
Enables new system tests for AAP Trace Tagging support.
Also fixes one XPASS test.
Depends-on: https://github.com/DataDog/dd-trace-go/pull/3619
=> [golang] AAP: Enable trace tagging rules support

utils/_context/_scenarios/endtoend.py, utils/_context/containers.py
The lack of a healthcheck can cause a race condition on the weblog container startup, where the first few requests to the proxy fail.
This healthcheck ensures the proxy container is ready before the weblog one starts.
* Add a simpke healthcheck on proxy container.
* Ensure the weblog container has the proxy among its dependencies.
:rocket: Once your PR is reviewed, you …
=> Add healthcheck on proxy container

tests/parametric/test_config_consistency.py, tests/parametric/test_dynamic_configuration.py, tests/parametric/test_span_sampling.py, tests/parametric/test_trace_sampling.py, utils/_context/_scenarios/__init__.py, utils/_context/_scenarios/default.py
dd-trace-go is [about to enable Client-Side-Stats by default](https://github.com/DataDog/dd-trace-go/pull/3548). This feature causes all P0 traces to be dropped on the tracer side.
Many system-tests targeting all tracers rely on the fact that all traces are flushed to the agent, and to avoid breaking this pattern, the FF controlling CSS on Go is set to false.
A follow up PR(s) will enhance CSS coverage, which is currently rather low.
Tests that rely on P0 traces being sent to the agent have `DD_TRACE_STATS_COMPUTATION` set to `false`, ensuring dd-trace-go doesn't drop P0 traces.
* Test logic is modified? -> Get a review …
=> Disable Client-Side-Stats on default tests

utils/_context/_scenarios/__init__.py
This is a small follow up on #4773 
These 2 scenarios are shared between libraries, and CSS should not be enabled to ensure consistency on flushed traces.
Disable Client-Side Stats on tests that rely on all P0 spans being flushed.
=> Disable CSS on SAMPLING, SCA_STANDALONE scenarios

manifests/python.yml
After https://github.com/DataDog/dd-trace-py/pull/13690 is merged this will validate the changes by enabling more tests.
APPSEC-58013
=> [python] enable new test for python

manifests/python.yml
=> [python] disable iast standalone test for flask

manifests/dotnet.yml, manifests/python.yml
This unskips some XPASS tests for an APM trace context propagation feature, so that we can track any regressions if they occur.
See PR title.
=> Enable Test_ExtractBehavior_* tests for .NET (v3.10.0+) and Python (v2.20.0+)

utils/build/docker/golang/install_orchestrion.sh
Avoid turning `system-tests` in smoke tests by not using `go get -u`.
Remove `-u` flag from `install_orchestrion.sh`'s calls to `go get`.
=> [golang] fix: update install_orchestrion.sh to remove the -u flag from go get commands for better compatibility

tests/appsec/test_asm_standalone.py
Test_AppSecStandalone_UpstreamPropagation(V2) are flaky in overnight runs
mark them as flaky til we investigate the issue
Tracking: APPSEC-57145
=> [python] chore(standalone): Mark flaky flask Test_AppSecStandalone_UpstreamPropagation(V2)

tests/appsec/test_automated_login_events.py, tests/appsec/test_automated_user_and_session_tracking.py, tests/appsec/waf/test_reports.py
=> [ruby] skip failing tests for APPSEC-58061

utils/build/docker/ruby/rails50/Gemfile, utils/build/docker/ruby/rails50/Gemfile.lock, utils/build/docker/ruby/rails51/Gemfile, utils/build/docker/ruby/rails51/Gemfile.lock, utils/build/docker/ruby/rails52/Gemfile, utils/build/docker/ruby/rails52/Gemfile.lock, utils/build/docker/ruby/rails60/Gemfile, utils/build/docker/ruby/rails60/Gemfile.lock
This PR aligns an external dependency webserver to be the same for all Rails weblog variants. Starting 5.x puma is able to hold fail sticky session which puma < 5.0 is unable to do.
If we want to test different puma variants it should be done either in dd-trace-rb repo or in weblog-variant which explicitly have that version in the name.
Otherwise it makes all the tests unpredictable because puma is not direct dependency of the Rails variant and behaves differently.
`puma ~> 5.0`
=> [ruby] Update puma gem to > 5.0 in all weblogs

utils/build/docker/ruby/install_ddtrace.sh
Native extensions are not compiled when using dd-trace-rb unpacked gem (dev branch)
This changes install_ddtrace.sh script for Ruby dev, by building a .gem file and using the packed gem instead.
=> [ruby] Change install_ddtrace script for dev versions

utils/build/docker/ruby/install_ddtrace.sh
I accidentally pushed a wrong folder name for dd-trace-rb (for testing purpose I renamed it to dd-trace-rb-null)
Fix wrong folder name for dd-trace-rb
=> [ruby] Fix wrong folder name for dd-trace-rb

manifests/java.yml
The baggage tests are currently failing on 1.50.0, so we should mark this feature as not completed yet
This reverts commit a4a3c8502d3bd3103da56b66a7380f40be595626.
=> [Java] Revert "[Java] Enable Baggage Tests (#4679)"

manifests/java.yml
This unskips some XPASS tests for an APM trace context propagation feature, so that we can track any regressions if they occur.
See PR title.
Note: There is one bug that exists when `DD_TRACE_PROPAGATION_BEHAVIOR_EXTRACT=ignore` so the manifest has been updated with a corresponding JIRA card.
🛟 …
=> Enable Test_ExtractBehavior_* tests for Java (v1.48.0)

manifests/ruby.yml
Rack doesn't support path parameters from router (no such functionality), so I mark it as irrelevant because it's impossible to implement for us.
Convert some Rack missing features into irrelevant with additional comment
=> [ruby] Exclude Rack contrib from API Security paths tests

manifests/java.yml
Fixing issues with enabling all weblog instrumentations from #4679. Reverts #4819 with updates.
=> [Java] Re-enabling Baggage Tests with Supported Weblog Instrumentations

manifests/java.yml
Enable the tests that were detected as easy wins in the feature parity dashboard.
=> [java] Enable user events SDK standalone tests

utils/docker_ssi/docker_ssi_images.json
Wildfy and webspher base images moved to the ecr private registry, to avoid rate limits
=> Docker SSI base images from ecr (wildfly and websphere)

tests/auto_inject/test_auto_inject_install.py, tests/auto_inject/utils.py, tests/test_the_test/test_group_rules.py, utils/_context/_scenarios/__init__.py, utils/_context/_scenarios/core.py, utils/_features.py, utils/onboarding/backend_interface.py, utils/onboarding/weblog_interface.py, utils/scripts/ci_orchestrators/aws_ssi.json, utils/scripts/ssi_wizards/aws_onboarding_wizard.sh
Validate the auto activation of Appsec (AAP) using SSI in different environments.
Added new scenarios with corresponding new feature:
- `SIMPLE_AUTO_INJECTION_APPSEC` (feature [478](https://feature-parity.us1.prod.dog/#/?feature=478))
- `HOST_AUTO_INJECTION_INSTALL_SCRIPT_APPSEC` (feature [479](https://feature-parity.us1.prod.dog/#/?feature=479))
- `CONTAINER_AUTO_INJECTION_INSTALL_SCRIPT_APPSEC` (feature [480](https://feature-parity.us1.prod.dog/#/?feature=480))
The appsec test is verifying that the received span contain the metric `_dd.appsec.enabled` set to `1` and the `meta` tag `appsec.event` set to `true`.
* Framework is …
=> Add Appsec SSI tests

manifests/python.yml
https://github.com/DataDog/system-tests/pull/4821 seems to have fix also IAST Standalone for Flask
Enable back those tests
#APPSEC-57145
=> [python] enable back iast standalone tests

manifests/ruby.yml, tests/appsec/waf/test_reports.py
PR for error reporting per config in Ruby tracer: https://github.com/DataDog/dd-trace-rb/pull/4757
This PR enables Remote Config rule changes tests.
=> [Ruby] Update ruby manifest

tests/appsec/waf/test_reports.py
RFC-1025 makes the WAF rules metrics obsolete; and libraries implemeting it should no longer produce them.
Mark `test_waf_monitoring_once` as irrelevant
=> [nodejs] Mark test_waf_monitoring_once as irrelevant

manifests/java.yml
Feature was updated in dd-trace-java v1.50.1. This PR enables the weblog tests for the feature.
=> [Java] Enable Tracecontext Propagation Extract Ignore tests

manifests/java.yml, tests/stats/test_stats.py, utils/_context/_scenarios/__init__.py, utils/build/docker/java/akka-http/src/main/scala/com/datadoghq/akka_http/AppSecRoutes.scala, utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/MyResource.java, utils/build/docker/java/play/app/controllers/AppSecController.scala, utils/build/docker/java/play/conf/routes, utils/build/docker/java/ratpack/src/main/java/com/datadoghq/ratpack/Main.java, utils/build/docker/java/resteasy-netty3/src/main/java/com/datadoghq/resteasy/MyResource.java, utils/build/docker/java/spring-boot-3-native/src/main/java/com/datadoghq/springbootnative/WebController.java, utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/App.java, utils/build/docker/java/vertx3/src/main/java/com/datadoghq/vertx3/Main.java, utils/build/docker/java/vertx4/src/main/java/com/datadoghq/vertx4/Main.java
Java already implement client stats computation
Improve coverage for java CSS. Implement `/stats-unique` endpoint of various java weblogs
=> [Java] Enable more CSS tests

docs/execute/binaries.md, manifests/ruby.yml
Stable config has been merged in dd-trace-rb
Adds next dd-trace-rb release to manifest for stable config.
=> [ruby] [APMAPI-1116] Enable Stable Config Phase 1

manifests/java.yml, utils/build/docker/java/akka-http/src/main/scala/com/datadoghq/akka_http/IastRoutes.scala, utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/IastSamplingResource.java, utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/Main.java, utils/build/docker/java/play/app/controllers/IastSamplingController.java, utils/build/docker/java/play/conf/routes, utils/build/docker/java/ratpack/src/main/java/com/datadoghq/ratpack/IastSamplingHandlers.java, utils/build/docker/java/ratpack/src/main/java/com/datadoghq/ratpack/Main.java, utils/build/docker/java/resteasy-netty3/src/main/java/com/datadoghq/resteasy/IastSinkResource.java, utils/build/docker/java/resteasy-netty3/src/main/java/com/datadoghq/resteasy/Main.java, utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/AppSecIast.java, utils/build/docker/java/vertx3/src/main/java/com/datadoghq/vertx3/Main.java, utils/build/docker/java/vertx3/src/main/java/com/datadoghq/vertx3/iast/routes/IastSamplingRouteProvider.java, utils/build/docker/java/vertx4/src/main/java/com/datadoghq/vertx4/Main.java, utils/build/docker/java/vertx4/src/main/java/com/datadoghq/vertx4/iast/routes/IastSamplingRouteProvider.java
Enable TestSamplingByRouteMethodCount test for java
Endpoints and enable test in java.yml
=> [Java] Enable TestSamplingByRouteMethodCount test

tests/docker_ssi/test_docker_ssi.py
Python has been failing the forwarder tests for some time. The injection metadata tests added by @sydney-tung also rely on this feature to be working. I've fixed the Python tracer integration with telemetry forwarding here: https://github.com/DataDog/dd-trace-py/pull/13926. This change enables both tests so they can be run on the Python pipeline.
- [chore: enable forwarder tests](https://github.com/DataDog/system-tests/pull/4910/commits/c9ef059bfccfb8a5e82cdee1c17375e6d0c75615) 
- This commit enables the telemetry forwarding tests that have been disabled.
- [fix: resolve an issue with the injection metadata test](https://github.com/DataDog/system-tests/pull/4910/commits/6b1780a294a765388ea2e5d85503cd7645dc0d43) 
- This commit accounts for the two events we expect, one from the injector …
=> [python]: enable forwarder tests

tests/appsec/test_asm_standalone.py
The problem is only affecting 2 specific weblogs
APPSEC-58276
=> [python] put flaky in bug mode just for flask and uds

manifests/php.yml, utils/scripts/load-binary.sh
Since `dd-trace-php` is now on gitlab, artifacts are not anymore available where they used to be. Now they are on a s3 bucket. This PR picks dev artifacts from s3
=> [php] Download dev artifacts from s3

manifests/php.yml
=> [php]  Enable scaner tests for PHP

manifests/java.yml
Following bugs were fixed in v1.51.0
bug (APPSEC-56869) in play
bug (APPSEC-56870) in vertx3
bug (APPSEC-56871) in vertx4
=> [Java] Easy wins related with API Security

tests/docker_ssi/test_docker_ssi_crash.py, utils/scripts/ci_orchestrators/docker_ssi.json
The CI job matrix is not correctly configured. We don't have the endpoint for docker ssi crashtracking for: java, php and ruby. 
Also fix the decorators of the test method
=> Docker SSI crashtracking: no java, no php, no ruby

tests/auto_inject/test_auto_inject_chaos.py, tests/auto_inject/test_auto_inject_install.py, tests/auto_inject/test_blocklist_auto_inject.py, utils/scripts/ci_orchestrators/aws_ssi.json
The failures for "redhat" branches and amazon linux 2 (all arm64) are related with the app, that cannot build due a requirements. Remove this machine from the workflow and remove the bug decorators
=> SSI: ruby remove inplat-103 decorators

.github/actions/pull_images/action.yml, .github/workflows/run-end-to-end.yml, .github/workflows/run-external-processing.yml
Running `docker prune` takes 5+ minutes, so we should instead use larger machines with more storage to run scenarios that need more space. Ideally we'd use smaller Docker images, but some of them are really difficult to reduce the size of as the software on them is large to begin with.
Fixes regression from https://github.com/DataDog/dd-trace-js/pull/5884
Remove docker prune before pulling images.
🛟 …
=> remove docker prune before pulling images

manifests/dotnet.yml, tests/appsec/test_asm_standalone.py
In API Sec standalone tests, if a schema is extracted in a span without a security event, the priority will be manual keep, and many tests are expecting a span with drop priority.
Add a function to fix the expected span priority based upon the presence of API Sec schema in the span
=> [APISec] Fix API Sec priority when schema is present

tests/appsec/iast/sink/test_command_injection.py
https://github.com/DataDog/dd-trace-py/actions/runs/16373446947/job/46267846615?pr=14051
=> skip test for old python tracer versions

utils/_context/_scenarios/parametric.py, utils/scripts/load-binary.sh
golang parametric test container can takes more than 5mn to build : https://github.com/DataDog/system-tests-dashboard/actions/runs/16361481218/job/46230058312#step:6:59
Give 10mn before timeout.
=> [golang] give more time to build parametric/golang

manifests/python.yml, tests/parametric/test_config_consistency.py
The default value of DD_LOGS_INJECTION is being reverted back to a boolean with default values of True/False. The telemetry emitted by the python tracer should match this change.
- Default value of DD_LOGS_INJECTION is no longer structured, it will be true.
=> config_telemetry: Ensure python reports True/False for logs injection

utils/build/build_python_base_images.sh, utils/build/docker/python/django-poc.Dockerfile, utils/build/docker/python/django-poc.base.Dockerfile, utils/build/docker/python/django-py3.13.Dockerfile, utils/build/docker/python/django-py3.13.base.Dockerfile, utils/build/docker/python/fastapi.Dockerfile, utils/build/docker/python/fastapi.base.Dockerfile, utils/build/docker/python/flask-poc.Dockerfile, utils/build/docker/python/flask-poc.base.Dockerfile, utils/build/docker/python/python3.12.Dockerfile, utils/build/docker/python/python3.12.base.Dockerfile, utils/build/docker/python/uds-flask.Dockerfile, utils/build/docker/python/uwsgi-poc.Dockerfile, utils/build/docker/python/uwsgi-poc.base.Dockerfile
xmltodict is used in the python weblogs but not installed. It works now because it's a transitive dependency of the python tracer, but will fail if the tracer is dropping it.
This PR install xmltodict explicitely in the weblog base images.
Also small install refactor for fastapi
APPSEC-58429
=> [python] make sure that xmltodict is installed for fastapi

utils/build/docker/python/parametric/apm_test_client/server.py
Update python parametric app to support https://github.com/DataDog/dd-trace-py/pull/14126
- Find default sampling rule by matching on SamplingRule.NO_RULE for older tracers and None for the next release of ddtrace. 
=> [Python] parametric: update python app to match sampling changes

utils/_context/_scenarios/parametric.py, utils/build/docker/nodejs/express4-typescript.Dockerfile, utils/build/docker/nodejs/express4.Dockerfile, utils/build/docker/nodejs/express5.Dockerfile, utils/build/docker/nodejs/fastify.Dockerfile, utils/build/docker/nodejs/nextjs.Dockerfile, utils/build/docker/nodejs/uds-express4.Dockerfile, utils/build/docker/nodejs_otel/express4-otel.Dockerfile
When npm goes down, it usually takes a moment to get back up again (presumably because of load balancers), so immediately retrying can often fail again, but when rerunning the job ~30-60 seconds later it usually passes. This thus adds a pause before retrying so that we're not retrying too quickly.
Add sleep before retrying `npm install`.
=> [nodejs] add sleep before retrying npm install

manifests/nodejs.yml, tests/parametric/test_config_consistency.py
Node counterpart of [Munir's Python PR](https://github.com/DataDog/system-tests/pull/4986)
Temporarily disabling Test_Stable_Config_Default to allow [corresponding changes in dd-trace-js](https://github.com/DataDog/dd-trace-js/pull/6174) to be merged
=> [NodeJS] config_telemetry: Ensure nodejs reports True/False for logs injection

tests/parametric/test_headers_tracestate_dd.py
Otherwise tracers may determine their own _dd.p.dm, overriding the injected one.
Reverts d4653da13381151e60a4b82d1e13ba66b85f446f.
=> Avoid _dd.p.dm without a sampling priority

manifests/dotnet.yml, manifests/golang.yml, manifests/java.yml, manifests/nodejs.yml, manifests/php.yml, manifests/python.yml, manifests/ruby.yml, tests/appsec/test_customconf.py, tests/appsec/test_event_tracking.py, tests/appsec/test_event_tracking_v2.py, tests/appsec/test_remote_config_rule_changes.py, tests/appsec/test_service_activation_metric.py, tests/appsec/utils.py, tests/appsec/waf/test_truncation.py
There was a misunderstanding with this task: it's not a telemetry metric, it's a configuration metric
Python PR: https://github.com/DataDog/dd-trace-py/pull/14198
=> AAP service activation origin configuration metric

tests/appsec/test_asm_standalone.py
SCA is now send as part of `app-client-configuration-change`. This changes adapt sca tests to work with both implementation
=> Adapt sca tests to new implementation

manifests/python.yml
Reverts DataDog/system-tests#5019
@christophe-papazian convinced me that it's wiser to have the version as .dev so it runs before the release.
=> Revert "Add non-.dev tracer flare version for Python"

.github/chainguard/self.update-agent-protobuf.create-pr.sts.yaml, .github/workflows/update-agent-protobuf.yml
Using the `GITHUB_TOKEN` for creation of PRs requires an insecure repository configuration to "Allow GitHub Actions to create and approve pull requests" which allows any person with write (push) access to a repository can bypass branch protection.
To adjust the insecure setting, we need to first move workflows using the `GITHUB_TOKEN` to create PRs to dd-octo-sts. This PR adjusts the workflow and adds the required trust policy. Settings change will be performed afterwards. …
=> Avoid using GITHUB_TOKEN for PR creation

.github/workflows/run-end-to-end.yml, .github/workflows/run-parametric.yml, .github/workflows/system-tests.yml, conftest.py, tests/test_the_test/test_features.py, tests/test_the_test/test_force_option.py, tests/test_the_test/test_group_rules.py, tests/test_the_test/test_strict.py, tests/test_the_test/utils.py, utils/_context/_scenarios/__init__.py, utils/scripts/grep-nightly-logs.py
=> Add force-execute input in official workflow

conftest.py, pyproject.toml, tests/test_miscs.py, tests/test_semantic_conventions.py, tests/test_smoke.py, tests/test_the_test/test_features.py, utils/_features.py
when system-tests fails, it may be complicated to get the owner. This change add a owner property to each tests, thanks to the existing features decorator.
It'll allow to cook better output message, and allow direct notifications
=> Add the dimension of feature owner

manifests/dotnet.yml
Debugger snapshots are broken on .NET main repo
Skip the broken tests
=> [.NET] Skip broken tests

.gitlab-ci.yml
<details open><summary>
</summary>
This repo has a reference to an unused variable as can be seen by the
warning printed in the logs:
```
WARNING: KUBERNETES_SERVICE_ACCOUNT_OVERWRITE variable is no longer used.
WARNING: The service account is now auto-assigned.
```
</details>
<details open><summary>
</summary>
Remove the service account overwrite that is no longer used.
I suspect this yaml is also exported and giving the illusion to other repos
that they overwrite the service account and have access to ci.system-tests*
SSM parameters which is not the case. Examples:
https://gitlab.ddbuild.io/DataDog/apm-reliability/dd-trace-dotnet/-/jobs/1064964347
[Widget here](https://app.datadoghq.com/logs?query=service%3Agitlab-ci%20%22486234852809%3Aparameter%2Fci.system-tests.fp-api-key%22%20%22Acce …
=> Remove KUBERNETES_SERVICE_ACCOUNT_OVERWRITE

manifests/nodejs.yml
re-enable Test_Stable_Config_Default after disabling it in this [PR](https://github.com/DataDog/system-tests/pull/4996)
=> [NodeJS] enable Test_Stable_Config_Default

utils/k8s_lib_injection/k8s_datadog_kubernetes.py
The latest tag of the apm_test_agent is failing. Quick fix: use the tag v1.31.1
=> K8s: use ddapm-test-agent:v1.31.1

.gitlab/ssi_gitlab-ci.yml
There are failures when we execute the aws ssi tests outside of system-tests, it's trying to execute this:
`          export FP_IMPORT_URL=$(aws ssm get-parameter --region us-east-1 --name ci.system-tests.fp-import-url --with-decryption --query "Parameter.Value" --out text)
export FP_API_KEY=$(aws ssm get-parameter --region us-east-1 --name ci.system-tests.fp-api-key --with-decryption --query "Parameter.Value" --out text)`
get the fpd parameters only for main branch on system-tests
:rocket: Once …
=> AWS SSI: Fix ssm getparameter for fpd

manifests/java.yml
Enabling `DD_TRACE_HEADER_TAGS` Wildcard Response Header tests since it has been released in dd-trace-java v1.51.0.
Note: `akka-http` and `play` inject the `Date` header after the tracer does bytecode injection, so they are considered as exceptions.
=> [Java] Enabling `DD_TRACE_HEADER_TAGS` Wildcard Response Header tests 

manifests/java.yml
#5066 broke dd-trace-java master branch since the relevant [PR](https://github.com/DataDog/dd-trace-java/pull/9358) is not merged.
=> [Java] Disabling Debugger Tests

manifests/parser/core.py
The python lambda manifest was not parsed because missing from the component list.
=> Core: read the python lambda manifest

manifests/dotnet.yml, manifests/golang.yml, manifests/java.yml, manifests/nodejs.yml, manifests/php.yml, manifests/python.yml, manifests/python_lambda.yml, manifests/ruby.yml, tests/appsec/test_blocking_addresses.py
Forwarded is now used as a source of ip data
Test if we can block on forwarded header.
Enable it for Python after last changes on main.
APPSEC-58261
=> blocking on forwarded ip

tests/debugger/test_debugger_inproduct_enablement.py
Feature is now generally available as part of the Python tracer
Removes `missing_feature` annotation from the `Test_Debugger_InProduct_Enablement_Dynamic_Instrumentation` function for Python.
=> [python] feat(di): run in-product enablement tests

manifests/java.yml, tests/appsec/test_asm_standalone.py
The recent OKR for Config Sources now reports telemetry for all Config Sources that have been set. This means that a single key can now have multiple telemetry entries, and the existing code accounts for the last one that is seen. Previously, system-tests stores the most recently processed source, which leads to inconsistencies since different tracers may send configs in different orders. The order of sources being sent is not enforced in the RFC. This PR updates the system-tests code to take in the highest precedence Config Source instead of the one most recently processed.
[RFC](https://docs.google.com/document/d/1vhIimn2vt4tDRSxsHn6vWSc8zYHl0Lv0Fk7CQps04C4/edit?tab=t.0#heading=h.7tw832mj0ztp)
3. Mark it as ready for …
=> Update Telemetry Tests to take Highest Source

utils/scripts/compute-impacted-libraries.py
When a branch is specified : 
* a job prevent the PR to be merged, so we don't care if there is a library mismatch
* and the PR is in draft mode : it can be very convenient to run only one tracer during this phase
So there is no loophole if we allow to run the CI, even if other libraries are impacted
If a branch name is set in title prefix (`[cpp@my-branch] Changes`), allow to run the CI, even if the change may impacts other libraries.
:rocket: Once your PR is reviewed and the CI green, you can …
=> Do not fails on library mismatch if a branch is specified

manifests/nodejs.yml
[APPSEC-58077](https://datadoghq.atlassian.net/browse/APPSEC-58077)
Enable the test in Node.js manifest
[APPSEC-58077]: https://datadoghq.atlassian.net/browse/APPSEC-58077?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [nodejs] Enable Test_Blocking_client_ip_with_K8_private_ip for Node.js

manifests/golang.yml
FIx missing path params on net-http
=> [golang] APPSEC-57080 Fix path params not working on net-http servemux instrum

utils/build/docker/python/install_ddtrace.sh
Old option not in use anymore.
Removed the appsec-beta option for dd-trace-py wheel install.
=> Remove appsec-beta

tests/test_smoke.py
=> do not check domain for intake.profile requests from agent

tests/stats/test_stats.py, utils/build/docker/java/vertx3/src/main/java/com/datadoghq/vertx3/Main.java, utils/build/docker/java/vertx4/src/main/java/com/datadoghq/vertx4/Main.java
Related to 
* https://github.com/DataDog/dd-trace-java/pull/9442
=> [APM] Enable CSS for java tracer

utils/_context/_scenarios/__init__.py, utils/_context/_scenarios/appsec_rasp.py, utils/scripts/compute_impacted_scenario.py
Isolating appsec rasp scenario to be able to work on it more easily
This scenario will be used to include API10 tests.
APPSEC-58715
=> isolate appsec rasp

manifests/python_lambda.yml, tests/appsec/test_blocking_addresses.py, utils/_context/_scenarios/aws_lambda.py, utils/build/docker/lambda_proxy/alb.py, utils/build/docker/lambda_proxy/main.py, utils/build/docker/python_lambda/alb-multi.Dockerfile, utils/build/docker/python_lambda/alb.Dockerfile, utils/build/docker/python_lambda/function-url.Dockerfile, utils/build/docker/python_lambda/function/handler.py
To finalize the work started with https://github.com/DataDog/system-tests/pull/5155, by adding the last three remaining http event types.
Following the same pattern as the previous PR:
- modify lambda-proxy to support lambda function url service, application load balancer and application load balancer multi header
- add corresponding python_lambda weblogs
- update the manifests and decorators with known irrelevant features and bugs 
:rocket: Once your PR is reviewed and the CI green, you can …
=> lambda: add three new lambda events with python weblogs

manifests/python_lambda.yml
- With this fix https://github.com/DataDog/datadog-lambda-python/pull/655, we can enable blocking tests for alb-multi weblog.
- With the release of dd-trace-py 3.13, python_lambda automatically passes the ip_forwarded case.
=> [python_lambda] update manifest

manifests/python.yml, utils/build/build_python_base_images.sh, utils/build/docker/python/django-py3.13.Dockerfile, utils/build/docker/python/django-py3.13.base.Dockerfile
Update the gevent version on a weblog to ensure that this version compatibility is tested.
This was resolved in: https://github.com/DataDog/dd-trace-py/pull/14530 
- Update gevent from version 25.5.1 to 25.8.2.
- Update python manifest accordingly
=> [python]: bump django-py3.13 weblog to gevent 25.8.2

tests/debugger/test_debugger_exception_replay.py
Fixes a bug introduced in https://github.com/DataDog/system-tests/pull/5232 where it raised "dictionary changed size during iteration"
* In the `__scrub_python` function, when the key is `"type"` and the value is `"er_snapshot"`, the function now returns `None` instead of deleting the key from the parent, ensuring more consistent handling of this special case.
🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025 …
=> fix(er): dictionary changed size during iteration

manifests/nodejs.yml, tests/appsec/iast/test_security_controls.py
Security controls tests have proven to be flaky for the `fastify` variant.
Flag security controls as flaky for fastify variant in Node.js manifest.
=> [nodejs] Flag all security controls test as flaky for `fastify` variant

.github/workflows/ci.yml
By not ignoring the devflow job, we had a sad situation where by clicking the merge button, you prevent the job from ever being mergable.
Ignore `devflow/merge` in all-jobs-are-green.
=> .github/workflows: allow devflow/merge to be running

tests/appsec/utils.py
- `find_series`  function do not support retreiving metrics from telemetry payloads with the `message-batch` request type
- `find_configurations` function does not support retrieving configurations from telemetry payloads with `app-started` and `message-batch` request type.
- This PR ensures that appsec tests parse telemetry payloads in a consistent manner.  …
=> appsec: Fix util functions that retrieve telemetry metrics and configs

utils/telemetry/intake/static/config_norm_rules.json
These two lines where introduced in https://github.com/DataDog/system-tests/pull/5267 but disappeared in a following PR (https://github.com/DataDog/system-tests/pull/5288/) because the PR to add them in dd-go was not merged yet.
executed: `./utils/telemetry/intake/update.sh`
=> resource renaming: update telemetry from dd-go

tests/fuzzer/main.py, tests/test_the_test/test_docker_scenario.py, utils/_context/_scenarios/appsec_rasp.py, utils/_context/_scenarios/aws_lambda.py, utils/_context/_scenarios/core.py, utils/_context/_scenarios/docker_ssi.py, utils/_context/_scenarios/endtoend.py, utils/_context/_scenarios/external_processing.py, utils/_context/_scenarios/k8s_lib_injection.py, utils/_context/_scenarios/open_telemetry.py, utils/_context/containers.py, utils/proxy/core.py
Supporting @jandro996 initiative to merge scenario that can be mergable, it turns out that many differences in scenario/container object was not specific to those classes, but derivated from context execution. One noticeable exemple is `host_log_folder`, which depends on scenario name, and does not change anything in `TestedContainer` logic.
It makes the script that detect difference complex, because it must ignores those properties.
`Scenario` and `TestedContainer`'s `__init__` methods only takes immutable arguments. The `configure` method will handle any properties that may change during the execution. 
* Framework is modified, …
=> Make scenario and container immutable at init

utils/dd_constants.py
Clean code: open telemetry constants does not belong to datadog constants file, and it's misleading. For instance, datadog also have a `SpanKind`, but its value are not the same from the otel one.
Per title
=> remove otel constants from dd_constants file

.github/CODEOWNERS, tests/test_the_test/reportJunit_expected.xml, utils/_features.py
Team name changed from API to Capabilities a while ago - this change is required to reflect this in Github teams
=> Update CODEOWNERS (apm-sdk-api to apm-sdk-capabilities)

manifests/java.yml
The spring-boot-3-native weblog variant is currently marked as a missing_feature in most tests. This causes the tests to still run for that variant, even though we’re not planning to support it anytime soon. Marking it as irrelevant instead will prevent those tests from running, helping to reduce unnecessary execution and lighten the load on the pipelines.
Change missing_feature with irrelevant spring-boot-3-native
🛟 …
=> [Java] Change missing_feature with irrelevant spring-boot-3-native

manifests/java.yml
Old implementation discarded so no need to run this tests, they were replaced by test_extended_data_collection.py
=> [Java] Mark test_extended_header_collection.py irrelevant

.github/workflows/run-stream-processing-offload.yml, utils/scripts/compute_impacted_scenario.py
=> Remove cleanup parameter for pull_images (not a valid input)

tests/parametric/test_dynamic_configuration.py
The dotnet tracer adds new RC capabilities for remote enabling DI products. This PR add those capabilies to the dotnet `DEFAULT_SUPPORTED_CAPABILITIES_BY_LANG` 
`Capabilities.APM_TRACING_ENABLE_DYNAMIC_INSTRUMENTATION,
Capabilities.APM_TRACING_ENABLE_EXCEPTION_REPLAY,
Capabilities.APM_TRACING_ENABLE_CODE_ORIGIN,
Capabilities.APM_TRACING_ENABLE_LIVE_DEBUGGING,`
🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025 …
=> [dotnet] update dotnet capabilities for DI

utils/dd_constants.py
FF&E integration into Node.js tracer
adds FFE_FLAG_CONFIGURATION_RULES bit 46 to constants
See capability bit PR here: https://github.com/DataDog/dd-go/pull/200760
=> Add FFE_FLAG_CONFIGURATION_RULES Capabilities Bit

tests/debugger/test_debugger_probe_snapshot.py, tests/debugger/utils.py
There are flaky debugger tests that take the form:
```
ValueError: Snapshot log1eed7-5302-4f49-992d-549570e584c2 was not received.
```
Unfortunately, this doesn't give us enough information to properly fix the problem, so instead we'll fail from the setup directly. We also bump the timeout while waiting for the `INSTALLED` status and the snapshot because either of these will prevent the test from passing.
* Added a timeout and failure handling when waiting for probes to reach the "INSTALLED" status. If probes do not reach this status within 60 seconds, a failure message is recorded and the setup process exits early.
* Added a timeout and failure handling when waiting for a snapshot to be received. If the snapshot is not received within 60 seconds, a failure message is recorded.
1. ⚠️ …
=> test(debugger): increase timeout & add probe status asserts

utils/_context/_scenarios/parametric.py
The version is needed for automatic test activation, and it is present in the other reports, so it is more homogeneous like this.
Added the library version to the report, following the format used for other reports.
=> Adding the library version to parametric scenario report

.github/chainguard/self.test-activation.sts.yaml
The policy was targeting a test workflow
=> Update policy to target nightly workflow

run.sh
fix https://github.com/DataDog/system-tests/pull/5363
Exclude deleted REMOTE_CONFIG_MOCKED_BACKEND_ASM_DD_NOCACHE to avoid failures in tracers with explicit execution of this scenario.
=> Fix REMOTE_CONFIG_MOCKED_BACKEND_ASM_DD_NOCACHE merge

manifests/dotnet.yml, tests/parametric/test_config_consistency.py, tests/parametric/test_telemetry.py, utils/build/docker/dotnet/parametric/Endpoints/ApmTestApi.cs
Hands-off config has been merged and is now fully supported in .NET. 
Activation of 2 steps here:
- handsoff config main default test
- telemetry test (but not config-id) is reported
Adapt weblog, adding some new configuration properties among which is profiler enabled
=> [HandsOffConfig] Activate default tests and one telemetry test

tests/test_profiling.py
=> fix: enable springbootnative for profiling test

manifests/ruby.yml, tests/appsec/api_security/test_endpoint_discovery.py
We have a [PR](https://github.com/DataDog/dd-trace-rb/pull/4919) that adds Endpoint Collection to the ruby tracer.
This enables endpoints collection tests for Ruby.
=> [ruby] Enable Endpoint Discovery tests

utils/virtual_machine/virtual_machines.json
The oracle linux vm have been disabled due to a problem.
The AMI are regenerated. Enable the machines again
=> AWS SSI: Enable Oracle Linux again

tests/appsec/test_automated_user_and_session_tracking.py, utils/build/build_python_base_images.sh, utils/build/docker/python/django-poc.Dockerfile, utils/build/docker/python/django-poc.base.Dockerfile, utils/build/docker/python/django-py3.13.Dockerfile, utils/build/docker/python/django-py3.13.base.Dockerfile, utils/build/docker/python/fastapi.Dockerfile, utils/build/docker/python/fastapi.base.Dockerfile, utils/build/docker/python/fastapi/main.py, utils/build/docker/python/python3.12.Dockerfile, utils/build/docker/python/python3.12.base.Dockerfile
Some tests failed on rc1 for the fastapi weblog but not for other commits: https://github.com/DataDog/system-tests/pull/5439.
The reason is that a middleware was not properly installed as `int("0rc1")` raises an Exception that used to make the version default to `(0, 0, 0)` which was below `(3, 1, 0)`.
Use the `packaging` dependency to handle semver correctly and simply.
🛟 …
=> [python]: fix semver parsing bug in fastapi weblog

docs/weblog/README.md, tests/appsec/rasp/rasp_ruleset.json, tests/appsec/rasp/test_api10.py, utils/build/docker/internal_server/app.py, utils/build/docker/python/django/app/urls.py, utils/build/docker/python/fastapi/main.py, utils/build/docker/python/flask/app.py
TRACE requests are not allowed to include a body according to the [specification](https://datatracker.ietf.org/doc/html/rfc7231#section-4.3.8), which can cause issues with client libraries that block such requests.
Use the PUT method instead of TRACE in tests that require a request body.
=> Replace TRACE method with PUT in api10 test with body
