tests/stats/test_stats.py

[golang] Skip stats test failing (APMAPI-738)

---

.gitlab-ci.yml
utils/_context/_scenarios/auto_injection.py
utils/_context/virtual_machines.py
utils/build/virtual_machine/provisions/auto-inject/docker/auto-inject_prepare_docker.yml
utils/build/virtual_machine/weblogs/dotnet/provision_test-app-dotnet-container.yml
utils/build/virtual_machine/weblogs/java/provision_test-app-java-alpine-jdk15.yml
utils/build/virtual_machine/weblogs/java/provision_test-app-java-alpine-jdk21.yml
utils/build/virtual_machine/weblogs/java/provision_test-app-java-alpine-libgcc.yml
utils/build/virtual_machine/weblogs/java/provision_test-app-java-alpine.yml
utils/build/virtual_machine/weblogs/java/provision_test-app-java-buildpack.yml
utils/build/virtual_machine/weblogs/java/provision_test-app-java-container-jdk15.yml
utils/build/virtual_machine/weblogs/java/provision_test-app-java-container.yml
utils/build/virtual_machine/weblogs/ruby/provision_test-app-ruby.yml

Add new virtual machine (ec2): alma linux

OnBoarding: Alma Linux

---

.github/workflows/run-parametric.yml
utils/scripts/compute_impacted_scenario.py

[java] Removes timeout guard on java

---

utils/build/ssi/base/install_os_deps.sh
utils/docker_ssi/docker_ssi_definitions.py

Add alma linux docker image to the Docker ssi tests matrix

Docker SSI: add alma linux

---

manifests/cpp.yml
manifests/dotnet.yml
manifests/golang.yml
manifests/java.yml
manifests/nodejs.yml
manifests/php.yml
manifests/python.yml
manifests/ruby.yml
tests/parametric/test_config_consistency.py
utils/build/docker/python/parametric/apm_test_client/server.py
utils/parametric/_library_client.py

config consistency initiative
implements rate limiting system tests for dd_trace_rate_limit environment variable

implement dd_trace_rate_limit system test

---

.gitlab-ci.yml
tests/parametric/test_crashtracking.py
utils/build/virtual_machine/provisions/auto-inject-ld-preload/provision.yml
utils/build/virtual_machine/provisions/auto-inject/docker/amazon-ecr-credential-helper.yml
utils/build/virtual_machine/provisions/container-auto-inject-install-script/provision.yml
utils/build/virtual_machine/provisions/installer-auto-inject/provision.yml
utils/build/virtual_machine/weblogs/php/provision_test-app-php-container-56.yml
utils/build/virtual_machine/weblogs/php/test-app-php-container-56/Dockerfile.template

[php] Enable INSTALLER_NOT_SUPPORTED_AUTO_INJECTION test

---

.github/workflows/update-agent-protobuf.yml

Update actions version for protobug WF

---

.github/workflows/run-lib-injection.yml

Remove PHP from K8s Lib init validation, because we don't have any weblog yet

K8s Lib Injection Validator: Fix workflow

---

tests/appsec/iast/utils.py

If for some reason a trace is not reported (sampling), the IAST test that was checking that no IAST event was reported was failing, because it didn't find any trace.
* If not trace is reported, no IAST event is reported -> do not complain if it does not find a trace
* Also, checking all spans, not only the first root spans. Better be safe than sorry. …

Better logic for assert_no_iast_event

---

manifests/golang.yml
utils/build/docker/golang/app/chi/main.go
utils/build/docker/golang/app/echo/main.go
utils/build/docker/golang/app/gin/main.go
utils/build/docker/golang/app/net-http/main.go

Support for Attacker Fingerprint for Appsec

[golang] Attacker Fingerprinting

---

pyproject.toml
tests/test_library_logs.py
utils/_features.py

[golang] Remove some orphans

---

utils/_context/virtual_machines.py
utils/build/virtual_machine/provisions/auto-inject/auto-inject_init_vm_config.yml
utils/build/virtual_machine/provisions/auto-inject/auto-inject_pre_installer_manual.yml
utils/build/virtual_machine/provisions/installer-auto-inject/provision.yml
utils/build/virtual_machine/weblogs/common/create_and_run_app_container.sh
utils/build/virtual_machine/weblogs/dotnet/provision_test-app-dotnet.yml
utils/build/virtual_machine/weblogs/dotnet/test-app-dotnet/test-app-dotnet_run.sh
utils/build/virtual_machine/weblogs/java/provision_test-app-java.yml
utils/build/virtual_machine/weblogs/java/test-app-java/test-app-java_run.sh
utils/build/virtual_machine/weblogs/php/provision_test-app-php-container-56.yml
utils/virtual_machine/aws_provider.py
utils/virtual_machine/krunvm_provider.py
utils/virtual_machine/virtual_machine_provider.py
utils/virtual_machine/virtual_machine_provisioner.py

Onboarding: speed up

---

manifests/java.yml

[java] Unskip tests for APPSEC-54982

---

.gitlab-ci.yml
utils/_context/_scenarios/auto_injection.py
utils/_context/virtual_machines.py
utils/build/virtual_machine/weblogs/dotnet/provision_test-app-dotnet.yml
utils/build/virtual_machine/weblogs/ruby/provision_test-app-ruby.yml

Add new ec2 VM to onboarding tests

OnBoarding:add ubuntu 20

---

.gitlab-ci.yml
utils/_context/virtual_machines.py

OnBoarding: Fix ubuntu20

---

.gitlab-ci.yml

Onboarding: fix gitlab

---

tests/remote_config/test_remote_configuration.py
utils/_remote_config.py
utils/proxy/core.py

Fix RC API

---

tests/appsec/test_fingerprinting.py

Complete previous tests with a format check for each fingerprint.
Add a new assert in each test to check the validness of the fingerprint format.

Check attacker fingerprint format

---

utils/_context/_scenarios/__init__.py

Fix typo in TRACING_CONFIG_NONDEFAULT

---

utils/_context/containers.py
utils/build/docker/dotnet/weblog/Endpoints/HealthcheckEndpoint.cs

[dotnet] Get version with healthcheck

---

tests/remote_config/test_remote_configuration.py

[php] Improve RC test to have a understandable error message

---

.gitlab-ci.yml
utils/_context/virtual_machines.py
utils/build/virtual_machine/weblogs/dotnet/provision_test-app-dotnet.yml

OnBoarding: dotnet ubuntu 24 

---

utils/build/virtual_machine/weblogs/dotnet/provision_test-app-dotnet.yml

Onboarding: dotnet add ubuntu 22 amd

---

.gitlab-ci.yml
utils/build/virtual_machine/weblogs/dotnet/provision_test-app-dotnet.yml

Onboarding: dotnet add ubuntu 23

---

utils/_context/containers.py
utils/build/docker/cpp/nginx/install_ddtrace.sh
utils/build/docker/cpp/nginx/nginx.conf

[cpp] Use healtcheck to get version #2799

---

manifests/nodejs.yml

Feature is now merged in the tracer, we want to enable the tests for the next release.

[nodejs] Enable cookie filters for the next release

---

manifests/python.yml
utils/build/build_python_base_images.sh
utils/build/docker/python/django-poc.Dockerfile
utils/build/docker/python/django-poc.base.Dockerfile
utils/build/docker/python/django/app/urls.py
utils/build/docker/python/fastapi.Dockerfile
utils/build/docker/python/fastapi.base.Dockerfile
utils/build/docker/python/fastapi/main.py
utils/build/docker/python/python3.12.Dockerfile
utils/build/docker/python/python3.12.base.Dockerfile

The python tracer changes have been released now.
Marking the released version.

[SVLS-5268] mark the span pointer tests as released

---

docs/execute/binaries.md

Realized steps where outdated when I tried contributing to the Datadog SDK PHP repo.

Adding Current PHP Binaries Steps

---

utils/_context/_scenarios/endtoend.py
utils/_context/containers.py

Allow scenario to define weblog volumes

---

tests/appsec/rasp/test_shi.py
tests/appsec/rasp/test_ssrf.py

Assign the correct feature to SHi and SSRF capability test
Fix test name and assigned feature

Fix SHi and SSRF capability test

---

.gitlab-ci.yml
utils/build/virtual_machine/weblogs/dotnet/provision_test-app-dotnet.yml

Onboarding: dotnet enable amazon linux 2

---

utils/_context/_scenarios/auto_injection.py

There are some characters in the components versions, that may impact on the FP reports. Clean the string
Clean component version string

Onboarding: Clean components versions

---

tests/appsec/test_asm_standalone.py

[python] Skip test for APPSEC-55222

---

utils/build/docker/python/flask/app.py

We shouldn't make assumption of module loaded
remove ddwaf get_version as it's not required anymore

[python] fix for flask-poc

---

utils/build/virtual_machine/weblogs/java/provision_test-app-java-container.yml

Activate more Vms for test-app-java-container

Onboarding: java container activation

---

utils/_context/containers.py
utils/build/docker/python_otel/flask-poc-otel.Dockerfile
utils/build/docker/python_otel/flask-poc-otel/app.py

[python] Add healtcheck on python_otel weblog

---

utils/build/virtual_machine/weblogs/java/provision_test-app-java-alpine-jdk15.yml
utils/virtual_machine/virtual_machine_provider.py

Onboarding: java alpine jdk15 activation

---

utils/_context/containers.py
utils/build/docker/nodejs_otel/express4-otel.Dockerfile
utils/build/docker/nodejs_otel/express4-otel/app.js

[nodejs] Implements healthcheck on nodejs otel weblog

---

utils/build/virtual_machine/weblogs/java/provision_test-app-java-alpine-jdk21.yml
utils/build/virtual_machine/weblogs/java/provision_test-app-java-alpine.yml
utils/build/virtual_machine/weblogs/java/provision_test-app-java-container-jdk15.yml

OnBoarding: Activate more VMs for java containers

---

utils/build/virtual_machine/weblogs/nodejs/provision_test-app-nodejs-alpine.yml
utils/build/virtual_machine/weblogs/nodejs/provision_test-app-nodejs-container.yml
utils/build/virtual_machine/weblogs/nodejs/provision_test-app-nodejs.yml

Onboarding: nodejs enable vms

---

utils/build/virtual_machine/weblogs/dotnet/provision_test-app-dotnet-container.yml

Onboarding: dotnet enable more vms

---

tests/auto_inject/conftest.py
tests/auto_inject/test_auto_inject_blocklist.py
tests/auto_inject/test_auto_inject_chaos.py
tests/auto_inject/test_auto_inject_guardrail.py
tests/auto_inject/test_auto_inject_install.py
tests/auto_inject/utils.py
utils/_decorators.py
utils/virtual_machine/utils.py

We need a bug marker for onboarding, in order to skip test by virtual machine properties

OnBoarding: Bug marker

---

tests/parametric/test_telemetry.py

Reverts DataDog/system-tests#3221
cc @mabdinur @khanayan123

Revert "[python] update telemetry configuration names"

---

manifests/java.yml
tests/appsec/test_fingerprinting.py

Enables the test for session fingerprints and also RC capabilities.
Updates the java manifest and also adds the required scenario to enable the RC endpoint in the agent.

Enable session fingerprint and capabilities tests

---

tests/stats/test_stats.py

This test was disabled for dotnet and go due to flakiness (and has flaked in python too)
From what I can tell what happens sometimes is under load / poor timing the hits stats being generated can occur across stats calculation boundaries (since flushes happen at specific time intervals). Previously the test looked for exactly one payload that would have the desired number of hits causing flakes. This changes the test to aggregate the hits and allows for up to 4 separate payloads (2 for each http status). 
* …

Reduce flakiness of client stats test APMAPI-738

---

.gitlab-ci.yml
conftest.py
utils/_context/_scenarios/auto_injection.py

Split feature parity dashboard by machine.
Add configuration node to the fpd report with os and arch

Onboarding: feature parity dashboard

---

utils/_context/_scenarios/auto_injection.py

Minor fixes on FPD report
- Add pipeline url
- set environment
- remove host from the testDependencies

Onboarding: fix FPD data

---

tests/parametric/test_headers_precedence.py

With distributed tracing, there are scenarios where we do not have a connection between a span created in a different service and spans created in Datadog. Thus, when a span is propagated from a different service to Datadog and has a different `trace_id` from the local trace, we want to use a `span_link` in order to create a relationship between the spans.
[RFC](https://docs.google.com/document/d/1xacBonCyuVk95D-L1STXGqdLtsOuf0_3jG-138uXHnQ/edit?tab=t.0#bookmark=id.uwnmpxy1znny)
Creating a new system test to check the existence of span links when spans are created with a w3c format precedence when spans are propagated through headers. Additionally, enabling the test that checks the existence of span links when spans are created with Datadog format precedence. …

Creating and enabling system tests to verify creation of span links for distributed tracing

---

.gitignore
default.nix
flake.lock
flake.nix
utils/scripts/compute_impacted_scenario.py

- Flakes are faster, especially when one is using direnv
- Python 3.9 usage is deprecated in favour of 3.12
- Migrate to Nix flakes
- Provide backwards compatible shims for non-flake usage
- Move to Python 3.12
- Add CI to check for any regression
Test locally with:
- [optional if nixpkgs is installed] `curl -L https://nixos.org/nix/install | sh -s -- --daemon`
- `nix flake show`
- `nix-shell` + `./build.sh -i runner` + `./run.sh TEST_THE_TEST`
- `nix develop` + `./build.sh -i runner` + `./run.sh TEST_THE_TEST`
Test in CI, [the workflow needs access allowed to these actions](https://github.com/DataDog/system-tests/actions/runs/11401608205):
- `DeterminateSystems/nix-installer-action@main`
- `DeterminateSystems/magic-nix-cache-action@main`
2. Work on you PR …

Update Nix stuff

---

manifests/nodejs.yml

Enable XPASSing tests.
To enable SRB missing test in Node.js manifest

[nodejs] Enable `Test_Suspicious_Request_Blocking` missing test for Node.js

---

docs/execute/binaries.md

Make it so the people testing know of all the options available to test their changes.

Updating Binaries Usage for Java

---

docs/edit/versions.md

Add a doc on how to use versions

---

tests/test_the_test/test_version.py

Just add more clarity to the precedence rules
Add a couple more tests for version comparisons

Add more SemVer comparisons for test-the-tests

---

.gitlab-ci.yml
utils/_context/_scenarios/auto_injection.py

Use standard FPD report parameters
Push: Only for scheduled main branch

onboarding FPD reports

---

run.sh

Some loose ends
- make the var `local`
- display actual version in message
- quote subshell capture

Fix python version deprecation warning

---

manifests/python.yml
utils/build/docker/python/fastapi/main.py

[python] enable fastapi cookies

---

.github/workflows/run-docker-mode.yml
.github/workflows/run-end-to-end.yml
.github/workflows/run-external-processing.yml
.github/workflows/run-graphql.yml
README.md
docs/CI/README.md
docs/CI/github-actions.md
docs/CI/gitlab-ci.md
docs/README.md
docs/execute/README.md
utils/_context/_scenarios/__init__.py
utils/_context/_scenarios/endtoend.py
utils/_context/_scenarios/open_telemetry.py
utils/_context/containers.py
utils/proxy/core.py

Make DD_API_KEY optional

---

manifests/python.yml

Update semver format as @cbeauchesne suggested https://github.com/DataDog/system-tests/pull/3292#discussion_r1814874980

[python] semver format

---

utils/_context/_scenarios/integrations.py

Do not require AWS keys for CROSSED_TRACING_LIBRARIES

---

docs/internals/flushing.md

Add updated links to flushing.md

---

utils/build/docker/java_otel/spring-boot-native.Dockerfile

Build errors:
```
> [ 3/10] RUN curl https://archive.apache.org/dist/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.tar.gz --output /opt/maven.tar.gz && 	tar xzvf /opt/maven.tar.gz --directory /opt && 	rm /opt/maven.tar.gz:
curl: (7) Failed to connect to archive.apache.org port 443: Connection timed out
```
🛟 …

[java] Use maven Docker image for java otel native

---

tests/test_schemas.py

[python] skip failing test for DEBUG-3083

---

tests/parametric/test_dynamic_configuration.py
tests/parametric/test_telemetry.py
tests/parametric/test_tracer_flare.py

[cpp] Skip test for APMAPI-833

---

pyproject.toml
tests/integrations/test_dsm.py

Reports RabbitMQ bugs in JIRA

---

pyproject.toml
tests/appsec/test_shell_execution.py

Reports ASM bugs to JIRA

---

manifests/ruby.yml
pyproject.toml
tests/parametric/test_dynamic_configuration.py
utils/_context/_scenarios/parametric.py

Report bug in jira for test_dynamic_configuration.py

---

manifests/java.yml
tests/test_config_consistency.py

Update Java manifest file to include updated config implementations from Config Consistency Work.

Release versions for config consistency efforts

---

docs/scenarios/parametric.md

ZachG parametric.md docs nit

---

tests/parametric/test_config_consistency.py

[ruby] skip test on a missing feature

---

utils/_context/virtual_machines.py

Change the ec2 amd instance type

Onboarding: Change amd instance type

---

utils/build/virtual_machine/weblogs/java/provision_test-app-java-multialpine.yml
utils/build/virtual_machine/weblogs/java/provision_test-app-java-multicontainer.yml

https://github.com/DataDog/system-tests/pull/3351 introduced an error with JDK8 + rpm.
Use the correct command to install jdk8 on non-Amazon Linux, rpm based systems

[Java] Fix JDK8 install with rpm

---

docs/weblog/README.md
manifests/cpp.yml
manifests/dotnet.yml
manifests/golang.yml
manifests/java.yml
manifests/nodejs.yml
manifests/php.yml
manifests/python.yml
manifests/ruby.yml
tests/serverless/span_pointers/aws/test_s3_span_pointers.py
tests/serverless/span_pointers/utils.py
utils/build/docker/python/django/app/urls.py
utils/build/docker/python/flask/app.py

More span pointer tests.
A test for the mocked s3 multipart upload process.

feat: [SVLS-5778] multipart upload tests for span pointers

---

utils/build/docker/python_otel/flask-poc-otel.Dockerfile

[python] Fix python_otel weblog

---

pyproject.toml
tests/debugger/test_debugger_pii.py

Remove one test form jira exception list

---

tests/debugger/test_debugger_expression_language.py

[dotnet] Skip failing test for DEBUG-3115

---

utils/virtual_machine/aws_provider.py

Onboarding: increase vm volume size

---

tests/debugger/test_debugger_expression_language.py

Fix typo in regular expression

---

tests/test_schemas.py

[python] Revert #3354

---

utils/virtual_machine/utils.py
utils/virtual_machine/virtual_machine_provisioner.py

Onboarding: mark test as bug by runtime_version

---

manifests/python.yml

[python] ddtrace span set_baggage is available on 2.16

---

utils/_context/_scenarios/auto_injection.py
utils/build/virtual_machine/provisions/auto-inject/auto-inject-tested_components.yml
utils/build/virtual_machine/provisions/auto-inject/check_glibc.sh
utils/virtual_machine/aws_provider.py

Extract glibc version and type
We only extract the glibc version from host, not from containers

Onboarding: glibc version as tested component

---

utils/build/docker/ruby/README.md
utils/build/docker/ruby/graphql23.Dockerfile
utils/build/docker/ruby/rack.Dockerfile
utils/build/docker/ruby/rails42.Dockerfile
utils/build/docker/ruby/rails50.Dockerfile
utils/build/docker/ruby/rails51.Dockerfile
utils/build/docker/ruby/rails52.Dockerfile
utils/build/docker/ruby/rails60.Dockerfile
utils/build/docker/ruby/rails61.Dockerfile
utils/build/docker/ruby/rails70.Dockerfile
utils/build/docker/ruby/rails71.Dockerfile
utils/build/docker/ruby/sinatra14.Dockerfile
utils/build/docker/ruby/sinatra20.Dockerfile
utils/build/docker/ruby/sinatra21.Dockerfile
utils/build/docker/ruby/sinatra22.Dockerfile
utils/build/docker/ruby/sinatra30.Dockerfile
utils/build/docker/ruby/sinatra31.Dockerfile
utils/build/docker/ruby/sinatra32.Dockerfile
utils/build/docker/ruby/sinatra40.Dockerfile
utils/build/docker/ruby/uds-sinatra.Dockerfile

Those ruby images are no longer maintained, we are using those from https://github.com/DataDog/images-rb
Swap ruby images for maintenence.

[Ruby] Swap ruby images

---

.gitlab-ci.yml
utils/_context/_scenarios/auto_injection.py
utils/_context/virtual_machines.py
utils/build/virtual_machine/weblogs/dotnet/provision_test-app-dotnet.yml
utils/build/virtual_machine/weblogs/ruby/provision_test-app-ruby-container.yml
utils/virtual_machine/aws_provider.py

Onboarding: Add AL2022

---

.gitlab-ci.yml
utils/_context/_scenarios/auto_injection.py
utils/_context/virtual_machines.py
utils/build/virtual_machine/provisions/auto-inject/auto-inject_init_vm_config.yml
utils/build/virtual_machine/provisions/auto-inject/docker/auto-inject_prepare_docker.yml

Onboarding: add Centos8

---

utils/_context/_scenarios/__init__.py
utils/virtual_machine/aws_provider.py

Onboarding: reduce vm profiling

---

utils/build/virtual_machine/weblogs/python/provision_test-app-python-alpine.yml
utils/build/virtual_machine/weblogs/python/provision_test-app-python-container.yml

We were excluding the amazon linux 2023 amd64 for python docker container. Enable again.

Onboarding: Enable python AL2023

---

manifests/java.yml

Reviewed and refined RASP tests for Java.
Created related tickets.
Corrected XPASS tests

[Java] Refine RASP tests

---

tests/debugger/test_debugger_pii.py
tests/debugger/test_debugger_probe_status.py

[python] Skip test for regression introduced in 2.16

---

tests/appsec/test_runtime_activation.py
tests/appsec/test_suspicious_attacker_blocking.py

[golang] Skip flaky test for APPSEC-55820

---

tests/appsec/waf/test_rules.py

[java] Skip flaky test for APPSEC-55828

---

utils/_context/_scenarios/auto_injection.py

OnBoarding: restore and fix full tracing without limits

---

utils/_context/_scenarios/__init__.py
utils/_context/_scenarios/core.py
utils/_context/_scenarios/default.py
utils/_context/_scenarios/integrations.py

Reintroduce essentials group

---

tests/appsec/test_runtime_activation.py
tests/appsec/test_suspicious_attacker_blocking.py

[golang] APPSEC-55820 is also impacting released dd-trace-go

---

tests/appsec/test_runtime_activation.py
tests/appsec/test_suspicious_attacker_blocking.py
utils/_context/_scenarios/__init__.py

[golang] Unskip tests for APPSEC-55820

---

docs/weblog/README.md
manifests/dotnet.yml
utils/build/docker/dotnet/weblog/Constants.cs
utils/build/docker/dotnet/weblog/Endpoints/RequestDownStreamEndpoint.cs
utils/build/docker/dotnet/weblog/Endpoints/VulnerableRequestDownstreamEndpoint.cs
utils/build/docker/dotnet/weblog/Helper.cs

Activating tests is good.
Add required endpoint and activate https://github.com/DataDog/system-tests/pull/3313 

[dotnet] activate standalone iast tests

---

manifests/cpp.yml
manifests/dotnet.yml
manifests/golang.yml
manifests/java.yml
manifests/nodejs.yml
manifests/php.yml
manifests/python.yml
manifests/ruby.yml
tests/appsec/iast/sink/test_template_injection.py
utils/_features.py
utils/build/docker/nodejs/express4-typescript/iast.ts
utils/build/docker/nodejs/express4-typescript/package-lock.json
utils/build/docker/nodejs/express4-typescript/package.json
utils/build/docker/nodejs/express4/iast/index.js
utils/build/docker/nodejs/express4/package-lock.json
utils/build/docker/nodejs/express4/package.json

Add tests for the new template injection feature implemented
Implement template injection endpoints in Node.js applications, enable the system tests for the next dd-trace-js version and add `missing_feature` for the rest of the traces.

Add template injection tests

---

tests/debugger/test_debugger_expression_language.py
utils/build/docker/dotnet/weblog/Controllers/DebuggerController.cs
utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/debugger/DebuggerController.java

Unmark java expression language bugs + fixes
Unmark fixed bugs.
Update Jira tickets.
Code fixes

[Debugger] Unmark java expression language bugs + fixes

---

tests/appsec/api_security/test_apisec_sampling.py

[nodejs] Skip test for APPSEC-55901

---

utils/_context/_scenarios/__init__.py

[nodejs] Adds APPSEC_API_SECURITY_WITH_SAMPLING to essentials group

---

.gitlab-ci.yml
tests/auto_inject/test_auto_inject_chaos.py
tests/auto_inject/test_auto_inject_install.py
tests/auto_inject/test_blocklist_auto_inject.py
utils/build/virtual_machine/provisions/auto-inject/auto-inject-tested_components.yml
utils/build/virtual_machine/weblogs/python/provision_test-app-python-unsupported-defaults.yml
utils/build/virtual_machine/weblogs/python/provision_test-app-python.yml
utils/build/virtual_machine/weblogs/python/test-app-python/test-app-python_run.sh

Onboarding: Python default installs

---

utils/build/virtual_machine/provisions/auto-inject/auto-inject-tested_components.yml

we can extract the java version dinamically for host apps

Onboarding: Extract Java version

---

run.sh

Fix run.sh on groups

---

utils/_context/_scenarios/auto_injection.py
utils/build/virtual_machine/provisions/auto-inject/auto-inject_init_vm_config.yml
utils/build/virtual_machine/weblogs/nodejs/provision_test-app-nodejs.yml

Ubuntu 23 need apt get update to find the ndoejs package

OnBoarding fix nodejs installation

---

.gitlab-ci.yml

A PR introduced a problem in gitlab. We cannot run all the jobs in parallel because the aws resources are not enough

OnBoarding: restore/fix gitlab ci

---

tests/docker_ssi/test_docker_ssi.py
utils/docker_ssi/docker_ssi_definitions.py

Enable more PHP docker-ssi tests

---

tests/parametric/test_parametric_endpoints.py

parametric: remove stale comment

---

utils/proxy/_deserializer.py

Support for gzip in multipart/form-data; #3508

---

utils/build/ssi/build_local.sh
utils/docker_ssi/docker_ssi_definitions.py

Docker ssi nodejs fixes

---

manifests/python.yml
releasenotes/notes/exploit_prevention_patch_fix-12736874c12b8b7d.yaml

After https://github.com/DataDog/dd-trace-py/pull/11453
APPSEC-55919

[python] easy wins for lfi  rule version

---

pyproject.toml
tests/integrations/test_db_integrations_sql.py
tests/integrations/test_open_telemetry.py
tests/parametric/test_headers_tracestate_dd.py
tests/parametric/test_otel_span_methods.py

Report some bugs to JIRA

---

utils/interfaces/_library/core.py

Corner-case : if traces payload has no content

---

tests/auto_inject/test_auto_inject_guardrail.py
tests/auto_inject/test_auto_inject_install.py

INPLAT-186 and INPLAT-136 have been resolved so these tests can be run again.

[nodejs] remove SSI skips

---

tests/parametric/test_telemetry.py

Fixes: https://github.com/DataDog/system-tests/actions/runs/12037245026/job/33560265947?pr=3563

fix linting errors [paremetric]

---

utils/_context/_scenarios/auto_injection.py

The repositories for ubuntu 23.04 amd64 are broken

Onboarding: Disable ubuntu23.04 amd

---

manifests/nodejs.yml

It is an XPASS, and want to fix it.
nodejs.yml to change from missing_feature to a version.

[nodejs] Set version for LFI Rules version tests

---

pyproject.toml
tests/remote_config/test_remote_configuration.py
tests/test_telemetry.py

Unskip some xpassing tests

---

.gitlab-ci.yml
utils/onboarding/injection_log_parser.py

remove check of log being cleaned

---

utils/_context/_scenarios/auto_injection.py

Onboarding: Fix library version

---

tests/test_profiling.py
utils/interfaces/_agent.py
utils/interfaces/_library/core.py
utils/proxy/_deserializer.py

fix profiling test

---

pyproject.toml
tests/parametric/test_span_sampling.py
tests/parametric/test_trace_sampling.py

[nodejs] Reports bug to JIRA

---

pyproject.toml
tests/test_telemetry.py

Do not check response from backend

---

pyproject.toml
tests/parametric/test_span_sampling.py
tests/parametric/test_trace_sampling.py

Report bugs to jira

---

utils/_context/_scenarios/__init__.py
utils/_context/_scenarios/profiling.py
utils/scripts/compute_impacted_scenario.py

Use a dedicated file to define profiling scenario

---

docs/weblog/README.md
manifests/dotnet.yml
manifests/golang.yml
manifests/java.yml
manifests/nodejs.yml
manifests/php.yml
manifests/python.yml
manifests/ruby.yml
tests/appsec/api_security/test_apisec_sampling.py
utils/_context/_scenarios/__init__.py
utils/build/docker/nodejs/express4-typescript/app.ts
utils/build/docker/nodejs/express4/app.js
utils/build/docker/python/django/app/urls.py
utils/build/docker/python/fastapi/main.py
utils/build/docker/python/flask/app.py

Add tests for new api security sampling algorithm
- Keep the existing sampling rate test
- Add tests for different endpoints
- Add tests for different paths
- Add tests for different statuses
- Add a test with delay

Add new api sampling algorithms tests

---

utils/build/virtual_machine/provisions/auto-inject/auto-inject_init_vm_config.yml

Ubuntu 23 was removed from the mirror we were using.
Use an archival mirror for older Ubuntu versions.

[onboarding] update mirror for old ubuntu versions

---

.github/workflows/run-lib-injection.yml

we are not storing the log files for k8s tests

K8s archive logs

---

lib-injection/build/build_lib_injection_images.sh

Add the new k8s weblog image to the script

K8s generate djm image

---

lib-injection/build/build_lib_injection_images.sh

k8s force djm weblog generation

---

utils/build/virtual_machine/weblogs/java/provision_test-app-java-alpine.yml
utils/build/virtual_machine/weblogs/java/provision_test-app-java-container.yml

There is not installation candidate for java 11 on ubuntu 23 arm
Skip the vm ubuntu 23 arm for the weblogs: test-app-java-alpine and test-app-java-container

Onboarding: exclude ubuntu 23.04 arm java

---

.gitlab-ci.yml
conftest.py
utils/_context/_scenarios/auto_injection.py
utils/virtual_machine/utils.py

Onboarding: one pipeline

---

pyproject.toml
tests/test_the_test/test_decorators.py
tests/test_the_test/test_force_option.py
tests/test_the_test/test_force_skip.py
tests/test_the_test/test_json_report.py
tests/test_the_test/test_strict.py

Add fake jira ticket to TEST_THE_TEST

---

pyproject.toml
tests/k8s_lib_injection/test_k8s_init_image_validator.py

K8s remove bug markers image validator

---

utils/_context/_scenarios/profiling.py

[python] Use DD_PROFILING_STACK_V2_ENABLED for profiling

---

pyproject.toml
tests/test_schemas.py

Report last known bug without jira to jira

---

utils/docker_ssi/docker_ssi_matrix_builder.py

Docker SSI fix fpd

---

pyproject.toml
utils/_decorators.py

Remove allow_no_jira_ticket_for_bugs exception list

---

utils/virtual_machine/utils.py

Onboarding: fix cache

---

manifests/python.yml

[python] easy wins for python on rasp cmdi tests

---

pyproject.toml
utils/_context/_scenarios/parametric.py
utils/parametric/_library_client.py
utils/parametric/spec/remoteconfig.py
utils/parametric/spec/trace.py
utils/parametric/spec/tracecontext.py

Fix ruff checks for parametric folders

---

lib-injection/build/docker/dotnet/dd-lib-dotnet-init-test-app/Program.cs
tests/docker_ssi/test_docker_ssi_crash.py
utils/build/ssi/base/dotnet_install_runtimes.sh
utils/build/ssi/base/tested_components.sh
utils/build/ssi/dotnet/dotnet-app.Dockerfile
utils/docker_ssi/docker_ssi_definitions.py
utils/docker_ssi/docker_ssi_matrix_utils.py
utils/interfaces/_test_agent.py

https://datadoghq.atlassian.net/browse/INPLAT-172
Enable docker-ssi tests for .net. 
Had to update the test slightly because it didn't support telemetry logs that are not arrays.

Enable docker-ssi tests for .net

---

utils/build/docker/nodejs_otel/express4-otel.Dockerfile
utils/scripts/compute_impacted_scenario.py

[nodejs] Fix otel scenario

---

pyproject.toml
utils/interfaces/_core.py
utils/interfaces/_library/appsec.py
utils/interfaces/_logs.py
utils/interfaces/_schemas_validators.py
utils/interfaces/_test_agent.py
utils/interfaces/schemas/serve_doc.py

Fix ruff checks in interfaces folder

---

tests/test_telemetry.py

[php] Skip failing test for APMAPI-971

---

tests/test_distributed.py

Improve stdout for span link tests

---

tests/test_profiling.py

[python] Unskip profiling test for PROF-11018

---

tests/appsec/test_asm_standalone.py

[python] Skip flaky test for APPSEC-56142

---

utils/_context/containers.py

Fix rabbitmq image version

---

tests/remote_config/test_remote_configuration.py

[python] Skip test for DEBUG-3243

---

tests/fuzzer/main.py
tests/test_the_test/test_docker_scenario.py
utils/_context/_scenarios/docker_ssi.py
utils/_context/_scenarios/endtoend.py
utils/_context/_scenarios/k8s_lib_injection.py
utils/_context/containers.py

Prepare #3549
Cherry picked from the POC #3624

[revamp] Each scenario handles how to start docker network

---

utils/build/docker/java/spring-boot-3-native.Dockerfile
utils/build/docker/java/spring-boot-3-native/pom.xml

[java] Remove useless Docker stage for spring-boot-3-native

---

utils/build/docker/java/spring-boot-3-native.Dockerfile

```
curl: (28) Failed to connect to archive.apache.org port 443: Connection timed out
```

[java] Avoid curl to install Maven on spring-boot-3-native

---

conftest.py
pyproject.toml
utils/_context/_scenarios/__init__.py
utils/_context/_scenarios/auto_injection.py
utils/_context/_scenarios/core.py
utils/_context/_scenarios/integrations.py
utils/_context/_scenarios/parametric.py
utils/_context/containers.py
utils/_context/core.py
utils/_context/virtual_machines.py
utils/_remote_config.py
utils/interfaces/_library/appsec.py
utils/interfaces/_logs.py
utils/onboarding/injection_log_parser.py
utils/parametric/spec/trace.py
utils/scripts/extract_appsec_waf_rules.py
utils/tools.py

Activate ruff RUF015, RET503, E501

---

docs/scenarios/parametric.md

Fix typos in links for parametric docs
Fixes links (and tests the fixed links)

[skipci] Fix typos in links

---

tests/test_telemetry.py
utils/_context/_scenarios/__init__.py
utils/_context/_scenarios/endtoend.py
utils/_context/_scenarios/ipv6.py
utils/_context/containers.py
utils/_remote_config.py
utils/_weblog.py
utils/buddies.py
utils/build/docker/java_otel/spring-boot-native/src/main/java/com/datadoghq/springbootnative/App.java
utils/build/docker/php/common/php.ini
utils/proxy/core.py
utils/proxy/ports.py

Revamp how proxy determine flow provenance

---

conftest.py
pyproject.toml
utils/_context/_scenarios/core.py
utils/_context/_scenarios/endtoend.py
utils/_context/_scenarios/k8s_lib_injection.py
utils/_context/containers.py
utils/_context/virtual_machines.py
utils/_decorators.py
utils/_remote_config.py
utils/_weblog.py
utils/interfaces/_agent.py
utils/interfaces/_backend.py
utils/interfaces/_core.py
utils/interfaces/_library/appsec.py
utils/interfaces/_open_telemetry.py
utils/k8s_lib_injection/k8s_command_utils.py
utils/k8s_lib_injection/k8s_weblog.py
utils/k8s_lib_injection/k8s_wrapper.py
utils/onboarding/weblog_interface.py
utils/parametric/_library_client.py
utils/properties_serialization.py
utils/proxy/_deserializer.py
utils/scripts/get-nightly-logs.py
utils/virtual_machine/utils.py
utils/virtual_machine/virtual_machine_provider.py

Activate ruff rules ARG001, ARG002, ARG005, D200, D404, D410 and D417

---

.gitattributes

Allow github searching in `utils/build`.
update `.gitattributes`.
see https://docs.github.com/en/search-github/searching-on-github/finding-files-on-github#customizing-excluded-files
thanks @kevingosse.

unhide directories called `build` from github file search

---

tests/parametric/test_span_sampling.py

[java] skip another test for APMAPI-978

---

conftest.py
pyproject.toml
utils/_context/_scenarios/__init__.py
utils/_context/_scenarios/endtoend.py
utils/_context/_scenarios/parametric.py
utils/_context/_scenarios/performance.py
utils/_context/containers.py
utils/_decorators.py
utils/_features.py
utils/_remote_config.py
utils/_weblog.py
utils/interfaces/_backend.py
utils/interfaces/_library/_utils.py
utils/interfaces/_library/core.py
utils/interfaces/_library/miscs.py
utils/interfaces/schemas/serve_doc.py
utils/parametric/_library_client.py
utils/parametric/spec/tracecontext.py
utils/scripts/get-nightly-logs.py
utils/telemetry_utils.py
utils/tools.py

* Activate INP001
* Activate N801
* Activate N806
* Activate RET504
* Activate RUF013
* Activate S507
* Activate SIM108
* Activate SIM401
* Activate SLF001

Activate ruff rules 

---

docs/weblog/README.md
manifests/cpp.yml
manifests/dotnet.yml
manifests/golang.yml
manifests/java.yml
manifests/nodejs.yml
manifests/php.yml
manifests/python.yml
manifests/ruby.yml
tests/appsec/iast/source/test_sql_row.py
utils/_features.py
utils/build/docker/nodejs/express/iast/sources.js
utils/build/docker/nodejs/express4-typescript/iast.ts

Add tests to check that database sources for SQLi vulnerability is supported.
- New test created
- yaml files updated

Add tests for database sources

---

tests/test_telemetry.py

Update runbook link (currently broken)

---

docs/weblog/README.md
manifests/nodejs.yml
tests/appsec/rasp/test_cmdi.py
utils/build/docker/nodejs/express/rasp.js
utils/build/docker/nodejs/express4-typescript/rasp.ts
utils/build/docker/nodejs/nextjs/src/app/rasp/cmdi/route.js

Add test for command injection exploit in Node.js
- Add Node.js endpoints
- Support Test_Shi_Telemetry_Variant_Tag test
- Add documentation

Exploit command injection

---

conftest.py
manifests/parser/core.py
pyproject.toml
utils/_context/_scenarios/docker_ssi.py
utils/_context/_scenarios/endtoend.py
utils/_context/_scenarios/open_telemetry.py
utils/_context/_scenarios/parametric.py
utils/_context/containers.py
utils/_remote_config.py
utils/otel_validators/validator_trace.py
utils/parametric/_library_client.py
utils/parametric/spec/trace.py
utils/proxy/core.py

Activate ruff rules  TRY002, TRY201, UP007

---

tests/appsec/test_rate_limiter.py

Remove php bug tag on a test

---

utils/virtual_machine/virtual_machine_provider.py

Fix onboarding git checkout system-tests repository conflicts

Onboarding: fix git checkout

---

utils/_context/_scenarios/auto_injection.py
utils/_context/_scenarios/core.py
utils/_context/_scenarios/docker_ssi.py
utils/_context/_scenarios/endtoend.py
utils/_context/_scenarios/k8s_lib_injection.py
utils/_context/_scenarios/test_the_test.py
utils/_context/core.py

Set CgroupVersion in FPD report

---

.github/workflows/update-agent-protobuf.yml

Fix Update agent protobuf deserializer

---

.github/workflows/update-telemetry-keys.yml

Automate update of telemetry keys

---

manifests/python.yml

Enable easy win for OTEL baggage test
Enables easy win

[python] Enable OTEL baggage test

---

docs/scenarios/parametric.md

Used updated image here: https://github.com/DataDog/system-tests/issues/3772

update parametric.md diagram image from grpc to http

---

manifests/python.yml

[python] easy wins ATO

---

manifests/python.yml

[python] easy wins header injection stack trace

---

tests/test_telemetry.py

Use a real ISO-8601 date parser

---

docs/scenarios/docker_ssi.md

I found some typos/language use problems and want the documentation to be polished.
A bunch of small prose updates.

Edit docker_ssi.md for language/clarity

---

manifests/java.yml
tests/appsec/iast/sink/test_sql_injection.py

We want to increase our percentage of easy wins in Java.
We have enable some easy wins for the following tests:
- `tests/appsec/api_security/test_api_security_rc.py::Test_API_Security_RC_ASM_DD_processors`
- `tests/appsec/api_security/test_api_security_rc.py::Test_API_Security_RC_ASM_DD_scanners`
- `tests/appsec/api_security/test_schemas.py::Test_Schema_Request_Json_Body`
- `tests/appsec/iast/sink/test_sql_injection.py::TestSqlInjection_StackTrace`
- `tests/appsec/rasp/test_lfi.py::Test_Lfi_StackTrace`
- `tests/appsec/rasp/test_lfi.py::Test_Lfi_Telemetry`
- `tests/appsec/rasp/test_shi.py::Test_Shi_StackTrace`
- `tests/appsec/rasp/test_shi.py::Test_Shi_Telemetry`
- `tests/appsec/rasp/test_shi.py::Test_Shi_Telemetry_Variant_Tag`
- `tests/appsec/rasp/test_sqli.py::Test_Sqli_StackTrace`
- …

[java] Enable new batch of easy wins

---

.github/workflows/run-end-to-end.yml

Disable jobs which require AWS keys

---

.gitlab/k8s_gitlab-ci.yml
utils/k8s_lib_injection/k8s_matrix_builder.py

Add the FPD parameter to the K8s pipeline

K8s fix pipeline url

---

utils/build/virtual_machine/provisions/auto-inject/auto-inject-vm_logs.yml

When there is a failure on the onboarding tests, we need to extract more info about the docker apps (if we are testing the container scenarios)

Onboarding: Docker apps extract more info

---

manifests/java.yml
tests/appsec/iast/test_security_controls.py
tests/appsec/iast/utils.py
utils/_context/_scenarios/integrations.py
utils/_context/containers.py

Update Iast security controls system tests for Milestone 1 ([RFC](https://docs.google.com/document/d/1j1hp87-2wJnXUGADZxzLnvKJmaF_Gd6ZR1hPS3LVguQ/edit?pli=1&tab=t.0))
Move iast global context flag from default scenario to integrations scenario (only some kafka tests need it)
Add suppressed.vulnerability metric check
🛟 …

Check metrics in security control tests

---

utils/build/virtual_machine/provisions/auto-inject/auto-inject-vm_logs.yml

We need more info about docker on the onboarding tests.
Added a command to extract journalct info

Onboarding: Get journalct logs

---

tests/parametric/test_dynamic_configuration.py

[python] Skip flaky test for APMAPI-1051

---

manifests/python.yml

enable api security tests for the new weblog django-py3.13

[python] simplify manifest and easy wins for api security

---

utils/build/virtual_machine/provisions/auto-inject-ld-preload/ld-preload.yml

There is a bug on the provision of the onboarding test vm.
Fix the provision

Onboarding: Fix amazon linux devtools provision bug

---

utils/build/virtual_machine/weblogs/nodejs/test-app-nodejs-esm/Dockerfile.node
utils/build/virtual_machine/weblogs/nodejs/test-app-nodejs-esm/Dockerfile.node20

Fix SSI tests with Node.js + ESM

---

tests/appsec/iast/sink/test_insecure_cookie.py
tests/appsec/iast/sink/test_no_httponly_cookie.py
tests/appsec/iast/sink/test_no_samesite_cookie.py

Although they are marked as easy wins, it has been confirmed that the tests are flaky
Mark as flaky:
- tests/appsec/iast/sink/test_insecure_cookie.py::TestInsecureCookie::test_telemetry_metric_executed_sink
- tests/appsec/iast/sink/test_no_httponly_cookie.py::TestNoHttponlyCookie::test_telemetry_metric_executed_sink
- tests/appsec/iast/sink/test_no_samesite_cookie.py::TestNoSamesiteCookie::test_telemetry_metric_executed_sink …

[JAVA]Mark as flaky IAST cookie test_telemetry_metric_executed_sink for vertx4

---

manifests/php.yml

PHP quick wins

---

manifests/java.yml

[Java] Enable session blocking tests in Java

---

manifests/php.yml

[php] Disable Login Events v2

---

tests/parametric/test_span_sampling.py

[cpp] Skip test failing for APMAPI-1052

---

utils/_context/_scenarios/external_processing.py

[golang] Fix weblog name

---

.github/actions/pull_images/action.yml
utils/_context/containers.py
utils/scripts/get-image-list.py

Allow to easily reuse this action
* use `argparse`
* allow to not set weblog and library (in that case, don't add any weblog related image)

Better get-image-list script

---

tests/auto_inject/test_auto_inject_install.py
tests/docker_ssi/test_docker_ssi.py
utils/virtual_machine/virtual_machine_provider.py

Onboarding: pipeline fixes

---

tests/integrations/test_db_integrations_sql.py
tests/integrations/test_dbm.py
tests/integrations/test_dsm.py

[python] Skip failing tests for APMAPI-1058

---

.github/workflows/ci.yml

Enable again the trigger of the jobs when something is merged into main branch
Changes on the github actions CI yml

Trigger Jobs on merge

---

.github/workflows/run-end-to-end.yml
utils/_context/_scenarios/endtoend.py

reactivate scenarios skipped in #3805

Reactivate scenarios

---

manifests/cpp.yml
manifests/dotnet.yml
manifests/golang.yml
manifests/java.yml
manifests/nodejs.yml
manifests/php.yml
manifests/python.yml
manifests/ruby.yml
tests/appsec/iast/sink/test_email_html_injection.py
utils/_features.py
utils/build/docker/dotnet/weblog/Controllers/IastController.cs

This PR contains the system tests for the IAST email html injection vulnerability.
Email HTML injection is a vulnerability where user input is included in the content of an email without proper validation and sanitization. This vulnerability can have severe consequences as it opens the door for various attacks, including phishing, social engineering exploits, and the exploitation of email client vulnerabilities.
This vulnerability is defined in [this RFC](https://docs.google.com/document/d/1-_cAoSo3zUxlBNAp1f4M_4NRq6zdVzwtVyW_GaU-xGs/edit?tab=t.0#heading=h.tonjsgarlieo)
* Test logic is modified? -> Get a review from RFC …

Email HTML injection system tests

---

tests/auto_inject/test_auto_inject_install.py
tests/k8s_lib_injection/test_k8s_lib_injection.py
utils/k8s_lib_injection/k8s_weblog.py

There are some bugs in the SSI pipelines. Add bug markers

SSI: Add bug markers

---

tests/debugger/test_debugger_exception_replay.py

[Debugger] Mark java bug

---

manifests/java.yml

Enable tests that pass due to https://github.com/DataDog/dd-trace-java/pull/8176

[Java] Updating Manifest for Remote Config Tests

---

utils/interfaces/schemas/library/symdb/v1/input-request.json

[Debugger] Fix symdb schema validation

---

.github/workflows/run-end-to-end.yml

[python] Skip CROSSED_TRACING_LIBRARIES for python 3.13 APMAPI-1096

---

utils/scripts/load-binary.sh

Fix load-binary script if TARGET_BRANCH is not set

---

manifests/nodejs.yml

Node.js IAST stack trace easy wins

[Nodejs] Fix nodejs stack trace easy wins for iast

---

utils/build/virtual_machine/weblogs/python/provision_test-app-python.yml

Onboarding: Disable ubuntu 21 arm64 for python

---

tests/appsec/test_asm_standalone.py

https://github.com/DataDog/system-tests/pull/3882 was partially reverted by https://github.com/DataDog/system-tests/pull/3846 merged almost at the same time.
This PR fixes that.

[python] ASM standalone from flaky to bug

---

utils/onboarding/backend_interface.py

We got feedback from #apm-trace-retrieval that this is the preferred URL and they can help us with rate limits if we are still encountering them.
This commit updates the trace URL to a better supported version. 

bug(ssi): update trace url

---

manifests/python.yml

Easy wins for stack trace report on iast code injection

[python] enable easy wins

---

conftest.py
manifests/parser/core.py
pyproject.toml
utils/_context/_scenarios/docker_ssi.py
utils/cgroup_info.py
utils/otel_validators/validator_log.py
utils/otel_validators/validator_metric.py
utils/otel_validators/validator_trace.py
utils/parametric/spec/trace.py
utils/parametric/spec/tracecontext.py
utils/properties_serialization.py
utils/proxy/core.py
utils/scripts/compute-workflow-parameters.py
utils/scripts/compute_impacted_scenario.py
utils/scripts/decode-rc.py
utils/scripts/extract_appsec_waf_rules.py
utils/scripts/get-image-list.py
utils/scripts/get-nightly-logs.py
utils/scripts/get-scenarios-from-group.py
utils/scripts/get-workflow-summary.py
utils/scripts/grep-nightly-logs.py
utils/scripts/junit_report.py
utils/scripts/markdown_logs.py
utils/scripts/merge_gitlab_aws_pipelines.py
utils/scripts/push-metrics.py
utils/tools.py

Activate ANN201 ruff rule

---

pyproject.toml
utils/_features.py
utils/interfaces/_backend.py
utils/interfaces/_library/appsec.py
utils/properties_serialization.py
utils/proxy/core.py
utils/telemetry_utils.py

Activate ANN205

---

docs/edit/runbook.md

Update runbook to reflect updated team ownership

---

tests/telemetry_intake/static/python_config_rules.json

Fixes ragas instrumentation telemetry test using instructions from here:
https://github.com/DataDog/system-tests/blob/main/docs/edit/runbook.md#test_config_telemetry_completeness

[MLOB] fix ragas telemetry test

---

tests/test_the_test/test_scrubber.py
utils/proxy/scrubber.py

Instrument pathlib.Path.open in scrubber

---

tests/auto_inject/test_auto_inject_install.py

Onboarding: nodejs profiling bug decorators

---

requirements.txt

Remove useless click requirement

---

tests/auto_inject/test_auto_inject_install.py

The tests are failing and blocking the nodejs tracer prs. I mark as bug

Onboarding: nodejs profiling bug marker

---

utils/_context/containers.py

Convert PosixPath to str first 

Convert PosixPath to str first

---

tests/appsec/iast/sink/test_code_injection.py

This reverts commit 81c51e5031d268115f18a8e0794f9157dc944c14.

Revert "Enable Nodejs telemetry metric for code injection"

---

pyproject.toml
requirements.txt
tests/parametric/conftest.py
utils/parametric/_library_client.py

Extend mypy scope

---

manifests/dotnet.yml
tests/appsec/test_automated_user_and_session_tracking.py

Activate user events for dotnet
Activate all v3 events except for 2 tests:
- login sdk overwrite needs to be changed, it's not correct
- session blocking is a non defined feature for now

[ASM][ATO][dotnet] activate user events v3

---

.github/actions/get_target_branch/action.yaml

Fix branch target resolution in titles containing "special" characters

[nodejs] Fix get_target_branch - "quotes, parens and # (#3952)""

---

tests/test_the_test/test_group_rules.py
utils/_context/_scenarios/parametric.py

Ensure tracer release coherence

---

pyproject.toml
requirements.txt
tests/parametric/conftest.py
tests/perfs/test_performances.py
tests/remote_config/test_remote_configuration.py
utils/_context/library_version.py
utils/_decorators.py
utils/build/docker/python/parametric/apm_test_client/__main__.py
utils/interfaces/_library/core.py
utils/interfaces/_logs.py
utils/interfaces/_test_agent.py
utils/interfaces/schemas/serve_doc.py
utils/otel_validators/validator_log.py
utils/proxy/_deserializer.py
utils/proxy/core.py
utils/proxy/scrubber.py
utils/scripts/extract_appsec_waf_rules.py
utils/scripts/get-change-log.py
utils/scripts/get-workflow-summary.py
utils/scripts/markdown_logs.py
utils/tools.py

Extend mypy to full project

---

manifests/nodejs.yml
tests/appsec/iast/sink/test_code_injection.py

Add support to Code injection Instrumented metric in Node.js

[Nodejs] Code injection telemetry metric

---

pyproject.toml
tests/appsec/api_security/test_schemas.py
tests/appsec/iast/sink/test_hardcoded_secrets.py
tests/appsec/iast/sink/test_weak_hash.py
tests/appsec/test_asm_standalone.py
tests/appsec/test_automated_login_events.py
tests/appsec/test_reports.py
tests/auto_inject/test_auto_inject_chaos.py
tests/auto_inject/test_auto_inject_guardrail.py
tests/auto_inject/test_auto_inject_install.py
tests/debugger/test_debugger_exception_replay.py
tests/debugger/test_debugger_expression_language.py
tests/debugger/utils.py
tests/integrations/crossed_integrations/test_sns_to_sqs.py
tests/integrations/crossed_integrations/test_sqs.py
tests/integrations/test_inferred_proxy.py
tests/k8s_lib_injection/test_k8s_init_image_validator.py
tests/parametric/test_headers_baggage.py
tests/parametric/test_otel_env_vars.py
tests/parametric/test_sampling_span_tags.py
tests/parametric/test_tracer_flare.py
tests/test_graphql.py
tests/test_sampling_rates.py
tests/test_telemetry.py
tests/test_the_test/test_decorators.py

Enable ruff rules on tests/ folder

---

tests/test_the_test/test_scrubber.py
utils/proxy/scrubber.py

Do not use special chars in "redacted" string used in scrubber

---

manifests/python.yml

[python] IAST Header source in werkzeug 3.1

---

manifests/python.yml

To unlock 2.x branch for system tests, update the version of the new enabled tests.

[python] update versions for major release

---

.vscode/launch.json
conftest.py
pyproject.toml
requirements.txt
utils/_context/_scenarios/integrations.py
utils/_context/_scenarios/parametric.py
utils/_remote_config.py
utils/_weblog.py
utils/scripts/compute-workflow-parameters.py
utils/scripts/get-image-list.py
utils/scripts/get-nightly-logs.py
utils/scripts/grep-nightly-logs.py
utils/tools.py

Extend mypy coverage

---

utils/_context/_scenarios/docker_ssi.py
utils/virtual_machine/vm_logger.py

Docker SSI: fix scenario

---

pyproject.toml
tests/apm_tracing_e2e/test_smoke.py
tests/appsec/test_asm_standalone.py
tests/appsec/waf/test_telemetry.py
tests/auto_inject/test_auto_inject_install.py
tests/fuzzer/core.py
tests/integrations/test_dsm.py
tests/otel/test_context_propagation.py
tests/parametric/conftest.py
tests/parametric/test_128_bit_traceids.py
tests/parametric/test_config_consistency.py
tests/parametric/test_headers_b3multi.py
tests/parametric/test_headers_datadog.py
tests/parametric/test_headers_precedence.py
tests/parametric/test_library_tracestats.py
tests/parametric/test_parametric_endpoints.py
tests/parametric/test_span_sampling.py
tests/parametric/test_tracer_flare.py
tests/test_distributed.py
tests/test_telemetry.py
tests/test_the_test/test_json_report.py

Activate ruff rules on tests/ folder

---

tests/appsec/test_automated_login_events.py

Test was passing due to another PR adding this feature to the weblog.
Remove a @missing_feature

[nodejs] remove auto login event skip

---

.github/workflows/run-end-to-end.yml

[java] Skip payara/CROSSED_TRACING_LIBRARIES/prod

---

tests/appsec/iast/sink/test_sql_injection.py
tests/appsec/iast/utils.py
utils/build/docker/python/django-poc.Dockerfile
utils/build/docker/python/django/app/urls.py
utils/build/docker/python/flask/app.py

[python] fix 500 errors in sql queries

---

utils/scripts/load-binary.sh

3.0 is about to be release, main branch is now again alive on ddtrace.py

[python] use main again for dev branch

---

.github/CODEOWNERS

Matches https://github.com/DataDog/dd-go/pull/167553
Updates CODEOWNERS from apm-ecosystems -> apm-sdk

[skipci] Update CODEOWNERS for static files

---

manifests/java.yml

[java] Enable Test_Blocking_strip_response_headers in some variants

---

manifests/java.yml

Endpoints were missing at some point.
[APPSEC-54879](https://datadoghq.atlassian.net/browse/APPSEC-54879) [APPSEC-54986](https://datadoghq.atlassian.net/browse/APPSEC-54986) [APPSEC-55791](https://datadoghq.atlassian.net/browse/APPSEC-55791) [APPSEC-55789](https://datadoghq.atlassian.net/browse/APPSEC-55789)
🛟 …

[java] Remove some outdated manifest entries

---

manifests/java.yml

[java] Fix xpass for Test_SecurityEvents_Appsec_Metastruct_Disabled

---

.github/workflows/ci.yml
utils/scripts/get-workflow-summary.py

Green CI policy, step 1 for #4037
GCP on github action requires a "last final job" that checks all others jobs. And if any of them fails, this job fails. Last step : make this "last job" required.

Green CI policy - step 1

---

tests/test_data_integrity.py

Skip flaky test on agent (APMSP-1791)

---

pyproject.toml
tests/apm_tracing_e2e/test_single_span.py
tests/appsec/iast/utils.py
tests/integrations/test_dbm.py
tests/k8s_lib_injection/test_k8s_init_image_validator.py
tests/otel/test_context_propagation.py
tests/parametric/test_crashtracking.py
tests/parametric/test_headers_b3.py
tests/parametric/test_headers_b3multi.py
tests/parametric/test_headers_precedence.py
tests/parametric/test_span_links.py
tests/test_library_conf.py

Activate ruff rule PT018 on tests folder

---

utils/build/virtual_machine/weblogs/dotnet/provision_test-app-dotnet.yml
utils/build/virtual_machine/weblogs/ruby/provision_test-app-ruby.yml

Onboarding: skip ubuntu24.10 for Ruby and dotNet

---

manifests/nodejs.yml

Update Nodejs yaml for iast extended location vulnerability

[Nodejs] Update nodejs yaml for extended iast location fields

---

utils/_context/_scenarios/endtoend.py

[java] skip schema check for APMAPI-1161

---

utils/scripts/load-binary.sh

Always use prod agent

---

tests/auto_inject/test_auto_inject_chaos.py
tests/auto_inject/test_auto_inject_install.py
tests/auto_inject/test_blocklist_auto_inject.py

There are bugs related with the python app:
- Ubuntu 24.10 errors: https://datadoghq.atlassian.net/browse/INPLAT-478
- Simple profiling: https://datadoghq.atlassian.net/browse/INPLAT-479

Onboarding: Python bugs

---

utils/_context/_scenarios/endtoend.py

[nodejs] Skip test for DEBUG-3487

---

utils/build/docker/python/flask/app.py

[python] use `ddtrace_iast_flask_patch` in Flask

---

utils/build/docker/java/spring-boot/pom.xml
utils/build/docker/java_otel/spring-boot/pom.xml

[java] Update mssql-jdbc version

---

utils/_context/_scenarios/endtoend.py

[nodejs] Revert #4066 for DEBUG-3487 (need more CI runs)

---

utils/virtual_machine/virtual_machine_provider.py
utils/virtual_machine/vm_logger.py

Generate a log file with the commands that we are launching to execute the machine provision

Onboarding: Debug - generate provision file with all the commands

---

utils/_context/_scenarios/endtoend.py

[java] Disable schema tests for all java version (APMAPI-1161)

---

tests/auto_inject/test_demo.py
tests/test_the_test/test_group_rules.py
utils/_context/_scenarios/__init__.py
utils/_context/_scenarios/auto_injection.py
utils/build/virtual_machine/provisions/demo/provision.yml
utils/build/virtual_machine/weblogs/nodejs/demo-app/demo_app_run.sh
utils/build/virtual_machine/weblogs/nodejs/provision_demo-app.yml
utils/scripts/ci_orchestrators/aws_ssi.json
utils/virtual_machine/virtual_machine_provisioner.py

Onboarding: Demo

---

utils/scripts/ssi_wizards/aws_onboarding_wizard.sh
utils/scripts/ssi_wizards/aws_onboarding_wizard_utils.py

Update the onboarding test local execution wizard script:
- Add ./build.sh in the wizard. At least ask to the user if he wants to run (to download deps) ✅
- In the wizard add the links to the documentation,for example how to get the subnet id or key pair.✅
- Add a step to check the aws client installation: .✅
- Create the keypair for the user using the command line:.✅
- Use the new url to access to the system-tests organization to generate their own api keys:✅
- Not run the scenario, ask to the user if he wants to run. If not  print the command line ✅
* Test logic is modified? -> Get a review from RFC owner. We're …

onboarding wizard tweaks

---

utils/build/virtual_machine/weblogs/java/provision_test-app-java.yml
utils/build/virtual_machine/weblogs/nodejs/provision_test-app-nodejs.yml
utils/build/virtual_machine/weblogs/python/provision_test-app-python.yml
utils/virtual_machine/virtual_machines.json

Onboarding: Add fedora vm

---

tests/auto_inject/test_auto_inject_install.py

The app "test-app-dotnet-multialpine" is not instrumented on Ubuntu 24 arm64. Add a bug marker

Onboarding: Dotnet alpine bug

---

utils/scripts/ci_orchestrators/aws_ssi.json
utils/virtual_machine/virtual_machines.json

Onboarding; Rocky Linux

---

manifests/nodejs.yml
manifests/python.yml

update manifests to enable inferred proxy tests for nodejs and python

---

utils/interfaces/_schemas_validators.py
utils/proxy/_deserializer.py

proxy : handle UnicodeDecodeError

---

utils/build/docker/python/django-poc.Dockerfile
utils/build/docker/python/django-py3.13.Dockerfile
utils/build/docker/python/fastapi.Dockerfile
utils/build/docker/python/flask-poc.Dockerfile
utils/build/docker/python/python3.12.Dockerfile
utils/build/docker/python/uds-flask.Dockerfile
utils/build/docker/python/uwsgi-poc.Dockerfile

This reverts commit 40fab89866032441ceed6400114c85f8e9bc83f0.

Revert "[python] remove old deduplication environment variable (#3881)"

---

tests/auto_inject/test_auto_inject_chaos.py
utils/build/virtual_machine/weblogs/dotnet/provision_test-app-dotnet.yml
utils/build/virtual_machine/weblogs/php/provision_test-app-php.yml
utils/build/virtual_machine/weblogs/python/provision_test-app-python.yml
utils/scripts/ci_orchestrators/aws_ssi.json
utils/virtual_machine/virtual_machines.json

Activate Oracle Linux machines

Onboarding: oracle linux

---

tests/appsec/test_asm_standalone.py

New tracer versions implements V2 breaking the tests

[JAVA] Disable ASM standalone billing tests

---

manifests/python.yml

[python] enable Datadog-Client-Computed-Stats test

---

manifests/python.yml
tests/test_standard_tags.py

APMLP-364
Fix route test for django on python 3.13

[python] fixing test for django 3.13

---

tests/appsec/test_automated_user_and_session_tracking.py

[python] enabling one more test

---

manifests/nodejs.yml

[nodejs] enable Test_Cmdi_StackTrace

---

utils/scripts/ci_orchestrators/aws_ssi.json
utils/virtual_machine/virtual_machines.json

Add Debian 11 vm to the onboarding tests

Onboarding: debian 11

---

tests/debugger/test_debugger_pii.py
tests/debugger/test_debugger_probe_snapshot.py

[nodejs] Skip tests for DEBUG-3526

---

manifests/java.yml

[JAVA] Enable Stacktrace for IAST vulnerabilities tests

---

.github/workflows/run-lib-injection.yml

lib-injection: do not start build job if not needed

---

manifests/java.yml

APPSEC-54879 is dedicated to easy wins
java.yml was changed for test_cmdi

[java] easy wins on test_cmdi

---

.gitlab-ci.yml
utils/scripts/ssi_wizards/aws_onboarding_wizard.sh

Onboarding: Wizard fixes

---

manifests/java.yml
tests/appsec/iast/utils.py

Enable Test_TrustBoundaryViolation_StackTrace
Improve stack trace check as its possible to have more than one vulnerability for the same stack and location

Enable test, bug APPSEC-56803 was fixed

---

.github/workflows/ci.yml
utils/scripts/compute_impacted_scenario.py
utils/scripts/get-workflow-summary.py

Adds debugging instructions on get-workflow-summary

---

tests/test_graphql.py

This PR expands testing documentation, to aid implementers on how to add the supporting endpoints for the test in `tests/test_graphql.py`.

Better docs for GraphQL test devs

---

utils/build/virtual_machine/weblogs/nodejs/demo-app/demo_app_run.sh

onboarding: fix demo aws

---

utils/build/virtual_machine/weblogs/nodejs/demo-app/demo_app_run.sh
utils/scripts/ci_orchestrators/aws_ssi.json

Onboarding:aws demo

---

pyproject.toml

Clean ruff rules in pyproject

---

tests/parametric/test_crashtracking.py

Skip crash-report for .NET (APMAPI-1177)

---

pyproject.toml
tests/appsec/iast/sink/test_hsts_missing_header.py
tests/appsec/iast/sink/test_trust_boundary_violation.py
tests/appsec/iast/sink/test_xcontent_sniffing.py
tests/appsec/iast/test_security_controls.py
tests/appsec/iast/utils.py
tests/fuzzer/main.py
tests/fuzzer/request_mutator.py
tests/parametric/test_otel_api_interoperability.py
tests/parametric/test_otel_env_vars.py
tests/test_telemetry.py
tests/test_the_test/test_force_option.py
tests/test_the_test/test_force_skip.py
tests/test_the_test/test_json_report.py
tests/test_the_test/test_scrubber.py
tests/test_the_test/test_strict.py
utils/parametric/_library_client.py

Activate ruff rule FBT003

---

utils/build/build.sh

Build script can save/load images in/from files in binaries folder

---

tests/parametric/test_crashtracking.py

Unskip test for APMAPI-1177, improve test logic

---

tests/test_sampling_rates.py

[nodejs] reskip test for APMAPI-1120

---

utils/docker_ssi/docker_ssi_images.json
utils/docker_ssi/docker_ssi_runtimes.json
utils/scripts/ci_orchestrators/docker_ssi.json

Docker SSI: json definitions

---

tests/telemetry_intake/static/php_config_rules.json

[php] add telemetry key

---

utils/build/docker/golang/install_ddtrace.sh

[golang] Fix build using production tracer

---

manifests/python.yml
tests/appsec/iast/sink/test_insecure_cookie.py
tests/appsec/iast/sink/test_no_httponly_cookie.py
tests/appsec/iast/sink/test_no_samesite_cookie.py

enable more iast tests already passing.

[python] enable easy wins tests

---

manifests/golang.yml

Golang tracer missed PR which will be fixed in next patch release
Updates golang manifest to test APIGW feature in next patch release

Update Golang Version for API Gateway Tests

---

tests/test_config_consistency.py

[golang] APMAPI-1196

---

tests/parametric/test_telemetry.py

[python] Skip test failing for APMAPI-1197

---

tests/appsec/api_security/test_schemas.py

Check that API Security schemas are added strictly to root spans

---

utils/scripts/ci_orchestrators/aws_ssi.json

The gitlab ci has issues computing the matrix for container profiling for languages: dotnet and python

Onboarding: Container profiling fixes

---

tests/parametric/test_telemetry.py

[python] Revert APMAPI-1197

---

manifests/dotnet.yml

Activate the fingerprint session test

[ASM][ATO][dotnet] Activate fingerprint session test on dev

---

tests/debugger/test_debugger_inproduct_enablement.py

add missing_feature decoration on classes

[java] Fix java tests for in-product enablement

---

manifests/golang.yml
tests/test_telemetry.py

Enable tests following https://docs.google.com/document/d/1C3xoTZHQZNQ-Jr1w5mMThIkpHNW_4qKRf-J5CNi7G-k/edit?pli=1&tab=t.0#heading=h.88xvn2cvs9dt

[golang] enable more telemetry tests

---

tests/test_data_integrity.py

Skip test failing for APMSP-1811

---

pyproject.toml
tests/appsec/iast/source/test_kafka_key.py
tests/appsec/iast/source/test_kafka_value.py
tests/appsec/iast/utils.py
tests/appsec/test_asm_standalone.py
tests/appsec/waf/test_addresses.py
tests/debugger/test_debugger_exception_replay.py
tests/debugger/test_debugger_pii.py
tests/fuzzer/core.py
tests/fuzzer/request_mutator.py
tests/fuzzer/tools/metrics.py
tests/integrations/test_db_integrations_sql.py
tests/integrations/test_inferred_proxy.py
tests/integrations/test_open_telemetry.py
tests/parametric/conftest.py
tests/parametric/test_library_tracestats.py
tests/parametric/test_span_sampling.py
tests/perfs/test_performances.py
tests/remote_config/test_remote_configuration.py
tests/test_telemetry.py
tests/test_the_test/test_docker_scenario.py
tests/test_the_test/utils.py

Enable some ruff rules on tests/ folder

---

tests/appsec/iast/sink/test_command_injection.py
tests/appsec/iast/sink/test_email_html_injection.py
tests/appsec/iast/sink/test_header_injection.py
tests/appsec/iast/sink/test_insecure_auth_protocol.py
tests/appsec/iast/sink/test_insecure_cookie.py
tests/appsec/iast/sink/test_ldap_injection.py
tests/appsec/iast/sink/test_no_httponly_cookie.py
tests/appsec/iast/sink/test_no_samesite_cookie.py
tests/appsec/iast/sink/test_reflection_injection.py
tests/appsec/iast/sink/test_sql_injection.py
tests/appsec/iast/sink/test_ssrf.py
tests/appsec/iast/sink/test_trust_boundary_violation.py
tests/appsec/iast/sink/test_unvalidated_redirect.py
tests/appsec/iast/sink/test_weak_cipher.py
tests/appsec/iast/sink/test_weak_hash.py
tests/appsec/iast/sink/test_xpath_injection.py

[dotnet] skip failing tests for APPSEC-56908

---

tests/test_library_logs.py

* Add `Test_NoExceptions.test_java_logs`: this test has a list of disallowed regular expressions (`disallowed_patterns`) that cannot appear in logs. There is a second list of allowed regular expressions (`allowed_patterns`) for exceptional cases. Any log printed during the execution of the `DEFAULT` scenario that matches the disallowed list, and not the allowed list, will make this test fail.
* Add `Test_NoExceptions.test_java_telemetry_logs`: similar to the above but for telemetry logs. Any telemetry log is considered disallowed, unless there's an exception marked at `allowed_patterns`.
* Every exception that is not meant to be permanent should have an associated JIRA ticket.
2. Work on you PR until the CI passes (if something not related to your task is …

[java] Check Java logs

---

manifests/nodejs.yml

More test coverage :)
Run Node.js debugger tests on the `uds-express4` app as well.

[nodejs] enable UDS tests for the debugger scenarios

---

.gitlab-ci.yml
tests/appsec/api_security/test_api_security_rc.py

Fix compute scenario on gitlab

Onboarding: Fix compute scenario gitlab

---

utils/_context/_scenarios/__init__.py

Onboarding: tune scenario groups

---

utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/WebSecurityConfig.java
utils/build/docker/java/spring-boot/src/main/webapp/WEB-INF/glassfish-web.xml
utils/build/docker/java/spring-boot/src/main/webapp/WEB-INF/payara-web.xml

Some tests require this. Trying to get the number of spurious error logs down.

[java] Allow TRACE requests in Spring Boot

---

manifests/nodejs.yml

enable graphql error reporting test nodejs

---

utils/_context/_scenarios/__init__.py
utils/_context/_scenarios/core.py
utils/scripts/ci_orchestrators/k8s_ssi.json

Tweak on aws pipeline: create a new group for profiling, remove multicontainer from the simple pipeline.
Remove cluster agent version of the k8s tests in order to avoid the docker hub limmits

SSI Pipeline: tweaks

---

.gitlab-ci.yml
utils/_context/_scenarios/__init__.py
utils/_context/_scenarios/core.py
utils/_context/_scenarios/k8s_lib_injection.py
utils/scripts/ci_orchestrators/external_gitlab_pipeline.py
utils/scripts/ci_orchestrators/gitlab_exporter.py
utils/scripts/ci_orchestrators/k8s_ssi.json

System-tests gitlab onepipeline

---

manifests/cpp.yml
manifests/dotnet.yml
manifests/golang.yml
manifests/java.yml
manifests/nodejs.yml
manifests/php.yml
manifests/python.yml
manifests/ruby.yml
tests/appsec/waf/test_truncation.py
utils/_features.py

Add new test for waf truncation metrics

Add waf truncation metrics test

---

utils/scripts/load-binary.sh

Support for choosing which branch to run the CI on using the go weblog.
`go get gopkg.in/[...]` does not support moving refs except main and master. So we have to get the commit from the github API. This is even better in all cases because the go proxyies involved here can be late to process moving refs so using directly commits are safer.
[Example PR CI where this code is working](https://github.com/DataDog/system-tests/actions/runs/13636990996/job/38118279490?pr=4233#step:11:90)
* Framework is modified, …

support for TARGET_BRANCH load_binary.sh golang

---

manifests/java.yml

[java] Fix TestCommandInjection_StackTrace XPASS

---

manifests/java.yml

Easy win detected by the feature parity dashboard
[APPSEC-54879]: https://datadoghq.atlassian.net/browse/APPSEC-54879?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YT …

[java] Enable Test_Automated_Session_Blocking in spring-boot-payara

---

manifests/java.yml

[java] Fix XPASS for API Security in vertx4

---

utils/scripts/compute_impacted_scenario.py

Run only e2e tests when proxy is modified

---

manifests/python.yml
tests/appsec/rasp/test_lfi.py
utils/build/docker/python/django/app/urls.py
utils/build/docker/python/fastapi/main.py
utils/build/docker/python/flask/app.py

- add new weblog endpoint for fastapi, flask and django to pass multiple lfi exploit tests
- small refactor in the python weblogs
- add check for 200 status response on test

add python endpoints for rasp multiple test

---

manifests/java.yml
tests/test_standard_tags.py
utils/build/docker/java/akka-http/src/main/scala/com/datadoghq/akka_http/Main.scala
utils/build/docker/java/akka-http/src/main/scala/com/datadoghq/akka_http/MainRoutes.scala
utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/MyResource.java
utils/build/docker/java/play/app/controllers/MainController.scala
utils/build/docker/java/play/conf/routes
utils/build/docker/java/ratpack/src/main/java/com/datadoghq/ratpack/Main.java
utils/build/docker/java/resteasy-netty3/src/main/java/com/datadoghq/resteasy/MyResource.java
utils/build/docker/java/vertx3/src/main/java/com/datadoghq/vertx3/Main.java
utils/build/docker/java/vertx4/src/main/java/com/datadoghq/vertx4/Main.java

Fix XPASS for http.route in Java

---

tests/appsec/waf/test_addresses.py

[dotnet] skip test for APPSEC-56987

---

pyproject.toml
tests/appsec/api_security/test_api_security_rc.py
tests/appsec/api_security/test_apisec_sampling.py
tests/appsec/api_security/test_schemas.py
tests/appsec/iast/utils.py
tests/appsec/test_asm_standalone.py
tests/appsec/test_automated_login_events.py
tests/appsec/test_ip_blocking_full_denylist.py
tests/appsec/test_rate_limiter.py
tests/appsec/test_traces.py
tests/appsec/utils.py
tests/appsec/waf/test_addresses.py
tests/auto_inject/utils.py
tests/parametric/test_crashtracking.py
tests/parametric/test_dynamic_configuration.py
tests/parametric/test_headers_b3.py
tests/parametric/test_headers_precedence.py
tests/parametric/test_headers_tracestate_dd.py
tests/parametric/test_span_links.py
tests/parametric/test_telemetry.py
tests/remote_config/test_remote_configuration.py
tests/test_identify.py
tests/test_sampling_rates.py
tests/test_telemetry.py
tests/test_the_test/test_features.py

Activate ruff rule N806

---

utils/scripts/compute_impacted_scenario.py

Sort keys in compute_impacted_scenario script

---

docs/scenarios/docker_ssi.md
manifests/parser/core.py
pyproject.toml
tests/docker_ssi/test_docker_ssi.py
tests/otel_tracing_e2e/test_e2e.py
utils/_weblog.py
utils/buddies.py
utils/cgroup_info.py
utils/interfaces/_agent.py
utils/interfaces/_backend.py
utils/interfaces/_library/core.py
utils/interfaces/_open_telemetry.py
utils/interfaces/_test_agent.py
utils/properties_serialization.py
utils/scripts/ci_orchestrators/workflow_data.py
utils/telemetry_utils.py
utils/tools.py

Activate ANN001 on some files

---

.gitlab-ci.yml
utils/scripts/ci_orchestrators/external_gitlab_pipeline.py

SSI gitlab pipeline: delay for parallel

---

tests/docker_ssi/test_docker_ssi.py
tests/docker_ssi/test_docker_ssi_crash.py

Docker SSI: Add python bug marker

---

.vscode/launch.json
pyproject.toml
utils/_context/_scenarios/docker_ssi.py
utils/_context/_scenarios/endtoend.py
utils/_context/_scenarios/open_telemetry.py
utils/_context/containers.py
utils/_context/library_version.py
utils/interfaces/__init__.py

Activate ANN001 on library_version.py and containers.py

---

manifests/java.yml

[java] Fix manifest for Graal and Identify tests

---

docs/edit/add-new-test.md
pyproject.toml
requirements.txt
tests/appsec/test_automated_login_events.py
tests/appsec/test_blocking_addresses.py
tests/appsec/test_event_tracking.py
tests/appsec/test_identify.py
tests/appsec/test_traces.py
tests/test_data_integrity.py
tests/test_identify.py
utils/_context/_scenarios/__init__.py
utils/_context/_scenarios/endtoend.py
utils/_context/_scenarios/external_processing.py
utils/_context/_scenarios/integrations.py
utils/_context/_scenarios/open_telemetry.py
utils/_context/containers.py
utils/build/docker/proxy.Dockerfile
utils/interfaces/_core.py
utils/interfaces/_library/_utils.py
utils/interfaces/_library/appsec.py
utils/interfaces/_library/core.py
utils/interfaces/_library/miscs.py
utils/interfaces/_library/telemetry.py
utils/proxy/_deserializer.py
utils/proxy/core.py
utils/proxy/scrubber.py

Activate ANN001 on utils/library

---

tests/test_telemetry.py

Adapt test on seq_id to allow bumps

---

utils/scripts/load-binary.sh

[golang] Harden load-binary script

---

tests/appsec/test_asm_standalone.py

Slightly better logs for IAST_STANDALONE

---

conftest.py
pyproject.toml
tests/test_telemetry.py
utils/interfaces/_agent.py
utils/interfaces/_backend.py
utils/interfaces/_logs.py
utils/interfaces/_misc_validators.py
utils/interfaces/_open_telemetry.py
utils/interfaces/_schemas_validators.py
utils/interfaces/_test_agent.py
utils/scripts/ci_orchestrators/workflow_data.py
utils/scripts/compute-workflow-parameters.py
utils/scripts/decode-rc.py
utils/scripts/extract_appsec_waf_rules.py
utils/scripts/get-nightly-logs.py
utils/scripts/get-workflow-summary.py
utils/scripts/grep-nightly-logs.py
utils/scripts/push-metrics.py

Activate ANN001 on conftest.py,  utils/interfaces and scripts files

---

manifests/nodejs.yml

Enable corrupted rules telemetry test for nodejs

[Nodejs] Enable corrupted rules telemetry test for nodejs

---

pyproject.toml
tests/appsec/api_security/utils.py
tests/appsec/iast/utils.py
tests/appsec/rasp/utils.py
tests/appsec/utils.py
tests/auto_inject/utils.py
tests/debugger/utils.py
tests/fuzzer/core.py
tests/fuzzer/corpus.py
tests/fuzzer/html_parser.py
tests/fuzzer/main.py
tests/fuzzer/request_generators.py
tests/fuzzer/request_mutator.py
tests/fuzzer/tools/__init__.py
tests/fuzzer/tools/metrics.py
tests/fuzzer/tools/random_strings.py
tests/integrations/utils.py
tests/k8s_lib_injection/utils.py
tests/parametric/conftest.py
tests/perfs/process.py
tests/serverless/span_pointers/utils.py

activate ANN201 on utils files in tests folder

---

pyproject.toml
tests/appsec/iast/sink/test_weak_hash.py
tests/appsec/iast/utils.py
tests/appsec/rasp/utils.py
tests/appsec/utils.py
tests/integrations/utils.py
tests/k8s_lib_injection/utils.py

Activate ANN001 on utils in tests folder

---

tests/appsec/test_automated_user_and_session_tracking.py

Another group of tests corrected to be able to work for all languages in addition to minimizing setup
Swapped scenarios

Change runtime activation to AppSec & RC enabled

---

utils/build/virtual_machine/provisions/auto-inject/auto-inject_installer_manual.yml

force the apm instrumentation after install the installer.
reduce the flakiness?

onboarding: force the apm instrumentation after install the installer.

---

tests/test_config_consistency.py

https://datadoghq.atlassian.net/browse/APMAPI-1251

[java] Skip test failing for APMAPI-1251

---

tests/debugger/test_debugger_telemetry.py
tests/debugger/utils.py

Fix debugger telemetry scenario

---

manifests/php.yml
tests/integrations/test_inferred_proxy.py
utils/build/docker/php/apache-mod/php.conf
utils/build/docker/php/common/inferred_span.php
utils/build/docker/php/php-fpm/php-fpm.conf

APIGW [PR](https://github.com/DataDog/dd-trace-php/pull/3116) for PHP
Added PHP endpoint to test inferred spans

[php] Add APIGW Tests

---

manifests/dotnet.yml
manifests/golang.yml
manifests/java.yml
manifests/nodejs.yml
manifests/php.yml
manifests/python.yml
manifests/ruby.yml
tests/appsec/rasp/test_cmdi.py
tests/appsec/rasp/test_lfi.py
tests/appsec/rasp/test_shi.py
tests/appsec/rasp/test_sqli.py
tests/appsec/rasp/test_ssrf.py
tests/appsec/rasp/utils.py

Adding RASP telemetry metrics V2

add rasp telemetry v2

---

tests/test_telemetry.py
utils/telemetry/intake/static/jvm_config_rules.json

Tests should be enabled :tada:
Updates the static files and enables Java telemetry completeness tests

[java] Enable telemetry completeness test

---

utils/virtual_machine/aws_infra_exceptions.json

Try to apply a retry policy for the errors:
- https://datadoghq.atlassian.net/browse/APMSP-1869
- https://datadoghq.atlassian.net/browse/APMSP-1873

AWS: retry policy ecr and ghcr rate limits

---

manifests/golang.yml
utils/telemetry_utils.py

https://datadoghq.atlassian.net/browse/APPSEC-56213
Enable already passing appsec tests

[golang] appsec easy wins

---

manifests/php.yml
utils/build/docker/php/apache-mod/php.conf
utils/build/docker/php/common/index.php
utils/build/docker/php/common/login.php
utils/build/docker/php/common/signup.php
utils/build/docker/php/common/users.php
utils/build/docker/php/php-fpm/php-fpm.conf

Enable V3 Login events tests now that it is implemented on the PHP tracer.
- Enable V3 Login events tests
- Disable V2 Login events tests
- Update the weblog to call the new functions that have been implemented
Related Jiras: [APPSEC-56144], [APPSEC-56145], [APPSEC-56146]
🛟 …

[php] Enable V3 Login events tests

---

pyproject.toml
tests/appsec/iast/sink/test_header_injection.py
tests/appsec/iast/source/test_parameter_value.py
tests/appsec/iast/utils.py
tests/integrations/crossed_integrations/test_kafka.py
tests/integrations/crossed_integrations/test_kinesis.py
tests/integrations/crossed_integrations/test_rabbitmq.py
tests/integrations/crossed_integrations/test_sns_to_sqs.py
tests/integrations/crossed_integrations/test_sqs.py
tests/integrations/test_dbm.py
tests/integrations/test_dsm.py
tests/integrations/utils.py

Activate mypy on some tests folders

---

tests/debugger/test_debugger_symdb.py
tests/debugger/utils.py

Skip failing test for DEBUG-3659

---

utils/scripts/ci_orchestrators/workflow_data.py

[php] skip DEBUGGER_PII_REDACTION for DEBUG-3661

---

tests/test_the_test/test_ci_orchestrator.py
utils/scripts/ci_orchestrators/workflow_data.py

Fix CI orchestrator

---

tests/docker_ssi/test_docker_ssi.py

Fix the bug marker for test telemetry on docker ssi and python

Docker SSI: bug marker python

---

utils/telemetry/intake/static/config_norm_rules.json

Manually add telemetry key third_party_shading_identifiers

---

tests/test_sampling_rates.py

[nodejs] Add uds-express4 for APMAPI-1252

---

tests/test_telemetry.py
utils/_context/_scenarios/endtoend.py
utils/telemetry/intake/static/config_prefix_block_list.json

[PHP] Fix failing tests for APMAPI-1270

---

manifests/dotnet.yml

Update tests to reflect the up-to-date .NET library feature parity
Enables the `Test_Config_LogInjection_128Bit_TraceId_Enabled` test for the .NET Tracer v3.13.0

Update final .NET test cases for DD_TRACE_128_BIT_TRACEID_LOGGING_ENABLED configuration

---

tests/appsec/iast/sink/test_command_injection.py

[python] Skip failing test for APPSEC-57094

---

manifests/python.yml

[python] update manifest for bug

---

utils/build/docker/java/play/pom.xml

[java] Do not treat warning as error during compilation

---

manifests/java.yml
tests/appsec/test_event_tracking_v2.py
utils/build/docker/java/akka-http/src/main/scala/com/datadoghq/akka_http/AppSecRoutes.scala
utils/build/docker/java/install_ddtrace.sh
utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/MyResource.java
utils/build/docker/java/play/app/controllers/AppSecController.scala
utils/build/docker/java/play/conf/routes
utils/build/docker/java/play/pom.xml
utils/build/docker/java/ratpack/src/main/java/com/datadoghq/ratpack/Main.java
utils/build/docker/java/resteasy-netty3/src/main/java/com/datadoghq/resteasy/MyResource.java
utils/build/docker/java/spring-boot-3-native/src/main/java/com/datadoghq/springbootnative/WebController.java
utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/App.java
utils/build/docker/java/vertx3/src/main/java/com/datadoghq/vertx3/Main.java
utils/build/docker/java/vertx4/src/main/java/com/datadoghq/vertx4/Main.java

[java] Add Java endpoints for ATO SDK v2 tests

---

utils/virtual_machine/virtual_machines.json

https://datadoghq.atlassian.net/browse/APMSP-1903

OnBoarding: Disable Debian 12 machines (temporary)

---

.gitlab/ssi_gitlab-ci.yml
utils/virtual_machine/aws_infra_exceptions.json

https://datadoghq.atlassian.net/browse/APMSP-1893
https://datadoghq.atlassian.net/browse/APMSP-1899
https://datadoghq.atlassian.net/browse/APMSP-1895
https://datadoghq.atlassian.net/browse/APMSP-1897
https://datadoghq.atlassian.net/browse/APMSP-1887
https://datadoghq.atlassian.net/browse/APMSP-1881
https://datadoghq.atlassian.net/browse/APMSP-1892
https://datadoghq.atlassian.net/browse/APMSP-1880 …

SSI: reduce flakiness II

---

format.sh

Update runner automatically if needed in format.sh

---

.gitlab-ci.yml
tests/auto_inject/test_auto_inject_chaos.py
tests/auto_inject/test_auto_inject_install.py
tests/auto_inject/test_blocklist_auto_inject.py

Active onboarding ruby easy wins

Onboarding: easy wins Ruby

---

utils/interfaces/_library/core.py

Running only python to not stress CI grid

[python] Minor improvments on logs to help debugging

---

utils/build/virtual_machine/weblogs/ruby/test-app-ruby/test-app-ruby_run.sh

Enable SSI when we launch "bundle install" of the app

Onboarding: Enable SSI on bundle install (ruby)

---

manifests/python.yml

switching to bug to plan an investigation later.

[python] Test_IastStandalone_UpstreamPropagation_V2 failing on flask-poc

---

manifests/python.yml

[python] adding uds-flask to APPSEC-57145

---

utils/build/docker/golang/app/net-http/main.go

This change ensures that all headers from the original request are propagated. 

[Go] make_disant_call endpoint for net-http

---

lib-injection/build/docker/python/dd-lib-python-init-test-django/django_app.py
pyproject.toml
tests/integrations/crossed_integrations/test_kafka.py
tests/integrations/crossed_integrations/test_kinesis.py
tests/integrations/crossed_integrations/test_rabbitmq.py
tests/integrations/crossed_integrations/test_sns_to_sqs.py
tests/integrations/crossed_integrations/test_sqs.py
tests/test_the_test/test_json_report.py

Activate easy ruff rules

---

utils/virtual_machine/aws_infra_exceptions.json

Apply a retry policy for these jira issues:
- https://datadoghq.atlassian.net/browse/APMSP-1907
- https://datadoghq.atlassian.net/browse/APMSP-1914
- https://datadoghq.atlassian.net/browse/APMSP-1915
- https://datadoghq.atlassian.net/browse/APMSP-1916
- https://datadoghq.atlassian.net/browse/APMSP-1917
🛟 …

Onboarding: networking flakiness

---

tests/auto_inject/test_auto_inject_chaos.py
tests/auto_inject/test_auto_inject_install.py

After merging the previous PR: https://github.com/DataDog/system-tests/pull/4460 some jobs are now easy wins. Enable them

Onboarding: Python profiling easy wins

---

.gitlab-ci.yml
utils/scripts/pulumi_clean_up.py

A new job to count the system-tests amis (cache) and push an event to DD with the number of amis

Onboarding: Count amis job

---

manifests/nodejs.yml

Tests are xpassing
Enable the tests

[nodejs] Enable ST for login sdk v1 metrics

---

utils/scripts/ci_orchestrators/gitlab_exporter.py

first step to activate dd-trace-js to use the new aws accoun for the onboarding tests

Onboarding: nodejs new aws account

---

tests/appsec/rasp/test_cmdi.py
tests/appsec/rasp/test_lfi.py
tests/appsec/rasp/test_shi.py
tests/appsec/rasp/test_sqli.py
tests/appsec/rasp/test_ssrf.py

The distribution metrics checks shouldn't be there, libraries haven't to implement it.
Do not check distribution metrics checks in rasp tests

Remove rasp distribution metric checks 

---

tests/appsec/waf/test_truncation.py

These checks shouldn't be there.
Remove more distribution checks

Remove more distribution metrics checks

---

utils/telemetry/intake/static/jvm_config_rules.json

Fixing system tests for https://github.com/DataDog/dd-trace-java/pull/8682 and following up on https://github.com/DataDog/dd-go/pull/178276

Add CI Visibility scalatest fork monitor telemetry config rule

---

utils/build/docker/golang/app/net-http/main.go

We should not copy headers in make_distant_call

Update make_distant_call in main.go

---

utils/scripts/ci_orchestrators/gitlab_exporter.py

We include the dd-trace-java and dd-trace-py to run the SSI tests on the new AWS account

SSI tests: new aws account for java and python

---

utils/proxy/_deserializer.py

Prevent failure in setup phase on malformated JSON

---

utils/_features.py

Adding baggage header propagation to feature parity dashboard. 

Adding baggage to feature parity dashboard

---

utils/scripts/ci_orchestrators/gitlab_exporter.py

Test the configuration of the auto_inject repository for the new aws account

ssi tests: auto_inject new aws account test

---

utils/scripts/ci_orchestrators/gitlab_exporter.py

First step to migrate the repositories dotnet, php and ruby to the new aws account

SSI Tests: Partial migration dotnet, php and rb to new aws account

---

utils/_context/_scenarios/integrations.py

These tests should be run by default

add crossed tracing integration propagation tests to essential and integrations scenarios

---

manifests/nodejs.yml

The test test_ExtractBehavior_Restart is failing. Mark for next release

[NodeJS] Updating Manifests for ExtractBehavior_restart

---

utils/_context/_scenarios/endtoend.py

[php] Skip schema validation for DEBUG-3709

---

.gitignore
utils/proxy/_deserializer.py
utils/scripts/compute_impacted_scenario.py

[php] Ignore content of response when backend answer 408

---

utils/scripts/ci_orchestrators/gitlab_exporter.py

Enable the new aws account for the repositories dotnet, php and rb

SSI tests: enable aws account: dotnet, php and rb

---

.github/workflows/compute-workflow-parameters.yml
utils/scripts/compute-workflow-parameters.py

Not related to nodejs, just here to speed up the CI

[nodejs] Fix typo in CI

---

tests/debugger/test_debugger_probe_snapshot.py

Follow up of DataDog/system-tests#4131
Use the good way to get the logger
Note : it's not related to nodejs, just here to save some CI time

[nodejs] Use utils logger

---

manifests/python.yml

enable telemetry v2 for rasp for python

[python] easy wins on rasp telemetry

---

utils/scripts/compute-workflow-parameters.py

[cpp] Fix compute scenarios

---

manifests/golang.yml
tests/appsec/test_asm_standalone.py
tests/appsec/waf/test_addresses.py

[golang] address easy wins

---

utils/build/virtual_machine/provisions/auto-inject/auto-inject_installer_manual.yml

https://datadoghq.atlassian.net/browse/APMSP-1912
Retries Docker instrumentation in the installer

fix(onboarding-tests): Retry docker instrumentation

---

docs/execute/ssi.md
docs/scenarios/onboarding.md
tests/test_the_test/test_group_rules.py
utils/__init__.py
utils/_context/_scenarios/__init__.py
utils/_context/_scenarios/appsec_low_waf_timeout.py
utils/_context/_scenarios/core.py
utils/_context/_scenarios/debugger.py
utils/_context/_scenarios/default.py
utils/_context/_scenarios/endtoend.py
utils/_context/_scenarios/external_processing.py
utils/_context/_scenarios/integrations.py
utils/_context/_scenarios/ipv6.py
utils/_context/_scenarios/k8s_lib_injection.py
utils/_context/_scenarios/open_telemetry.py
utils/_context/_scenarios/parametric.py
utils/_context/_scenarios/profiling.py
utils/scripts/compute-workflow-parameters.py
utils/scripts/compute_impacted_scenario.py
utils/scripts/get-scenarios-from-group.py
utils/telemetry/_utils.py

Allow to attach tests to a group of scenarios : 
```python
@scenario_groups.appsec_activated
class Test_AppSecBeahviour:
```

Revamp scenario groups

---

utils/scripts/ci_orchestrators/workflow_data.py

3.13 is supported since last major version

[python] enable 3.13 for prod

---

manifests/python.yml
tests/appsec/test_asm_standalone.py

Easy wins for python ATO + Standalone ASM

[python] easy wins for ATO + Standalone ASM

---

.github/workflows/run-end-to-end.yml
tests/integrations/utils.py
utils/_context/_scenarios/integrations.py
utils/_context/containers.py

remove dead code

---

utils/_features.py

Fix line and method feature ids

[Debugger] Feature ids fix

---

tests/debugger/test_debugger_probe_status.py
tests/debugger/utils.py

[php] skip failing test for DEBUG-3814

---

tests/appsec/iast/utils.py

More informative assert for IAST location tests

---

utils/_context/_scenarios/core.py
utils/scripts/compute_impacted_scenario.py

fix compute scenario script

---

utils/virtual_machine/aws_infra_exceptions.json

https://datadoghq.atlassian.net/browse/APMSP-1982

AWS SSI Flakiness: APMSP-1982

---

manifests/python.yml

[python] follow up of #4590

---

tests/parametric/test_dynamic_configuration.py

[python] Skip failing test for APMAPI-1400

---

manifests/python.yml

feat: enable test_vulnerability_schema for Python

---

tests/apm_tracing_e2e/test_single_span.py

The new tests are failing in the nightly build. For now skip the tests
The failing pipeline: https://github.com/DataDog/system-tests-dashboard/actions/runs/14923227144/job/41923198077#step:30:161

Skip SingleSpan tests temporarily

---

manifests/php.yml
utils/build/docker/php/apache-mod/entrypoint.sh
utils/build/docker/php/apache-mod/php.conf
utils/build/docker/php/common/api_security_sampling.php
utils/build/docker/php/common/php.ini
utils/build/docker/php/php-fpm/php-fpm.conf

Enable sampling tests for PHP

---

utils/scripts/ssi_wizards/aws_onboarding_wizard.sh

AWS SSI improvements.
This case is based on https://datadoghq.atlassian.net/browse/APMSP-1950 that focus on the ssi wizard improvements

aws ssi improvements based on APMSP-1950

---

manifests/nodejs.yml

Enable Api security with asm standalone test

[nodejs] Enable Api security with asm standalone test

---

.github/workflows/ci.yml

use last version of DataDog/ensure-ci-success

---

utils/scripts/ssi_wizards/common_wizard_functions.sh

ssi wizard improvements.
related to: https://datadoghq.atlassian.net/browse/APMSP-1987

ssi improvements APMSP-1987

---

.github/workflows/ci.yml

Use all-green v2.1.1

---

utils/_context/_scenarios/docker_ssi.py

Docker SSI improvements related to https://datadoghq.atlassian.net/browse/APMSP-1988

Docker SSI improvements APMSP-1988

---

manifests/ruby.yml
tests/appsec/test_automated_user_and_session_tracking.py
utils/build/docker/ruby/rails42/app/controllers/sessions_controller.rb
utils/build/docker/ruby/rails42/config/routes.rb
utils/build/docker/ruby/rails50/app/controllers/sessions_controller.rb
utils/build/docker/ruby/rails50/config/routes.rb
utils/build/docker/ruby/rails51/app/controllers/sessions_controller.rb
utils/build/docker/ruby/rails51/config/routes.rb
utils/build/docker/ruby/rails52/app/controllers/sessions_controller.rb
utils/build/docker/ruby/rails52/config/routes.rb
utils/build/docker/ruby/rails60/app/controllers/sessions_controller.rb
utils/build/docker/ruby/rails60/config/routes.rb
utils/build/docker/ruby/rails61/app/controllers/sessions_controller.rb
utils/build/docker/ruby/rails61/config/routes.rb
utils/build/docker/ruby/rails70/app/controllers/sessions_controller.rb
utils/build/docker/ruby/rails70/config/routes.rb
utils/build/docker/ruby/rails71/app/controllers/sessions_controller.rb
utils/build/docker/ruby/rails71/config/routes.rb
utils/build/docker/ruby/rails72/app/controllers/sessions_controller.rb
utils/build/docker/ruby/rails72/config/routes.rb
utils/build/docker/ruby/rails80/app/controllers/sessions_controller.rb
utils/build/docker/ruby/rails80/config/routes.rb

Another attempt on https://github.com/DataDog/system-tests/pull/4606 without breaking current dd-trace-rb
I've changed v2.15.0-dev to v2.15.1-dev and it should work for current master 😠

[APPSEC-57504] Enable session tracking and fingerprinting (separate attempt)

---

tests/test_smoke.py

Skip agent test for CONTINT-4688

---

manifests/java.yml

easy wins for sampling

---

manifests/cpp_nginx.yml
manifests/dotnet.yml
manifests/golang.yml
manifests/java.yml
manifests/nodejs.yml
manifests/php.yml
manifests/python.yml
manifests/ruby.yml
tests/appsec/test_extended_request_body_collection.py
utils/_context/_scenarios/__init__.py
utils/_features.py

[JIRA](https://datadoghq.atlassian.net/browse/APPSEC-57268)

APPSEC extend request body collection

---

manifests/nodejs.yml
utils/build/docker/nodejs/nextjs/src/app/api_security/sampling/[status]/route.js
utils/build/docker/nodejs/nextjs/src/app/api_security_sampling/[i]/route.js

Enable all API Security sampling tests for Next.js
1. Create API sec sampling endpoints on nextjs
2. Change nodejs yml file

[nodejs] Create nextjs api sec sampling endpoints

---

manifests/java.yml

[Java] Enable Test_APISecurityStandalone tests

---

manifests/nodejs.yml

Easy win: Enable API sec on standalone in Next.js

[nodejs] Enable API sec on standalone in Next.js

---

utils/build/ssi/base/install_script_ssi.sh
utils/build/virtual_machine/provisions/auto-inject/auto-inject_installer_manual.yml
utils/build/virtual_machine/provisions/auto-inject/repositories/autoinstall/execute_install_script.sh

fix(onboarding): Use Node.js major 6 in staging

---

manifests/java.yml

[Java] Enable Baggage Tests

---

manifests/java.yml

[Java] enable Test_ExtendedHeaderCollection tests

---

.github/workflows/ci.yml
.vscode/launch.json
tests/fuzzer/request_mutator.py
utils/_context/_scenarios/__init__.py
utils/_context/_scenarios/core.py
utils/scripts/compute_impacted_scenario.py

Fix fuzzer scenario

---

docs/scenarios/docker_ssi.md
utils/docker_ssi/docker_ssi_definitions.py
utils/docker_ssi/docker_ssi_runtimes.json

SDKMan! dropped the old updates and we need to adjust
Updating the JDK versions to the latest available

[Java] Update JDK versions

---

manifests/nodejs.yml
tests/appsec/test_extended_request_body_collection.py
utils/build/docker/nodejs/express/app.js
utils/build/docker/nodejs/express4-typescript/app.ts
utils/build/docker/nodejs/nextjs/src/app/customResponseHeaders/route.js
utils/build/docker/nodejs/nextjs/src/app/exceedResponseHeaders/route.js

Test extended data collection
- Endpoints for Node.js variants
- Conditional check on request body collection test
[APPSEC-57290](https://datadoghq.atlassian.net/browse/APPSEC-57290)
[APPSEC-57290]: …

[nodejs] Appsec extended data collection

---

.gitlab-ci.yml
.gitlab/ssi_gitlab-ci.yml

Update docker base runner.
Related to:
- https://github.com/DataDog/libdatadog-build/pull/112
- https://github.com/DataDog/libdatadog-build/pull/108
- https://datadoghq.atlassian.net/browse/CONTSEC-1626?linkSource=email

gitlab ci: update docker base runner

---

manifests/nodejs.yml

Feature implemented here (https://github.com/DataDog/dd-trace-js/pull/5794)
nodejs.yml enabling the tests

[nodejs] Enable activation metrics in Node.js

---

tests/test_sampling_rates.py

[nodejs] skip test for APMAPI-1441

---

manifests/nodejs.yml
tests/appsec/test_asm_standalone.py

Enable ST for already implemented feature.
Enable the tests and replace `post` call by a `get` call, which was the expected method.

Enable asm standalone SDK methods for Node.js

---

manifests/cpp_nginx.yml
manifests/dotnet.yml
manifests/golang.yml
manifests/java.yml
manifests/nodejs.yml
manifests/php.yml
manifests/python.yml
manifests/ruby.yml
tests/appsec/blocking_rule.json
tests/appsec/test_remote_config_rule_changes.py
tests/appsec/test_trace_tagging.py
utils/_features.py

The goal of this PR is to validate support for trace-tagging rules and ancillary features, as defined [here](https://docs.google.com/document/d/1bqDtGgMJgsTW6I16iEcRn1lb9RRQjFRDGim8zRrbs0s/edit?tab=t.0). 
This PR adds the following:
- New tests for trace-tagging rules:
- The first one uses a rule which only provides attributes.
- The second one uses a rule which provides attributes and requires elevated sampling priority.
- The third one generates both events and attributes and also requires elevated sampling priority.
- The fourth one generates both events and attributes, but doesn't require elevated sampling priority.
- The final test verifies the that the correct RC capability is provided.
- A new `ASM_DD` multiconfiguration test to validate that a configuration with the `rules_compat` …

[AAP] Add tests for trace-tagging rules and rules_compat through RC

---

utils/scripts/ci_orchestrators/workflow_data.py

Better distribution of jobs in runner
Use First Fit Decreasing algorithm to distribute scenarios in runners

Improve paralelization distribution

---

utils/build/docker/ruby/rack/config.ru

I've noticed that Rack weblog is not sampling request right after the finish of the "customer" code like other higher level frameworks do.
```
Rails
181:debug.trace_operation.initialize
182:debug.trace_operation.sampled nil
183:debug.trace_operation.sampling_priority nil
184:debug.trace_operation.sample_rate nil
194:debug.request_path /tag_value/api_match_AS001/200
195:debug.trace.sampled true
196:debug.trace.sampling_priority 1 <------------------------ set to 1
197:debug.trace.priority_sampled? true
198:debug.apm.tracing.enabled true
199:debug.api_security.enabled? true
200:debug.api_security.sample_trace? true
201:debug.api_security.sample? true
Rack
146:debug.trace_operation.initialize
147:debug.trace_operation.sampled nil
148:debug.trace_operation.sampling_priority nil …
```

[ruby] Sample request before end of lifecycle in Rack weblog

---

tests/appsec/test_automated_login_events.py
tests/appsec/test_automated_user_and_session_tracking.py
tests/appsec/waf/test_reports.py

Reverts DataDog/system-tests#4811

[ruby] Revert skip failing tests for APPSEC-58061

---

tests/appsec/test_asm_standalone.py
utils/build/docker/python/flask/app.py
utils/build/docker/python/flask/app.sh

Standalone tests are flaky for flask
Properly add gevent patching for urllib3, minor changes....
APPSEC-57145

[python] tentative fix on the flask weblog for standalone

---

tests/test_config_consistency.py

[nodejs] Skip test for APMAPI-1444

---

docs/CI/github-actions.md

Update GHA doc

---

utils/_features.py

Fixes the id for the process tags feature (was a bad copy paste)

Fix bad feature parity link

---

tests/appsec/test_asm_standalone.py

skip tests for APPSEC-57145

---

.gitlab/ssi_gitlab-ci.yml
lib-injection/build/build_lib_injection_weblog.sh
utils/build/virtual_machine/weblogs/common/create_and_run_app_container.sh

Docker build retries and timeouts for k8s

SSI: Docker build retries and timeouts

---

manifests/dotnet.yml
tests/test_the_test/test_existing_versions.py

[dotnet] Only used existing versions

---

tests/appsec/test_asm_standalone.py
tests/test_the_test/test_existing_versions.py

[python] Skip another tests for APPSEC-57145

---

tests/test_the_test/test_group_rules.py

Small fix on a test on tracer-release group

---

.github/workflows/ci.yml

Fix rate limit on test-the-test

---

tests/appsec/test_asm_standalone.py

[python] daily skip for APPSEC-57145

---

manifests/dotnet.yml
tests/integrations/test_dsm.py
utils/build/docker/dotnet/weblog/Endpoints/DsmEndpoint.cs
utils/build/docker/dotnet/weblog/app.csproj

DSM/.NET: RabbitMQ Topic/Fanout scenarios

---

manifests/ruby.yml

Process discovery has been merged in dd-trace-rb
Adds next dd-trace-rb release to manifest for process discovery.

[ruby] [APMAPI-1068] Enable Process Discovery

---

utils/build/virtual_machine/weblogs/java/test-app-java-buildpack/test-app-java_docker_compose_run_buildpack.sh
utils/virtual_machine/aws_infra_exceptions.json

Apply retry policies to aws ssi tests

aws ssi: buildpack and retries

---

utils/_context/containers.py
utils/build/build.sh

Do not load weblog image if the weblog is in binaries

---

.gitlab-ci.yml
tests/auto_inject/test_auto_inject_install.py

Remove the check_pipeline_status job

GitLab: remove check_pipeline_status job

---

tests/test_smoke.py

https://docs.datadoghq.com/agent/configuration/network/?site=us5
Add comment to explain the ignore list

Add a small comment on ignored hosts in agent check

---

pyproject.toml
utils/virtual_machine/virtual_machine_provisioner.py
utils/virtual_machine/vm_logger.py

Activate few ruff rules for onboarding files

---

.gitlab/ssi_gitlab-ci.yml
utils/_context/_scenarios/auto_injection.py
utils/build/virtual_machine/provisions/auto-inject/auto-inject-vm_logs.yml
utils/onboarding/debug_vm.py
utils/virtual_machine/virtual_machine_provider.py
utils/virtual_machine/virtual_machines.py

This PR removes the previous log extraction mechanism, which only supported downloading text files.  
That approach was limiting in scenarios like .NET, where downloading binary files such as core dumps is required.
- Now, **all files located in**:
- `/var/log/datadog/`
- `/var/log/datadog_weblog/`
will be downloaded from the instance.
- If you need to retrieve a specific file, **make sure it is placed in one of these directories**.  
You can move or copy files there during the installation step:  
`utils/build/virtual_machine/provisions/auto-inject/auto-inject-vm_logs.yml`
- In the **GitLab job**, the `after_script` step uploads the full `logs/` folder (previously downloaded from the machine) to **S3**.
- A **pre-signed URL** will be provided to access the logs from S3.  
> 🛑 **Note:** …

AWS SSI: vm logs to S3

---

manifests/nodejs.yml

Enable test for the new supported feats
Test enabled in Node.js manifest

[nodejs] Enable obfuscation config test

---

tests/integrations/crossed_integrations/test_kinesis.py
tests/integrations/crossed_integrations/test_sns_to_sqs.py
tests/integrations/crossed_integrations/test_sqs.py
utils/_context/_scenarios/integrations.py

The scenario CROSSED_TRACING_LIBRARIES is failing. The failure is related how the json traces are writing. Adding `ENV DD_TRACE_API_VERSION=v0.4` should fix the problem. 

Fix integrations: API Versions

---

manifests/php.yml
tests/appsec/test_event_tracking_v2.py
utils/build/docker/php/apache-mod/php.conf
utils/build/docker/php/common/user_login_failure_event_v2.php
utils/build/docker/php/common/user_login_success_event_v2.php
utils/build/docker/php/php-fpm/php-fpm.conf

[php] Add php ato v2 tests

---

.gitlab/ssi_gitlab-ci.yml
utils/virtual_machine/aws_infra_exceptions.json

Reduce SSI flakiness
Add new rule to the retry policy
Increase K8s timeout

SSI minor fixes (flakiness)

---

manifests/php.yml

[php] Enable rate limit tests

---

tests/docker_ssi/test_docker_ssi.py

Docker SSI: INPLAT-427

---

manifests/python.yml
tests/appsec/iast/test_security_controls.py
utils/_context/_scenarios/default.py
utils/build/docker/python/flask/app.py

[python] security controls

---

manifests/java.yml
tests/appsec/iast/source/test_parameter_value.py
utils/build/docker/java/play/app/controllers/IastSourceController.scala
utils/build/docker/java/play/conf/routes

Add Play endpoints for /appsec/iast/source/test_parameter_value.py::TestParameterValue
Enable tests for play 
Add bug annotations as only the telemetry tests are working

[Java] Easy wins related with IAST

---

manifests/java.yml

[Java] Easy wins related with waf custom rule

---

manifests/java.yml
tests/appsec/test_remote_config_rule_changes.py

[Java] Easy wins related with remote config 

---

manifests/java.yml

[Java] Easy wins related with Standalone

---

manifests/dotnet.yml
manifests/golang.yml
manifests/java.yml
manifests/nodejs.yml
manifests/php.yml
manifests/python.yml
manifests/ruby.yml
tests/appsec/test_remote_config_rule_changes.py

Add test to check that unknown action doesn't break RC in libraries

---

.github/workflows/update-agent-protobuf.yml

Update Go version in update-agent-protobuf.yml to v1.24.0

---

manifests/golang.yml
tests/appsec/waf/test_telemetry.py
utils/build/docker/golang/app/_shared/rasp/rasp.go
utils/build/docker/golang/app/chi/main.go
utils/build/docker/golang/app/echo/main.go
utils/build/docker/golang/app/gin/main.go
utils/build/docker/golang/app/net-http-orchestrion/main.go
utils/build/docker/golang/app/net-http/main.go

Cover first part of easy wins for go

[golang] easy wins

---

utils/build/build.sh
utils/scripts/load-binary.sh

`zsh` does not support empty array 😢 

Do not use array in sh scripts

---

utils/_context/_scenarios/profiling.py
utils/proxy/_deserializer.py

Reverts DataDog/system-tests#5010

Revert "workaround for protobuf errors on dd-trace-py"

---

manifests/php.yml
utils/build/docker/php/apache-mod/php.conf
utils/build/docker/php/common/php.ini
utils/build/docker/php/common/session_new.php
utils/build/docker/php/php-fpm/php-fpm.conf

Enable fingerprint blocking tests for PHP

[php] Enable fingerprint blocking tests

---

utils/_context/containers.py

In a previous PR #4419, a specific image built for the system tests was published. Now all problems are resolved and the latest one should be used.

ext_proc: Update system tests specific image to latest

---

utils/build/docker/cpp_httpd/httpd.Dockerfile
utils/build/docker/cpp_httpd/install_ddtrace.sh
utils/build/docker/github.sh

[cpp_httpd] harden install_ddtrace script

---

utils/onboarding/debug_vm.py

Certain containerized applications have been exhibiting issues. This PR adds additional logging to help reproduce and troubleshoot the problem.

AWS SSI: add more debug logs

---

tests/stats/test_stats.py

https://datadoghq.atlassian.net/browse/APMSP-2202

Mark test Test_Client_Stats.test_client_stats as flaky

---

utils/scripts/ci_orchestrators/workflow_data.py

Do not run APPSEC_LAMBDA_API_SECURITY for non-lambda libraries

---

tests/k8s_lib_injection/test_k8s_lib_injection.py

Mark the tests as bug for cluster agent 7.56.2 for nodejs and ruby

K8s Lib Injection: APMSP-2215

---

utils/build/virtual_machine/weblogs/python/provision_test-app-python-27.yml

AWS SSI: Fix debian 11

---

utils/_features.py

Fix typo made in #5119

---

utils/build/virtual_machine/provisions/auto-inject/auto-inject_init_vm_config.yml
utils/build/virtual_machine/weblogs/python/provision_test-app-python-27.yml

AWs SSI: Fix debian 11 v2

---

manifests/java.yml

[Java] Enable Test_Blocking_client_ip_with_forwarded

---

tests/debugger/utils.py

look into diagnostics path as new snapshot will be sent to diagnostics endpoint

[java] Fix snapshot received lookup

---

utils/interfaces/_schemas_validators.py
utils/interfaces/schemas/agent/api/v2/debugger-request.json
utils/interfaces/schemas/library/debugger/v1/diagnostics-request.json

As snapshot will be sent to same. endpoint than diagnostic, schema validation need to be updated to handle both

fix schema validation for diagnostic and snapshot

---

utils/_context/_scenarios/endtoend.py

skip chema assertio for php >= 1.12.0 (DEBUG-4431)

---

.github/workflows/debug-harness.yml
utils/scripts/compute_impacted_scenario.py

add debugger harness

---

tests/appsec/test_traces.py

[cpp_nginx] Skip test for APPSEC-58808

---

utils/build/docker/python/uwsgi-poc.Dockerfile

https://github.com/DataDog/dd-trace-py/pull/14526

[python] uwsgi sets `--skip-atexit`

---

utils/interfaces/_agent.py

Allow empty payload on /api/v2/series

---

.github/workflows/compute-impacted-libraries.yml
.github/workflows/compute-scenarios.yml

Better get-modified-files

---

tests/debugger/test_debugger_exception_replay.py

Approval snapshot structure changed, need to update approvals for upcoming version. This is temporary soluction that will be replaced with something more robust in future.
Temporary mark python as `missing_feature` for upcoming version

[Debugger] Temporary mark python as `missing_feature` for upcoming version

---

tests/integrations/test_open_telemetry.py
utils/_context/_scenarios/__init__.py
utils/_context/_scenarios/endtoend.py
utils/_context/_scenarios/open_telemetry.py
utils/_context/containers.py
utils/proxy/core.py
utils/scripts/compute-impacted-libraries.py

fix otel scenario

---

utils/build/virtual_machine/provisions/auto-inject/auto-inject_init_vm_config.yml
utils/virtual_machine/virtual_machines.json

The ubuntu 24.10 repositories were moved. Fix to point to new url repositories

AWS SSI: Ubuntu 24_10 fix

---

.github/actions/pull_images/action.yml
.github/workflows/run-end-to-end.yml
.github/workflows/run-external-processing.yml

clean-up disk space for PHP

---

utils/scripts/ssi_wizards/docker_ssi_wizard.sh

The user may be confused in these two cases:
- Testing the docker image with a different architecture may cause problems when running the tests.
- Referencing an incorrect pipeline can cause runtime errors that can lead to misunderstandings.
Update the wizard adding warning messages

Docker ssi wizard updates

---

tests/appsec/test_asm_standalone.py

[python] skip failing test for APPSEC-59081

---

.github/workflows/ci.yml
.github/workflows/run-end-to-end.yml
.github/workflows/run-external-processing.yml
.github/workflows/run-stream-processing-offload.yml
.github/workflows/system-tests.yml
docs/CI/github-actions.md

* precise list of secret in `workflow_call`
* all private parameters starts with a `_`
* improved documentation

Clean official workflow  + documentation

---

.github/workflows/run-end-to-end.yml
.github/workflows/run-external-processing.yml
.github/workflows/run-parametric.yml
.github/workflows/run-stream-processing-offload.yml

Harden step that compress logs

---

utils/_features.py

Set owners on some features

---

utils/_context/_scenarios/endtoend.py

Skip schema test for DEBUG-4541

---

utils/scripts/activate-easy-wins.py

Xpass activation script update

---

utils/build/virtual_machine/provisions/auto-inject/auto-inject_installer_manual.yml
utils/build/virtual_machine/provisions/installer-auto-inject/provision.yml

Reverts DataDog/system-tests#5380

Revert "fix(tests): Force site:datadoghq.com"

---

tests/apm_tracing_e2e/test_process_tags.py

Enable go test suite for process tags 

[go] enable process tags test for go

---

utils/virtual_machine/virtual_machines.json

The machines are failing. 
Disable until the problem is fixed

AWS SSI: Disable oracle linux

---

tests/integrations/test_dsm.py

[java] Skip flaky test for AIDM-117

---

utils/_features.py

Affect tests to team that owns the feature. @mabdinur @mtoffl01 , you created tests attached to those feature, please let me know if this change is relevant, or if I should affect them to another team.

Set owners for SDK features

---

tests/test_config_consistency.py
utils/_context/_scenarios/__init__.py
utils/interfaces/_agent.py

Do not complain of sketches property is missing in agent payload

---

manifests/golang.yml
tests/debugger/test_debugger_symdb.py
tests/debugger/utils.py
utils/_context/_scenarios/endtoend.py
utils/build/docker/golang/app/chi/main.go
utils/build/docker/golang/app/echo/main.go
utils/build/docker/golang/app/gin/main.go
utils/build/docker/golang/app/net-http-orchestrion/main.go
utils/build/docker/golang/app/net-http/main.go
utils/interfaces/schemas/library/symdb/v1/input-request.json

DEBUG-4541: relax schema for Go symbols

---

tests/appsec/test_automated_user_and_session_tracking.py

[python] skip failing test for APPSEC-59541

---

tests/debugger/test_debugger_expression_language.py

Remove bug annotation for DEBUG-4417
