utils/build/docker/golang/install_ddtrace.sh

Fix the Go version lookups for every possible case:
- prod branch with go get
- custom go get
- local directory

Fix Go version lookups

---

tests/appsec/waf/test_addresses.py
tests/appsec/waf/test_miscs.py
utils/interfaces/_library/appsec.py
utils/interfaces/_library/core.py

This PR changes the WAF attack assertion to check for the address and the key path separately.

AppSec addresses don't have semi-colons

---

.github/workflows/ci.yml
tests/appsec/test_traces.py
utils/build/docker/golang/net-http-poc.Dockerfile

- APPSEC_KEEP didn't get approved so MANUAL_KEEP should be validated instead
- Check for every appsec span tags in case of an event, and not only the event-specific tags.
- Rework the test file.
- Add the missing user agent span tag in Go.

Fix trace tests

---

utils/interfaces/schemas/miscs/appsec/contexts/actor/0.1.0.json
utils/interfaces/schemas/miscs/appsec/contexts/agent/0.1.0.json
utils/interfaces/schemas/miscs/appsec/contexts/code_location/0.1.0.json
utils/interfaces/schemas/miscs/appsec/contexts/host/0.1.0.json
utils/interfaces/schemas/miscs/appsec/contexts/http/0.1.0.json
utils/interfaces/schemas/miscs/appsec/contexts/http/1.0.0.json
utils/interfaces/schemas/miscs/appsec/contexts/http/parameters.json
utils/interfaces/schemas/miscs/appsec/contexts/library/0.1.0.json
utils/interfaces/schemas/miscs/appsec/contexts/service/0.1.0.json
utils/interfaces/schemas/miscs/appsec/contexts/service_entry_span/0.1.0.json
utils/interfaces/schemas/miscs/appsec/contexts/span/0.1.0.json
utils/interfaces/schemas/miscs/appsec/contexts/sqreen/0.1.0.json
utils/interfaces/schemas/miscs/appsec/contexts/tags/0.1.0.json
utils/interfaces/schemas/miscs/appsec/contexts/trace/0.1.0.json
utils/interfaces/schemas/miscs/appsec/events/_definitions/rule/0.1.0.json
utils/interfaces/schemas/miscs/appsec/events/_definitions/rule/1.0.0.json
utils/interfaces/schemas/miscs/appsec/events/_definitions/rule_match/0.1.0.json
utils/interfaces/schemas/miscs/appsec/events/_definitions/rule_match/1.0.0.json

In java, we have POJO generated automatically from JSON schemas. When class generated it use json-file name or title field for generated class name. Since, most of filenames are versions (e.g. `0.1.0.json`) it's generates ambiguous class names like `010`, `010_1`, `010_2` etc.
To bring better naming for generated class, I've added title field, which used for class names.
Another one problem, there is difficult consistently describe dictionary in json-schema and there is no suitable way to generate java classes which uses Map (i.e. dictionary).
The best workaround I found was to add java-specific tag `existingJavaType`, which used by java code generator to define Map. The `existingJavaType` tag is ignored by any other parsers, so should not be any problem.

Tuned schemas for Java code generator

---

tests/appsec/test_reports.py
utils/interfaces/_library/appsec.py

Fix of checking response instead of request headers

Check request headers instead of response

---

tests/appsec/test_reports.py

To solve the CI failing in dd-trace-go in the branch for appsec span tags

appsec/test_reports.py: disable actor ip address test for go

---

.github/CODEOWNERS
utils/build/docker/golang/app/net-http.go

Fix the `net/http` variant of weblog so that:
- An access to `/` returns the status code 200 Ok
- Accesses to anything else such as `/i-dont-exist` returns the status 404 Not Found.
This is due to the way the `net/http.ServeMux` works and matches its pattern: `/` will match anything starting with `/`. This problem doesn't exist the two other variants gorilla and echo whose matching works differently.

go/net-http: fix root route

---

tests/appsec/test_logs.py
tests/appsec/test_reports.py
tests/appsec/test_traces.py
tests/appsec/waf/test_addresses.py
tests/appsec/waf/test_rules.py
tests/test_library_conf.py
tests/test_semantic_conventions.py
utils/build/docker/cpp/nginx.Dockerfile
utils/build/docker/dotnet/poc.Dockerfile
utils/build/docker/golang/gorilla.Dockerfile
utils/build/docker/golang/net-http.Dockerfile
utils/build/docker/java/spring-boot-poc.Dockerfile
utils/build/docker/nodejs/armv7.Dockerfile
utils/build/docker/nodejs/express-poc.Dockerfile
utils/build/docker/php/vanilla-poc.Dockerfile
utils/build/docker/python/armv7.Dockerfile
utils/build/docker/python/flask-poc.Dockerfile
utils/build/docker/python/uwsgi-poc.Dockerfile
utils/build/docker/ruby/armv7.Dockerfile
utils/build/docker/ruby/sinatra-poc.Dockerfile

- Remove older versions of log tests
- Annotations on .net tests attributes
- Change DD_TAGS to current implementation, tracers separate value by comma, agent and heroku separate by spaces (specs need to be reworked)

Adapt tests and attributes

---

.github/workflows/ci.yml
tests/appsec/test_traces.py
utils/build/docker/golang/echo.Dockerfile

Add a new weblog variant for the HTTP framework called echo.

go: add a new weblog framework variant for echo

---

utils/interfaces/schemas/library/telemetry/proxy/api/v2/apmtelemetry-request.json

This doesn't include the full schema, so is more of a placeholder to prevent errors for languages that implement the telemetry API.
For example, in .NET I'm [currently seeing an error](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=86072&view=logs&j=f9b5f215-18f7-5982-482b-42aaa98babdc&t=3f7875b6-f8c9-5740-4fc6-e671f428789e) in the system tests in my telemetry branch.
I'm not 100% sure I've defined the schema in the correct way (mostly around objects + potentially missing properties), so I've attached below an example from the logs generated in the above system tests for verification.
```json
{
"path": "/telemetry/proxy/api/v2/apmtelemetry",
"query": "",
"host": "agent",
"port": 8126,
"request": {
"timestamp_start": "2022-01-05T17:54:43.576669",
"content": …
```

Add initial apmtelemetry-request schema

---

tests/test_sampling.py
utils/build/docker/golang/app/common.go

Fix the fact the agent now sends the `DropP0s` config to `true` to dd-trace-go, which drops every trace having span priorities <= 0.

go: enforce init.service priority to be greater than 0

---

tests/test_sampling.py
utils/build/docker/golang/app/common.go

Reverts DataDog/system-tests#126
This test was failing for real. We want to re-enable it.

go: revert "enforce init.service priority to be greater than 0 (#126)"

---

tests/appsec/waf/test_addresses.py
tests/appsec/waf/test_rules.py
utils/build/docker/php/php.conf

This change makes it trivial to test 404 rules without having specific tests for PHP.

Add ErrorDocument to PHP weblog

---

.github/workflows/ci.yml
.gitignore
docs/execute/build.md
utils/build/docker/nodejs/express4-typescript.Dockerfile
utils/build/docker/nodejs/express4-typescript/app.ts
utils/build/docker/nodejs/express4-typescript/package-lock.json
utils/build/docker/nodejs/express4-typescript/package.json
utils/build/docker/nodejs/express4-typescript/tsconfig.json

This PR adds an express4/typescript app.
The app has 2 new commands:
- `npm run build` to compile the TS app to JS
- `npm start` to start the application

Add express4 typescript app

---

utils/build/docker/golang/install_ddtrace.sh

Get the rule file version out of the inlined rule json in the Go library.

go: automated rule file version

---

tests/test_miscs.py
utils/build/docker/dotnet/Helper.cs
utils/build/docker/dotnet/Startup.cs

We want to have an endpoint that generates a lot of load in APM to test our services. This new endpoint takes URL parameters to generate a number of spans and tags with random data (to increase the size of the payload)
We're using this in our load tests through https://github.com/DataDog/k9-appsec-testing-env

Adding an endpoint to generate multiple spans

---

tests/test_sampling.py

Tracking in the test the reason of the different implementations on the sampling mechanism to make it obvious it's not an issue.

More info around sampling feature test

---

tests/appsec/waf/test_addresses.py
utils/build/docker/golang/app/chi.go
utils/build/docker/golang/app/common.go
utils/build/docker/golang/app/echo.go
utils/build/docker/golang/app/gin.go
utils/build/docker/golang/app/gorilla.go
utils/build/docker/golang/app/net-http.go

- `utils/build/docker/golang/app/`: use appsec SDK to monitor http request body
- `utils/build/docker/golang/app/common.go`: add http request body parser
- `tests/appsec/waf/test_addresses.py`: enable http.request.body related tests for go starting from v1.37.0

go: handle http.request.body address tests

---

run.sh
utils/build/docker/nodejs/armv7.Dockerfile
utils/build/docker/weblog-cmd.sh

Several things here : 
* Remove the check on hashbang : it can be `bash`, or `sh`, ot anything else (reduce requirements is always good)
* use `--force-recreate` on docker-compose up, it removes the need of `docker-compose down` at the begining of `run.sh`, and reduce noise in output
* `cgroup` command:  ignore if it fails (check will be done after)
* Add a check on each container, and display stdout if one has been unexpectably stopped

Fix ARM node

---

utils/scripts/load-binary.sh

See https://github.com/DataDog/system-tests-dashboard/runs/5565042743?check_suite_focus=true
```
Install from gem 'ddtrace', require: 'ddtrace/auto_instrument', github: 'Datadog/dd-trace-rb', branch: 'master'
The git source `git://github.com/Datadog/dd-trace-rb.git` uses the `git` protocol, which transmits data without encryption. Disable this warning with `bundle config git.allow_insecure true`, or switch to the `https` protocol to keep your data secure.
Fetching git://github.com/Datadog/dd-trace-rb.git
fatal: remote error: 
The unauthenticated git protocol on port [94](https://github.com/DataDog/system-tests-dashboard/runs/5565042743?check_suite_focus=true#step:7:94)18 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more …
```

Fix ruby install_ddtrace

---

utils/_context/core.py
utils/interfaces/_library/trace_headers.py

`/proc/self/cgroup` gives `0::/` on my laptop.
At least ruby tracer use the same method, and do not have the container id, so the header `datadog-container-id` is missing.

container-id can be missing

---

tests/appsec/test_traces.py

Waiting for @Anilm3 confirmation of this : "*Trace outside a context of a web request is not possible on PHP*".

Non web trace test is not relevant on PHP

---

scenarios/appsec/waf/test_addresses.py
tests/appsec/waf/test_addresses.py

Make two `missing_feature` tests `irrelevant` as we rely on the standard Go parser and it doesn't handle those corner cases properly. We don't plan to do anything about it, even in the long term when we will have dynamic instrumentation.

go: fix server.request.cookies tests

---

run.sh
scenarios/appsec/test_traces.py
tests/appsec/test_traces.py

- Fix the existing test
- Check the obfuscation results on the library interface now that it is implemented by the WAF
- And most importantly, introduce a new test for `server.request.cookies` to check the behavior in case of several cookies having attacks so that we can validate only the one with sensitive data are getting obfuscated.

appsec: better obfuscator tests

---

utils/interfaces/_library/sampling.py

A decision has been made that the libraries would report the WAF rules version for every request rather than once.
The current check in system tests for sampling decision is made assuming that this happens once per WAF instantiation which will lead the tests to fail once the library change goes live. This change makes sure to do the check on a tag that gets reported only once, to make sure that the MANUAL_KEEP priority is not expected when it should not be.

utils: rework sampling decision for spans with WAF metrics

---

tests/appsec/waf/test_addresses.py

This PR skips the non-encoded query key test because there is no rule for it yet, and modifies the encoded query key rule as it wasn't matching with any keys_only rule

fix query key rule

---

scenarios/appsec/waf/test_reports.py
tests/appsec/waf/test_reports.py

Some libraries dont report the error tags object if there's no errors at waf loading. So test the object's value only if it's present

Adapt test for dont report error tag if errors 0

---

tests/test_standard_tags.py
utils/build/docker/php/apache-mod.Dockerfile
utils/build/docker/php/apache-mod/php.conf
utils/build/docker/php/php-fpm.Dockerfile
utils/build/docker/php/php-fpm/php8.0-fpm.conf
utils/build/docker/set-system-tests-weblog-env.Dockerfile
utils/interfaces/_library/core.py
utils/interfaces/_library/miscs.py

Enabling the tests currently doesn't work, even though the tags are provided, because the validator itself requires the user-agent to be available in order to find the relevant spans.

Enable some standard tags tests for PHP

---

utils/build/docker/dotnet/Endpoints/IdentifyEndpoint.UserDetails.cs
utils/build/docker/dotnet/Endpoints/IdentifyEndpoint.cs
utils/build/docker/dotnet/app.csproj
utils/build/docker/dotnet/poc.Dockerfile

extract ddtrace_version from the loaded binary with regex
read env variable DDTRACE_VERSION from msbuild 
define constants dependin on the tracer version and different partial class executed depending on it

Handle several version of .NET tracer

---

tests/appsec/test_reports.py

Mark the test as irrelevant since the Go library now relies on the backend copying what's in `http.client_ip` into `actor.ip`

go: @irrelevant test_actor_ip

---

scenarios/remote_config/test_remote_configuration.py

The RFC allows for has_error to be set to false, so we need to check
this before asserting that error be non-empty.

remote_config: allow for has_error to be set to false

---

utils/build/docker/golang/install_ddtrace.sh

System tests are failing for the PR that will increase dd-trace-go go support version policy. I believe it's due to this line not specifying compatibility with 1.17 now that 1.19 is out.
Here's a link to a failing test: https://github.com/DataDog/dd-trace-go/runs/7660149337?check_suite_focus=true

Bump go mod tidy to compat with 1.17

---

utils/build/docker/dotnet/install_ddtrace.sh

We are refactoring the package layout and as part of the change we need to update these system tests.
Package layout before:
Package layout after:
Note that the package layout should not be breaking, it's only because the `query-versions.fsx` script assumes certain things about the WAF/PInvokes that we need these changes

[dotnet] Support new package layout in system tests

---

scenarios/appsec/waf/test_addresses.py

Mark Cookie test as irrelevant because It isn't handled by the Python standard cookie parser

feat(python/asm): update cookie test

---

tests/appsec/test_conf.py

With release 1.4.0 of the event rules, a different rule trigger this test case

[ASM] Make a config test slightly less restrictive about the triggering rule

---

utils/proxy/forwarder.py

Attempts to modify responses from `/info` endpoint were failed.
It happened on trying to parse content response.
Since `/info` is `GET` endpoint, therefore, content doesn't exists.

Fix modifying `/info` responses

---

parametric/test_span_sampling.py

Despite never failing locally for me, it seems the range is a little more varied in CI, so expanding it to reduce flakiness.

increase range for span sampling test to reduce flakiness

---

parametric/run.sh

I got issue running the parametric tests on my laptop.
There is a parameter from the `run.sh` script to exclude the parent `conftest.py` but its path must be absolute.
When using symbolic link in its project path (like when cloning the project into the `~/dd` folder), the absolute file path is wrong, leading to the following error:
```INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/bruce.bujon/go/src/github.com/DataDog/system-tests-main/parametric/.venv/lib/python3.9/site-packages/_pytest/main.py", line 268, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/Users/bruce.bujon/go/src/github.com/DataDog/system-tests-main/parametric/.venv/lib/python3.9/site-packages/_pytest/main.py", line 321, in _main …
```

Fix parametric test run script

---

parametric/.gitignore
parametric/README.md

- Ignore the generated dockerfiles
- Rename the venv to match the name used by system-tests

Update parametric tests gitignore

---

utils/build/docker/dotnet/query-versions.fsx

From 1.15 we add unit tests to test specific versions of the waf with current tracer, and make sure it doesnt init with wrong waf version, so another param was added

Edit dotnet weblog script : add param to waf creation 

---

run.sh

The "Live Debugger" product has been renamed to "Dynamic Instrumentation", and as such, the opt-in configuration environment variable has been changed from DD_DEBUGGER_ENABLED to DD_DYNAMIC_INSTRUMENTATION_ENABLED.
This change has already been applied to the relevant tracers (Java, Python, and .NET), this PR also updated the relevant system tests.

Rename DD_DEBUGGER_ENABLED to DD_DYNAMIC_INSTRUMENTATION_ENABLED

---

tests/appsec/test_reports.py

Simple update of tests to switch from actor.ip to http.client_ip as we wish to fully migrate to http.client_ip in the long run to stay consistent with APM.

APPSEC-5847 - Migrate tests to test presence and value of http.client_ip

---

parametric/README.md
parametric/conftest.py
parametric/run.sh
parametric/test_library_tracestats.py
parametric/test_span_sampling.py

Before, all test cases needed to use an all_libs() decorator to specify running the test against all the libraries. Now the server factory fixture is parametrized out to run with all the libraries by default.

parametric: run all libraries by default

---

parametric/README.md
parametric/apps/dotnet/Dockerfile
parametric/apps/golang/Dockerfile
parametric/apps/python/Dockerfile
parametric/conftest.py

As requested per @Kyle-Verhoog, I created a dedicated PR from #504 to add the support for custom binaries for parametric tests.
- Build docker images from project root in order to access to /binaries.
- Update dockerfile copy paths.
- Clean up generated dockerfiles.

Add custom binaries support for parametric tests

---

parametric/conftest.py
parametric/test_trace_distributed.py
parametric/test_tracer.py

Group the logs into sections of the pytest report:
```
======================================================================== test session starts =========================================================================
platform darwin -- Python 3.9.11, pytest-7.1.3, pluggy-1.0.0
rootdir: /Users/kverhoog/dev/system-tests/parametric, configfile: conftest.py
plugins: ddtrace-1.4.4, json-report-1.2.1, metadata-2.0.2
collected 3 items / 2 deselected / 1 selected                                                                                                                        
test_tracer.py F                                                                                                                                               [100%] …
```

parametric: better log organization

---

parametric/run.sh
parametric/test_span_sampling.py

Before we used the setting of manual_drop to 1 in order to modulate the tracer's decision to keep or drop the span. However changing manual_drop doesn't effect the Go tracer (and possibly other tracer's) decision when setting the tag `_sampling_priority_v1` which is what  matters when making the decision to try single span sampling or not. Using `DD_TRACE_SAMPLE_RATE` to modulate the tracer's decision is more consistent across tracers and easier to understand.
I did keep the option to add manual_drop in the generate_span method, as it was the only option I know of to modulate trace sampling for Python during runtime which is necessary for sss011.

parametric: use DD_TRACE_SAMPLE_RATE in span sampling tests

---

parametric/conftest.py

Adds the `NODEJS_DDTRACE_MODULE` env var to configure parametric tests from Node.js with a given package identifier. This corrersponds to: https://github.com/DataDog/dd-trace-js/pull/2442/files#diff-3f74be22ab2d868e3d9812082a1635cdf9938e2f1eb18bb3abf4a899fd7837f1R88.

parametric: add env var to configure Node.js dd-trace module version

---

utils/interfaces/schemas/library/v0.7/config-request.json

Make the products field optional for the remote configuration client interface validation.
Some clients may not subscribe to any product and can thus omit this field.

utils/interface/schemas: make 'products' optional for RC client schema

---

utils/build/docker/java/jersey-grizzly2.Dockerfile
utils/build/docker/java/ratpack.Dockerfile
utils/build/docker/java/resteasy-netty3.Dockerfile
utils/build/docker/java/spring-boot-jetty.Dockerfile
utils/build/docker/java/spring-boot-undertow.Dockerfile
utils/build/docker/java/spring-boot.Dockerfile
utils/build/docker/java/vertx3.Dockerfile

Building a Java application is slow (fetching dependencies, compiling), while adding the library jar to the Docker image is fast, and possibly more frequent.
By moving the step of adding the library jar later in the process, we can still reuse most of the Docker build cache after changing to a different library jar, which is particularly useful for local testing.

Add Java library later in the Docker build process

---

docker-compose.yml

On linux, files created inside runner container has root as owner. It causes lot of issues.

Fix root ownership on files created inside containers #557

---

parametric/conftest.py

Before, no output would be displayed if the docker build command failed for a container
this is fixed by outputting the output so far

parametric: output docker build logs if command fails

---

scenarios/appsec/test_conf.py
tests/appsec/iast/test_iast.py
tests/appsec/test_traces.py
tests/appsec/waf/test_addresses.py
tests/test_telemetry.py

We have detected some XPASSED test in java@0.113.0
**Scenarios:** Default, UDS
**Weblog variant:** spring-boot, spring-boot-jetty
**Test:** tests/appsec/iast/test_iast.py::Test_Iast::test_insecure_hash_remove_duplicates
**Scenarios:** Default, UDS
**Weblog variant:** spring-boot, spring-boot-jetty, jersey-grizzly2, resteasy-netty3, ratpack, vertx3
**Tests:** 
- tests/test_telemetry.py::Test_Telemetry::test_app_started
- tests/test_telemetry.py::Test_Telemetry::test_proxy_forwarding 
- tests/test_telemetry.py::Test_Telemetry::test_telemetry_messages_valid
- tests/test_telemetry.py::Test_Telemetry::test_telemetry_proxy_enrichment
- tests/appsec/test_traces.py::Test_AppSecObfuscator::test_appsec_obfuscator_key
**Scenarios:** Default, UDS
**Weblog variant:** spring-boot
**Test:** …

Enable XPASSED tests detected in java@0.113.0

---

tests/test_telemetry.py

We have detected some XPASSED test in java@0.113.0
Scenarios: Default, UDS
Weblog variant: spring-boot, spring-boot-jetty, jersey-grizzly2, resteasy-netty3, ratpack, vertx3
Tests:
- tests/test_telemetry.py::Test_Telemetry::test_status_ok
- tests/test_telemetry.py::Test_Telemetry::test_app_started_sent_only_once
- tests/test_telemetry.py::Test_Telemetry::test_seq_id

Enable telemetry XPASSED tests detected in java@0.113.0

---

scenarios/appsec/test_traces.py
tests/appsec/test_traces.py

Reenable obfuscator tests on PHP.

Revert skipped obfuscator tests on PHP

---

scenarios/appsec/test_ip_blocking.py
utils/build/docker/java/spring-boot-jetty.Dockerfile
utils/build/docker/java/spring-boot-undertow.Dockerfile

This requires enabling remote config for these two variants. These flags will be removed once remote config is enabled by default.

Enable IP blocking tests for Java with Jetty and Undertow

---

scenarios/appsec/test_client_ip.py

Enable http.client_ip test when ASM is disabled on the release version of the tracer.

Enable http.client_ip test on ASM disabled

---

.github/workflows/ci.yml
tests/appsec/iast/test_iast.py
tests/appsec/test_reports.py
tests/appsec/test_traces.py
tests/appsec/waf/test_addresses.py
tests/appsec/waf/test_miscs.py
tests/appsec/waf/test_rules.py
tests/test_telemetry.py
utils/build/docker/java/spring-boot-openliberty.Dockerfile
utils/build/docker/java/spring-boot/pom.xml
utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/iast/utils/CryptoExamples.java
utils/build/docker/java/spring-boot/src/main/liberty/config/server.xml

- Add weblog-variant: spring-boot-openliberty
- Fix CryptoExamples doCypher method
- Marked as bug:
> tests/test_telemetry.py::Test_Telemetry::test_app_started_sent_only_once
> tests/test_telemetry.py::Test_Telemetry::test_seq_id
> tests/appsec/test_traces.py::Test_AppSecEventSpanTags::test_header_collection
> tests/appsec/waf/test_addresses.py::Test_BodyUrlEncoded::test_body_value
> tests/appsec/waf/test_addresses.py::Test_ResponseStatus::test_basic
> tests/appsec/waf/test_rules.py::Test_DiscoveryScan::test_security_scan
>tests.appsec.waf.test_miscs.Test_404.test_404
>tests.appsec.test_reports.Test_StatusCode.test_basic

Add OpenLiberty springboot app

---

tests/appsec/test_identify.py
tests/appsec/test_traces.py
tests/appsec/waf/test_reports.py
tests/test_identify.py

Reenable PHP tests disabled due to duplicate traces.

PHP reenable tests affected by duplicate traces

---

utils/build/docker/golang/install_ddtrace.sh

Allow parsing the appsec rules version from dd-trace-go/internal/appsec/rules.json.
This will allow dd-trace-go to use go:embed to embed the default rule files, see https://github.com/DataDog/dd-trace-go/pull/1573. After https://github.com/DataDog/dd-trace-go/pull/1573 is merged we can do a follow-up PR to remove the old rules version parsing (we need to keep it as is for now to allow https://github.com/DataDog/dd-trace-go/pull/1573 to go in).

go: parse appsec rules version from rules.json

---

utils/build/docker/golang/chi.Dockerfile
utils/build/docker/golang/echo.Dockerfile
utils/build/docker/golang/gin.Dockerfile
utils/build/docker/golang/gorilla.Dockerfile
utils/build/docker/golang/net-http.Dockerfile

Make sure jq is available in the Go weblog docker containers (needed for rules version parsing).

go: install jq in Docker envs

---

scenarios/remote_config/test_remote_configuration.py

Enable more remote config tests in Java.

Enable more remote config tests in Java

---

scenarios/appsec/test_ip_blocking.py

If DD_APPSEC_RULES is set, remote config subscriptions from appsec should not be made.

Disable ip blocking tests with custom ruleset

---

scenarios/appsec/test_client_ip.py
tests/test_standard_tags.py

Signed-off-by: Juanjo Alvarez <juanjo.alvarezmartinez@datadoghq.com>
Enable client ip tag that was implemented in 1.5.0

python: enable client_ip tags

---

utils/scripts/junit_report.py

When running a single test it was failing due to a missing entry in the docs dictionary:
```
runner           |   File "/app/conftest.py", line 440, in _pytest_junit_modifyreport
runner           |     junit_modifyreport(
runner           |   File "/app/utils/scripts/junit_report.py", line 35, in junit_modifyreport
runner           |     test_doc = _docs[nodeid]
runner           | KeyError: 'tests/appsec/iast/test_iast_sql_injection.py::TestIastSqlInjection::test_secure_sql'
```

Fix issue when running single test due to missing docs

---

docs/edit/lint.md
format.sh

Since setting up a virtualenv might be a hassle for some, and some users
have reported diffulties to get it installed correctly in their systems,
the script `format.sh` adds a simple way to run a dockerized black. The
only requisite is having Docker installed, and a Unix-like host (macOS
or Linux).

Add format.sh for easy black formatting

---

tests/appsec/iast/test_iast_command_injection.py
tests/appsec/iast/test_iast_path_traversal.py
tests/appsec/iast/test_iast_sql_injection.py
tests/appsec/iast/test_iast_weak_hash.py

java@1.1.0 supports SQL Injection, Command Injection, and Path Traversal. The enabled tests pass in master.

Enable new IAST tests for java 1.1.0

---

parametric/spec/trace.py
parametric/test_trace_distributed.py

The parametric tests failed with the recent update to the Python client to use the v0.5 agent endpoint by default instead of the v0.4 endpoint. Specifically, in situations with  invalid parent/span ids being provided with the v0.4 endpoint resulted in the parent id not being set at all. However with the v0.5 endpoint, the resulting span is now set with a parent id of 0, which is still fine (but fails the current test) since this denotes that the span does not have a parent. 
The test `test_distributed_headers_extract_datadog_invalid` was fixed to accept both results, as both are expected.

Fix parametric python tests for v05

---

parametric/apps/java/build.sh
parametric/apps/java/pom.xml
parametric/apps/java/run.sh
parametric/apps/java/src/main/java/com/datadoghq/ApmClientImpl.java
parametric/apps/java/src/main/java/com/datadoghq/App.java
parametric/apps/java/src/main/proto/apm_test_client.proto
parametric/conftest.py
parametric/test_library_tracestats.py
parametric/test_trace_distributed.py
parametric/test_tracer.py

Update Java client for `parametric tests`:
* Upgrade to new Trace/Span ID
* Use new flush traces/metrics API
* Update client protobuf (inject header not supported yet)
* Update java client test coverage (disable tests not supported yet)
* Add support for `dd-trace-ot` and `dd-trace-api` artifact from the custom `binaries` folder
Update tracer test to start agent before client (see f3ff519)

Update Java client for parametric tests

---

utils/build/docker/dotnet/Helper.cs

Adding support for sending custom tags when calling the `/spans` URL in the dotnet container.
[Related PR](https://github.com/DataDog/k9-appsec-testing-env/pull/23)

Send custom span tags in dotnet container

---

docs/execute/README.md
docs/execute/troubleshooting.md

I ran into issues when trying to run the tests, I didn't immediately notice there was an additional file called troubleshooting.md (it solved the issue for me). So adding a link to this page to make it easier to find / navigate from the github interface.

Add more links to make it easier to navigate docs

---

utils/build/docker/dotnet/Helper.cs

This reverts commit 58f4ff7330103f3bfec0cda2f2cb0c638156c7df.
It's not needed since we can make use of [DD_TAGS](https://docs.datadoghq.com/getting_started/tagging/assigning_tags/?tab=noncontainerizedenvironments#environment-variables)

Revert "Send custom span tags in dotnet container (#700)"

---

parametric/apps/nodejs/servicer.js

Disable dns plugin in parametric test, this is creating more spans than expected.
With some changes in dd-trace-js@2.x library, we have started to generate more spans related with dns. It generates extra `dns.lookup` span and causes the test fail, because it has 2 spans instead of expected one. 
With this change we are disabling `dns` plugin in the affected test to fix it, and be able to release 2.x version with success test results.

Disable dns in parametric test

---

utils/scripts/upload_results_CI_visibility.sh

Failure tolerance for CI results upload.
Sometimes when we try to download de CI Visibility script from github, service is not active and returns http 503. When this case happens, we won't upload results and we won't throw the failure, pipeline will continued....

CI Upload failure tolerance

---

.github/workflows/ci.yml

As we just released (yesterday 🎉 ) a version with the missing parts from the Java tracer to work properly with the parametric tests, here is finally the change to enable the Java client in parametric system tests during CI.
I ignored two new tests about SSS until fixed. I will reach @ygree about them. 

feat(parametric): Enable Java client in parametric

---

parametric/README.md
parametric/apps/dotnet/Program.cs
parametric/apps/golang/main.go
parametric/apps/java/src/main/java/com/datadoghq/App.java
parametric/apps/nodejs/server.js
parametric/apps/python/apm_test_client/__main__.py
parametric/conftest.py

Prior, the port 50051 was hardcoded in the Java and .NET servers.
The port 50051 can also conflict with multipass so the default is changed to 50052.
The port can also now be configured using the APM_GRPC_SERVER_PORT environment variable.
Thanks @Qard for finding out the issue with buildkit the hard-way.

parametric: parameterize, change default grpc server port

---

tests/appsec/iast/test_iast_command_injection.py
tests/appsec/iast/test_iast_sql_injection.py
tests/appsec/iast/test_iast_weak_hash.py

I disabled some test when we did some changes in the tracer related with the paths of the vulnerability.
In the last release dd-trace-js release, we have included that fixes and and activate included also others vulnerabilities detection. 
In that PR I am just updating the nodejs versions to production versions.

Activate again nodejs iast system test

---

tests/remote_config/test_remote_configuration.py

Mark remote config NoCache scenarios as irrelevant for Java.
These are only for tracers that do not implement caching.

Mark remote config NoCache scenarios as irrelevant for Java

---

utils/build/docker/dotnet/install_ddtrace.sh
utils/build/docker/dotnet/query-versions.fsx

Previously we relied on the C# library Datadog.Trace.dll for the version detection, this kept breaking as the library internals changed. To avoid these issues we now directly call the native waf library.

Simplfiy dotnet WAF version detection

---

tests/appsec/test_ip_blocking.py

- Enable ip blocking test for Go (except for uds-echo)

go: enable IP blocking test

---

tests/appsec/waf/test_addresses.py
tests/appsec/waf/test_reports.py
tests/appsec/waf/test_rules.py
utils/build/docker/ruby/install_ddtrace.sh

Some test where passing with XPASS, but they were enable for ruby.
The changes include:
- Updated test to acccount for the ruby library
- Make sure we are using the lastest version of dd-trace-rb for images
The PR doesn't enable all ruby test. 
There are some ruby tests that require a little bit of more work. I'm going to take the time to enable them in subsequent PRs

Update test for ruby ASM library

---

parametric/apps/nodejs/server.js
parametric/apps/nodejs/servicer.js
parametric/test_headers_b3.py
parametric/test_headers_b3multi.py
parametric/test_headers_datadog.py
parametric/test_headers_none.py
parametric/test_headers_precedence.py
parametric/test_headers_tracecontext.py
parametric/test_headers_tracestate_dd.py

Enables the w3c trace context parametric tests started in #691. A bunch of them are not working yet, so I've only enabled the ones passing currently. I'll continue work on the PR to Node.js to get the last few things passing.

Enable parametric w3c trace context tests for Node.js

---

tests/test_standard_tags.py

Enable the `http.client_ip` standard tag test for Go.

go: enable standard tag http.client_ip test

---

.github/CODEOWNERS

Add remote-config team as co-codeowners of the RC tests

[RCM] Add RC to codeowners

---

tests/remote_config/test_remote_configuration.py

This change marks the RC NOCACHE scenarios as irrelevant for Go since caching is implemented.

go: mark NOCACHE scenarios as irrelevant for RC testing

---

tests/appsec/test_runtime_activation.py

APPSEC_RUNTIME_ACTIVATION is failing on Java 1.6.0. See https://github.com/DataDog/dd-trace-java/pull/4614

Fix failing test on java 1.6.0

---

tests/remote_config/test_remote_configuration.py

Increase the library timeout for all RC tests due to flakiness caused by the polling interval of 5 seconds.

Increase timeout for all libraries in RC tests

---

tests/test_semantic_conventions.py

Adding version tags to some newly added metadata tag tests for Ruby and some other tracers that recently had tags added.

add version released tags for ruby to new metadata tag tests

---

tests/appsec/blocking_rule.json
tests/appsec/waf/test_blocking.py
utils/_weblog.py

This PR specifies custom actions as a result of a WAF trigger.
All tracers with support for blocking requests include a builtin action `block`. The `block` action interrupts an HTTP request and returns an HTTP response with status code `403` and a body corresponding to the request `accept` header.
A tracer may be instructed to trigger a custom action, to block using a different HTTP status code or redirect to a given URL for instance. Two tests are introduced in this PR to test those cases.

[ASM] Custom blocking response

---

tests/appsec/test_reports.py

Skipping flaky test to unblock https://github.com/DataDog/system-tests-apps-ruby/pull/11
CI will still be broken because we first need to merge the PR above so we can deploy new images for ruby apps 

mark flaky test for rails 3.2 and rails 4.0

---

tests/test_standard_tags.py

test_multiple_matching_substring was failing due to dotnet string truncation for performance reasons

[ASM] Fix test_multiple_matching_substring test for dotnet

---

tests/appsec/test_client_ip.py
tests/appsec/test_traces.py
tests/appsec/waf/test_addresses.py
tests/test_miscs.py
tests/test_standard_tags.py

Enable ruby tests for already released features.
This change goes in coordination with the addition of new endpoint to the ruby tests apps https://github.com/DataDog/system-tests-apps-ruby/pull/6
A part from enabling new tests I also added some test metadata on certain standard tags tests. 

Enable ruby test for already released features

---

utils/interfaces/schemas/library/telemetry/proxy/api/v2/apmtelemetry-request.json

Add missing types to the Telemetry API JSON schema according to: [generate-metrics](https://github.com/DataDog/instrumentation-telemetry-api-docs/blob/main/GeneratedDocumentation/ApiDocs/v1/producing-telemetry.md#generate-metrics)

Add missing types for metrics

---

tests/appsec/test_ip_blocking.py
tests/appsec/test_runtime_activation.py
tests/appsec/waf/test_blocking.py

Some tests had been disabled, but they invariably pass locally. Opened PR to investigate further.

Reenable ip blocking tests on java

---

utils/build/docker/dotnet/query-versions.fsx

We need to extract the waf's version to execute the system tests.
Older wafs <=1.3.0 were giving a struct to give the version, more recent ones a string for the version.
Test per version and get the version the adapted way
[Jira item](https://datadoghq.atlassian.net/browse/APPSEC-8040)

Find version for older wafs

---

tests/appsec/waf/test_exclusions.py

Graalvm only supports tracing. Exclude from WAF tests

Fix: Missing feature for GraalVm on WAF tests

---

run.sh
tests/apm-tracing-e2e/test_smoke.py
utils/interfaces/_backend.py

This change fixes the `backend` interface and adds a smoke test that verifies that we can submit traces, and fetch them from the backend.
I added some useful helpers to wait until the trace is ready as well, to keep the actual tests' code simple.
During a discussion with Charles last week, we decided to introduce a new scenario (`APM_TRACING_E2E`), until the fully end-to-end (e2e) tests are ready for adoption. And since these tests will take longer to run due to querying the actual backend, we don't want to run them in any other scenario unexpectedly.
```
lambros.petrou@COMP-F371T7QC44 system-tests % ./run.sh APM_TRACING_E2E
============ Run APM_TRACING_E2E tests ===================
ℹ️  Log folder is ./logs_apm_tracing_e2e
Starting containers in background
[+] Running 5/5
⠿ Network …
```

Successfully running a smoke test that exercises the full e2e APM tracing pipeline

---

tests/test_semantic_conventions.py

Two features were not yet implemented prior to 2.6:
- process_id tag
- language meta tag
which makkes CI on older version of tracers fail: 
See 4th [attempt](https://github.com/DataDog/appsec-event-rules/actions/runs/4012188888/jobs/7163561116)

Tests on old tracer failing because of some features werent implemented yet

---

tests/appsec/test_runtime_activation.py
tests/remote_config/test_remote_configuration.py

Version 1.8.0 of the agent should subscribe ASM_FEATURES even with a custom rules file present. This enables two tests that were disabled because of the previous behavior.

Enable ASM_FEATURES w/ custom rules for java 1.8.0

---

lib-injection/build/docker/dotnet/config-1.yaml
lib-injection/build/docker/dotnet/config-disabled.yaml
lib-injection/build/docker/dotnet/config-mismatch-clustername.yaml
lib-injection/build/docker/dotnet/config.yaml
lib-injection/build/docker/dotnet/dd-lib-dotnet-init-test-app/Dockerfile
lib-injection/build/docker/dotnet/dd-lib-dotnet-init-test-app/MinimalWebApp.csproj
lib-injection/build/docker/dotnet/dd-lib-dotnet-init-test-app/Program.cs
lib-injection/build/docker/dotnet/dd-lib-dotnet-init-test-app/appsettings.json
lib-injection/build/docker/dotnet/dd-lib-dotnet-init-test-app/build.sh
lib-injection/build/docker/dotnet/install_ddtrace.sh
lib-injection/build/docker/dotnet/values-override.yaml

Adds a test application and setup so we can test the .NET Tracer in the lib-injection test suite. I've tested this dev branch by invoking it from a dev branch of `dd-trace-dotnet` and the tests are up and running correctly

Add dotnet lib-injection test app

---

parametric/apps/java/pom.xml

If one changed the java binaries for the parametric tests, by adding an `dd-trace-api` jar file to the `binaries` folder, the app could no longer find all classes, due to the typo, and would fail to start with the following exception:
```
Exception in thread "main" java.lang.NoClassDefFoundError: datadog/trace/api/Tracer
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
at …
```

Fix typo in Java build file for adding external binaries to class path

---

docs/weblog/README.md
tests/apm_tracing_e2e/test_single_span.py
utils/build/docker/golang/app/chi.go
utils/build/docker/golang/app/common.go
utils/interfaces/_backend.py

For the single spans tests, we need to either set a [retention filter](https://docs.datadoghq.com/tracing/trace_pipeline/trace_retention/#retention-filters) that will index the single spans submitted, or we need to use Driveline live search to fetch the spans for assertion.
Using the Live-search API is still not supported, and we don't know when it will be.
Also, since creating manual retention filters in every org/account we want to run these tests is cumbersome, this change manually adds the tags that will force the indexing of these spans, in a similar way to how retention filters work.
The org I use with `DD_SITE=datadoghq.com` does NOT have a retention filter setup for the test spans, and with this change the tests still pass!
```sh
DD_SITE=datadoghq.com …
```

[apm] manually index spans without manual retention filter

---

tests/appsec/test_reports.py

Currently and for some reasons (dependency changes?) `self.r.raw._connection.sock` on the IP Django system test was returning `None` which was breaking all Django system tests. 
This changes it so we don't use a private-ish struct but instead retrieve the IP by doing:
```
s = socket.fromfd(self.r.raw.fileno(), socket.AF_INET, socket.SOCK_STREAM)
self.actual_remote_ip = s.getsockname()[0]
```
which seems to fix the issue. 
4. Mark it as ready …

fix: retrieve IP in a more reliable way for Python IP tests

---

parametric/apps/java/build.sh
parametric/apps/java/pom.xml
parametric/conftest.py

Fix regression introduced by #899 where protobuf file is not included within docker image during build.

Fix parametric Java client docker build

---

utils/build/docker/java/jersey-grizzly2.Dockerfile
utils/build/docker/java/ratpack.Dockerfile
utils/build/docker/java/resteasy-netty3.Dockerfile
utils/build/docker/java/spring-boot-jetty.Dockerfile
utils/build/docker/java/spring-boot-openliberty.Dockerfile
utils/build/docker/java/spring-boot-undertow.Dockerfile
utils/build/docker/java/spring-boot-wildfly.Dockerfile
utils/build/docker/java/spring-boot.Dockerfile
utils/build/docker/java/uds-spring-boot.Dockerfile
utils/build/docker/java/vertx3.Dockerfile

Update Docker images for Java to Temurin 11
AdoptOpenJDK images are deprecated and not updated anymore.

Update Docker images for Java to Temurin 11

---

binaries/agent-image
utils/_context/core.py

```sh
DD_SITE=datadoghq.com ./run.sh APM_TRACING_E2E
```

fix the APM_TRACING_E2E scenario missing after migration of run.sh

---

.github/workflows/parametric.yml
parametric/apps/java/pom.xml
parametric/apps/java/src/main/java/com/datadoghq/ApmClientImpl.java
parametric/test_headers_b3.py
parametric/test_headers_b3multi.py
parametric/test_headers_datadog.py
parametric/test_headers_precedence.py
parametric/test_headers_tracecontext.py
parametric/test_headers_tracestate_dd.py
parametric/utils/headers.py
utils/scripts/generate-github-action-file.py

Fix some bugs in the Java parametric test server and mark all unsupported tests as skipped. Enable java in the parametric GitHub workflow.
Once your PR is reviewed, …

Enable Java parametric tests in workflow

---

tests/remote_config/test_remote_configuration.py

update RC gunicorn behavior. Gunicorn creates 2 process (main gunicorn process + X child workers). It generates two payloads for each request number
Once your PR is …

feat(python): update RC gunicorn behavior

---

tests/appsec/test_event_tracking.py
utils/build/docker/java/ratpack/src/main/java/com/datadoghq/ratpack/Main.java

* Enable Event Tracking tests in Java.
* Fix Event Tracking call in Ratpack weblog variant.

Enable Event Tracking tests in Java

---

parametric/apps/nodejs/servicer.js
parametric/test_span_sampling.py

Depends on #848
Depends on DataDog/dd-trace-js#2779
This will enable the new single span ingestion tests for Node.js, when it's ready.

Enable nodejs single span ingestion tests

---

tests/test_standard_tags.py

We have fixed the bug with the Client-IP resolution for ruby.
The PR that fixes it is: https://github.com/DataDog/dd-trace-rb/pull/2665
On the next release, the test should execute and pass. I tested locally to validate that assumption.

Enable Client-IP test for ruby. The test would work on the next release.

---

utils/scripts/load-binary.sh

We recently changed the job name where the library jar is attached, so it broke nightlies.

Fix load_binary.sh for Java

---

tests/test_standard_tags.py

Enable `Client-IP` test for ruby

update ruby version to the one that fixed the client IP extraction logic

---

utils/interfaces/schemas/miscs/telemetry/v2/telemetry_request.json

The json schema for v2 instrumentation telemetry expected every request to have `request_type` equal to `app-client-configuration-change` and `app-product-change` because of missing `if...then...` logic, causing schema validation to fail. This PR adds the `if...then...` logic for these two request types into the schema. 
> **_NOTE:_**  By default in PR only default scenario tests will be launched. Please refer to …

Fix v2 instrumentation telemetry json schema

---

tests/appsec/waf/test_exclusions.py
tests/appsec/waf/test_miscs.py

Enabling some more tests on PHP, specifically exclusion filter tests and a no-timeout WAF test.

Enable exclusion and no waf timeout tests

---

tests/appsec/test_event_tracking.py

`re.fullmatch(r"spring-.+native", context.weblog_variant)` returns `None` if it's not a match. Calling `@irrelevant` with `None` is like calling it without any argument, and thus, flag the test as irrelevant.
This PR simply replace `re.fullmatch()` by `re.fullmatch() is not None`.
> **_NOTE:_**  By default in PR only default scenario tests will be launched. Please refer to the …

Fix skip condition on spring*native

---

tests/test_telemetry.py

This test is too flaky to be included as it in default scenario
And also skipping a telemetry test on .NET

Disable telemetry flaky test

---

utils/_context/_scenarios.py
utils/interfaces/_backend.py
utils/interfaces/_core.py
utils/proxy/core.py

In a similar way to how we log every tracer/agent request and response, this PR integrates `mitmproxy` with the requests we make to the backend API during tests (e.g. fetching traces/spans) in order to allow for easier debugging and troubleshooting.
It will also allow both `DD_APP_KEY` and `DD_APPLICATION_KEY`.
- ATI-2553
```
./run.sh APM_TRACING_E2E_SINGLE_SPAN
...
runner  | tests/apm_tracing_e2e/test_single_span.py ..                                                                     [100%]
runner  | 
runner  | ------------------------------------ generated xml file: /app/logs/reportJunit.xml -------------------------------------
runner  | ========================================== 2 passed, 304 deselected in 30.81s ========================================== …
```

Use mitmproxy for the backend requests

---

parametric/test_headers_datadog.py
parametric/test_headers_tracestate_dd.py

* Changes origin tests to allow splitting the origin at the first `,` which is the Java behavior since it is impossible to distinguish between a single header with `,` in it and multiple headers combined with `,` in some web frameworks.
* Splits out the tests that override the sampling decision via the `traceparent` and _keeps_ or resets the decision maker
> **_NOTE:_**  By default in PR only default scenario …

Fixes for w3c test parametric tests

---

parametric/test_span_sampling.py

These got added after PHP tests were merged and are failing PHP now.

Skip PHP on newly added span sampling tests

---

utils/build/build.sh
utils/build/docker/dotnet/install_ddtrace.sh

This change adds the ability to include a binary file in the binaries files. The binary file can be a URL (by using `--binary-url` parameter) or a path to a local directory (by using `--binary-path`). Once the binary file is included, it will be copied to the binaries directory. Both parameters are optional, and don't change default behaviour.
This change modifies the install_ddtrace.sh shell script to accept not only an archived file but also a directory. 
Additionally, the script is modified to check `.dll` from the assembly version instead of relying solely on the filename.

Add binary path support

---

parametric/apps/java/pom.xml
parametric/test_headers_b3.py
parametric/test_headers_b3multi.py
parametric/test_headers_datadog.py
parametric/test_headers_precedence.py
parametric/test_headers_tracecontext.py
parametric/test_headers_tracestate_dd.py

Enable W3C tests for released Java Library v1.11.0

Enable W3C tests for released Java Library v1.11.0

---

tests/test_telemetry.py

Enable Tracer Telemetry test for Ruby.
This support has been merged for a while, but Ruby didn't get parametric system tests until recently.
One fix was needed for the Ruby Tracer (https://github.com/DataDog/dd-trace-rb/pull/2710), but this PR can be merged as is with the `@bug` tag for that specific fix.
Tests will still run, but report as `XPASS` when succeeded. If failed, they won't break the build.
> …

Enable Ruby Telemetry tests

---

parametric/apps/dotnet/ApmTestClient.csproj
parametric/apps/dotnet/Program.cs
parametric/apps/dotnet/Services/ApmTestClientService.cs
parametric/test_headers_tracecontext.py
parametric/test_headers_tracestate_dd.py

Combined with https://github.com/DataDog/system-tests/pull/954, this PR will allow the .NET Tracer to run (and pass) all the W3C tracecontext tests in the parametric test suite. Changes in this PR include:
- Run all of the tracestate tests for .NET (except for the newly added DecisionMaker resetting tests that will be covered in a follow-up PR)
- Make the header lookup case-insensitive for the .NET service
- Run the case-insensitive header tests for .NET
This PR cannot be merged until https://github.com/DataDog/dd-trace-dotnet/pull/3873 is merged and published.
2. Follows the style guidelines of this project (See [how to easily lint the code](https://github.com/DataDog/system-tests/blob/main/docs/edit …

[parametric] Fix remaining dotnet w3c tracecontext header tests

---

tests/appsec/waf/test_miscs.py

Add a test checking that the case_sensitive setting of crs-933-131 is properly parsed

ASM - Add a test for boolean options in WAF rules

---

tests/test_library_conf.py

Test that checks that the tracer uses `DD_TRACE_HEADER_TAGS` to tag root spans.
This test was failing for dotnet, as the test checked all web spans, it should only check root entry spans. The test has been corrected.
> **_NOTE:_**  By default in PR only default scenario tests will be launched. Please refer to the [documentation](https://datadoghq.atlassian.net/wiki/spaces/APMINT/pages/2866381467/CI+Workflow+Github+ …

[dotnet library] activate headers tag config test

---

tests/appsec/iast/sink/test_iast_sql_injection.py
tests/appsec/iast/sink/test_iast_weak_hash.py

Fixes the python tracer version required for some iast tests

chore(python): update tracer version in iast tests

---

tests/appsec/blocking_rule.json
tests/appsec/test_blocking_addresses.py
tests/appsec/waf/test_blocking.py
utils/build/docker/dotnet/Models/Model.cs

Activates the blocking tests that are currently working for the .NET library.

[dotnet library] Active some blocking tests

---

utils/build/build.sh

This enables producing images with inline cache, as well as passing cache args as extra docker args in a consistent way.
It also makes all build cases consistent, reducing the potential for buildkit vs no buildkit discrepancies.
> **_NOTE:_**  By default in PR only default scenario tests will be launched. Please refer to the [documentation](https://datadoghq.atlassian.net/wiki/spaces/APMINT/pages/2866381467/CI+Work …

Use buildx throughout

---

parametric/test_otel_span_methods.py

`test_otel_get_span_context` is currently broken. It asserts that `child_span.trace_id == parent_span.span_id`. Instead we should check if `child_span.trace_id == parent_span.trace_id`. 
> **_NOTE:_**  By default in PR only default scenario tests will be launched. Please refer to the [documentation](https://datadoghq.atlassian.net/wiki/spaces/APMINT/pages/2866381467/CI+Workflow+Github+Actions) to run all scenarios …

fix(parametric-test): update test_otel_get_span_context

---

parametric/test_otel_span_methods.py

Increases the test coverage of setting attributes on opentelemetry spans. 
- Ensures sequences of integers, booleans, strings, and floating point can be set as Span attributes ([spec](https://opentelemetry.io/docs/reference/specification/common/#attribute))

paramteric(otel): update set attributes test

---

tests/test_telemetry.py

The only feature not supported is `DD_FORCE_BATCHING_ENABLE`, thus its test is disabled.

Ruby:Enable test for all supported telemetry features

---

tests/appsec/iast/sink/test_iast_sql_injection.py
tests/appsec/iast/sink/test_iast_weak_hash.py

Removes misleading trailing slash from IAST vulnerability reports

chore(python): remove misleading trailing slash from vulnerability path

---

parametric/apps/dotnet/ApmTestClient.csproj
parametric/test_headers_tracestate_dd.py

Unskip the dotnet test case that resets dm to DEFAULT. This requires a new release of Datadog.Trace, so the NuGet package update for the .NET Tracer is included in this commit as well. This means that dotnet will now pass all header tests in the parametric test suite 🎉 
> **_NOTE:_**  By default in PR only default scenario tests will be launched. Please refer to the …

[parametric] For dotnet, unskip the dotnet test case that tests the decision maker reset

---

tests/appsec/test_blocking_addresses.py

Add 10 test classes for suspicious request blocking for automatic detection of features in the appsec library dashboard.
- 7 test classes for each request address
- 2 test classes for each response address
-  1 test class for combinations and corner cases
All tests are currently empty
> **_NOTE:_**  By default in PR only default scenario tests will be launched. Please refer to the …

add suspicious requests tests

---

parametric/run.sh

This should simplify setting the right python version in various scenarios, like having a system-wide Python 3.9 in Ubuntu, or having pyenv with multiple Python versions.
Related: https://github.com/DataDog/dd-trace-java/pull/5068
> **_NOTE:_**  By default in PR only default scenario tests will be launched. Please refer to the [documentation](https://datadoghq.atlassian.net/wiki/spaces/APMINT/pages/2866381467/CI+Wo …

parametric: use python3.9 binary if available

---

parametric/run.sh

Revert "parametric: use python3.9 binary if available (#1073)"
This reverts commit 85e6f1a7b66f866550fa7bc27c8b231256db34f1.
It caused build issues in at least 1 local development environment. We have a workaround at dd-trace-java CI anyway.
> **_NOTE:_**  By default in PR only default scenario tests will be launched. Please refer to the [documentation](https://datadoghq.atlassian.net/wiki/spaces/APMINT/pages/28663 …

Revert "parametric: use python3.9 binary if available (#1073)"

---

tests/test_telemetry.py

The tests in this PR were skipped due to a bug in the agent that was fixed in version 7.41.
It should be safe to remove the skips.
Once your PR is reviewed, you can …

[Telemetry] Unskip tests that should no longer be flaky

---

requirements.txt
run.sh
shell.nix
utils/_context/containers.py
utils/build/build.sh

- Improve nix environment
- Fix docker client connection when using `DOCKER_HOST` env var
- Allow docker connection over `DOCKER_HOST=ssh://`
This DOES NOT fix reaching to the various docker services exposed ports, which need do be accessed using the external IP of where Docker is hosted (in my case a VM). This IP is the one present in `DOCKER_HOST`.
There are theoretically two cases:
- `runner` (outside VM) reaching to `agent` (inside VM) and `weblog` (inside VM), notably for health check
This needs the VM IP. `DOCKER_HOST` contains it in my case.
- weblog (inside VM) reaching to runner's proxy (IIUC outside VM)
This needs the host IP on the VM network. it should be the TCP client IP that a listening process running in the VM sees as a peer.
<details>
<summary>List of references to …

Improve nix environment

---

parametric/test_otel_span_methods.py

`parametric/test_otel_span_methods.py:test_otel_set_attributes_different_types` raises the following error:
`TypeError: otel_start_span() missing required argument 'new_root`
`new_root` was removed  in the following PR: https://github.com/DataDog/system-tests/pull/1062

parametric(otel): fix TypeError raised in test_otel_set_attributes_different_types 

---

utils/build/docker/dotnet/uds.Dockerfile
utils/build/docker/golang/uds-echo.Dockerfile
utils/build/docker/java/uds-spring-boot.Dockerfile
utils/build/docker/python/uds-flask.Dockerfile
utils/build/docker/set-system-tests-weblog-env.Dockerfile

apt-get update executed on all weblog was breaking some of them. It was needed to install socat, which is usefull only for uds weblog -> moved it to only UDS weblogs

Move  apt-get install socat to uds weblog

---

utils/_context/containers.py
utils/build/docker/python/flask-poc.Dockerfile
utils/build/docker/python/uds-flask.Dockerfile
utils/build/docker/python/uwsgi-poc.Dockerfile

The latest version of flask released yesterday removed some decorators. see https://flask.palletsprojects.com/en/2.3.x/changes/#version-2-3-0: 
> The app.before_first_request and bp.before_app_first_request decorators are removed.
It make the tracer break the app : 
```
File "/usr/local/lib/python3.9/site-packages/ddtrace/vendor/wrapt/wrappers.py", line 804, in lookup_attribute
return getattr(parent, attribute)
AttributeError: type object 'Flask' has no attribute 'before_first_request'
```
Pin the flask version for now, waiting a fix from the tracer.

Tracer does not support latest version of flask

---

conftest.py
utils/_context/_scenarios.py
utils/_weblog.py

Show requests/response in log on failure 

---

tests/test_telemetry.py

Skips an irrelevant test. Sending application dependencies is supported for the python client.
Currently dependencies are only submitted in the `app-started` event. Moving forward dependencies will not be sent in `app-started`. This data will only be sent in the `app-dependencies-loaded`  event. This change was made to support telemetry v2.
Unblocks: https://github.com/DataDog/dd-trace-py/pull/5740

telemetry(python): skip irrelevant app-dependencies-loaded validation

---

tests/appsec/waf/test_telemetry.py
utils/_context/_scenarios.py
utils/_weblog.py

Expand WAF telemetry tests:
* Test payload headers separately.
* Add a test for each metric.
* Previous tests did not test every WAF metric.
* They did not ensure that all metrics were present (e.g. the test would success with 0 metrics).
Depends on:
* https://github.com/DataDog/dd-trace-java/pull/5105
* https://github.com/DataDog/dd-trace-java/pull/5111
* https://github.com/DataDog/dd-trace-java/pull/5113
Future work:
* Check that timestamps in metric points are correctly defined in seconds.

Expand WAF telemetry tests

---

parametric/apps/dotnet/ApmTestClient.csproj
parametric/test_128_bit_traceids.py

Stop skipping dotnet tests for 128-bit trace ids.
Support for 128-bit trace ids was added [dotnet tracer library version 2.30.0](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v2.30.0).
See https://github.com/DataDog/dd-trace-dotnet/pull/3744.
We still skip the following tests because dotnet does not implement these _optional_ features:
```
test_datadog_128_bit_propagation_tid_malformed_optional_tag
test_w3c_128_bit_propagation_tid_inconsistent_optional_tag
test_w3c_128_bit_propagation_tid_malformed_optional_tag
```

[parametric/dotnet] don't skip 128-bit trace id tests

---

tests/test_miscs.py

This remove the library versions decorator for the Test_Basic class as it's testing the weblog app, not the library. Hence having a library version makes no sense.

Remove library versions for Test_Basic

---

parametric/test_headers_tracestate_dd.py

Fix a parametric test for propagation headers. When both Datadog and W3C headers are enabled, the test compares the propagated tags in `x-datadog-tags` and `tracestate` and expects them to be the same. However, the `_dd.p.tid` tag used for 128-bit trace ids is not added to `tracestate`, since `traceparent` already contains the full 128-bit trace id.
The test started failing for .NET when we updated to tracer 2.30 in #1101 which added support for 128-bit trace ids. 
It is still not clear if adding `t.tid` to `tracestate` is optional or if we should require that it is never added. For now the test allows for either no `t.tid`, or that its value matches `_dd.p.tid`.

[parametric] fix test, don't require "t.tid" in "tracestate" W3C header

---

.github/workflows/ci.yml
tests/otel_tracing_e2e/_validator.py
tests/otel_tracing_e2e/test_e2e.py
utils/_context/_scenarios.py
utils/build/docker/java_otel/spring-boot-native/src/main/java/com/datadoghq/springbootnative/App.java
utils/build/docker/java_otel/spring-boot-native/src/main/java/com/datadoghq/springbootnative/WebController.java

Allow to choose which path to include (agent, collector or intake) in OTel E2E test instead of always running them all. Also some refactor on `java_otel` weblog container.

[opentelemetry] Allow to configure which path to include

---

.github/workflows/ci.yml
.gitignore
conftest.py
tests/appsec/test_blocking_addresses.py
tests/appsec/test_logs.py
tests/fuzzer/main.py
tests/integrations/test_dsm.py
tests/test_the_test/test_stdout_reader.py
utils/_context/_scenarios.py
utils/_context/containers.py
utils/_weblog.py
utils/interfaces/_backend.py
utils/interfaces/_core.py
utils/interfaces/_logs.py

See #1093
Will run tests only using an existing log folder.
`./run.sh --replay`
* speed up iteration when writing tests
* allow debugging
* replay tests based on CI artifact

Add a mode that replay tests based on logs

---

tests/appsec/waf/test_custom_rules.py
tests/appsec/waf/test_exclusions.py

activate two more tests for python tracer for custom rules testing:
- Test_CustomRules
- Test_Exclusions

activate more tests for custom rules on python

---

.github/CODEOWNERS

Add tracer teams as owners of weblog variants

---

utils/build/docker/nodejs/express4/app.js

This PR removes the hardcoded IAST configuration to be able to use the environment variables to configure it.
People is using this application to do other test, and it is easier to activate/deactivate it if we can just change the environment var value.

Remove iast conf from node test application to use env vars

---

tests/appsec/blocking_rule.json
tests/appsec/test_blocking_addresses.py

Add a rule to block on uri raw address that starts with `http` and check that this rule is not used to block on the uri raw value (as it should never be prefixed with the base URL)
Also add a missing_feature tag for a non implemented test.

improve suspicious request blocking test on uri raw

---

parametric/test_128_bit_traceids.py

This test is currently broken on main for dd-trace-go. There is a pull request [here](https://github.com/DataDog/dd-trace-go/pull/1969/commits/738be7379c11aea0e88a214f73abbbbc926fe08a) to fix it, but to unblock merging for now we'll skip until that's ready to merge 
unblock dd-trace-go PRs

Skip broken 128 test for golang until fix is merged there

---

tests/appsec/test_blocking_addresses.py

After fixing uri.raw address in python tracer [PR6005](https://github.com/DataDog/dd-trace-py/commit/a89569af53781ffd8b89ae64994989d657f88194) update the system tests for that feature to the next release version.

update python version number for srb uri.raw tests

---

tests/parametric/conftest.py
utils/build/docker/java/parametric/Dockerfile
utils/build/docker/java/parametric/run.sh

Upgrades the JVM version that runs the parametric tests for better container support (and hopefully faster startup). Also adds some startup flags that disable unnecessary components.
Slow startup is slow, and parametric tests starts a new JVM for every test.
> **_NOTE:_**  By default in PR only default scenario tests will be launched. Temove `run-default-scenario` label to run all scenarios ([more info](https://datadoghq.atlassian.net/wiki/spaces/APMINT/pages/2866381467/C …

Upgrade java version for parametric tests

---

.gitignore
tests/parametric/conftest.py
utils/build/docker/dotnet/parametric/.dockerignore
utils/build/docker/dotnet/parametric/.gitignore
utils/build/docker/dotnet/parametric/ApmTestClient.csproj
utils/build/docker/dotnet/parametric/Dockerfile
utils/build/docker/dotnet/parametric/Program.cs
utils/build/docker/dotnet/parametric/Protos/apm_test_client.proto
utils/build/docker/dotnet/parametric/Services/ApmTestClientService.cs

This PR is a redo of #1144 after files related to parametric tests were moved around. What follows is a copy of that PR's description:
This PR makes some updates to the .NET app used for parametrics tests:
~https://github.com/DataDog/system-tests/tree/main/parametric/apps/dotnet~
https://github.com/DataDog/system-tests/tree/main/utils/build/docker/dotnet/parametric/
- update nuget package references to latest versions
- enable automatic instrumentation (not used yet, but required for OTel test endpoints coming soon)
- change `Datadog.Trace` nuget package to `Datadog.Trace.Bundle`
- add required environment variables
- allow running app without env var `APM_TEST_CLIENT_SERVER_PORT` (easier to run as a stand-alone app)
- misc code clean-up
- added `.gitignore` and `.dockerignore` files …

[parametric/dotnet] prepare auto-instrumentation and other code clean-up, redux

---

.vscode/launch.json
.vscode/settings.json

Enable the VsCode testing integrations. #1084 
Two way to run them : 
1. threw the `run and debug` panel
* works on normal mode
* you can choose your scenario
* it runs all tests
2.  threw the Testing panel. VsCode does not allow several confs for this panel, so, by default, it's DEFAULT scenario on replay mode:  
* you need to manually edit `.vscode/settings.json` to change the scenario, or run on normal mode
* but you can pick only one test
Easily run and debug a tests
4. Follows the style guidelines of this project (See [how to easily lint the code](https://github.com/DataDog/system-tests/blob/main/docs/edit/lint.md))
5. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore it)
6. Mark it as ready for review …

Add vscode conf to run and debug default scenario

---

run.sh

Add -p no:warnings for set of scenarios

---

utils/build/docker/php/parametric/install.sh

The initial support for parametric tests was created with a fixed artifact to have tests pass, which is expired by now.

Update php install URL to latest

---

parametric/test_span_sampling.py
tests/parametric/conftest.py

Waits for a number of spans instead of a number of traces in some single span sampling scenarios.
In Java the single sampled spans are sent to a different queue than the rest of the trace spans, and depending on timing they might end up in the same or different trace chunks. This leads to intermittent failures if we only wait for a specific number of traces instead of spans. 
> **_NOTE:_**  By default in PR only default scenario tests will be launched. Temove …

Parametric tests wait for number of spans instead of traces

---

tests/appsec/waf/test_addresses.py

activate Test_Headers in` tests/appsec/waf/test_addresses.py` for python. The feature is supported for a long time but was not covered.

activate test headers in appsec waf for Python

---

tests/appsec/test_user_blocking_full_denylist.py
utils/build/docker/ruby/rack/config.ru
utils/build/docker/ruby/rails32/app/controllers/system_test_controller.rb
utils/build/docker/ruby/rails32/config/routes.rb
utils/build/docker/ruby/rails40/app/controllers/system_test_controller.rb
utils/build/docker/ruby/rails40/config/routes.rb
utils/build/docker/ruby/rails41/app/controllers/system_test_controller.rb
utils/build/docker/ruby/rails41/config/routes.rb
utils/build/docker/ruby/rails42/app/controllers/system_test_controller.rb
utils/build/docker/ruby/rails42/config/routes.rb
utils/build/docker/ruby/rails50/app/controllers/system_test_controller.rb
utils/build/docker/ruby/rails50/config/routes.rb
utils/build/docker/ruby/rails51/app/controllers/system_test_controller.rb
utils/build/docker/ruby/rails51/config/routes.rb
utils/build/docker/ruby/rails52/app/controllers/system_test_controller.rb
utils/build/docker/ruby/rails52/config/routes.rb
utils/build/docker/ruby/rails60/app/controllers/system_test_controller.rb
utils/build/docker/ruby/rails60/config/routes.rb
utils/build/docker/ruby/rails61/app/controllers/system_test_controller.rb
utils/build/docker/ruby/rails61/config/routes.rb
utils/build/docker/ruby/rails70/app/controllers/system_test_controller.rb
utils/build/docker/ruby/rails70/config/routes.rb
utils/build/docker/ruby/sinatra14/app.rb
utils/build/docker/ruby/sinatra20/app.rb
utils/build/docker/ruby/sinatra21/app.rb

Enable user blocking ruby specs

[APPSEC-9344] Enable user blocking tests for ruby

---

tests/appsec/waf/test_blocking.py
tests/appsec/waf/test_custom_rules.py
tests/appsec/waf/test_exclusions.py

[APPSEC-9344] Enable specs for released features for Ruby

---

tests/appsec/test_reports.py

Remove old decorators for Ruby. The test doesn't work for any language at the moment, but having the flaky decorators makes the report think Ruby has a bug 🐛 

cleanup old decorators

---

tests/appsec/test_blocking_addresses.py

Blocking before is still flaky in java.
Also reduces a little bit of python magic.

Skip a flaky feature in java

---

.github/pull_request_template.md

Fix minor typo in PR template.

Fix typo in pull_request_template.md

---

parametric/run.sh

Fix issue `./run.sh: line 12: CLIENTS_ENABLED: unbound variable` as using `set -u` where running `./run.sh` as stated by the README.
Remove shell error.

Minor shell fix

---

conftest.py
docs/edit/egg-chicken-changes.md
docs/execute/force-execute.md

See the documentation  
Ease the egg-chicken issue

Add a way to force a test execution #913

---

tests/appsec/iast/sink/test_no_httponly_cookie.py
tests/appsec/iast/sink/test_no_samesite_cookie.py
utils/build/docker/nodejs/express4/iast/index.js

This PR adds test to cookies related vulnerability detections that the libraries are working on. 
As insecure-cookie is in production already in node, it is also activated with the correct version number.
Once your PR is reviewed, …

Add test for no HttpOnly cookie and no SameSite cookie

---

utils/_context/_scenarios.py
utils/interfaces/_core.py
utils/proxy/core.py

Lot of issue using the default OS dependant notifiers : 
* not working on WSL
*  reaching some inotify watcher limits on Linux
-> using the good old bare polling system
Stability
Once your PR is reviewed, you can merge it! …

Fix watchdog issues

---

run.sh

Enable concurrent execution of parametric tests again.
Running all the tests sequentially takes way to long.

Make parametric tests concurrent again

---

tests/appsec/iast/sink/test_unvalidated_redirect.py
tests/appsec/iast/sink/test_unvalidated_redirect_forward.py
utils/build/docker/java/vertx3/src/main/java/com/datadoghq/vertx3/iast/routes/IastSinkRouteProvider.java
utils/build/docker/java/vertx4/src/main/java/com/datadoghq/vertx4/iast/routes/IastSinkRouteProvider.java

- Add vertx3 unvalidated redirect endpoints
- Add vertx4 unvalidated redirect endpoints
- Enable xpassed tests for java unvalidated redirect
Test unvalidated redirect vulnerability
Some test are enabled for next version (1.17.0)

Add IAST unvalidated redirect vertx enpoints

---

tests/parametric/test_span_sampling.py

It is difficult to be very accurate when we specify one or two request per second span sampling rate limit

Reduce flakiness on span sampling tests.

---

utils/_context/_scenarios.py
utils/_context/virtual_machines.py

Import pulumi only when it's really needed.
First exception caught and formatted by pytest in a test triggers a bunch of pulumi initialization (presumably from their lazy import logic), dominating the execution time in replay mode.
On my machine, replaying the default scenario takes ~8s. After this change, <4s. The change is proportionally much bigger when running single tests  (e.g. from several seconds to sub-second).
Here's a flamegraph before this change, where ~62% of the samples are in pytest's `repr_traceback`, and whose breakdown goes almost entirely to initialization of various pulumi modules.
3. …

Late pulumi import: improve pytest performance

---

.github/workflows/experimental.yml
lib-injection/README.md
lib-injection/runner/action.yml
lib-injection/src/test/shell/functions.sh

Log outputs for experimental tests.
Currently the "auto lib-injection" tests are failing, but we can't access to the logs.
I removed the calls to the "print-debug-info" from inside the scripts.
I think we don't need to call this method from other functions:
- When something fails, in most cases we do not get to execute the "print-debug-info" function, because the execution of the script is aborted.
- Multiple calls from different locations messes up the code a bit.
Added the existence of this method to the documentation.
Added the call to this method "always" after launch the tests
Currently the "auto lib-injection" tests are failing, but we can't access to the logs.
2. Follow the style guidelines of this project (See [how to easily lint the …

Logs for experimental tests (lib-injection)

---

.github/workflows/experimental.yml

The job is disabled, but I replace the reference to my branch and change it by main.
When we enable again, the reference will be ok.

fix reference auto lib-injection 

---

tests/test_telemetry.py

Fix tests so that they test:
* app-started is sent at least once (not properly checked before if there were telemetry messages but not app-started messages).
* app-started is sent exactly once.
* app-started is the first telemetry message.
Mark Ruby and Python as bugged in some cases.

Extend telemetry app-started tests

---

tests/appsec/test_rate_limiter.py

This test is flaky on rails 5.1, see ticket APPSEC-10303

Skip Appsec rate limiter test on rails 5.1

---

tests/appsec/iast/sink/test_xpath_injection.py
utils/build/docker/java/akka-http/src/main/scala/com/datadoghq/akka_http/IastRoutes.scala
utils/build/docker/java/iast-common/src/main/java/com/datadoghq/system_tests/iast/utils/XPathExamples.java
utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/IastSinkResource.java
utils/build/docker/java/resteasy-netty3/src/main/java/com/datadoghq/resteasy/IastSinkResource.java
utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/AppSecIast.java
utils/build/docker/java/vertx3/src/main/java/com/datadoghq/vertx3/iast/routes/IastSinkRouteProvider.java
utils/build/docker/java/vertx4/src/main/java/com/datadoghq/vertx4/iast/routes/IastSinkRouteProvider.java

- Add XPath injection tests 
- Add Java XPath injection enpoints in:
- spring-boot
- resteasy-netty3
- jersey-grizzly2
- vertx3
- vertx4
- akka
Test XPath vulnerability
Some test are enabled for next dd-java-agent version (1.17.0)

Add IAST XPath injection system test

---

utils/build/docker/python/django-poc.Dockerfile
utils/build/docker/python/django-poc.base.Dockerfile
utils/build/docker/python/flask-poc.Dockerfile
utils/build/docker/python/flask-poc.base.Dockerfile
utils/build/docker/python/uds-flask.Dockerfile
utils/build/docker/python/uwsgi-poc.Dockerfile
utils/build/docker/python/uwsgi-poc.base.Dockerfile

* Use python-slim as base image
* use pre-build base image for python weblogs
See #562
Build time ! 

Optimize python build time 

---

utils/build/build.sh

When running build.sh, users will often inadvertedly get a build with an old agent that was pulled previously. This can lead to surprising differences with CI. Always pull bases when building.

Always pull agent and weblog bases on build

---

utils/_context/containers.py

Depending on the umask settings (e.g. umask 0007), the otel conf path might be set without read permissions by other users. Since we bind mount this file into a Docker container, and the user within the container is different from the one in the host, the file requires permission to read by other users. Force it when needed before starting the container.

Fix /etc/otelcol-config.yml perms in Linux

---

docs/execute/e2e.md

Fix typo and formatting of the E2E tests documentation.
I tried to add some E2E tests…

Improve E2E tests documentation

---

utils/build/docker/agent.Dockerfile

Revert some optimizations to agent build, too much trouble, see https://github.com/DataDog/system-tests/issues/1349
For further context, see:
* https://github.com/DataDog/system-tests/pull/1299
* https://github.com/DataDog/system-tests/pull/1340

Restore support for arm64

---

tests/test_telemetry.py

Increase the delta when the test is checking that heartbeat interval is not executed too fast. 
This line added few days ago has become a source of a flakyness in dd-trace-js. If the first request needs a bit more time than second to send the heartbeat, the test will fail. 

Increase heartbeat interval check delta

---

tests/test_the_test/test_json_report.py
tests/test_the_test/test_stdout_reader.py
utils/_context/_scenarios.py

Incorrect generation of json report could cause problems in system-tests-dashboard due to we are parsing the report. This PR adds a new test to validate it.
To generate the report we have to launch a new scenario "mock_the_test".This scenario is launched programatically executing ./run.sh MOCK_THE_TEST
Incorrect generation of json report could cause problems in system-tests-dashboard due to we are parsing the report.

Test the test: Validate json report generation

---

tests/apm_tracing_e2e/test_otel.py

Skip  Test_Otel_Span.test_distributed_otel_trace, because its currently very flaky (probably backend issue ?) https://github.com/DataDog/system-tests/actions/runs/5473868372/jobs/9968033513?pr=1366
No flaky test

Skip flaky open-telemetry test

---

.github/pull_request_template.md
.github/workflows/ci.yml
docs/edit/update-docker-images.md

Recent performance improvement used some pre-build images on hub.docker.com
It lack a process to update those images. For reliability reason, we'll keep the push process manual (AFAIK, there is no way to protect an image from overwrite on docker.com, and we absolutely do not want a rogue PR overwrite an used image).
But appart from that very last manual push, this process will make the update possible during a PR.
Ease the process of updating pre-build images
Once your PR …

Process to update images on hub.docker.com

---

utils/parametric/spec/trace.py

Makes the checks on the spans returned from `find_span` stricter.
The `find_*` methods are to loose and can return unexpected Spans/Traces.
Some tests failed intermittently on Java on non helpful asserts, and when debugging this, it was discovered that some traces where split into two chunks, and the `child` span we thought we got back was actually the `parent` span once more. None of the tests seem to expect anything other than a _strict_ match, but the original methods are available as `find_similar*`.
3. Work on you PR until the CI passes (if something not related to your task is failing, you can ignore …

Make find_span in parametric tests stricter

---

tests/appsec/test_automated_login_events.py

Activate auto instrumentation of user events in extended mode configured for dotnet
Had to adapt the main classes as 
- dotnet login oob doesnt have a login field (framework design, username matters)
- sdk was using a different naming that we cant break (already having customers using it)
- when user is found with wrong password, we report his user id and not the name in usr.id field

[dotnet] Activate user extended mode 

---

.gitlab-ci.yml
tests/onboarding/infra_provision/provision_onboarding_container.yml
tests/onboarding/infra_provision/provision_onboarding_host.yml

Enable stable version tests for onboarding

Onboarding enable "prod" environment tests

---

utils/build/docker/golang/parametric/datadog.go
utils/build/docker/golang/parametric/main.go
utils/build/docker/golang/parametric/otel.go

This concerns only GO tracer. Fixes, an issue where setup for OTel tests causes test failures for non-otel tests

[GO] parametric: separated tracer initialisation for datadog and otel tests

---

tests/appsec/waf/test_blocking.py

Enable custom blocking response test for Go.

go: enable custom blocking response test

---

utils/build/docker/nodejs/express4-typescript/auth.ts
utils/build/docker/nodejs/express4/auth.js
utils/build/docker/nodejs/express4/iast/index.js

When authentication returns an error, the nodejs application is broken because `next` method is not in `handleAuthentication` methods, in this PR we are fixing it.
Some PR builds fails and release process is stopped. 

Fix nodejs system-test

---

tests/test_telemetry.py

app started should be sent only once, but if answer is 503 (lot of unstability on telemetry backend those days), it should be resent.
Fix flakyness

Fix check on telemetry app started only once

---

lib-injection/src/test/resources/dd-apm-test-agent-config.yaml
tests/parametric/conftest.py

Update test agent configuration to opt into checks
As of the latest image, test agent checks have been change to opt-in. See https://github.com/DataDog/dd-apm-test-agent/blob/3833182b3d864d93c41550ab645c47af8fd855eb/releasenotes/notes/Checks-changed-to-opt-in-8716cac4ecdbb1c2.yaml
2. just before merging, locally build and push the …

Update test agent configuration

---

tests/test_schemas.py

With last dev agent (image on `docker.io/datadog/agent-dev:master-py3`), `DD_APPSEC_RULESET` set on the tracer, and the last dev tracer on python, an error happen on schema validation : https://github.com/DataDog/system-tests/actions/runs/5534817039/jobs/10100298061#step:14:186 
2. just before merging, locally build and push the …

Allow an error with last dev agent on python

---

utils/scripts/load-binary.sh

Pin dev agent image while things get resolved
`dev` test cases [started failing tonight](https://github.com/DataDog/system-tests/actions/runs/5538435351):
- `docker.io/datadog/agent-dev:master-py3@sha256:a50aee313c362a30429fc6948aeb1f63925fd43ba7c67fe9fb68a3a83c694040` worked
- `docker.io/datadog/agent-dev:master-py3@sha256:ae0937801ae912dd13afa8411e2f7128846e1cbddda86811a3e979c84af38eb7` failed
* if any of …

Mitigate agent failure on dev tests

---

utils/_context/containers.py

Previous OTel collector healthcheck endpoint is `localhost:13133`, that will introduce problems when running the tests in CI (in docker images). While `0.0.0.0:13133` works in both local tests and CI jobs.

Fix OTel collector healthcheck endpoint

---

tests/README.md
tests/parametric/README.md
tests/parametric/test_128_bit_traceids.py
tests/parametric/test_headers_b3multi.py
tests/parametric/test_headers_datadog.py
tests/parametric/test_headers_precedence.py
tests/parametric/test_headers_tracecontext.py
tests/parametric/test_headers_tracestate_dd.py
tests/parametric/test_span_sampling.py
utils/build/docker/cpp/parametric/tracing_service.cpp

Recent changes to [dd-trace-cpp][1] have made it more compatible with some of the parametric tests in this repository. Specifically, tests involving:
- 128-bit trace IDs
- trace propagation, with the exception of the "B3 single header" style.
This revision removes "cpp" exemptions from many tests, which now pass. Some of the tests for which "cpp" is still exempt now have updated descriptions. For example, it is still an open question (at least until Zach Montoya returns) how `_dd.p.dm` propagation should be handled in certain cases. Also, whether dd-trace-cpp should support the B3 single header propagation style, which has not been requested by any users of the C++ tracer and which is largely superseded by the similar W3C propagation style. Those questions we can address later.
See the …

cpp: pass more parametric tests

---

tests/appsec/waf/test_telemetry.py
tests/test_telemetry.py
utils/interfaces/_agent.py
utils/interfaces/_library/core.py

Add support for v2 telemetry `message-batch` payloads by "flattening" the batch into multiple requests. Not all tests require this, but many do.
The telemetry tests commonly assert for particular message types, but when you use `message-batch`, the messages are nested inside the payload. So instead of this:
```json
{
"request": {
"content": {
"api_version": "v1",
"request_type": "app-started",
"payload": {}
}
}
},
{
"request": {
"content": {
"api_version": "v1",
"request_type": "app-dependencies-loaded",
"payload": {}
}
}
```
you have something like this:
```json
{
"request": {
"content": {
"api_version": "v2",
"request_type": "message-batch",
"payload": [
{
"request_type": "app-started",
"payload": {}
},
{
"request_type": "app-dependencies-loaded",
"payload": {}
}
]
}
}
}
```
To handle …

Add support for message-batch (v2) payloads

---

tests/appsec/test_blocking_addresses.py
tests/appsec/waf/test_addresses.py
tests/appsec/waf/test_blocking.py
tests/appsec/waf/test_custom_rules.py
tests/appsec/waf/test_exclusions.py

Activate those tests : 
* appsec-blocking_addresses-blocking_request_body
* appsec-blocking_addresses-blocking_request_cookies
* appsec-blocking_addresses-blocking_request_headers
* appsec-blocking_addresses-blocking_request_method
* appsec-blocking_addresses-blocking_request_path_params
* appsec-blocking_addresses-blocking_request_query
* appsec-blocking_addresses-blocking_request_uri
* appsec-blocking_addresses-blocking_response_headers
* appsec-blocking_addresses-blocking_response_status
* appsec-waf-custom_rules-customrules
* appsec-waf-exclusions-exclusio
They are all XPASS
I set the prod version of the tracer `1.16.1`, but they may be working prior to that version.
2. Follow the style guidelines of this project (See [how to easily lint the …

Activate APPSEC Xpass tests

---

run.sh

Fix pycache clearing.
`-prune` appears to be useless, unless (or even if) someone expects a `__pycache__` folder to be nested.
@cbeauchesne reported that this occcured:
```
rm: cannot remove 'tests/parametric/__pycache__': Directory not empty
```
Possible causes:
- The `find` command attempted to delete things before the directory was entirely cleared out (but there's `-rf` on `rm`)
- Something regenerated pycache files while it was being recursively removed
- Something created nested files that could not be removed (e.g due to permissions):
- A typical candidate would be a container with that path exposed as a volume, but the users within (root) and outside (regular user) are in mismatch, so the generated files and folders are not writable, thus not removable
- `ProxyContainer` does that …

Fix pycache clearing

---

docs/edit/manifest.md

This PR will be used for the very first iteration of manifest file.
The goal is to provide a alternative way to declare versions, using one file per components.

RFC: manifest file

---

tests/appsec/test_blocking_addresses.py
utils/build/docker/python/flask/app.py

Remove default log level to DEBUG in flask application
Since merge of https://github.com/DataDog/system-tests/pull/1426 some tests using python tracer with flask-poc were failing non deterministically. It seems that default log level to debug can generate too much data and prevent some requests to have their responses caught by the tests.

remove log level to debug in flask application

---

utils/interfaces/_core.py

We are introducing proper `DD_TRACE_HEADER_TAGS` support in `dd-trace-rb` (https://github.com/DataDog/dd-trace-rb/pull/2935) and it trips a few appsec system-tests.
The issue happens because we tag non-service entry spans with `DD_TRACE_HEADER_TAGS`, but those tags are used to find the request id (`rid`) by system-tests to perform assertions.
It is likely very uncommon to set HTTP serve `DD_TRACE_HEADER_TAGS` tags in non-service entry spans, but it's the current state of the Ruby tracer. We should likely change this, and stop tagging Sinatra spans with `DD_TRACE_HEADER_TAGS`, but that's a breaking change for our clients and won't happen in the short term.
Disabling test until this change happens in the Ruby tracer is also not a great approach, because that would mean disabling a large set …

Prevent finding rid in non-service entry spans

---

.github/workflows/ci.yml
run.sh
shell.nix

In contexts where we run, `perl` is available with `YAML` module. Use that instead of `python` to read `yml`.
This PR also introduce:
- a verbosity control flag
- a dry run flag
Both being very useful for debugging the `run.sh` script.
The need for `activate_venv` in #1427 is caused by `pyyaml` being needed byt not being available as a default.
It's a bit early to activate the virtualenv in some scenarios, and in others, activating the venv is potentially harmful (e.g when there is no need for a venv). …

Fix yaml parsing

---

utils/interfaces/_library/core.py

Fixes a bug in the `messag-bach` support previously implemented in #1411
The condition is the wrong way round 🤦‍♂️ 

Fix bug in telemetry `message-batch` support

---

tests/parametric/conftest.py
tests/parametric/test_tracer.py
utils/_context/_scenarios.py

As per title add version detection. This enables parametric tests to reuse the `@released` decorator used by other system tests.
It works by retrieving the real tracer version from the library being tested by reading the http headers of requests made to the test agent.
This enables tests to be merged prior to the release of a feature.
A more accurate approach is proposed in #1445

Add library version detection for parametric tests

---

tests/appsec/iast/sink/test_insecure_cookie.py
tests/appsec/iast/sink/test_no_httponly_cookie.py
tests/appsec/iast/sink/test_no_samesite_cookie.py
utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/IastSinkResource.java
utils/build/docker/java/resteasy-netty3/src/main/java/com/datadoghq/resteasy/IastSinkResource.java
utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/AppSecIast.java
utils/build/docker/java/vertx3/src/main/java/com/datadoghq/vertx3/iast/routes/IastSinkRouteProvider.java
utils/build/docker/java/vertx4/src/main/java/com/datadoghq/vertx4/iast/routes/IastSinkRouteProvider.java

Replace HttpOnly=true with HttpOnly in the vulnerability tests for HttpOnly Cookie
HttpOnly is meant to be used as a flag, not as name value pair

replace HttpOnly=true with HttpOnly

---

utils/interfaces/_backend.py

When we hit the rate limit (HTTP 429), retry after the time specified in the response. This does not count toward the number of retries based on other criteria.
Example of failed job: https://github.com/DataDog/system-tests/actions/runs/5733958512/job/15539438714 …

Retry when hitting backend API rate limit

---

utils/build/docker/java/iast-common/src/main/java/com/datadoghq/system_tests/iast/utils/CryptoExamples.java

A simple change in Cryptoexamples so only one weak cipher vulnerability is reported. Before the change two of them were reported.
We are adding instrumentation to KeyGenerator and this resulted in two vulnerabilities being reported in this example where we had one before. This confuses the vulnerability parser.
2. just before …

Changed example so it only generates one vulnerability

---

utils/build/docker/java/spring-boot-payara.Dockerfile

See https://docs.hazelcast.com/hazelcast/lat/phone-homes These call home calls can fail, leading to confusing errors in the logs and extra spans.

[Java][Payara] Disable Hazelcast's phone home

---

utils/interfaces/_core.py

Fix getting `rid` from user-agent for cpp tracer.
It uses http_user_agent attribute.

Fix getting `rid` from user-agent for cpp tracer

---

tests/test_telemetry.py
utils/build/docker/dotnet/poc.Dockerfile
utils/build/docker/dotnet/uds.Dockerfile

Unskips some .NET telemetry tests
Enable the v2 implementation in .NET build images
These tests are now passing for .NET (when v2 telemetry is enabled)

Un-skip .NET telemetry tests

---

.github/workflows/ci.yml
tests/test_telemetry.py

GraalVM variant has it's own workflow part, making the management of scenario a pain. And what should happen happened, we missed some of them.
This PR reintegrate GraalVM in the base job, skipping not relevant scenario, and remove the dedicated part.
It also add some skip for test that fails due to the new set of run (nodejs / telemetry_app_started_products_disabled) for instance.
Less error prone, easier to maintan
1. …

Merge graalVM in base matrix

---

utils/_context/containers.py

Cleaner logs.
Before:
```
08:08:13.947 DEBUG    Healthcheck #12: ExecResult(exit_code=7, output=b'  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\ncurl: (7) Failed to connect to localhost port 7777 after 0 ms: Connection refused\n')
08:08:24.943 DEBUG    Healthcheck #13: ExecResult(exit_code=22, output=b'  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\n                                 Dload  Upload   Total   Spent    Left  Speed\n\r  0     0    0     0    0     0      0      0 --:--:-- …
```

Less verbose curl health checks

---

tests/test_telemetry.py

The telemetry heartbeat check validate the `2s` interval between every heartbeat payload.
Depending on the tracer, the very first heartbeat may be sent in a request that pays the connection initialization time. This time is very unpredictible, so we remove the very first heartbeat from the list.
Reduce flakyness …

Reduce flakyness in .NET telemetry check

---

utils/build/docker/golang/app/go.mod
utils/build/docker/golang/chi.Dockerfile
utils/build/docker/golang/echo.Dockerfile
utils/build/docker/golang/gin.Dockerfile
utils/build/docker/golang/install_ddtrace.sh
utils/build/docker/golang/net-http.Dockerfile
utils/build/docker/golang/uds-echo.Dockerfile

- Upgrade golang weblog to 1.20 from a mix of 1.18 (golang) and 1.17 (gomod)
- Change dockerfile command orders to downlaod apt and golang packages first. These steps are now cached even if the tracer version or the app code is changed.
Speed up the local dev experience. Bonus points if it makes our CI a bit faster. …

Upgrade golang to 1.20 and optimize dockerfile caching

---

tests/parametric/test_headers_b3.py
tests/parametric/test_headers_b3multi.py
tests/parametric/test_headers_datadog.py
tests/parametric/test_headers_none.py
tests/parametric/test_headers_precedence.py
tests/parametric/test_headers_tracecontext.py
tests/parametric/test_headers_tracestate_dd.py
utils/build/docker/ruby/parametric/generate_proto.sh
utils/build/docker/ruby/parametric/server.rb

Unskip Ruby tests and update the skip message for tests that are still failing with the latest Ruby release. Changes include:
- Update of Ruby parametric web server app
- Change header propagation tests to use `DD_TRACE_PROPAGATION_STYLE_EXTRACT` and `DD_TRACE_PROPAGATION_STYLE_INJECT` configuration variables so Ruby can run them
- Add secondary test scenarios:
- "Single key" where the `DD_TRACE_PROPAGATION_STYLE` configuration variable is used
- "Case insensitive" where the value of the propagation variable is mixed case
- Add duplicate set of b3single tests where the tracer understands `b3`==`B3 single header`
- 
At first the goal was to run the `tracecontext` parametric tests, but in the end we ended up running more tests and fixing them so that they now pass for the Ruby tracer.
1. …

[parametric] Unskip Ruby parametric tests

---

utils/_context/containers.py
utils/_weblog.py

- Add docker host other protocols
- ... and actually extract only the host, ignoring the dockerd port
- Ignore protocols that don't make sense to find host/ip in, falling back to `localhost`, overridable by `env SYSTEM_TESTS_WEBLOG_HOST=something`
The previously implemented attempt was merely replacing a prefix matching the ssh protocol.
As reported by @LotharSee this failed e.g when using `colima` which sets a `unix://` link to the socket, and tried to stuff that in the weblog URL:
```
Request SKVRAMWGIWEOGZULCINYCOSOVOZPPLPKOHEE raise an error: HTTPSConnectionPool(host='unix', port=443): Max retries exceeded with url: /Users/benjamin/.colima/docker.sock:7777/sample_rate_route/1 (Caused by SSLError(CertificateError("hostname 'unix' doesn't match either of '*.us1.something.something', …
```

Add docker host other protocols

---

tests/appsec/iast/sink/test_trust_boundary_violation.py

Skip TrustBoundaryViolation for java tracer
It was supposed to be working for `1.19` tracer, it is not : https://github.com/DataDog/system-tests-dashboard/actions/runs/5805070456/job/15735639467#step:12:213

Skip TrustBoundaryViolation for java

---

tests/test_standard_tags.py
utils/build/docker/golang/app/net-http.go

Fix `/sample_rate_route/{i}` route in Golang `net/http`.
Golang `net/http` doesn't support parametrized requests so all tests in SAMPLING were hitting 404, but were hidden because of poor error handling (problem I'll address in another PR).
This change fixes the endpoint, and added the endpoint to `Test_StandardTagsRoute::test_route`. 
While working on another PR to improve SAMPLING tests, I was using `net/http` variant for local testing, and it revealed this bug.
Once …

Fix net/http sample_rate_route endpoint

---

tests/appsec/waf/test_telemetry.py

Include optional telemetry metrics and distributions tags
`APPSEC_WAF_TELEMETRY` tests fail in nodejs because `version` and `lib_version` tags are included in the telemetry metrics and distributions payloads

Allow other tags to be present in the telemetry metrics and distributions payload

---

tests/parametric/test_library_tracestats.py
utils/build/docker/golang/parametric/go.mod
utils/build/docker/golang/parametric/go.sum

Make sure client-stats computation is aligned with the spec in the Go tracer - https://github.com/DataDog/dd-trace-go/pull/2168

tests/parametric: align Go with client-stats spec

---

tests/appsec/iast/sink/test_insecure_cookie.py
tests/appsec/iast/sink/test_no_httponly_cookie.py
tests/appsec/iast/sink/test_no_samesite_cookie.py
tests/appsec/iast/source/test_parameter_value.py

Some IAST tests were supposed to be ok for `1.18` python tracer. They are not. Skipping them as missing feature.

Remove 1.18 for some IAST test on python

---

tests/apm_tracing_e2e/test_otel.py
utils/_context/_scenarios.py
utils/build/docker/java/spring-boot.Dockerfile
utils/build/docker/java/spring-boot/pom.xml
utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/App.java

Implement OTel smoke tests in Java spring-boot default library.
Get smoke tests covered for OTel GA.

Implement OTel smoke tests in Java library

---

tests/otel_tracing_e2e/test_e2e.py
tests/test_the_test/test_stdout_reader.py
utils/_context/_scenarios.py
utils/interfaces/_agent.py
utils/interfaces/_backend.py
utils/interfaces/_core.py
utils/interfaces/_library/_utils.py
utils/interfaces/_library/core.py
utils/interfaces/_logs.py
utils/interfaces/_open_telemetry.py
utils/tools.py

Lot of code in InterfaceValidator is only used by proxy based interface (library, agent, backend), leading to lot of distorsion in client code.
* splitting this feature in a based dedicated class
* cleaning some code that do not belong to interface
Clean code and designs

Refactor Interface object

---

conftest.py
utils/_context/_scenarios.py
utils/tools.py

Access to stdout in pytest is restricted, and a dedicated object (terminal) is used. Provide an access to this object with two methods : 
* `logger.stdout(message)`, simple method
* `logger.terminal` for direct access to more features
`logger` is accessible with `from utils.tools import logger`

Provide an universal way to send message to stdout

---

utils/_context/_scenarios.py
utils/_context/containers.py

Make the log collection automatic before removing a container
Simplify code

Refactor log collection

---

utils/_context/_scenarios.py
utils/_context/containers.py

Each container handles and feed its stdout interface
Pave the way for DB stdout interfaces

Automate stdout interface with their container

---

utils/build/docker/java/iast-common/src/main/java/com/datadoghq/system_tests/iast/utils/CryptoExamples.java

Change CryptoExamples so it generates a single vulnerability for weak cipher as opposed to two
Avoid cases where two vulnerabilities are reported on the same endpoint.

Change test so it only generates one weak cipher vulnerability

---

tests/test_sampling_rates.py
utils/interfaces/_library/core.py

- Remove unused `uniqueness_exceptions` variable
- Simplify `get_sampling_decision` function signature
- Disable Ruby tests, given that `/sample_rate_route/*` isn't implemented in any of the Rails nor Sinatra app.
Commits can be reviewed independently.
I'm working on adding additional sampling tests cases to the suite. I'm starting with preliminary minor cleanups before opening PRs with the new logic.
1. is the image …

Cleanup sampling test cases

---

utils/build/docker/dotnet/Controllers/LoginController.cs
utils/build/docker/dotnet/Controllers/TagValueController.cs
utils/build/docker/dotnet/Controllers/UsersController.cs
utils/build/docker/dotnet/Endpoints/EventTrackingSdkEndPoint.cs
utils/build/docker/dotnet/app.csproj

`EventTrackingSdk` and `UserDetails` didnt exist respectively before 2.23 see https://github.com/DataDog/dd-trace-dotnet/pull/3703 and 2.7 see https://github.com/DataDog/dd-trace-dotnet/pull/2546
The ruleset ci testing older tracer versions fails: https://github.com/DataDog/appsec-event-rules/pull/162

[ASM] Fix dotnet CI for older tracers

---

tests/appsec/custom_rules_with_errors.json

Waf 1.13.0, with current custom rules with error ruleset, gives:
`   Exception: unexpected span tag _dd.appsec.event_rules.errors value: got {'rule has no valid conditions': ['missing-tags', 'missing-name']} instead of {"missing key 'name'": ['missing-name'], "missing key 'tags'": ['missing-tags']}` on test `test_waf_monitoring_errors` 
It's because from 1.13, there are checks for rules without conditions. With valid conditions, the other errors are now visible.
Error on [dotnet ci pipeline ](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=142794&view=logs&j=db9fa4c5-7955-555f-a768-e4035391ef90&t=7d5d711c-4a8f-5e4b-8411-167d1ffbaddc) when integrating waf 1.13 (confirmed with Anil)
2. Follow the style guidelines of this project (See …

Add conditions to custom rules with errors for waf 1.13

---

tests/otel_tracing_e2e/_test_validator_log.py
tests/otel_tracing_e2e/_test_validator_trace.py
tests/otel_tracing_e2e/test_e2e.py
utils/interfaces/_backend.py

Fix OTel log and tracing e2e test.

Fix OTel e2e test

---

tests/appsec/test_automated_login_events.py

Enable automated user login events for ruby in production

enable automated user login events for ruby in production

---

tests/parametric/test_partial_flushing.py

Adding `missing_feature` for `nodejs` to `test_partial_flushing_disabled` in parametric tests.
`dd-trace-js` doesn't currently support `DD_TRACE_PARTIAL_FLUSH_ENABLED`. Thus, even though we do support partial flushing via `DD_TRACE_PARTIAL_FLUSH_MIN_SPANS`, this test is still flaky in our CI. We'll plan to add support for it, but for now need to skip it for our library.
2. just …

Skip Partial Flushing Disabled Test for Node.js

---

.github/CODEOWNERS

Fix codeowners for manifests

---

tests/test_the_test/test_scenario_decorator.py
utils/_context/_scenarios.py

Raise an error if two scenario are declared for a test/class

---

tests/test_telemetry.py
utils/build/docker/php/apache-mod/entrypoint.sh
utils/build/docker/php/php-fpm/entrypoint.sh

The tracer extension now launches a sidecar process which is contained within `ddtrace.so`. Once apache / fpm forked, the tracer couldn't open `ddtrace.so` due to invalid permissions of the root directory, which didn't allow read or execute for others. This in turn resulted in timeouts, however the predictable nature of the timeouts is unclear.
2. just before merging, locally …

Fix extension path permissions

---

tests/appsec/iast/_test_iast_fixtures.py
tests/appsec/test_conf.py
tests/appsec/test_traces.py
utils/interfaces/_agent.py
utils/interfaces/_library/core.py
utils/interfaces/schemas/library/v0.4/misc/trace-item.json
utils/proxy/_deserializer.py
utils/tools.py

appsec & iast data are json-strings in meta tag. They are currently deserialized at test level. This PR modify this to deserialize them in the deserializer, in order to have easier logs to read.

Deserilize appsec tags in deserializer

---

tests/appsec/waf/test_reports.py

This test is failing on ruby/main

Skip failing test on ruby on appsec_rules_monitoring_with_errors scenario

---

conftest.py
utils/_decorators.py

By running `./run.sh --collect-only`, it will produce a valid `logs/manifest.yaml` that can be copy paste in manifest file for the relevant tracer (the one that would have been run in `run.sh`).
Helping migrate all `@released` decorators, otherwise, it will never be done.

Add a helper to build manifest files

---

tests/appsec/waf/test_reports.py

Found the issue for why the test was failing for ruby. 
We can merge this PR once this [PR](https://github.com/DataDog/dd-trace-rb/pull/3106) is merged 

Fix a bug with ASM span tags reporting the number of WAF failed loaded rules

---

.github/workflows/ci.yml

Temporary fix: always use dev PHP tracer, as released PHP extension does not works with prod tracer.

Temporary fix: always use dev PHP tracer

---

lib-injection/README.md
lib-injection/runner/action.yml

* Add back missing debug logs for datadog-cluster-agent status and pod description.
* Improve doc to run lib-injection tests locally.
Following #1317 datadog-cluster-agent status and pod description were missing from debug logs because USE_ADMISSION_CONTROLLER env variable  was not set when calling print-debug-info. …

Improve doc and debug logs for lib-injection tests

---

tests/appsec/test_blocking_addresses.py
tests/appsec/waf/test_blocking.py
tests/test_standard_tags.py
utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/App.java

The scenario APPSEC_BLOCKING was using a rule that block any request with a **response** header `content-language=en-US`. Turns out that `spring-boot-openliberty` adds this header by default, blocking the healthcheck...

Fixing APPSEC_BLOCKING scenario

---

docs/weblog/README.md
manifests/cpp.yml
manifests/dotnet.yml
manifests/golang.yml
manifests/java.yml
manifests/nodejs.yml
manifests/php.yml
manifests/python.yml
manifests/ruby.yml
tests/remote_config/test_remote_configuration.py
utils/build/docker/dotnet/Controllers/CreateExtraServiceController.cs

Checks that the extra_services tag is correctly populated by the remote config client.
This feature will be used to help give any fake services that appear the correct status.

Test for RC client extra_services field

---

docs/weblog/README.md
tests/appsec/api_security/test_schemas.py
utils/build/docker/python/django/django.app.urls.py
utils/build/docker/python/flask/app.py
utils/build/docker/python/install_ddtrace.sh
utils/proxy/_deserializer.py

Add body response test for api security
- add new capability to tag_value end point of the weblog
- use that to test schema computation of body response for api security
- allow meta tags for api security to be gzip/b64 encoded or not (before it was mandatory, but it's not in the RFC)

response body support for api security

---

tests/debugger/test_debugger.py

`content` can be `null` on `/api/v2/logs` requests

Fix DEBUGGER_METHOD_PROBES_SNAPSHOT scenario

---

tests/test_sampling_rates.py

Enable `test_sample_rate_function` for dotnet.
Fixed in 2.37.0. https://github.com/DataDog/dd-trace-dotnet/pull/4548

Enable test_sample_rate_function for dotnet

---

tests/otel_tracing_e2e/test_e2e.py

The source of those flakyness is mainly the backend. If we don't find a way to make the test reliable, the signal/noise ratio is terrible.
Test must not be flaky

Marking some otel test as flaky

---

tests/appsec/blocking_rule.json
tests/appsec/waf/test_blocking.py

The PR adds a few more test cases for `Test_CustomBlockingResponse`. Also, updates the RFC link to the one that specify how the libraries should handle the blocking response configuration
From the RFC:
> Possible parameters for type redirect_request:
-  status_code : libraries should check that the provided status code starts with a 3xx and if it does, set it. If it doesn’t then a default code should be set: 303
- location : libraries should set the location as specified here.  If location is empty: ignore all other fields and fallback on default behavior.  The library won’t check the location itself, if it’s correct or reachable.
2. Follow the style guidelines of this project (See [how to easily lint the …

add more test cases for Test_CustomBlockingResponse

---

utils/proxy/_deserializer.py

Meta tags starting with `_dd.appsec.s.` are JSON strings, or gzip/b64 JSON. They are decoded in v0.5 traces, but not in v0.4 traces.

Deserialize `_dd.appsec.s.` meta in v0.4 traces

---

.github/workflows/ci.yml
.github/workflows/compute-scenarios.yml
docs/CI/labels.md

Support for run-appsec-scenarios

---

utils/build/docker/python/django-poc.Dockerfile
utils/build/docker/python/flask-poc.Dockerfile
utils/build/docker/python/uds-flask.Dockerfile
utils/build/docker/python/uwsgi-poc.Dockerfile

Building weblog from python tracer source is slow (and terribly slow on Mac M1).
This PR does not solve the underlying issue, but mitigate it for one use case: when you modify the weblog code, the python file were copied in first in the docker file, invalidating the whole cache.
By copying those file after installing the tracer, docker can use the cache for this step.
It does not change anything for the other use case (modifying the tracer), as the base issue is not solved.
Faster local iterations
4. …

Optimize python build

---

tests/test_telemetry.py

Test is failing -> https://github.com/DataDog/system-tests-dashboard/actions/runs/6231337233/job/16912766829#step:12:155

Skip test_app_started_sent_exactly_once as flaky on python

---

manifests/dotnet.yml
manifests/golang.yml
manifests/python.yml
tests/apm_tracing_e2e/test_otel.py
tests/apm_tracing_e2e/test_single_span.py
tests/appsec/iast/source/test_parameter_value.py
tests/appsec/test_blocking_addresses.py
tests/appsec/test_ip_blocking_full_denylist.py
tests/appsec/test_user_blocking_full_denylist.py
tests/appsec/waf/test_addresses.py
tests/appsec/waf/test_blocking.py
tests/debugger/test_debugger.py
tests/integrations/test_dbm.py
tests/remote_config/test_remote_configuration.py
tests/test_profiling.py
tests/test_semantic_conventions.py

Migrate few leftovers in manifest files for .NET, Golang and python

Migrate some leftovers in manifest files

---

manifests/java.yml
tests/appsec/test_blocking_addresses.py
tests/test_data_integrity.py

Enable some tests in Java

---

manifests/python.yml
utils/_context/_scenarios.py
utils/build/docker/python/django/django.app.urls.py
utils/build/docker/python/flask/app.py

To be merged after https://github.com/DataDog/dd-trace-py/pull/6933 [done]
- Re-enable api security tests for python after updating python tracer with rfc conformant sampling strategy.
- Improve the flask and django weblogs to follow new specifications from https://github.com/DataDog/system-tests/pull/1602
- Deactivate tracer debug log in api security scenario by default
2. just …

python api security enabled again

---

.github/workflows/ci.yml
docs/execute/build.md
manifests/python.yml
tests/test_semantic_conventions.py
tests/test_standard_tags.py
utils/_context/containers.py
utils/build/docker/python/python3.12.Dockerfile
utils/build/docker/python/python3.12.base.Dockerfile

Add weblog variant for python 3.12

---

manifests/cpp.yml
manifests/dotnet.yml
manifests/golang.yml
manifests/java.yml
manifests/nodejs.yml
manifests/php_appsec.yml
manifests/python.yml
manifests/ruby.yml
tests/appsec/iast/sink/test_hsts_missing_header.py
utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/AppSecIast.java

Added endpoints and tests for the hsts missing header vulnerability
To test the new hsts vulnerability detection code

HSTS missing header vulnerability tests for IAST

---

manifests/cpp.yml
manifests/dotnet.yml
manifests/golang.yml
manifests/java.yml
manifests/nodejs.yml
manifests/php_appsec.yml
manifests/python.yml
manifests/ruby.yml
tests/appsec/iast/sink/test_xcontent_sniffing.py
utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/AppSecIast.java
utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/WebSecurityConfig.java

X-Content-Type sniffing vulnerability tests and endpoints
This functionality was added recently and we need tests for it.

X-Content-Type-Options tests for IAST

---

manifests/java.yml
tests/appsec/iast/sink/test_hsts_missing_header.py

Set Test_HstsMissingHeader as bugged in Java

---

manifests/java.yml
tests/appsec/test_reports.py

Enabled test for extra tags in AppSecEvent report for Java.
Missing functionality have been added in the Java tracer
See: [APPSEC-11111](https://datadoghq.atlassian.net/browse/APPSEC-11111)
[APPSEC-11111]: https://datadoghq.atlassian.net/browse/APPSEC-11111?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2Zh …

Enabled test for extra tags in AppSecEvent report for Java

---

tests/appsec/iast/sink/test_hsts_missing_header.py

Now fixed in master: https://github.com/DataDog/dd-trace-java/pull/5950

Restrict HSTS @bug to java <1.22.0

---

manifests/nodejs.yml
tests/appsec/iast/sink/test_hsts_missing_header.py
tests/appsec/iast/sink/test_xcontent_sniffing.py
utils/build/docker/nodejs/express4/app.js
utils/build/docker/nodejs/express4/iast/index.js

Enable HSTS and X-Content-Type missing headers for nodejs.

Add hsts and x content type missing headers to nodejs system tests

---

tests/test_telemetry.py

Make `test_app_started_is_first_message` less strict checking that `app-started` message was sent first, based on the request's `seq_id`, allowing the message to not necessarily arrive first
Remove flaky `test_app_started_is_first_message` test in nodejs

Check the seq_id of the app-started request [APPSEC-10465]

---

tests/test_telemetry.py

Reactivating a test that should have been fixed by https://github.com/DataDog/dd-trace-py/pull/7043

Reactivate test_app_started_sent_exactly_once for python

---

manifests/python.yml
tests/test_the_test/test_version.py

`tests/appsec/api_security/test_schemas.py` tests are failing on `2.0.0`, but are ok on the `2.x` branch.

Update version number for python/api-security

---

utils/build/docker/ruby/rails32/app/controllers/system_test_controller.rb
utils/build/docker/ruby/rails32/config/routes.rb
utils/build/docker/ruby/rails40/app/controllers/system_test_controller.rb
utils/build/docker/ruby/rails40/config/routes.rb
utils/build/docker/ruby/rails41/app/controllers/system_test_controller.rb
utils/build/docker/ruby/rails41/config/routes.rb
utils/build/docker/ruby/rails42/app/controllers/system_test_controller.rb
utils/build/docker/ruby/rails42/config/routes.rb
utils/build/docker/ruby/rails50/app/controllers/system_test_controller.rb
utils/build/docker/ruby/rails50/config/routes.rb
utils/build/docker/ruby/rails51/app/controllers/system_test_controller.rb
utils/build/docker/ruby/rails51/config/routes.rb
utils/build/docker/ruby/rails52/app/controllers/system_test_controller.rb
utils/build/docker/ruby/rails52/config/routes.rb
utils/build/docker/ruby/rails60/app/controllers/system_test_controller.rb
utils/build/docker/ruby/rails60/config/routes.rb
utils/build/docker/ruby/rails61/app/controllers/system_test_controller.rb
utils/build/docker/ruby/rails61/config/routes.rb
utils/build/docker/ruby/rails70/app/controllers/system_test_controller.rb
utils/build/docker/ruby/rails70/config/routes.rb
utils/build/docker/ruby/sinatra14/app.rb
utils/build/docker/ruby/sinatra20/app.rb
utils/build/docker/ruby/sinatra21/app.rb

Update the Ruby weblog to be able to handle the case ASM API Security response body scenario

[APPSEC-10967] Update ruby weblog variants for API security response body test

---

tests/parametric/conftest.py
utils/_context/_scenarios.py
utils/_context/core.py

Dump test specific configuration on the json results report, in order to be uploaded correctly to FPD
We need to generate results report as other scenarios in order to push the content to FPD

Parametric: dump scenario context to json report

---

utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/AppSecIast.java
utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/WebMvcConfig.java
utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/iast/XContentTypeInterceptor.java

Ensures that `XCONTENTTYPE_HEADER_MISSING` is not triggered in requests other than the ones performed against the endpoint `/iast/xcontent-missing-header`
Not sending the proper header in non vulnerable endpoints might case the tests to be flaky. 

Prevent XCONTENTTYPE_HEADER_MISSING from showing in arbitrary endpoints

---

tests/appsec/iast/sink/test_sql_injection.py

Enable telemetry tests for executed python sql injection sinks.
These tests should have been already active.

chore(python): enable telemetry tests for executed sinks

---

manifests/python.yml
tests/appsec/iast/sink/test_ssrf.py
utils/build/docker/python/django/django.app.urls.py
utils/build/docker/python/flask/app.py

Enable IAST SSRF vulnerability for Flask, UWSGI and Django

feat(python): enable iast ssrf vulnerability

---

tests/integrations/test_dsm.py

Currently, the DSM system tests try to check for exact tags match. This leads to issues when developing new features where system-tests would fail for any new tags that are added for DSM data. See example from a PR with a new feature:
Makes it easier to add new features to DSM without triggering system-tests failures. …

Update DSM system tests to not fail on extra tags

---

tests/integrations/test_dsm.py

DSM tests are failing when the payload has no stats (it can be Backlogs-only payload).
Fix broken tests and unblock changes to .NET tracer (see https://github.com/DataDog/dd-trace-dotnet/pull/4704)

[DSM] - Accept empty payloads for stats in DSM

---

tests/test_standard_tags.py

After query string obfuscation regex was updated, dotnet tracer will contain the new regex from 2.39
Tested locally with before and after versions

[dotnet] deactivate query obfuscation legacy regex tests for 2.40

---

tests/test_standard_tags.py

We bumped the .NET version recently, and that caused tests which should be skipped to no longer be skipped, which broke the build 
The main branch in .NET is broken currently. We're anticipating merging a fix to the tracer for this soon, so we shouldn't have to update these numbers again 🤞 

[dotnet] Fix standard tag system tests

---

utils/_context/_scenarios.py
utils/interfaces/_core.py

Previously, when data coming from proxy was ingested, a check was made on it, and if it contains a deserialization error, the process was stopped with a nice error message.
But the ingestion process was moved inside a thread. In consequence : 
1. the thread exit on error, but the main process continue
2. later data are not ingested
3. tests are executed, but those who need missing ingested data fails (lot of them)
4. the good error message is it the top of stdout, followed by dazillion error messages
This PR move the error check frm the ingestion thread to the main thread, after closing the test target. Now, the error looks like this, and nothing more :
6. Follow the style guidelines of this project (See [how to easily lint the …

When proxy fails to deserialize, improve stdout

---

.vscode/launch.json
.vscode/settings.json
utils/_context/containers.py

Fix agent version getter in replay mode

---

tests/test_telemetry.py

Fix product assertion that is part of payload according to the spec

Fix product assertion that is part of payload according to the spec

---

manifests/python.yml

Both Weak Hash and Weak Cipher were introduced in version 1.7, but the metrics that validate those vulnerabilities were released in version 1.18.
This PR fix the backport https://github.com/DataDog/dd-trace-py/pull/7298

chore(python): fix Weak Hash and Weak Cipher version

---

manifests/python.yml

SQLi was introduced in version 1.12, but the metrics that validate this vulnerabilities were released in version 1.18.
This PR fix the backport https://github.com/DataDog/dd-trace-py/pull/7308

chore(python): fix SQLi version

---

manifests/python.yml

Telemetry tests are filing in 1.15 version and older
```
heartbeats = [d for d in telemetry_data if d["request"]["content"].get("request_type") == "app-heartbeat"]
>       assert len(heartbeats) >= 2, "Did not receive, at least, 2 heartbeats"
E       AssertionError: Did not receive, at least, 2 heartbeats
E       assert 0 >= 2
E        +  where 0 = len([])
```
This PR fix:
- https://github.com/DataDog/dd-trace-py/pull/7308
- https://github.com/DataDog/dd-trace-py/pull/7309
4. Mark it as ready for …

chore(python): bump telemetry tests version

---

tests/test_standard_tags.py

Complete one of the test with a key that was not handled before by previous regex
Activate tests for dotnet
Thought mostly json and quotes were tested so far but testing new keys might be relevant too 
Activate dotnet tests since regex is now updated and merged

[dotnet] activate new tests for regex obfuscation

---

manifests/dotnet.yml
tests/appsec/iast/source/test_parameter_name.py
utils/build/docker/dotnet/Controllers/IastController.cs

This PR implements the tests that check if a parameter name has been tainted.
It's a feature that we already support.

[.Net] Test query parameter names

---

manifests/python.yml
tests/appsec/iast/sink/test_command_injection.py

Enable IAST CMDi vulnerability for Flask, UWSGI and Django

feat(python): enable iast cmdi vulnerability

---

conftest.py

When a test is defined in a parent class located in another file, it's this another file who is reported in the setup phase, giving this ugly output : 
-> report the file where the test class is defined rather than the file where the parent class is defined.

Fix setup file path

---

tests/otel_tracing_e2e/_test_validator_trace.py

Skip validation on trace meta `_dd.ingestion_reason`
Temporary fix to https://github.com/DataDog/system-tests/actions/runs/6641096994/job/18042876027?pr=1739#step:8:106.

[opentelemetry] Skip validation on trace ingestion reasons

---

manifests/dotnet.yml
tests/appsec/iast/sink/test_no_httponly_cookie.py
utils/build/docker/dotnet/Controllers/IastController.cs

This PR contains the tests for the no http only cookie vulnerability.
This is a feature already supported, but no system test was done.

[.Net] IAST: No http only cookie vulnerability test

---

tests/appsec/iast/sink/test_hsts_missing_header.py

The IAST test on HSTS report some times a XCONTENTTYPE_HEADER_MISSING event

Skip flaky IAST test on java

---

.github/workflows/ci.yml
manifests/java.yml
tests/appsec/test_blocking_addresses.py
tests/appsec/waf/test_blocking.py
tests/appsec/waf/test_rules.py
utils/build/docker/java/akka-http/pom.xml
utils/build/docker/java/akka-http/src/main/scala/com/datadoghq/akka_http/AppSecRoutes.scala
utils/build/docker/java/akka-http/src/main/scala/com/datadoghq/akka_http/IastRoutes.scala
utils/build/docker/java/akka-http/src/main/scala/com/datadoghq/akka_http/Main.scala
utils/build/docker/java/akka-http/src/main/scala/com/datadoghq/akka_http/package.scala
utils/build/docker/java/app-play.sh
utils/build/docker/java/play.Dockerfile
utils/build/docker/java/play/app/Binders.scala
utils/build/docker/java/play/app/Module.scala
utils/build/docker/java/play/app/controllers/AppSecController.scala
utils/build/docker/java/play/app/controllers/controllers.scala
utils/build/docker/java/play/conf/application.conf
utils/build/docker/java/play/conf/logback.xml
utils/build/docker/java/play/conf/routes
utils/build/docker/java/play/pom.xml

Add support for appsec in akka-http and add a Play application. Support for appsec is to be available on both since v1.22.0.

akka-http and play appsec support

---

manifests/php.yml

Skip Test_StandardTagsUrl as bug on PHP. Real version is v0.76.0, but temporary bug with appsec, to be restored october 30th EOD.

Temp skip on Test_StandardTagsUrl/PHP

---

manifests/dotnet.yml
tests/appsec/iast/sink/test_ldap_injection.py
utils/build/docker/dotnet/Controllers/IastController.cs
utils/build/docker/dotnet/app.csproj

This PR contains the implementation of the Ldap tests for .net
This is a feature not tested that we already support.

[.Net] Ldap tests

---

manifests/python.yml

Re-enable Kafka tests in python for DSM

---

utils/build/docker/golang/install_ddtrace.sh

The recommended ruleset was moved from dd-trace-go/internal/appsec/rules.json to appsec-internal-go/appsec/rules.json (blocked by DataDog/dd-trace-go#2312). Since this script references the rules location to extract its version so we need to modify it.
We are moving the recommended ruleset from dd-trace-go to appsec-internal-go to centralize some code between the datadog-agent repo and the dd-trace-go repo.
1. is the …

build: go: switch rules location

---

docs/internals/generate-core-dump.md

Profiling is flaky at startup on profiling/python3.12
A core is dumped, but is not present in artifact. This PR fixes this.

Doc : Get core info on segfault

---

tests/appsec/iast/sink/test_hsts_missing_header.py
utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/iast/XContentTypeInterceptor.java

The error showed up depending on the order of the tests. The deduplication code did remove it most of the time. The error showed up because the XContentType header was set post request and not pre request, so the header was not present during analysis.
To get the test to pass every time.

Fix flaky HSTS header missing request test

---

utils/build/docker/java/parametric/src/main/java/com/datadoghq/OpenTelemetryClient.java

Looks like the OTel span kind got a new enum value.
This PR adds it to fix the parametric OTel tests.

Fix Java parametric client OTel span kind mapping

---

tests/integrations/test_db_integrations_sql.py

Skips failing database tests for the python client library. These tests were introduced in: https://github.com/DataDog/system-tests/pull/1785
The tests are asserting that db.operation, db.instance , and db.type tags are set on database spans. The python tracer doesn't meet this spec. The python tracer only sets these tags on `db.query` spans: https://github.com/DataDog/dd-trace-py/blob/v2.1.4/ddtrace/ext/db.py.
We may need to add these tags but I think this feature request should block ci.
Unblocks CI. Sample Failure: https://github.com/DataDog/dd-trace-py/actions/runs/6736110484/job/18310760441?pr=7216
3. …

ddtracepy: skip failing db tests

---

tests/remote_config/test_remote_configuration.py

* Allows additional extra_services beyond the one added by the test. This can happen peer services like kafka, mysql, etc.
* Ensure that once the extra_service of interest is seen, it is also seen in all subsequent requests.
JIRA issue: [APPSEC-11886]
[APPSEC-11886]: …

Adjust extra_services assertions

---

manifests/nodejs.yml
utils/build/docker/nodejs/express4-typescript/app.ts
utils/build/docker/nodejs/express4/app.js
utils/build/docker/nodejs/nextjs/src/app/createextraservice/route.js

Implement and enable RC extra services test

[node.js] Enable RC extra services test [APPSEC-11927]

---

tests/parametric/test_128_bit_traceids.py

I have no idea why these tests are disabled, but they work.

Remove missing_feature for PHP in 128 bit trace id tests

---

docs/weblog/README.md
manifests/cpp.yml
manifests/dotnet.yml
manifests/golang.yml
manifests/java.yml
manifests/nodejs.yml
manifests/php_appsec.yml
manifests/python.yml
manifests/ruby.yml
tests/appsec/iast/_test_iast_fixtures.py
tests/appsec/iast/sink/test_hardcoded_secrets.py
utils/build/docker/nodejs/express4/iast/index.js

Includes a nodejs test for the new `HARDCODED_SECRET` vulnerability.
In the case of nodejs, the vulnerability is detected in the application startup so it differs a bit from the rest of the existing sink tests.
`test_insecure` method checks the value of the new `detection_stage` property in `BaseSinkTestWithoutTelemetry`:
- If `DetectionStage.REQUEST` (the default value), `test_insecure` passes the request as always. 
- If `DetectionStage.STARTUP` it passes a `None` request.
NOTE: Another option could be to add a `request` argument to the `test_insecure` method and pass a `None` request when necessary. 
3. …

Hardcoded secrets test [APPSEC-11807]

---

tests/parametric/test_headers_b3.py
tests/parametric/test_headers_b3multi.py

If 128-bit trace id generation is enabled, B3 parametric tests do not check the the low order bits only.
Test will break if we enable 128-bit trace id generation by default.

Fix B3 parametric tests when 128-bit trace id generation is enabled

---

tests/integrations/test_db_integrations_sql.py

Waiting for DataDog/dd-trace-java#6153 to fix DBMON-3088, unskipping the test. 

Unskip test (DBMON-3088)

---

tests/appsec/iast/_test_iast_fixtures.py
tests/appsec/iast/source/test_body.py
tests/appsec/iast/source/test_cookie_name.py
tests/appsec/iast/source/test_cookie_value.py
tests/appsec/iast/source/test_multipart.py
tests/appsec/iast/source/test_parameter_name.py
tests/appsec/iast/source/test_parameter_value.py
tests/appsec/iast/source/test_path.py

…part test
Allow multiple Source names in vulnerability specifications.
For some tests, in this case the multipart file upload test, some web servers (openliberty) will report a different source name from other web servers (tomcat). Both source names are correct and we need a way to allow more than one source name for the test to pass.
2. just before merging, locally build and …

Allow multiple source names in tests and use the feature in the multipart test

---

utils/build/docker/python/parametric/apm_test_client/server.py

Now that we've switched to 128-bit trace ids by default, we'll error when we try to return what's expected to be 64-bit trace id. This change truncates the 128-bit trace id to 64-bits so we can still compare the bottom 64 bits.

Fix Python otel tests

---

tests/parametric/test_otel_span_methods.py

Added a test suit for a corner case in OTel operation remapping

Add a test to parametric test suit for OpenTelemetry -> Datadog name conventions

---

tests/parametric/test_headers_precedence.py

Fix truncate the compared trace id for headers

---

tests/parametric/test_128_bit_traceids.py

Adds test to assert that tracing client libraries generate 128-bit trace-id's by default. The test behavior is identical to the enabled case.
This test asserts that all libraries implement the new behavior.

[parametric] Add system-test for client libraries to generate 128 bit trace-id's by default

---

utils/build/docker/nodejs/nextjs/.babelrc
utils/build/docker/nodejs/nextjs/next.config.js
utils/build/docker/nodejs/nextjs/package-lock.json

Next.js compiler uses SWC. The installation of SWC dependencies are unstable, causing flaky builds for Next.js application. This PR opt-out SWC compiler to avoid installing SWC deps.
Resolve flakyness when building Next.js app

Opt-out SWC compiler for NextJS app

---

tests/parametric/test_otel_span_methods.py

Enable parametric OpenTelemetry span naming tests for Java tracer.
As the tests was just merged, we want to enable them on our CI as soon as possible.
Feature is expected to be merged by the end of the week.

Enable parametric OpenTelemetry span naming tests for Java tracer 

---

tests/remote_config/test_remote_configuration.py

Not just any service
Fix bug in `Test_RemoteConfigurationExtraServices:` and re-enable dotnet test on dotnet platform.

wait for a heartbeat with reqired service

---

tests/parametric/test_otel_span_methods.py

We should always be able to rely on `span.kind` for the operation name as it will always have a value - by default the `span.kind` is `SpanKind.Internal`.
This removes the possibility of having `otel_unknown` as the operation name as we can always fallback on `span.kind`.
We will always have a value for `span.kind` to fallback to for the operation name. 
2. just before merging, …

When no span.kind, name should default to `internal`

---

tests/parametric/conftest.py

Set timeout for subprocess. trying to avoid CI blocked running the parametric tests.
This PR won't solve the root cause of the problem (I don't know which is), but at least we won't block for hours the build CI execution
Today was the first time that I managed to block the execution of parametric tests on my laptop.
So far I have only seen this problem in the CI:
1. It happens more times in system-tests-dashboard than in system-tests. Why? 
2. It happens more times in Java than in other languages. Why?
I used "py-spy dump" to see the blocked program. My output:
```
(venv) roberto.montero@COMP-WMH2MQLQFT 20231115 % ps -fea|grep python         
503  3140  2924   0 Mon10AM ??         0:11.87 /opt/homebrew/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/Resources/Python.app/C …
```

Parametric: Timeout to running subprocess

---

utils/build/docker/golang/parametric/datadog.go
utils/build/docker/golang/parametric/main.go

Don't restart the Go tracer on span creation.
Seems to be a regression in https://github.com/DataDog/system-tests/pull/1381/ - the tracer is already started by the `NewTracerProvider` call in main.go.

golang/parametric: dont restart tracer on span creation

---

tests/parametric/test_128_bit_traceids.py
tests/parametric/test_headers_precedence.py
tests/parametric/test_headers_tracestate_dd.py
tests/parametric/test_otel_span_methods.py
tests/parametric/test_otel_span_with_w3c.py
tests/parametric/test_otel_tracer.py
utils/build/docker/java/parametric/src/main/java/com/datadoghq/OpenTelemetryClient.java

This PR enables the latest parametric test for the Java tracer.
Java tracer recently implement new features that system-tests cover.

Update Java tracer parametric tests 

---

tests/parametric/test_headers_precedence.py

Update tests for cpp@v0.1.12
Our latest version of `dd-trace-cpp` uses by default `datadog, tracecontext` propagation style. Some tests needs to be mark as relevant or bug.

Update tests for cpp@0.1.12

---

manifests/java.yml

Enable tracer-flare system-tests for Java tracer 1.25.0 and later
We've merged enough of the tracer-flare work to begin system-testing it as of the upcoming 1.25.0 release.

Enable tracer-flare system-tests for Java tracer 1.25.0 and later

---

utils/build/docker/php/apache-mod/build.sh
utils/build/docker/php/common/install_ddtrace.sh

Currently the system tests (with the exception of the parametric tests) use the independent tracer and appsec packages, this PR adds support for the unified package to allow local testing and testing in the tracer's CI.
Related Jira: [APPSEC-4581]
[APPSEC-4581]: …

[PHP] Support unified package

---

tests/test_the_test/test_decorators.py
tests/test_the_test/test_json_report.py
utils/coverage.py

The reason for "missing feature" must start with `missing_feature` : https://github.com/DataDog/system-tests/pull/1865/files#diff-96ff462305095ff0c4eeed881aa496b4f8c22fd31d58181eead8507978e8ec29R23

Remove a small leftover in missing feature declaration

---

utils/build/docker/php/common/install_ddtrace.sh

Small typo introduced in the tracer installer, doesn't affect the system tests CI at the moment.

[PHP] Fix typo on tracer installer

---

tests/parametric/test_headers_precedence.py
utils/build/docker/ruby/parametric/Gemfile

[Ruby 1.17.0] Parametric missing feature: test_headers_precedence_propagationstyle_default

---

tests/parametric/test_headers_tracestate_dd.py
tests/parametric/test_otel_span_methods.py

This PR updates the active tests for the Java client library.
Not all supported tests were running.

Update active tests for Java client library

---

utils/build/docker/ruby/rails42.Dockerfile
utils/build/docker/ruby/sinatra14.Dockerfile

As the Ruby Tracing team start the work to deprecate support for Ruby < 2.5, this PR upgrades the base version of two older Ruby apps (Sinatra 1.4 and Rails 4.2) as these applications can still work with Ruby >= 2.5 but `dd-trace-rb` won't install in their containers if they are running Ruby < 2.5.
This should have no impact in testing of the currently stable release of `dd-trace-rb`.
1. is the image labl have been …

Ruby:Upgrade Ruby version for older apps

---

docs/scenarios/parametric.md
requirements.txt
utils/build/docker/python_http/parametric/requirements.txt
utils/scripts/parametric/run_reference_http.sh

prep for the incoming http revolution

Fix parametric http docs

---

manifests/golang.yml
tests/integrations/test_crossed_integrations.py
utils/build/docker/golang/app/go.mod
utils/build/docker/golang/app/go.sum
utils/build/docker/golang/app/net-http.go

This PR adds a`kafka.produce` and `kafka.consume` endpoint using the sarama integration in dd-trace-go.
Endpoints:
1. `/kafka/produce`
1. `/kafka/consume`
Relates to the goals of https://github.com/DataDog/system-tests/pull/1757 and https://github.com/DataDog/system-tests/pull/1783 .
3. Follow the style guidelines of this project (See [how to easily lint the code](https://github.com/DataDog/system-tests/blob/main/docs/edit/lint.md))

[APM][Context Propagation] Add Golang endpoints for Kafka produce and consume

---

conftest.py
tests/test_the_test/test_decorators.py
utils/_context/_scenarios.py
utils/_decorators.py

Export a log file that can be curled to the feature parity dashbaord
Remove unecessary process in system-tests-dashbaord

Report for Feature Parity Dashbaord

---

utils/_context/_scenarios.py

Painful to know what version is tested on parametric scenario
Same as end-to-end scenario : display in stdout, at the begining of the test run, the version of the library used

Display library version in stdout for parametric scenario

---

tests/test_telemetry.py

- node.js tracer is working on dropping v1 support
- https://github.com/DataDog/dd-trace-js/pull/3827
- v2 > v1

nodejs: going to drop instrumentation v1 support

---

.github/workflows/ci.yml
utils/scripts/load-binary.sh

https://github.com/DataDog/appsec-event-rules is now private, we can't load the last set anymore
Waiting for a proper solution, skip loading the rule set
Also change the script to make it fail on `404`, (it was a silent fail) …

[HotFix] Skip loading WAF rule set

---

tests/parametric/test_otel_span_methods.py

Follow-up from https://github.com/DataDog/system-tests/pull/1885. Offline discussions found that the case was flipped.
Only run the old tests on old versions, and run the new tests on v1.59.0 and all new code in main.

parametric: fix Go versions for running otel span array attribute tests

---

manifests/python.yml
tests/appsec/test_conf.py
tests/appsec/waf/test_telemetry.py
tests/parametric/test_headers_tracestate_dd.py

With growing support of FastAPI for ASM, enable more tests on the FastAPI variant. 

chore(python): enable more tests for fastapi

---

tests/test_telemetry.py

No flaky test
https://datadoghq.atlassian.net/browse/AIT-9152
And also some minor improvements on log output

Flag seq_id test as flaky on java AIT-9152

---

tests/appsec/waf/test_telemetry.py

Update test_telemetry.py after dd-trace-js migrates to telemetry v2

---

tests/appsec/test_ip_blocking_full_denylist.py
utils/_context/containers.py

thanks to @Julio-Guerra and Feature Parity Dasbaord, we found a bug in system tests
The logic that check if the tracer was using a rule file was missing the potential custom declaration in weblog env in the scenario.
And some test was thinking a rules files was present (they were not used), and skip themselves.
* fix the logic in scenario
* remove the skip that is now useless  …

Fix appsec_rules check on scenario

---

tests/test_telemetry.py

No flaky test
Skip `test_app_heartbeat` (see AIT-9176)

Skip failing telemetry test on node 

---

utils/_context/_scenarios.py

We may need to check architecture and platform used to run the weblog and the tracer. 
This PR adds, just after the warmup phase, a call to the weblog container to print its current system information.

add weblog container system information to startup messages

---

manifests/dotnet.yml
manifests/golang.yml
manifests/java.yml
manifests/nodejs.yml
manifests/php_appsec.yml
manifests/python.yml
manifests/ruby.yml
tests/appsec/api_security/test_schemas.py
utils/_features.py

Add tests to check scanners for api security are working as expected

tests scanners for api security

---

tests/apm_tracing_e2e/test_otel.py
utils/interfaces/_backend.py

The two following tests have been flaking since July. This PR aims to reduce the flakiness.
Added a new `retries` keyword argument in the caller methods that rely in `_wait_for_event_platform_spans`, that accepts this keyword with default value of 5. …

tests/apm_tracing_e2e: increase retries in OTel tests from 5 to 10

---

.github/workflows/ci.yml
.github/workflows/parametric.yml

Currently Parametric only executes tests using latest tracer release. We add support to run snapshot version of the java tracer (dev).
In this case we only add the support adding "dev" parameter on the parametric.yml (CI)

Parametric: Add client: java version: dev

---

utils/interfaces/schemas/miscs/telemetry/v2/events/client-configuration-change.json

As of the [schema reference](https://github.com/DataDog/instrumentation-telemetry-api-docs/blob/main/GeneratedDocumentation/ApiDocs/v2/SchemaDocumentation/Schemas/payload.md#if-request_type--app-client-configuration-change-we-add-the-following-to-payload), the configuration field is not expected as `conf_key_value` but `configuration`.
Fixes the failing system tests for https://github.com/DataDog/dd-trace-go/pull/2444 …

Fix telemetry v2 app-client-configuration-change schema

---

.github/workflows/ci.yml
.github/workflows/parametric.yml
docs/scenarios/parametric.md
tests/parametric/conftest.py
utils/build/docker/nodejs/parametric/Dockerfile
utils/build/docker/nodejs/parametric/ddtracer_version.Dockerfile
utils/build/docker/nodejs/parametric/ddtracer_version.sh

Currently Parametric only executes tests using latest tracer release. We add support to run snapshot version of the nodejs tracer (dev).

Parametric: Add client: nodejs version: dev

---

manifests/python.yml
tests/appsec/api_security/test_schemas.py
utils/build/docker/python/fastapi/main.py
utils/build/docker/python/install_ddtrace.sh

https://github.com/DataDog/dd-trace-py/pull/7954 add api security support for fastapi.
This PR activates the tests for the corresponding weblog (PR7954 is now merged)
Also fix a fastapi endpoint to accept urlencoded payload.
Add an `ANY` value for api sec tests to match any value.
🛟 …

activate api security tests for python fastapi

---

manifests/java.yml
tests/appsec/iast/sink/test_header_injection.py
utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/AppSecIast.java

Testing the new Java tracer feature. Header injection vulnerability.
Added endpoints and java test to the test suite.

IAST Header injection java test and endpoint

---

manifests/dotnet.yml
tests/parametric/conftest.py
tests/parametric/test_dynamic_configuration.py

Enable dynamic configuration v2 tests for .NET.
- Enable dynamic configuration v2 tests for .NET
- message-batch messages weren't handled properly
- In test_tracing_client_tracing_tags, remove the tracing_tags key instead of setting an empty value (mimicking the behavior in production)
🛟 …

Fix dynamic config v2 tests and enable for .net

---

manifests/golang.yml

This test is failing. Disabling it and logging APPSEC-18224 to investigate.
Mark API Security Test_Schema_Request_Cookies as bug for uds-echo in the golang manifest

go: uds-echo: tag API Sec cookies schema test as bug

---

utils/_context/_scenarios.py

Parametric executes a docker build of "ddtracer_version.Dockerfile".  This PR mutes the docker build output.
If the docker build fails, we'll see the traces. 

Parametric: Mute output on ddtracer_version docker build

---

tests/parametric/test_otel_span_methods.py

The [RFC](https://docs.google.com/document/d/1KB6XQxZDUgSSQHp1TEk_0X6zgOzmB9-r8NKE9TVaRJw/edit#bookmark=id.44nna34oqd3j) states that the reserved span attributes must match the behavior of the [OTLP code](https://github.com/DataDog/datadog-agent/blob/ea1911d5618df80c1dd25b362369a2e0491910be/pkg/trace/api/otlp.go#L466-L483) which uses Go's [strconv.ParseBool](https://cs.opensource.google/go/go/+/refs/tags/go1.21.5:src/strconv/atob.go;l=10).
```
// ParseBool returns the boolean value represented by the string.
// It accepts 1, t, T, TRUE, true, True, 0, f, F, FALSE, false, False.
```
More specifically, this means that 1, t, T, 0, f, and F strings are also valid entries, while anything other than those listed above shouldn't set the `_dd1.sr.eausr` in the metrics. This PR tests this …

[OTel] Test `analytics.event` override with respect to OTLP Code

---

manifests/dotnet.yml
tests/appsec/iast/_test_iast_fixtures.py
tests/appsec/iast/sink/test_trust_boundary_violation.py
utils/build/docker/dotnet/Controllers/IastController.cs
utils/build/docker/dotnet/Startup.cs

IAST TrustBoundaryViolation implementation for dotnet
Set data as params when creating the secure and insecure requests when GET method is selected

[dotnet] IAST TrustBoundaryViolation implementation

---

manifests/nodejs.yml
tests/integrations/test_crossed_integrations.py
utils/build/docker/nodejs/express4/app.js

This request expands the crossed-tracer integration tests to include NodeJS
This change adds the 'produce' and 'consume' endpoints to the express4 integration in support of the crossed tracer integration tests.  These endpoints are used to produce/consume from Kafka queues.

Add NodeJS to the Crossed Tracer integration tests

---

.gitlab-ci.yml
pyproject.toml
tests/onboarding/test_onboarding_install.py

Enable gitlab job that pushes the tests results to system-tests-dashboard

OnBoarding: Push results to FPD

---

manifests/ruby.yml
tests/integrations/test_crossed_integrations.py
utils/build/docker/ruby/rails70/Gemfile
utils/build/docker/ruby/rails70/app/controllers/system_test_controller.rb
utils/build/docker/ruby/rails70/config/routes.rb

This change adds the 'produce' and 'consume' endpoints to the express4 integration in support of the crossed tracer integration tests.  These endpoints are used to produce/consume from Kafka queues.

Add Ruby to the Crossed Tracer integration tests

---

manifests/dotnet.yml
utils/build/docker/dotnet/Controllers/IastController.cs

Unvalidated Redirect implementation for dotnet
Redirect method and Location header tests

[dotnet] Unvalidated Redirect implementation

---

.github/workflows/ci.yml
tests/otel_tracing_e2e/_test_validator_trace.py

There are random tests failures on the otel_tracing_e2e scenario.
This PR tries to debug and fix these failures.
@songy23 I'm not sure if I'm fixing the root cause, or just hiding it.

Debug flakyness otel_tracing_e2e

---

manifests/php.yml
tests/parametric/test_otel_span_methods.py
tests/parametric/test_otel_span_with_w3c.py
tests/parametric/test_otel_tracer.py
utils/build/docker/php/parametric/composer.json
utils/build/docker/php/parametric/composer.lock
utils/build/docker/php/parametric/server.php

Run OTel parametric tests for PHP
- Unskip OTel PHP tests
- A new `composer.lock` file was created as a result of the changes in the `composer.json`. I generated this file in my buster container. If this is not the way to do it, please advice me.
- `test_otel_get_span_context`: Allow hexadecimal span id, as span identifiers generated by OTel are hexadecimal
:rocket: Once …

Run OTel parametric tests for PHP

---

.github/workflows/ci.yml
.github/workflows/parametric.yml
docs/scenarios/parametric.md
tests/parametric/conftest.py
utils/_context/_scenarios.py
utils/build/docker/ruby/parametric/Gemfile
utils/build/docker/ruby/parametric/ddtracer_version.Dockerfile

Currently Parametric only executes tests using latest tracer release. We add support to run snapshot version of the ruby tracer (dev).
The idea behind this is to use the same approach to install dd-trace-rb as is used by system-tests (maintainability reasons).
We are using the previously existing script to install the tracer: utils/build/docker/ruby/install_ddtrace.sh …

Parametric: Add client: ruby version: dev

---

manifests/java.yml

[The Java tag-based sampling rules](https://github.com/DataDog/dd-trace-java/pull/6298) have been released in [v1.26.0](https://github.com/DataDog/dd-trace-java/releases/tag/v1.26.0)
Enable tag-based sampling tests for Java v1.26.0+

Enable tag-based sampling tests for Java

---

tests/debugger/test_debugger.py

Following https://github.com/DataDog/dd-trace-java/pull/6365 a new probe status was introduced, requiring to update those tests

fix debugger tests with new EMITTING probe status

---

.github/workflows/ci.yml
.github/workflows/parametric.yml
docs/scenarios/parametric.md
tests/parametric/conftest.py
utils/build/docker/dotnet/parametric/Dockerfile
utils/build/docker/dotnet/parametric/ddtracer_version.Dockerfile

Adapt parametric test to use the script load-binary.sh to test snapshot and release versions

Parametric: Add client: dotnet version: dev

---

tests/parametric/test_headers_precedence.py

The new test was failing for python: test_headers_precedence_propagationstyle_resolves_conflicting_contexts
Python versions:
- python@2.5.0.dev45+g8d0a35e76
- python@2.4.0
Commit that introduced the failure: https://github.com/DataDog/system-tests/pull/1892/files
The CI failing on main branch: https://github.com/DataDog/system-tests/actions/runs/7401652827/job/20137904629 …

Parametric: Disable header precedence failing test

---

utils/_context/_scenarios.py

Help debugging
When the proxy raise an exception caused by a deserialization issue, the runner print the stacktrace in stdout (good), and early quit (good again) without saving weblog stdout (bad).
This change saves weblog stdout in that situation. …

In case of deserialization error, get weblog logs

---

.github/workflows/ci.yml
.github/workflows/parametric.yml
docs/scenarios/parametric.md
tests/parametric/conftest.py
utils/build/docker/cpp/parametric/ddtracer_version.Dockerfile
utils/build/docker/cpp/parametric/http/Dockerfile
utils/build/docker/cpp/parametric/install_ddtrace.sh
utils/scripts/load-binary.sh

Adapt parametric test to use the script load-binary.sh to test snapshot and release versions.
The idea behind this is to retrieve tracer versions in similar way as other tracer. Also we try to use the same mechanism in system-tests and in parametric tests
🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C …

Parametric: Add client: cpp version: dev

---

utils/interfaces/schemas/miscs/telemetry/v2/events/client-configuration-change.json

The `configuration` property is an array of items, but it was incorrectly typed as an array of arrays of items, which is incorrect.
Fixes the schema to match what is expected by the Telemetry API.

Fix telemetry v2 client-configuration-change schema

---

tests/debugger/test_debugger.py

dd-trace-java now upload probe statuses to new Debugger track. need to wait other tracers to switch system tests
to this new track

Fix debugger tests for new Debugger track

---

.github/workflows/ci.yml
utils/build/docker/python/python3.12.Dockerfile
utils/build/docker/python/python3.12.base.Dockerfile

Use new python image
Follow-up of #2015, actually use the new image 😃  
I've built and pushed the base image to docker repo, so no need to add the label `build-base-image`

Use the new python3.12 base image

---

tests/integrations/test_open_telemetry.py

The open telemetry failing test related with the previously not considered span.

fix open telemetry. Register new span

---

manifests/golang.yml
tests/test_data_integrity.py

`Datadog-Container-ID` header should not be an empty string
Test asserting that `Datadog-Container-ID` is not empty

Ensure that Datadog-Container-ID is not empty if present

---

pyproject.toml
tests/remote_config/test_remote_configuration.py
tests/test_data_integrity.py
tests/test_distributed.py
tests/test_library_conf.py
tests/test_no_ip_is_reported.py
tests/test_remote_config.py
tests/test_scrubbing.py
tests/test_semantic_conventions.py
tests/test_telemetry.py
utils/_features.py

Decorate few missing tests with feature ids

---

manifests/php.yml
tests/appsec/test_shell_execution.py
utils/build/docker/php/apache-mod/php.conf
utils/build/docker/php/common/shell_execution.php
utils/build/docker/php/php-fpm/php-fpm.conf

Command execution spans for PHP. Requires the version 0.95 of the tracer.

Command execution for PHP

---

.gitlab-ci.yml

OnBoarding tests are reporting to feature parity dashboard in bad way, and cause problems on system-test-dashboard CI when we are pushing the results to FPD
Use feature-report.json instead of reports.json

OnBoarding: Fix feature parity report

---

utils/_context/virtual_machines.py

The alpine arm support is fixed on the snapshot 0.12.3. Enable the tests

OnBoarding: Enable alpine arm tests for staging

---

tests/parametric/conftest.py
utils/build/docker/python/parametric/Dockerfile
utils/parametric/spec/remoteconfig.py

This is the recommended approach to instrumenting Python applications and the same code path that is used with Single Step APM.

Update python app to use ddtrace-run

---

utils/interfaces/schemas/library/v0.6/stats-request.json

`utils/interfaces/schemas/library/v0.6/stats-request.json` requires stats payloads to contain hostnames. This is incorrect. Hostnames should only be set if  `DD_TRACE_REPORT_HOSTNAME=True` is set. By default hostnames should be resolved by the Datadog Agent. This will reduce cardinality in trace stats.
Fixes the following tests for the python tracer: `tests/test_schemas.py::Test_Library::test_full` and `tests/test_schemas.py::Test_Library::test_non_regression` ([link](https://github.com/DataDog/dd-trace-py/actions/runs/7559749497/job/20584254662?pr=8130)).
* Test logic is modified? -> Get a review from RFC owner. We're …

trace-stats: fix hostname validator

---

tests/appsec/test_shell_execution.py

* Make initial asserts more explicit.
* Assert `resource`.

Refine shell tracing tests

---

manifests/cpp.yml

Skip an irrelevant test in C++

---

manifests/dotnet.yml
tests/test_data_integrity.py

.NET is implementing the Datadog-Entity-ID feature in https://github.com/DataDog/dd-trace-dotnet/pull/5058
Unskips tests/test_data_integrity.py::Test_LibraryHeaders::test_datadog_entity_id for .NET.
Now that the .NET Tracer [v2.46.0](https://github.com/DataDog/dd-trace-dotnet/releases/tag/v2.46.0) has released, this test passes.
:rocket: Once your PR is reviewed, you can …

Enable Datadog-Entity-ID test for .NET

---

manifests/cpp.yml
manifests/dotnet.yml
manifests/golang.yml
manifests/java.yml
manifests/nodejs.yml
manifests/php.yml
manifests/python.yml
manifests/ruby.yml
tests/integrations/crossed_integrations/test_rabbitmq.py
utils/_context/_scenarios.py
utils/_features.py
utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/App.java
utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/rabbitmq/RabbitmqConnector.java

More testing
Adds new cross integration test class for rabbitmq, modifies java weblog to have a new rabbitmq consume and produce endpoints

add rabbitmq cross integration tests for trace context propagation

---

manifests/cpp.yml
manifests/dotnet.yml
manifests/golang.yml
manifests/java.yml
manifests/nodejs.yml
manifests/php.yml
manifests/ruby.yml
tests/parametric/test_dynamic_configuration.py

Parametric tests don't work after merge this PR: https://github.com/DataDog/system-tests/pull/2039

Fix parametric: dynamic config

---

format.sh

`format.sh` previously broken by https://github.com/DataDog/system-tests/pull/2005
The script would fail in systems without DOCKER_HOST env var defined.
Ensure `DOCKER_HOST` is defined within the script before referencing it.

Fix format.sh (unbound variable DOCKER_HOST)

---

manifests/dotnet.yml
tests/appsec/iast/sink/test_header_injection.py
utils/build/docker/dotnet/Controllers/IastController.cs

This PR adds the IAST system tests for the header injection vulnerability.
To test a feature that we already support.

[.Net] IAST header injection system tests

---

utils/_context/_scenarios.py

API Security is leaving the private status to become soon available to customer. 
To reflect that, RFC changed the name of the  environment variable to enable API Security.
Add new env var name to concerned scenarios.

add new env var for api security

---

.github/workflows/ci.yml
.gitlab-ci.yml
utils/build/build_tracer_buddies.sh
utils/scripts/get_pr_merged_labels.sh

We need to regenerate buddies if a PR with this label is merged to main branch.
Use gitlab job to trigger the buddies generation on merge if the labels has been set 

Generate buddies on merge

---

tests/appsec/test_blocking_addresses.py
tests/appsec/waf/test_blocking.py

no flaky test
Skip test impacted by https://datadoghq.atlassian.net/browse/APPSEC-51448

Skip flaky test on PHP (APPSEC-51448)

---

manifests/nodejs.yml
utils/build/docker/nodejs/nextjs/src/app/shell_execution/route.js

Shell execution feature merged in master, we are enabling the tests here. 
I saw that nextjs endpoint wasn't implemented, so I implemented it also.
Enable test
Add new endpoint in nextjs
_(Modified tests are in default scenario)_

Shell execution enabled and added in nextjs

---

utils/build/docker/java/spring-boot/pom.xml

OpenLiberty Maven Plugin defaults to latest version. This might not be fully available at Maven Central during releases if there is any replication issue. Pinning the version will avoid breakage.
Pin openliberty version

Pin openliberty version

---

manifests/java.yml
tests/appsec/iast/sink/test_command_injection.py
tests/appsec/iast/sink/test_ldap_injection.py
tests/appsec/iast/sink/test_no_samesite_cookie.py
tests/appsec/iast/sink/test_path_traversal.py
tests/appsec/iast/sink/test_sql_injection.py
tests/appsec/iast/sink/test_ssrf.py
tests/appsec/iast/sink/test_trust_boundary_violation.py
tests/appsec/iast/sink/test_weak_cipher.py
tests/appsec/iast/sink/test_weak_hash.py
tests/appsec/iast/source/test_body.py
tests/appsec/iast/source/test_cookie_name.py
tests/appsec/iast/source/test_cookie_value.py
tests/appsec/iast/source/test_header_name.py
tests/appsec/iast/source/test_header_value.py
tests/appsec/iast/source/test_parameter_name.py
tests/appsec/iast/source/test_parameter_value.py
tests/test_semantic_conventions.py
tests/test_standard_tags.py

Enable more Java tests

---

manifests/java.yml
tests/test_data_integrity.py

Test changes in https://github.com/DataDog/dd-trace-java/pull/6559
Enables `Test_LibraryHeaders` for Java v1.29.0+

Enable Test_LibraryHeaders for Java v1.29.0+

---

tests/appsec/test_blocking_addresses.py

No flaky tests
APPSEC-51448 makes other tests flaky : https://github.com/DataDog/system-tests-dashboard/actions/runs/7721430273/job/21048010717#step:35:236

Skip other tests impacted by APPSEC-51448

---

manifests/dotnet.yml
tests/appsec/iast/sink/test_hsts_missing_header.py
tests/appsec/iast/source/test_path.py
utils/build/docker/dotnet/Controllers/IastController.cs

This PR adds the system tests for IAST - .Net that check if the path of a query has been tainted. For instance, if a controller has the attribute [HttpGet("/iast/source/path/test")], "/iast/source/path/test" should be tainted.
It is a feature that we already support.
🛟 …

[ASM[ Tainted path system tests

---

utils/build/docker/nodejs/express4/iast/sources.js

Hide errors when weblog is trying to read some files that do not exist. 
We are not testing that the reading is working, we are testing that the vulnerability is in the request, an the result of the operation does not matter.

Hide some expected error logs

---

tests/parametric/conftest.py

Turns out due to an implementation detail in the go json library, byte arrays can be encoded equally as base64 or an array of numbers.
The Python, .NET and Node libraries (at least) use base64 encoding to encode the capabilities and it seems like the Java implementation uses an array of numbers.
Since both are currently accepted by the agent, both should be accepted by the tests.
In the future we should standardize to avoid further unexpected behaviour.

Add decode support for capability byte arrays

---

manifests/dotnet.yml
utils/_context/_scenarios.py
utils/build/docker/dotnet/Controllers/TagValueController.cs
utils/build/docker/dotnet/Models/ApiSecurity/RequestBodyModel.cs

Activate api security tests dotnet
[Api Security PR](https://github.com/DataDog/dd-trace-dotnet/pull/4654/) has been merged

Activate api security tests dotnet

---

tests/appsec/api_security/test_schemas.py

equality for schema computation was too permissive
- ensure that keys are present before check for values, to ensure that keys set to ANY are present.
- ensure arrays of types have the same length

api security tests: fix equal_value

---

manifests/nodejs.yml

Feature merged in dd-trace-js
Test enabled in the manifest
_(Only dotnet tests fail, when my change is only in `manifests/nodejs.yml`)_

[nodejs] Enable FormData address test for nextjs

---

tests/appsec/test_blocking_addresses.py
tests/appsec/waf/test_blocking.py

Reverted commits adding flaky annotations now that [APPSEC-51448] has been resolved.
[APPSEC-51448]: https://datadoghq.atlassian.net/browse/APPSEC-51448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1c …

Revert PHP skips on ZTS/PHP 7.0/7.1

---

tests/appsec/api_security/test_schemas.py

Fix broken test:
in c#, the api security model for value is a float, as we sometimes send some decimals for it, and not a string
the nullable field is nullable so it's a 1. I cant make it a string as it wouldnt pass other tests

[Api Security] Test_Schema_Request_FormUrlEncoded_Body expect float for value and 1 for nullable property 

---

manifests/python.yml
tests/integrations/crossed_integrations/test_kafka.py
tests/integrations/crossed_integrations/test_sqs.py
tests/integrations/test_dsm.py
utils/build/docker/nodejs/express4/app.js
utils/build/docker/nodejs/express4/integrations/messaging/aws/sqs.js
utils/build/docker/python/flask-poc.Dockerfile
utils/build/docker/python/flask/app.py
utils/build/docker/python/flask/integrations/messaging/rabbitmq.py

Enables more Kafka, and SQS tests for DSM and Trace Context Propagation.
Updates a few weblogs to have better comments, switches AWS SQS Context Propagation tests to use NodeJS Buddy since it is the only tracer buddy with SQS Propagation implemented in prod release. Also adds a few other random fixes.
🛟 …

enable/fix more DSM and Context Propagation Messaging Tests

---

tests/test_data_integrity.py

Fix Hex digit check on Datadog-Entity-ID

---

manifests/python.yml
tests/integrations/test_dsm.py

fix RabbitMQ DSM tests for dd-trace-py
A few tests should've been disabled. Also, the hashes and DSM edge tags needed to be corrected.

fix python rabbitmq tests

---

manifests/cpp.yml
manifests/dotnet.yml
manifests/golang.yml
manifests/java.yml
manifests/nodejs.yml
manifests/php.yml
manifests/python.yml
manifests/ruby.yml
tests/appsec/iast/_test_iast_fixtures.py
tests/appsec/iast/sink/test_insecure_auth_protocol.py
utils/_features.py
utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/IastSinkResource.java
utils/build/docker/java/resteasy-netty3/src/main/java/com/datadoghq/resteasy/IastSinkResource.java
utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/AppSecIast.java
utils/build/docker/java/vertx3/src/main/java/com/datadoghq/vertx3/iast/routes/IastSinkRouteProvider.java
utils/build/docker/java/vertx4/src/main/java/com/datadoghq/vertx4/iast/routes/IastSinkRouteProvider.java

Test INSECURE_AUTH_PROTOCOL detection in Java.
Define a new iast_sink_insecure_auth_protocol feature
Add new test_insecure_auth_protocol.py
Modify BaseSinkTestWithoutTelemetry to accept different headers for secure/insecure requests
Add endpoints for java frameworks
🛟 …

Add tests to insecure auth protocol

---

manifests/dotnet.yml
tests/appsec/iast/sink/test_nosql_mongodb_injection.py
utils/build/docker/dotnet/Controllers/IastController.cs
utils/build/docker/dotnet/Dependencies/MongoDbHelper.cs
utils/build/docker/dotnet/app.csproj

Add the dotnet tests for the NoSQL MongoDB Injection IAST vulnerability.
- Enable the 2 available tests for mongodb
- Integrate into the dotnet IastController the 2 endpoints.

[dotnet][IAST] Add NoSQL MongoDB Injection tests

---

utils/build/docker/dotnet/app.csproj
utils/scripts/load-binary.sh

Fix the run for the arm64 version. The weblog was failing because, the project was lacking of the arm64 version of the SQLite binaries.
- Change the SQLite dependency (that doesn't provide an arm64 version)

[dotnet] Fix dotnet project for arm64 architecture

---

manifests/cpp.yml
manifests/dotnet.yml
manifests/golang.yml
manifests/java.yml
manifests/nodejs.yml
manifests/php.yml
manifests/python.yml
manifests/ruby.yml
tests/parametric/test_trace_sampling.py

Updating Tests to include Feb 2024 revisions to the Extended Sampling API RFC
- glob case insensitivity
- glob extensions like set & range are forbidden
- glob special character handling
- matching of metrics in addition to meta
Introduced test classes Test_Trace_Sampling_Globs_Feb2024_Revision & Test_Trace_Tag_Sampling_Feb2024_Revision
:rocket: Once your PR is reviewed, …

Feb2024 Extended Sampling API Revision Tests

---

manifests/python.yml
tests/parametric/test_dynamic_configuration.py

Version 2.6.0 of ddtracepy was released recently and includes the functionality tested in this change.

enable remote tracing disablement test for python tracer

---

manifests/cpp.yml
manifests/dotnet.yml
manifests/golang.yml
manifests/java.yml
manifests/nodejs.yml
manifests/php.yml
manifests/python.yml
manifests/ruby.yml
tests/parametric/test_dynamic_configuration.py

The backend normalizes service and env values, so we need a test case that verifies such a scenario to make sure that a Tracer is case-insensitive of env or service name values.
Add sevice+env case-insensitivity test.
Extract service+env test to TestDynamicConfigV1_ServiceTargets.
Enable TestDynamicConfigV1_ServiceTargets for [the Java Tracer v1.30+](https://github.com/DataDog/dd-trace-java/pull/6636). …

Add sevice+env case-insensitivity test to TestDynamicConfigV1

---

manifests/dotnet.yml
tests/appsec/api_security/test_schemas.py

Activate scanners test for api security in dotnet
- activate the dotnet test in the scenario file
- cookies in dotnet can't contain spaces
- allow other values as in aspnet core (dotnet) headers come like key - values [] so it generates such an api security schema with nested arrays.
🛟 …

Add scenario and cases

---

.github/actions/install_runner/action.yaml
.github/actions/pull_images/action.yml
.github/workflows/ci.yml
.github/workflows/run-end-to-end.yml
.github/workflows/run-exotics.yml
.github/workflows/run-graphql.yml
.github/workflows/run-lib-injection.yml
.github/workflows/run-open-telemetry.yml
.github/workflows/run-parametric.yml
.github/workflows/system-tests.yml
.github/workflows/update-agent-protobuf.yml
docs/CI/github-actions.md

Allow `DataDog/system-tests/.github/workflows/system-tests.yml` to be called from a different repo
* `checkout` -> force system-tests repo to be checkout, rather than the calling repo

Allow the main workflow to be called in a distant workflow

---

manifests/cpp.yml
manifests/dotnet.yml
manifests/golang.yml
manifests/java.yml
manifests/nodejs.yml
manifests/php.yml
manifests/python.yml
manifests/ruby.yml
tests/appsec/iast/sink/test_reflection_injection.py
utils/_features.py
utils/build/docker/java/iast-common/src/main/java/com/datadoghq/system_tests/iast/utils/ReflectionExamples.java
utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/IastSinkResource.java
utils/build/docker/java/resteasy-netty3/src/main/java/com/datadoghq/resteasy/IastSinkResource.java
utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/AppSecIast.java
utils/build/docker/java/vertx3/src/main/java/com/datadoghq/vertx3/iast/routes/IastSinkRouteProvider.java
utils/build/docker/java/vertx4/src/main/java/com/datadoghq/vertx4/iast/routes/IastSinkRouteProvider.java

Test REFLECTION_INJECTION detection in Java.
Define a new iast_sink_reflection_injection feature
Add new test_reflection_injection.py
Add endpoints for java frameworks

Add Reflection Injection tests

---

.gitlab-ci.yml

Avoid commiting reports to system-tests-dashboard.
Push the results to FPD without commiting  on system-tests-dashboard

OnBoarding tests - FPD reports

---

utils/build/docker/cpp/nginx/install_ddtrace.sh

See opentracing-contrib/nginx-opentracing#586 , some assets are missing from their last release
Use v0.33 of opentracing-contrib/nginx-opentracing

Use v0.33.0 of opentracing-contrib/nginx-opentracing

---

tests/appsec/waf/test_addresses.py

Reduce false positive GRPC detection detections after signal review
Replaced grpc basic detection SQLi cases 

removing is_sqli basic test

---

utils/build/virtual_machine/provisions/container-auto-inject/auto-inject_container_manual.yml

Load installation "datadog-apm-library-lang" from binaries folder if exists

Fix OnBoarding container from binaries folder

---

.gitlab-ci.yml

We are not reporting all onboarding scenarios. This PR fixes it

OnBoarding fix FPD reports

---

tests/appsec/test_blocking_addresses.py
utils/interfaces/_agent.py
utils/interfaces/_library/core.py
utils/proxy/_deserializer.py

Support new data format. DataDog/dd-trace-py#8474
Support for msgpack in msgpack.
Decoded payload  (meta is collapsed in this screenshot) 
Add support for appsec json structure in meta struct in all tests. Tracers moving the data from meta to meta struct should not see any changes in system tests.
Tested with https://github.com/DataDog/dd-trace-py/pull/8474, both on CI and locally with all appsec tests  …

Support for meta_struct payloads in traces

---

tests/test_telemetry.py

Java will report telemetry config settings in snake_case. 
Supports both new snake_case and old Java format for reported config settings. See https://github.com/DataDog/dd-trace-java/pull/6694 that introduced snake_case formats

Java will report telemtry config settings in snake_case

---

tests/otel_tracing_e2e/_test_validator_trace.py

Fix span link comparison in opentelemetry e2e tests. The string -> int conversion may truncate leading 0s e.g. https://github.com/DataDog/opentelemetry-collector-contrib/actions/runs/7933164122/job/21661541009?pr=5257

[opentelemetry] Fix span link comparison

---

manifests/dotnet.yml
utils/build/docker/dotnet/Dependencies/KafkaHelper.cs
utils/build/docker/dotnet/Endpoints/DsmEndpoint.cs
utils/build/docker/dotnet/Endpoints/MessagingEndpoints.cs

ability to run Kafka tests with dotnet
Added 2 endpoints, `/kafka/produce` and `/kafka/consume`. The class where those lie will be extended in future PRs to integrate other messaging systems like RabbitMQ or SQS.

Add a kafka endpoint to the dotnet weblog

---

manifests/dotnet.yml
tests/appsec/iast/sink/test_reflection_injection.py
utils/build/docker/dotnet/Controllers/IastController.cs

Add the dotnet tests for the Reflection Injection IAST vulnerability.
- Enable the 2 available tests for the Reflection Injection
- Integrate into the dotnet IastController the 2 endpoints.

[dotnet][IAST] Add Reflection Injection tests

---

utils/build/docker/java/install_ddtrace.sh

We'll probably start shipping minified AppSec rules in Java. This requires tweaking the way we extract our AppSec rules version during build.
Use `jq` to extract AppSec rules version, regardless of whether it's pretty printed or minified.

Support minified AppSec rules in Java

---

utils/build/build.sh

On some systems, `docker run` fails without explicitly specifying the same platform args with which the image was built.
This PR adds platform args to the three `docker run` commands that lacked them.

Specify platform in docker run

---

tests/otel_tracing_e2e/_test_validator_log.py

The open telemetry manual started failing when we validate the "OTel log trace attributes". This PR fixes this problem

Fix Open-Telemetry-Manual scenario

---

tests/otel_tracing_e2e/_test_validator_log.py

Fix log validator for open telemetry manual

Fix open telemetry manual logs validator

---

manifests/python.yml

API Security sampling new algorithm prevents API Security tests from passing
This PR disables the tests until a more permanent fix is merged.

disable api sec tests for python until fix for sampling

---

tests/appsec/api_security/test_apisec_sampling.py

Revert a change made in #2166 to re-enable API Security sampling tests in Node.js

[nodejs] Re-enable API Sec sampling test for Node

---

manifests/dotnet.yml
tests/integrations/crossed_integrations/test_sqs.py
utils/build/docker/dotnet/Endpoints/DsmEndpoint.cs
utils/build/docker/dotnet/Endpoints/MessagingEndpoints.cs
utils/build/docker/dotnet/app.csproj

increase test coverage
Adding support for SQS in the dotnet weblog, & enabling the test that goes with it.
SQS support was merged in https://github.com/DataDog/dd-trace-dotnet/pull/4973 and will be available from the next tracer version.

add sqs endpoints for dotnet

---

manifests/python.yml
utils/_context/_scenarios.py

Once https://github.com/DataDog/dd-trace-py/pull/8578 will be merged, this PR can activate again API Security tests for Python.
Also add sample delay set to 0. in the scenario to ensure all requests will be used to compute schemas in the tests for all tracers with the new algorithm
🛟 …

activate python tests and sample delay to 0.

---

utils/build/docker/php/apache-mod/build.sh
utils/build/docker/php/php-fpm/build.sh

In dd-trace-php-1.0.0 we'll change the way how it's configured. It doesn't do any harm to have both in the INI, so until dd-trace-php-1.0.0 is release we'll just have both. That way system tests can still run on that branch.

Provide the new way to fetch the sources for PHP

---

utils/build/virtual_machine/provisions/container-auto-inject/auto-inject_container_manual.yml
utils/build/virtual_machine/provisions/host-auto-inject/auto-inject_host_manual.yml

OnBooarding tests were failing for Amazon linux 2 in local installation.

OnBoarding fix local installation amazon linux 2

---

.github/workflows/run-lib-injection.yml
.gitlab-ci.yml
utils/scripts/get_pr_merged_labels.sh

Fix pr labels: generate docker images lib-injeciton

---

manifests/dotnet.yml
manifests/golang.yml
manifests/java.yml
manifests/nodejs.yml
manifests/php.yml
manifests/python.yml
manifests/ruby.yml
tests/appsec/test_traces.py

The goal for this pr is to collect various headers from incoming headers which will help ASM with linking logs and traces.
See [rfc](https://docs.google.com/document/d/1xf-s6PtSr6heZxmO_QLUtcFzY_X_rT94lRXNq6-Ghws/edit?pli=1#heading=h.u0e1mc4e24ms) for more context
Link to [JIRA](https://datadoghq.atlassian.net/jira/software/c/projects/APPSEC/boards/5991?selectedIssue=APPSEC-52097) …

[APPSEC-51301] Add HTTP headers to collect

---

manifests/nodejs.yml

add node versions after apm uninstrumentation is released

Added node versions for test_telemetry

---

.github/workflows/run-end-to-end.yml
tests/integrations/test_dsm.py

There is massive failure when we run in replay mode for integrations scenario. The problems resides on test_dsm.py

Fix integrations dsm tests in replay mode

---

utils/build/docker/nodejs/express4-typescript/iast.ts
utils/build/docker/nodejs/express4/iast/sources.js

Missing try-catch in kafka key express4 and express4-typescript tests

Try catch nodejs kafka key consumer

---

run.sh
tests/k8s_lib_injection/conftest.py
tests/k8s_lib_injection/test_k8s_configmap_auto_inject.py
tests/k8s_lib_injection/test_k8s_manual_inject.py
utils/k8s_lib_injection/k8s_command_utils.py
utils/k8s_lib_injection/k8s_datadog_cluster_agent.py
utils/k8s_lib_injection/k8s_kind_cluster.py
utils/k8s_lib_injection/k8s_sync_kubectl.py
utils/k8s_lib_injection/k8s_weblog.py
utils/k8s_lib_injection/resources/kind-config-template.yaml
utils/k8s_lib_injection/resources/operator/operator-helm-values-auto.yaml
utils/k8s_lib_injection/resources/operator/operator-helm-values-uds.yaml
utils/k8s_lib_injection/resources/operator/operator-helm-values.yaml

Run k8s-lib-injection tests in parallel

k8s-lib-injection: run in parallel

---

.github/CODEOWNERS
tests/parametric/test_telemetry.py

Java has `logs_injection` enabled by default, which is a supported scenario @Kyle-Verhoog 
Allows `logs_injection_enabled` to be true for initial configurations

Log injection can be enabled by default

---

tests/remote_config/test_remote_configuration.py
utils/build/docker/php/apache-mod/entrypoint.sh
utils/build/docker/php/common/install_ddtrace.sh

Enable PHP RC ASM_FEATURES scenarios

---

tests/integrations/test_open_telemetry.py

open telemetry 2.2.0 released, and causes test failures for the obfuscation feature. The failure resides on the test. There are not detected any problem with the agent or collector.
https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases
🛟 …

Java OpenTelemetry Auto: Fix for 2.2.0 and obfuscation test issues

---

.github/workflows/run-lib-injection.yml
tests/k8s_lib_injection/conftest.py
tests/k8s_lib_injection/test_k8s_configmap_auto_inject.py
tests/k8s_lib_injection/test_k8s_manual_inject.py
utils/_context/_scenarios.py
utils/k8s_lib_injection/k8s_command_utils.py
utils/k8s_lib_injection/k8s_datadog_cluster_agent.py
utils/k8s_lib_injection/k8s_kind_cluster.py
utils/k8s_lib_injection/k8s_logger.py
utils/k8s_lib_injection/k8s_weblog.py
utils/k8s_lib_injection/resources/operator/operator-helm-values-auto.yaml

Enable tests for lib-injeciton auto and snapshot versions

Lib injection: auto lib-injection

---

.github/workflows/run-end-to-end.yml

CI was failing. typo on scenario name

Fix scenario name: DEBUGGER_PII_REDACTIONS

---

.github/workflows/run-lib-injection.yml

There is some bug in buildx 3. The generated images contain a bad manifest and the architectures are not correct. I can see unknown architecture
Use buildkit 2 again

Lib Injection: downgrade buildx version

---

tests/parametric/test_otel_api_interoperability.py
tests/parametric/test_otel_sdk_interoperability.py

Motivated by this [PR](https://github.com/DataDog/dd-trace-php/pull/2549) (e.g., [failure](https://app.circleci.com/pipelines/github/DataDog/dd-trace-php/15214/workflows/d67c3fa0-58a9-4584-87c1-cb3cffe343c4/jobs/4022316?invite=true#step-110-431)) - The Parametric Tests are failing because the comparison are too strict in some places.
Allow for more flexibility in the comparisons, and only test what's relevant. This will prevent test failures from unrelated features.
The Span Links's tracestate comparisons were purposefully left strict.
* Test logic is modified? -> Get a review from RFC owner. We're working on refining …

fix(otel): Strict attributes and tracestate comparisons

---

tests/parametric/test_headers_tracestate_dd.py

There is a bug since the release 2.7.2. Release 2.7.3 also contains the same bug, because this PR wasn't merged: https://github.com/DataDog/dd-trace-py/pull/8673 
This PR 

Parametric tarcestate: annotate bug python release

---

tests/test_library_logs.py

The [.NET Exception Debugging PR](https://github.com/DataDog/dd-trace-dotnet/pull/5163) has just been merged into [dd-trace-dotnet](https://github.com/DataDog/dd-trace-dotnet), and the [system-tests has started to fail](https://dev.azure.com/datadoghq/dd-trace-dotnet/_build/results?buildId=154612&view=logs&j=c26e76bd-da46-50ee-4755-0e58d94fc624&t=92993314-6f81-5dd3-7188-86548f340d7b) because it found a log pattern that contains the word 'Exception'. All the code of Exception Debugging in .NET is under a new namespace `ExceptionAutoInstrumentation`, so it falsely reporting it.
Added `Logger retrieved for: Datadog.Trace.Debugger.ExceptionAutoInstrumentation.ExceptionDebugging` to the `allowed_patterns` list.

Avoid alarming exceptions log pattern for Exception Debugging logger in .NET

---

tests/parametric/conftest.py

PHP spawns a sidecar which will have its own app lifecycle and send telemetry events itself. For the purpose of the system tests it's pure noise, which we have to ignore.
It leads to flakiness in some of our tests as ordering of these is not deterministic.

Ignore SIDECAR telemetry events

---

manifests/golang.yml
tests/appsec/waf/test_blocking.py

Enable all custom blocking response tests for Go now that the lib is finally aligned with the RFC.
Gin variant is disabled due to a bug.

go: enable custom blocking response tests

---

tests/test_telemetry.py

Reduces flakyness
This tests was checking something on app-started event. But if there is no `app-started`, the test was ok, leading to fan xpass if the feature is not implemented at all.

Remove false positive in telemetry test

---

manifests/php.yml
tests/appsec/test_rate_limiter.py
tests/parametric/test_128_bit_traceids.py
tests/parametric/test_headers_precedence.py
tests/parametric/test_headers_tracestate_dd.py
tests/remote_config/test_remote_configuration.py
tests/test_standard_tags.py

[AIT-9964](https://datadoghq.atlassian.net/browse/AIT-9964)
Enables passing PHP tests
[AIT-9964]: https://datadoghq.atlassian.net/browse/AIT-9964?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

tests: Enable PHP XPASS tests

---

manifests/python.yml
tests/test_semantic_conventions.py

We want more green
Activate already passing tests

python: activate more easy_wins

---

tests/k8s_lib_injection/conftest.py
tests/k8s_lib_injection/test_k8s_configmap_auto_inject.py
tests/k8s_lib_injection/test_k8s_manual_inject.py
utils/k8s_lib_injection/k8s_command_utils.py
utils/k8s_lib_injection/k8s_datadog_cluster_agent.py
utils/k8s_lib_injection/k8s_weblog.py
utils/k8s_lib_injection/k8s_wrapper.py

Wrap the kubernetes python client in order to apply a retry policy

k8s lib injection: api wrapper

---

manifests/golang.yml
manifests/nodejs.yml
manifests/ruby.yml

The debugger team started to implement features for `golang`, `ruby`, and `nodejs`. Thus, missing feature is a more accurate description of the situation.
Mark relevant tests as `missing feature` instead of `irrelevant`.

[Debugger] Mark golang, ruby and nodejs as missing feature

---

tests/appsec/iast/sink/test_path_traversal.py
tests/appsec/iast/sink/test_reflection_injection.py
tests/appsec/iast/sink/test_sql_injection.py
tests/appsec/iast/sink/test_ssrf.py
utils/build/docker/dotnet/Controllers/IastController.cs

Fix IAST tests that was reporting bad response code.
These tests were disabled after [this PR](https://github.com/DataDog/system-tests/pull/2262).
- Fixing some try/catch clause to not send 500. Only report 200 when the test successfully passed.
- Fixing some tests that weren't properly running
🛟 …

[dotnet][IAST] Fix tests with incorrect status code

---

.github/workflows/run-lib-injection.yml
requirements.txt
run.sh
tests/k8s_lib_injection/test_k8s_configmap_auto_inject.py
tests/k8s_lib_injection/test_k8s_manual_inject.py
utils/_context/_scenarios.py
utils/k8s_lib_injection/k8s_command_utils.py
utils/k8s_lib_injection/k8s_datadog_cluster_agent.py
utils/k8s_lib_injection/k8s_weblog.py
utils/k8s_lib_injection/k8s_wrapper.py

If we execute on system-tests-dashboard, we can't push the images because we don't have the permissions.
To asign the permissions, we need to configure the image on ghcr, but due to a issue we can't do it
The case is opened with github support
🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) …

k8s lib injection: Don't build weblog images on schedule run

---

manifests/java.yml
tests/parametric/test_dynamic_configuration.py

Current test behavior doesn't match the [spec](https://github.com/DataDog/instrumentation-telemetry-api-docs/blob/a12d385f8db705d776b625b6c77c5dcd61edfdb9/GeneratedDocumentation/ApiDocs/v2/SchemaDocumentation/Schemas/app_client_configuration_change.md)
Only checks for the telemetry events if the config changes.
🛟 …

Fix trace disablement test to properly test telemetry events

---

manifests/java.yml
tests/appsec/test_blocking_addresses.py
tests/appsec/waf/test_addresses.py

* Enable most tests for Payara. Skip some for 2 bugs (JIRA tickets in the skip reason).

[Java] Enable all test for Payara

---

tests/k8s_lib_injection/test_k8s_manual_inject.py
utils/k8s_lib_injection/k8s_datadog_cluster_agent.py

Add a new test on k8s lib injection test

K8s Lib Injection: New test added

---

tests/test_telemetry.py

With the implementation of Telemetry V2 (https://github.com/DataDog/dd-trace-rb/pull/3551), this PR updates system tests to work with the currently released `ddtrace` and to unlock testing when Telemetry V2 is released.

Upgrade Ruby to telemetry v2

---

manifests/golang.yml
tests/appsec/waf/test_blocking.py

Enable custom blocking response tests for Gin (previously marked as bug)

go: enable custom response tests for Gin

---

tests/otel_tracing_e2e/_test_validator_metric.py
tests/otel_tracing_e2e/test_e2e.py
utils/_context/_scenarios.py
utils/build/docker/java_otel/spring-boot-native/src/main/java/com/datadoghq/springbootnative/App.java
utils/build/docker/java_otel/spring-boot-native/src/main/java/com/datadoghq/springbootnative/WebController.java
utils/proxy/core.py

Cover OTLP metrics intake in OTel system test.
Extend system test `OTEL_METRIC_E2E` to cover the OTLP metrics intake scenario.

[OTEL-1734][opentelemetry] Extend test to OTLP metrics intake

---

docs/execute/README.md

update the slack channel to `#apm-shared-testing` in docs.

update slack channel to apm-shared-testing

---

tests/test_telemetry.py

The test `test_app_dependencies_loaded_not_sent` is not relevant anymore for telemetry. No more changes are required to the backend when sending `app-dependencies-loaded ` today.

Remove stale test_app_dependencies_loaded_not_sent

---

tests/appsec/waf/test_addresses.py

This was giving a xpass because it's testing for the current "parsed" body address, not the body.raw address, that is currently not in use.
Change the address from `server.request.body` to `server.request.body.raw`

Update address in body raw test

---

tests/appsec/test_customconf.py

Merge some tests with negative searchs to avoid false positive

---

tests/test_standard_tags.py

[Node.js] Enable test_client_ip_with_appsec_event_and_vendor_headers

---

manifests/dotnet.yml
manifests/golang.yml
manifests/java.yml
manifests/nodejs.yml
manifests/php.yml
manifests/python.yml
manifests/ruby.yml
tests/appsec/test_traces.py

Update in header spec to enforce collecting se headers: https://datadoghq.atlassian.net/wiki/spaces/APS/pages/2186870984/HTTP+header+collection
Add a test that check that Accept User agent and content-type header are sent in all spans

(asm) Add system test for collecting header by default in ASM

---

tests/debugger/test_debugger_base.py

Debug scenarios are failing when we execute in replay mode.

Fix: Debug scenarios in replay mode

---

tests/debugger/test_debugger_base.py

From `dotnet` tracer version 2.49.0 we will use `debugger` path instead of `logs`
Required for https://github.com/DataDog/dd-trace-dotnet/pull/5373
Use `dotnet` path

[Debugger] Use debugger path for dotnet instead of logs

---

utils/_context/_scenarios.py
utils/build/docker/python/flask/app.py
utils/build/docker/python/flask/integrations/db/mssql.py

We use weblog applications for some testing cases outside of system-tests. Being able to run without some of the most complex dependencies, like Sql Server driver or librdkafka is a plus in these cases.
* Inject environment variables like `INCLUDE_POSTGRES` to the weblog container, with `true` value if that service will be used in that scenario.
* Modify flask app to make some imports optional to these environment variables. …

Optional dependencies in python

---

tests/appsec/test_rate_limiter.py
tests/test_sampling_rates.py

[Node.js] re-enable sampling priority tests

---

utils/k8s_lib_injection/k8s_datadog_cluster_agent.py

There are some random failures waiting for the operator to be ready.
This PR catch the exception and retry

K8s Lib Injeciton: Debug failures

---

utils/_context/_scenarios.py

The Ruby library flushes on `at_exit`.
Timeouts:
- make things slow
- seem unneeded when the library flushes on `at_exit`/ `shutdown`.
- Set system test timeout to `0`.
- Optional: add a `/flush` endpoint to enforce flushing for all products.
🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) …

Remove timeout for Ruby

---

utils/build/docker/dotnet/Dependencies/RabbitMQHelper.cs
utils/build/docker/dotnet/Endpoints/MessagingEndpoints.cs

failure report by @cbeauchesne, showing a 500 error in the consumer
see #2302 as well
I think very much that this happens when we subscribe to a non-existing queue. Creating the queue is a noop if it already exists, so we can safely do that in the consumer to ensure it's there.
This is actually what's recommended in the official doc 🫥 https://www.rabbitmq.com/tutorials/tutorial-one-dotnet#receiving …

solve concurency error that could happen in dotnet rabbit consumer

---

utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/RejectedRequestConfig.java

[Java] Use 400 error rather than 500 for malformed requests

---

.vscode/launch.json
tests/appsec/test_blocking_addresses.py
tests/integrations/crossed_integrations/test_rabbitmq.py
tests/test_sampling_rates.py
utils/_context/_scenarios.py

* ~Mark RabbitMQ test as flaky on dotnet~
* enable xpass blocking_uri_raw on .NET
* Better ouput for test_sample_rate_function
* improve output of test_sample_rate_function
* Fix launch.json

skip dotnet failures

---

tests/appsec/test_blocking_addresses.py

fix appsec blocking

---

.github/workflows/run-lib-injection.yml
utils/k8s_lib_injection/k8s_command_utils.py

Run lib injection tests on largue runners.
Add debug options to helm chart

K8s Helm debug and CI largue runners

---

manifests/cpp.yml
tests/test_data_integrity.py
tests/test_semantic_conventions.py
tests/test_telemetry.py
utils/_context/_scenarios.py
utils/build/docker/cpp/nginx.Dockerfile
utils/build/docker/cpp/nginx/hello.html
utils/build/docker/cpp/nginx/install_ddtrace.sh
utils/build/docker/cpp/nginx/nginx.conf

Given that `dd-opentracing-cpp` is no longer actively developed, transitioning to dd-trace-cpp would be advantageous. As `nginx-datadog` relies on `dd-trace-cpp` internally and now supports several features and bug fixes that were previously marked as missing, this switch would ensure better compatibility and support for the current and future needs. …

weblog: Use nginx-datadog instead of dd-opentracing-cpp

---

manifests/cpp.yml
manifests/dotnet.yml
manifests/golang.yml
manifests/java.yml
manifests/nodejs.yml
manifests/php.yml
manifests/python.yml
manifests/ruby.yml
tests/parametric/test_dynamic_configuration.py
utils/parametric/spec/remoteconfig.py

WIP, sharing for co-programming.
System tests of remote sampling rules: its precedence with regard to other sampling mechanism (local rules/global rate etc), as well as the propagation of `_dd.p.dm` for the remote rules (user provided or dynamically configured).
Ran with and passed with this Go PR:
https://github.com/DataDog/dd-trace-go/pull/2643 …

Adding a new test case of remote sampling rules.

---

tests/parametric/test_headers_b3.py
tests/parametric/test_headers_b3multi.py
tests/parametric/test_headers_datadog.py
tests/parametric/test_headers_none.py
tests/parametric/test_headers_precedence.py

Skip python on failing tests on paramatric scenario

---

manifests/dotnet.yml

Debugger tests for dev are currently failing because of the bug.
Temporary disable debugger tests

[Debugger] Temporary disable debugger tests

---

.github/workflows/ci.yml
.github/workflows/run-docker-mode.yml

* Help users to see the issue when test the test, or lint job fails
* do not run unecessarelly CIs
Run ruby docker mode IIF test the test and lint are ok 

Run ruby docker mode iif lint and tests are ok

---

manifests/python.yml

Activate relevant test after https://github.com/DataDog/dd-trace-py/pull/8916
Already in the easywins of Python
APPSEC-52404

add default headers collections for ASM in python

---

manifests/dotnet.yml

This feature was added in .NET tracing library v2.49.0.
Mark the test as "should pass."

[.NET] Enable remote config test for `DD_TRACE_ENABLED` 

---

tests/test_telemetry.py

The test requires that you send the same `seq_id` twice when there's an error, but [the documentation explicitly states](https://github.com/DataDog/instrumentation-telemetry-api-docs/blob/main/GeneratedDocumentation/ApiDocs/v2/development.md#telemetry-message-retries) that we shouldn't retry messages. Given that this test relies on the backend (AFAICT), then if there's an error response, the agent passes it on, and we get flake
- Assert that the telemetry `seq_id` is always consecutive. 
- Try un-skipping some languages to see if they pass …

[Telemetry] Telemetry `seq_id` should always increase

---

manifests/dotnet.yml

These feature were added to the .NET tracing library in versions 2.46 and 2.48.
Mark the test as "should pass."

[.NET] enable trace sampling tests

---

utils/build/docker/nodejs/express4-typescript/iast.ts
utils/build/docker/nodejs/express4/iast/sources.js

Fix flaky nodejs kafka tests
Ensure consumed kafka messages are from our test

[nodejs][IAST] Fix flaky nodejs kafka tests

---

manifests/dotnet.yml

After parametric sampling test activation for dotnet, there are some test failures.
I revert the change and mark the tests again as missing_feature

DotNet: Parametric sampling - revert

---

manifests/java.yml
tests/appsec/iast/_test_iast_fixtures.py
tests/appsec/iast/source/test_body.py
tests/appsec/iast/source/test_cookie_value.py
tests/appsec/iast/source/test_header_value.py
tests/appsec/iast/source/test_parameter_value.py

Reduce XPASS related with IAST metrics. Improve our false positives in easy wins.
Same approach that was implemented to reduce the easy wins related with secure endpoints in iast test, now for metrics. Metrics tests don't matter if the feature is not implemented.
🛟 …

Improve iast telemetry test easy wins

---

manifests/python.yml

Following https://github.com/DataDog/dd-trace-py/pull/8925, activate the test for that feature. (Already in easy wins since yesterday)
APPSEC-52393

chore(python): add one more test

---

manifests/python.yml

There are failures on the test "": Test_Trace_Sampling_Tags_Feb2024_Revision::test_metric_matching
Errors: 
```
def assert_matching_span(self, test_agent, **kwargs):
matching_span = find_span_in_traces(test_agent.wait_for_num_traces(1), Span(**kwargs))
>       assert matching_span["metrics"].get(SAMPLING_PRIORITY_KEY) == 2
E       AssertionError: assert -1 == 2
E        +  where -1 = <built-in method get of dict object at 0x7f6f3caff0c0>('_sampling_priority_v1')
E        +    where <built-in method get of dict object at 0x7f6f3caff0c0> = {'_dd.rule_psr': 0.0, '_dd.top_level': 1, '_dd.tracer_kr': 1.0, '_sampling_priority_v1': -1, ...}.get
tests/parametric/test_trace_sampling.py:411: AssertionError
```
Disable the failing test
2. Work on you PR until the CI …

Parametric: mark as bug python sampling (Tags Feb2024 Revision)

---

manifests/python.yml

Reverts DataDog/system-tests#2332
Because 2.8 branch is reporting the same version number, hence the 2.8 backports are failing to pass this test, preventing them from being merged.

Revert "chore(python): add one more test"

---

manifests/java.yml
tests/test_telemetry.py

Enabling more telemetry tests in Java.
* Split telemetry metrics test case, one per metric.
* Enable these for Java, and skip those for unimplemented metrics.

Enable more telemetry tests in Java and split metrics test cases

---

manifests/python.yml

decorators in tests are deprecated and manifest is the correct way to declare which test class must run.
Also improve linting of the python manifest
- remove unrequired spaces
- use ' for strings everywhere
- use the same comment everywhere for unknown version
add parametric tests to python manifest
🛟 …

move parametric to manifest for python

---

manifests/python.yml
tests/parametric/test_dynamic_configuration.py
tests/parametric/test_otel_tracer.py
tests/parametric/test_tracer.py

activate a few more passing tests

chore(python): activate more tests

---

manifests/dotnet.yml
tests/parametric/test_otel_span_with_w3c.py

Since we have some tests with the xpass status, we want to enable them so any regressions are immediately detected.
Updates the `manifests/dotnet.yaml` and one in-line `@missing_feature` annotation for dotnet.

Enable some xpass tests for dotnet

---

tests/appsec/waf/test_telemetry.py

The issue was close and there is no reason to keep that decorator.
Remove one flaky decorator for django

remove flaky decorator for python

---

tests/appsec/waf/test_addresses.py

`test_specific_key2` is a very strict test and it should pass for all reasonnable implementation of blocking feature
Many frameworks replace underscore with dash to normalize header names. Allow that behaviour in that test too.
Known impacted frameworks:
- Flask (Python)
- Django (Python)
- Rack (Ruby)
- ...
🛟 …

less strict test for Test_Headers

---

manifests/java.yml
tests/appsec/test_reports.py

These tests were passing if the library did not implement AppSec at all (no appsec events, no iteration, no assert).
* Ensure the tests assert the existence of the expected data.
* Minor refactor to have more descriptive tests (rather than `test_basic`).
🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C0 …

Avoid false XPASS in test_reports.py

---

manifests/dotnet.yml
tests/appsec/iast/sink/test_insecure_auth_protocol.py
utils/build/docker/dotnet/Controllers/IastController.cs

Add insecure auth protocol test for dotnet

---

manifests/cpp.yml
manifests/dotnet.yml
manifests/golang.yml
manifests/java.yml
manifests/nodejs.yml
manifests/php.yml
manifests/python.yml
manifests/ruby.yml
tests/parametric/test_telemetry.py

This PR enables the check for `DD_APPSEC_SCA_ENABLED` env variable. This variable and it's value is sent through telemetry if set, otherwise it's not sent.
See RFC: https://docs.google.com/document/d/1xTLC3UEGNooZS0YOYp3swMlAhtvVn1aa639TGxHHYvg/edit
Jira: APPSEC-52424
Two more parametric tests for the app-started event, one with the variable set, other with it unset. …

DD_APPSEC_SCA_ENABLED env var test

---

manifests/python.yml
tests/parametric/test_headers_b3.py
tests/parametric/test_partial_flushing.py

- Replace missing features with flaky in manifest for flaky parametric tests
- Remove deprecated missing feature decorator in a parametric test
- Replace one missing feature decorator with the more accurate bug decorator.
- activate Test_Environment for 2.9.0.dev (no flakyness detected anymore)
🛟 …

update manifest and parametric test to manage easy wins for python

---

manifests/java.yml
tests/appsec/waf/test_miscs.py

* This test will never fail, because it checks a log that is not used anymore.
* If we want to bring it back, we'd probably need to check any of `_dd.waf.timeouts`  tags of telemetry metrics on tracers that support them.
* Remove `Test_NoWafTimeout`. …

Remove Test_NoWafTimeout

---

docs/scenarios/parametric.md

If you `cp` using the currently provided wildcard you may get more JARs than required and that breaks things elsewhere in the testing process.
Remind user to confirm only copying two required JARs.

Copy only two JARs to binaries dir

---

tests/appsec/api_security/test_schemas.py

Per title.
Also skipping the test for PHP as it's currently failing, wait EOD before merging

Improve output for appsec_api_security

---

manifests/dotnet.yml
manifests/golang.yml
manifests/java.yml
manifests/nodejs.yml
manifests/php.yml
manifests/python.yml
manifests/ruby.yml
tests/appsec/test_blocking_addresses.py
tests/appsec/waf/test_blocking.py

Standardize a previously undefined behavior in the blocking response.
Add a new test that make sure response headers set by the app are not leaked through the blocking response.

add test to make sure headers are stripped from blocking response

---

tests/auto_inject/test_auto_inject_install.py
utils/_context/_scenarios.py
utils/build/virtual_machine/provisions/host-auto-inject-ld-preload/ld-preload.yml
utils/build/virtual_machine/provisions/host-auto-inject-ld-preload/main.c
utils/build/virtual_machine/provisions/host-auto-inject-ld-preload/provision.yml

Adding new onboarding scenario in order to test different "ld.so.preload" status before installing the auto injection software

Add new onboarding tests scenario

---

manifests/ruby.yml

Activate SCAEnvVar test for the next release (1.23.0)
Activate ExternalWAFRequestId for current release (1.22.0)

[Ruby] Activate SCAEnvVar and ExternalWAFRequestId test

---

manifests/java.yml
tests/appsec/iast/sink/test_trust_boundary_violation.py

Trust boundary violation tests were passing for Java

[java] Enable trust boundary violation tests for java

---

.github/workflows/run-parametric.yml
tests/parametric/test_headers_b3.py
utils/build/docker/ruby/parametric/server.rb

Fix ruby parametric with GRPC propagation

Fix ruby parametric with GRPC propagation

---

utils/interfaces/schemas/miscs/telemetry/common/objects/logs.json

The telemetry logs schema validation is incorrect
Change the `tracer_time` property to be `number` instead of `string`

[Telemetry] Fix telemetry logs schema

---

tests/test_telemetry.py

This scenario passed on GraalVM, where we do not implement telemetry at all.
* Assert that we receive telemetry (this scenario should have all telemetry working except metrics).
* Make the assert more informative (it'll print contents if it fails). …

Avoid Test_Metric_Generation_Disabled XPASS if telemetry is not implemented or broken

---

manifests/nodejs.yml
tests/test_identify.py

We support these feature but only the incoming part.

[nodejs] Enable incoming identify.py tests

---

.github/actions/lint_code/action.yaml
.github/workflows/run-lib-injection.yml

Fix warning on lib-injection CI

---

.github/workflows/run-end-to-end.yml
conftest.py
tests/remote_config/test_remote_configuration.py
tests/test_schemas.py
utils/_context/_scenarios.py
utils/interfaces/_agent.py
utils/interfaces/_core.py
utils/interfaces/_library/core.py
utils/interfaces/_schemas_validators.py
utils/interfaces/schemas/agent/api/v2/debugger-request.json
utils/interfaces/schemas/library/debugger/v1/diagnostics-request.json
utils/interfaces/schemas/library/debugger/v1/input-request.json

Simpler API for testing schema
* The default check verifies all points, excluding failing ones
* Excluded point are checked individually in a dedicated test method (one per point), skipping the lib that are failing
* And schema tests are activated for all end-to-end scenarios
🛟 …

Better schema test logic API

---

manifests/golang.yml
tests/appsec/waf/test_rules.py

Increase system-tests easy wins value

[go] easywins

---

tests/remote_config/test_remote_configuration.py

* removes `test_client_state_errors`, as it;'s already checked by schemas in https://github.com/DataDog/system-tests/blob/main/utils/interfaces/schemas/library/v0.7/misc/config-state.json#L23
* revamp a little bit the RC test to prevent XPASS on appsec feature
🛟 …

Removes test_client_state_errors

---

utils/build/docker/python/flask/app.py

to avoid error if directory exists
There is an exception thrown in the weblog code and it's confusing we're not catching it.
Just a try/except block

[python] catch exception

---

tests/appsec/waf/test_telemetry.py

Marked as flaky for everyone, it's useless to keep it

Remove Test_TelemetryResponse class

---

utils/build/docker/nodejs/parametric/server.js

Spans in a parametric application should not be deleted when a span is finished. This makes it difficult to test the state of the a finished span. Spans should be removed from parametric apps when the tracer is flushed. 
This change brings the node parametric app in-line with parametric apps written for other libraries (ex: otel, ruby, python, go, php).
:rocket: Once your …

parametric(node): flush spans on tracer flush

---

utils/build/docker/nodejs/nextjs/src/app/tag_value/[tag]/[status]/route.js

The test is a false positive easy-win that we can't figure out how to fix.
When the `DD_API_SECURITY_PARSE_RESPONSE_BODY` env var is used, the test will fail on purpose with "not implemented".

[nodejs] special case to avoid false positive easy win

---

manifests/python.yml

- one parametric test marked as flaky 
- one parametric test enabled
- one remote config test enabled
APPSEC-52926

[python] update python manifest

---

tests/appsec/waf/test_addresses.py
utils/build/docker/python/django/app.sh
utils/build/docker/python/django/app_3.12.sh
utils/build/docker/python/flask/app.sh
utils/build/docker/python/python3.12.Dockerfile

- remove bug decorator for waf header tests (this was fixed for Django previously)
- enable gunicorn to manage those headers in Flask by adding the appropriate option (by default, they were entirely dropped by gunicorn)
APPSEC-52926

[python] fix header test for python

---

manifests/golang.yml
tests/parametric/test_dynamic_configuration.py

This is to avoid a conflict with the duplicate value `-10` used by data jobs.
The Go tracer change is also being made and will be released in `1.63.1`.

Fixes decision maker tag values for remote user rules and dynamic rules

---

manifests/python.yml
tests/parametric/test_telemetry.py

Fixing a test that shouldn't be flaky
Increases wait time for the telemetry event to arrive

fix flaky sca env var test

---

tests/appsec/iast/sink/test_hardcoded_passwords.py

Hardcoded password is reporting now the variable name as the evidence value.
marking it as `@missing_feature` until tracer PR merged

[iast] Hardcoded password vulnerability - variable name as evidence value

---

utils/build/docker/postgres-init-db.sh

some linux users are getting permissions problems when starting postgres container due `postgres-init-db.sh` file flags

Include a note for guidance on the postgres init permission error

---

manifests/nodejs.yml
tests/appsec/iast/sink/test_hardcoded_passwords.py

Hardcoded password is reporting now the variable name as the evidence value.
Remove `@missing_feature` and update nodejs manifest

[iast] Hardcoded password vulnerability test

---

tests/appsec/test_conf.py

No flaky tests
https://datadoghq.atlassian.net/browse/APPSEC-53058

[python] Skip low waf timout test as flaky

---

manifests/python.yml
tests/appsec/test_conf.py
tests/appsec/test_event_tracking.py
tests/appsec/test_ip_blocking_full_denylist.py
tests/appsec/test_user_blocking_full_denylist.py

Activate more tests or test parts for python appsec

[python] more easywins for python appsec

---

utils/_context/_scenarios.py

We need faster test and waiting time seems to be larger than needed right now for python

[python] decrease the waiting time for python libraries from 25s to 5s

---

manifests/python.yml
utils/build/docker/python/flask/app.py

Enable Code Security (IAST) source parameter value

[python] enable iast source parameter value

---

manifests/python.yml
utils/_context/containers.py
utils/build/docker/python/django/app.sh

Enable python 3.12 IAST tests https://datadoghq.atlassian.net/browse/APPSEC-53107

[python] enable python 3.12 IAST tests

---

utils/build/docker/python/install_ddtrace.sh

We are considering add rust native extensions to the dd-trace-py Python package. In order to support that, we need a rust compiler available for us.
Install rust compiler during `install_ddtrace.sh`.
I decided on `install_ddtrace.sh` instead of adding to the base images to make it potentially easier to keep build dependencies in one place. …

[python] ensure rust compiler is available for package install

---

utils/build/docker/python/install_ddtrace.sh

The change #2454 did not add /root/.cargo/bin to the path, so even though it is installed, rust is still not available to ddtrace install.
Add /root.cargo/bin to the $PATH

[python] ensure rustup is on the PATH

---

utils/build/docker/nodejs/nextjs/src/app/tag_value/[tag]/[status]/route.js

Some test from NextJS variant were failing due to json body was nos correctly consumed (form data body was correctly consumed).
Refactor `getBody` function to check content type header and consume body properly.

[nodejs] Refactor NextJS getBody to properly consume request body

---

manifests/python.yml

After this PR https://github.com/DataDog/dd-trace-py/pull/9307 (fix(asm): enabling builtins.open sink point) we can revert this system-tests PR https://github.com/DataDog/system-tests/pull/2449

[python] enabling builtins.open sink point

---

utils/_context/_scenarios.py
utils/build/docker/nodejs/express4/integrations/db/postgres.js

NodeJS weblog was erroring when trying to run otel tests due to ddtrace require statement.
Hide the require behind a try catch with an if statement.

fix nodejs otel integration test error

---

utils/build/docker/python/parametric/ddtracer_version.Dockerfile

`curl` is needed to install `rustup`. It was available in the other scenario containers, but was missing from the parametric image.
Install `curl` in the Python parametric image.

[python] ensure curl is available for parametric container

---

utils/_context/virtual_machines.py

Security
Bumps the `AmazonLinux2023` AMIs to resolve [security issues](https://app.datadoghq.com/security/csm/vm?query=cve%3ACVE-2024-21626%20&column=desc&group=none&order=desc&sort=score&vulnerability=0ed099173a71810eeaadf74ff2aee9f5) found by signals
Note that custom cache AMIs will need to be deleted
🛟 …

chore(security): Bump AmazonLinux2023 AMIs

---

manifests/python.yml
tests/appsec/rasp/test_span_tags.py

- enable span tag rasp tests for python tracer
- look for the span tags in `_dd` namespace

enable spantag rasp tests for python tracer

---

tests/test_schemas.py
tests/test_telemetry.py

Skip failing test on agent telemetry payloads

---

utils/build/virtual_machine/provisions/installer-auto-inject/provision.yml
utils/virtual_machine/aws_provider.py

Less failures
- An env var to check if we're running the tests locally or not - to avoid updating the python at each check
- Properly use the docker mirror in installer tests

fix(installer): Fix docker rate limiting & add local test env var

---

.github/workflows/run-parametric.yml
manifests/cpp.yml
tests/parametric/conftest.py
utils/build/docker/cpp/parametric/install_ddtrace.sh

https://github.com/DataDog/dd-trace-cpp/pull/119 changes build argument.
Prod is failing for this exact reason. Since,  `dd-trace-cpp@HEAD` is not as I considered prod. Could you change the system-test to only consider the latest release as …

build(cpp): Update build args for dd-trace-cpp

---

tests/parametric/test_telemetry.py

This fixes a test failure with https://github.com/DataDog/dd-trace-js/pull/4322. That PR modifies the default for `profiling_enabled` in our Node.js tracer from `false` to `undefined` as for SSI-enabled profiling we need the ability to distinguish between explicitly specified `DD_PROFILING_ENABLED=false` env var and `DD_PROFILING_ENABLED` not being set; now the `undefined` value represents this latter condition.
Adds `None` to the list of acceptable values. Note this is rather analogous to [`05b08aa` (#2172)](https://github.com/DataDog/system-tests/pull/2172/commits/05b08aa4eef210ecf824f112eef7fd3e689600aa).
* Test …

PROF-9791: Allow None as default for profiling_enabled

---

tests/integrations/test_dsm.py
utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/App.java
utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/aws/KinesisConnector.java
utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/aws/SnsConnector.java
utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/aws/SqsConnector.java
utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/kafka/KafkaConnector.java
utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/rabbitmq/RabbitmqConnector.java
utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/rabbitmq/RabbitmqConnectorForDirectExchange.java
utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/rabbitmq/RabbitmqConnectorForFanoutExchange.java
utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/rabbitmq/RabbitmqConnectorForTopicExchange.java

Fix for flaky DSM tests with the Java app.
Adds `thread.join()` calls to all the calls to produce/consume.  Also updates method signatures to allow this to happen.

[Java] DSM: Fix kafka test flakiness

---

utils/build/virtual_machine/provisions/installer-auto-inject/provision.yml

Installer tests are broken
Following a change in the agent the injector must be installed first - this is enforced in the install script but we don't use it here because we need to override the packages.

fix(installer): Fix ordering

---

manifests/dotnet.yml

After the new .Net tracer release, the in RASP span metrics are supported. The tests that test this feature have been enabled.

[ASM] Add RASP in span metrics tests (.Net)

---

.gitignore
pyproject.toml
tests/test_the_test/test_version.py
utils/_context/_scenarios.py
utils/_context/containers.py
utils/_context/library_version.py

Faster launch
* do not execute a docker command to get agent version, but rather get it from `/info` (as it's already called for healthcheck)
* remove useless cleans on agent version string

Remove unecessary command call to agent container

---

manifests/golang.yml
tests/parametric/test_otel_span_methods.py
utils/build/docker/golang/parametric/otel.go

enable otel span link system tests for golang & separate span link attribute validation into its own test
enable otel span link tests for golang
update golang parametric server to create span links & isolate attribute validations from existing span link system tests into a separate system test

enable otel span link system tests for golang

---

.gitlab-ci.yml
utils/build/virtual_machine/weblogs/nodejs/provision_test-app-nodejs-container.yml
utils/build/virtual_machine/weblogs/nodejs/test-app-nodejs-container/Dockerfile.template
utils/build/virtual_machine/weblogs/nodejs/test-app-nodejs-container/test-app-nodejs_docker_compose_run.sh
utils/build/virtual_machine/weblogs/python/provision_test-app-python-container.yml
utils/build/virtual_machine/weblogs/python/test-app-python-container/Dockerfile.template
utils/build/virtual_machine/weblogs/python/test-app-python-container/test-app-python_docker_compose_run.sh
utils/build/virtual_machine/weblogs/ruby/provision_test-app-ruby-container.yml
utils/build/virtual_machine/weblogs/ruby/test-app-ruby-container/Dockerfile.template
utils/build/virtual_machine/weblogs/ruby/test-app-ruby-container/test-app-ruby_docker_compose_run.sh

Having installer-based injection system tests working for all languages
- Adds more test scenarios to scheduled injection tests to add all installer-based scenarios
- Override Dockerfiles used in VM scenarios to `public.ecr.aws` to avoid Docker rate limits
🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/ …

upgrade(tests): Add installer-based regular injection tests

---

.github/workflows/run-parametric.yml
manifests/cpp.yml
tests/parametric/test_dynamic_configuration.py
tests/parametric/test_headers_tracecontext.py
tests/parametric/test_trace_sampling.py

dd-trace-cpp released a new version two days ago. This PR enable prod and enable more parametric tests.
- CI
- Parametric tests for cpp

parametric(cpp): enable prod and more parametric tests

---

manifests/python.yml
tests/appsec/iast/sink/test_ssrf.py

Enable login user event tests for flask variants and one iast SSRF test.

[python] more easy wins

---

utils/build/virtual_machine/provisions/installer-auto-inject/provision.yml

Some system tests are failing
Bumping the injector OCI version

fix(system-tests): Bump installer-based injector version

---

tests/appsec/test_automated_login_events.py

Small fix to revert a print introduced in https://github.com/DataDog/system-tests/pull/2524

remove debugging print

---

manifests/cpp.yml
manifests/dotnet.yml
manifests/golang.yml
manifests/java.yml
manifests/nodejs.yml
manifests/php.yml
manifests/python.yml
manifests/ruby.yml
tests/parametric/test_otel_env_var.py
tests/parametric/test_otel_env_vars.py
tests/parametric/test_telemetry.py
utils/build/docker/nodejs/parametric/server.js
utils/parametric/_library_client.py
utils/parametric/protos/apm_test_client.proto

adds system tests for OTEL env var to DD env var mapping 
adds a new test telemetry test to test telemetry metrics, a new otel env var test file under parametric/ to test correct mapping, & new http/grpc routes for sending config data from the test app

add system tests for otel env var mapping

---

manifests/python.yml
tests/parametric/test_otel_env_vars.py
utils/build/docker/nodejs/parametric/server.js
utils/build/docker/python/parametric/apm_test_client/server.py
utils/parametric/_library_client.py

Run tests in `tests/parametric/test_otel_env_vars.py` with the python parametric app

parametric(otel_env): run tests for python

---

tests/parametric/test_otel_span_methods.py

.NET array encoding changed in a recent PR, and so now system tests are broken on master
Disables the legacy test, and enables the "new encoding" test

[dotnet] Try fix parameteric tests

---

tests/parametric/test_otel_span_methods.py
utils/build/docker/nodejs/parametric/server.js

enabling span events and record exception system tests for node.js
enables span events and record exception system tests for node.js along with separating record exception serialization test into two since node.js does not support attributes for the record exception api

enable node span events system tests

---

manifests/dotnet.yml
manifests/golang.yml
manifests/java.yml
manifests/nodejs.yml
manifests/php.yml
manifests/python.yml
manifests/ruby.yml
tests/appsec/test_automated_login_events.py
utils/_context/_scenarios.py

Add two tests classes 'V2'. The plan is that each tracer will stop conforming to V1 tests and use V2 to implement the new RFC.
- The first class `Test_V2_Login_Events` will use the DEFAULT scenario and check the default mode "identification"
- The second class `Test_V2_Login_Events_Anon` will use the APPSEC_AUTO_EVENTS_EXTENDED scenario and check the new mode "anonymization"
APPSEC-53571 …

ASM: tests for new User Id collection RFC [ATO]

---

manifests/python.yml

We are changing implementation of the user event feature. We need to deactivate the tests for the old feature to be able to add the new feature. The new feature will be tested later with the V2 version of the tests.
APPSEC-53571

[python] remove old Test_Login tests for python

---

tests/parametric/test_dynamic_configuration.py

[ruby] Skip failing parametric test

---

utils/onboarding/injection_log_parser.py

[Auto injection tests] Remove telemetry logs from the logs we use to verify the blocklist is implemented

---

.dockerignore
manifests/dotnet.yml
tests/parametric/conftest.py
utils/build/docker/dotnet/parametric/.dockerignore
utils/build/docker/dotnet/parametric/Dockerfile

This reverts commit 267542c0a60ca8094bdee522e6badf685cf5e6bf.
The original PR #2320 enabled sampling tests for .NET.
The tests were failing, so they were reverted in #2331.
This PR attempts to enable the tests again.
- enable some sampling tests for .NET
- effectively disable the sampling rate limiter by default in parametric tests by setting `DD_TRACE_RATE_LIMIT=10000000`
- bonus: add more entries to `.dockerignore` files to enable easier local .NET builds
* Framework is modified, or non obvious usage of …

[.NET] enable parametric trace sampling tests, redux

---

manifests/java.yml
tests/appsec/test_ip_blocking_full_denylist.py
tests/appsec/test_user_blocking_full_denylist.py
utils/build/docker/java/akka-http/src/main/scala/com/datadoghq/akka_http/AppSecRoutes.scala
utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/MyResource.java
utils/build/docker/java/play/app/controllers/AppSecController.scala
utils/build/docker/java/play/conf/routes
utils/build/docker/java/ratpack/src/main/java/com/datadoghq/ratpack/Main.java
utils/build/docker/java/resteasy-netty3/src/main/java/com/datadoghq/resteasy/MyResource.java
utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/App.java
utils/build/docker/java/vertx3/src/main/java/com/datadoghq/vertx3/Main.java
utils/build/docker/java/vertx4/src/main/java/com/datadoghq/vertx4/Main.java

* Add `/users` endpoint in Java.
* Enable IP and user blocking tests ([APPSEC-51385](https://datadoghq.atlassian.net/browse/APPSEC-51385)).
[APPSEC-51385]: https://datadoghq.atlassian.net/browse/APPSEC-51385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[java] Enable some blocking test and simplify asserts

---

tests/appsec/test_automated_login_events.py

- fix a small error (wrong assertions)
- add check for user.id when user does not exist

update test for user events

---

tests/appsec/iast/sink/test_insecure_auth_protocol.py

User event tracking test use basic authentication that might cause the vulnerability to not be triggered depending on the order of execution of the tests. 
Use digest instead of basic for the insecure auth protocol test.

Use digest auth instead of basic in the insecure auth protocol test

---

tests/appsec/test_automated_login_events.py
utils/build/docker/java/spring-boot/pom.xml
utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/WebSecurityConfig.java
utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/security/AppSecAuthenticationFilter.java
utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/security/AppSecAuthenticationProvider.java
utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/security/AppSecSdkToken.java
utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/security/AppSecUser.java

Add support to test auto user login events in java.
Updates the spring-boot weblog to include support for the login endpoints

[java] Add support for auto user events in java

---

manifests/dotnet.yml
tests/parametric/test_dynamic_configuration.py
utils/build/docker/dotnet/parametric/Endpoints/ApmTestApi.cs

Our .NET SDK added support for remote sampling rules in 2.53.2, so we can enable these tests.
Enable .NET tests for sampling rules over remote configuration (RCM).
Bonus: add support for adding span tags in .NET parametric tests (will be used in another test soon)
🛟 …

[.NET] enable parametric tests for remote sampling rules

---

tests/auto_inject/test_auto_inject_install.py
utils/build/virtual_machine/weblogs/dotnet/test-app-dotnet-container/test-app-dotnet_docker_compose_run.sh

Current hypothesis is that we're hitting https://github.com/paramiko/paramiko/issues/515, so this PR tries to implement the suggested https://github.com/paramiko/paramiko/issues/109#issuecomment-111621658 fix.
Implements https://github.com/paramiko/paramiko/issues/109#issuecomment-111621658 for our use case
🛟 …

fix(installer): Close stdout when not closed

---

tests/parametric/test_headers_b3.py

In `tests/parametric/test_headers_b3.py`:
- `test_headers_b3_migrated_extract_valid` was calling `test_headers_b3_migrated_extract_invalid`
(note: `valid` vs `invalid`)
Call the correct test.

fix calling the wrong B3 headers test

---

manifests/dotnet.yml
tests/parametric/test_128_bit_traceids.py
tests/parametric/test_headers_b3.py
tests/parametric/test_otel_span_methods.py
tests/parametric/test_otel_tracer.py

These test are getting `XPASS` results for .NET.
Enable the tests.

[.NET] enable XPASS parametric tests for dotnet

---

.github/workflows/run-end-to-end.yml
.github/workflows/system-tests.yml
utils/scripts/compute_impacted_scenario.py

Do not runn the default scenario by default in reusable workflow

---

tests/parametric/test_dynamic_configuration.py

Enable another parametric test for remote sampling rules in .NET.
Follow up from #2553, where we enabled `TestDynamicConfigSamplingRules`, but skipped `test_trace_sampling_rules_with_tags` because it was failing for two reasons:
- the .NET test app app did not support adding span tags, fixed in #2553
- the .NET SDK was looking at local sampling rules as a fallback when no remote rules matched, the expected behavior is to ignore all local rules if remote rules are configured (even if none of them match), fixed in DataDog/dd-trace-dotnet/pull/5720
Enable this test.
```
test_dynamic_configuration.py
TestDynamicConfigSamplingRules
test_trace_sampling_rules_with_tags
```
2. Work on you PR until the CI passes (if something not related to your task is failing, …

[.NET] enable another parametric test for remote sampling rules

---

.gitattributes
utils/scripts/compute_impacted_scenario.py

Make it easier to build and run .NET tests locally on Windows.
Add a root `.gitattribute` file to keep the Linux-style LF line endings in `*.sh` files, even on Windows. This removes the need to change line endings manually or to install and run the `dos2unix` tool inside .NET docker images.
🛟 …

add `.gitattributes` file

---

docs/RC/RC-API.md
tests/appsec/test_automated_login_events.py
tests/appsec/test_runtime_activation.py
utils/_remote_config.py

Some RC test scenarios might require using multiple config files at the same time to validate correct behavior.
Add support for multiple config files in RC payloads.

Allow multiple config files in RC payloads

---

tests/parametric/test_headers_tracecontext.py

The Java trace agent was not correctly clearing context between spans.
This test confirms that the previously leaked context is now cleared between spans.

Add trace ID high order bits context leak test

---

utils/onboarding/injection_log_parser.py

The last changes in auto_inject imply changing our log parser, to keep detecting the commands ignored by user rules, by rules related to their arguments

OnBoarding: Fix log parser

---

tests/test_data_integrity.py

Update tests to support `datadog-external-env` header and new entity id prefix as defined in the [new RFC](https://datadoghq.atlassian.net/wiki/spaces/CONTP/pages/3731783774/New+Origin+Detection+Spec+for+Traces+and+DogStatsD)
- Add `ci` as a valid prefix for `entity-id`
- Add test for `datadog-external-env` format
🛟 …

Add tests for external env

---

tests/appsec/blocking_rule.json
tests/appsec/test_blocking_addresses.py

OpenLiberty sets `Content-Language: en-US` on responses by default. Using this value in our test rules for blocking makes it trigger for every request. We could workaround this on the weblog side, but using a more uncommon value is simpler.
* ~[ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change~

Avoid blocking on content-language: en-us

---

utils/build/virtual_machine/provisions/host-auto-inject-install-script/auto-inject_host_script.yml

The agent linux installer script was released with the fix for failing on empty `/etc/environment`, making the workaround obsolete.
Removes the VM setup remote command that ensured `/etc/environment` is not empty.

PROF-9979: Remove the workaround now that installer script has been fixed

---

utils/build/build.sh

I tried running the example below from `build.sh --help` and it failed.
```
OPTIONS
[...]
--default-weblog           Prints the name of the default weblog for a given library and exits.
EXAMPLES
[...]
Print default weblog for Python:
./utils/build/build.sh --default-weblogs --library python   <------ HERE
```
Changed `--default-weblogs` to `--default-weblog` (no `s`) in the help text. …

`build.sh`: fix typo in help text

---

tests/auto_inject/test_auto_inject_blocklist.py

Removing the process ignore option. With the new self-inject approach https://github.com/DataDog/auto_inject/pull/266 this option is not relevant anymore. The accessible cmdline is now straight the interpreter /.../bin/(java|python|ruby|dotnet..). 
Starting with the test to pass CI, and then will remove in auto_inject

remove process_ignore

---

utils/build/docker/java/akka-http/src/main/scala/com/datadoghq/akka_http/IastRoutes.scala
utils/build/docker/java/akka-http/src/main/scala/com/datadoghq/akka_http/Main.scala
utils/build/docker/java/akka-http/src/main/scala/com/datadoghq/akka_http/RaspRoutes.scala
utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/RaspResource.java
utils/build/docker/java/play.Dockerfile
utils/build/docker/java/play/app/Module.scala
utils/build/docker/java/play/app/controllers/RaspController.scala
utils/build/docker/java/play/app/resources/Resources.scala
utils/build/docker/java/play/conf/routes
utils/build/docker/java/play/pom.xml
utils/build/docker/java/ratpack/src/main/java/com/datadoghq/ratpack/Main.java
utils/build/docker/java/ratpack/src/main/java/com/datadoghq/ratpack/RaspHandlers.java
utils/build/docker/java/resteasy-netty3/src/main/java/com/datadoghq/resteasy/Main.java
utils/build/docker/java/resteasy-netty3/src/main/java/com/datadoghq/resteasy/RaspResource.java
utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/App.java
utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/rasp/RaspController.java
utils/build/docker/java/vertx3/pom.xml
utils/build/docker/java/vertx3/src/main/java/com/datadoghq/vertx3/Main.java
utils/build/docker/java/vertx3/src/main/java/com/datadoghq/vertx3/rasp/RaspRouteProvider.java
utils/build/docker/java/vertx4/pom.xml
utils/build/docker/java/vertx4/src/main/java/com/datadoghq/vertx4/Main.java
utils/build/docker/java/vertx4/src/main/java/com/datadoghq/vertx4/rasp/RaspRouteProvider.java

RASP protection requires custom weblog endpoints in order to validate protection capabilities
Add required endpoints for RASP SQLi protection to all java weblogs

[java] Add requires endpoints for SQLi protection in RASP

---

tests/auto_inject/test_auto_inject_blocklist.py

Trying to fix the remaining tests of the new injector: https://github.com/DataDog/auto_inject/pull/266
2 problems have been caught,
1: (python tests) `/home/datadog/.pyenv/shims/python: Permission denied`. The existing injector injected by intercepting execve call, the new one self-injects on a process that gets started. Meaning that a permission denied prevents testing the block list here
2: (ruby tests) we catch now the runtime, 
"bundle" -->`Path":"/usr/bin/ruby","Args":["/usr/bin/ruby","/usr/local/bin/bundle","config","build.pg","--with-pg-config=/path/to/pg_config"]}`
The logs interceptor is searching for bundle in the path and fails to find it. Instead of adding complexity on the code (if bundle try either bundle or ruby), I propose removing bundle assertion and add them back once …

update args tests

---

.gitlab-ci.yml
tests/auto_inject/test_auto_inject_install.py
utils/_context/_scenarios.py
utils/_features.py
utils/build/virtual_machine/weblogs/nodejs/provision_test-app-nodejs-16.yml
utils/build/virtual_machine/weblogs/nodejs/provision_test-app-nodejs-alpine-libgcc.yml
utils/build/virtual_machine/weblogs/nodejs/provision_test-app-nodejs-alpine.yml
utils/build/virtual_machine/weblogs/nodejs/provision_test-app-nodejs-container.yml
utils/build/virtual_machine/weblogs/nodejs/provision_test-app-nodejs.yml
utils/build/virtual_machine/weblogs/nodejs/provision_test-shell-script.yml

The feature "guardrail" has been implemented for some languages.
This PR creates a new scenario to test unsupported version of the language.
In this case we are testing node18 for supported language version and node16 to test a unsupported version of the language
🛟 …

OnBoarding: Host and container guardrail testing

---

utils/onboarding/injection_log_parser.py

Other iteration on tests for PR: https://github.com/DataDog/auto_inject/pull/266
detected executable path: executable Path: `/home/datadog/.pyenv/versions/3.8.15/bin/python3.8`
New failure
```
15:12:33.861 DEBUG    - Checking command: ['/home/datadog/.pyenv/shims/python', 'myscript.py', 'arg1', 'arg2', 'arg3']
15:12:33.861 INFO         Command /home/datadog/.pyenv/shims/python was NOT FOUND
```
Changed test to match on base path: https://gitlab.ddbuild.io/DataDog/auto_inject/-/jobs/559879541

fix command path

---

tests/parametric/conftest.py
utils/_context/_scenarios.py
utils/build/docker/python/parametric/Dockerfile
utils/build/docker/python/parametric/ddtracer_version.Dockerfile

* better ouput when version getter fails on parametric test
* use new test runner for python, as it requires rust install

[python] Fix parametric tests

---

tests/auto_inject/test_auto_inject_blocklist.py

We're failing now on the symlink resolution when comparing args at the end, changing the path for the test

Fix block test

---

tests/parametric/test_otel_span_methods.py

It's flaky.
Tests should not use `traces[0]` to get the "first" span, since the order of spans is not guaranteed.
Skip it by marking with `@flaky`.

[.NET] skip flaky test `test_otel_get_span_context` for now

---

tests/appsec/test_automated_login_events.py

New specification of automated login events is going to be released with the next java tracer v1.37, this PR ensures that the java tracer quirks are took into consideration.
Update specific assertions when there are login failures for Java.

[java] Update java metadata and assertions for automated login events

---

tests/appsec/rasp/test_sqli.py
utils/build/docker/golang/app/internal/rasp/rasp.go
utils/build/docker/python/django/app/urls.py
utils/build/docker/python/fastapi/main.py
utils/build/docker/python/flask/app.py

The queries and assertions from the SQLi RASP tests did not conform to the documentation:
The statement used in the query should be similar to the following:
```sql
SELECT * FROM users WHERE id='$user_id';
```
Change the queries in order to follow the guidelines included in the RASP endpoint documentation.
🛟 …

Update rasp SQLi queries to conform to documentation

---

tests/appsec/api_security/test_schemas.py

Skip appsec_api_security test on PHP as flaky

---

tests/appsec/test_customconf.py

We should not do assumption on logs or stdout. Telemetry is now used to report configuration information.
Remove stdout checks on missing or corrupted rule file tests

remove stdout checks for threats configuration

---

manifests/dotnet.yml
manifests/golang.yml
manifests/java.yml
manifests/nodejs.yml
manifests/php.yml
manifests/python.yml
manifests/ruby.yml
tests/appsec/test_conf.py
tests/appsec/test_reports.py
tests/appsec/test_traces.py
tests/appsec/waf/test_telemetry.py

deprecated test should be removed
Remove deprecated test
- Test_HttpClientIP
- Test_DistributedTraceInfo
- Test_TelemetryMetrics::test_metric_waf_updates

remove not implemented deprecated tests

---

.github/workflows/run-docker-mode.yml

The branch referenced was `master` but the main branch is `main`.
Fix incorrect ref to determine when to push latest tag.

fix incorrect ref to determine when to push latest tag

---

tests/appsec/test_ip_blocking_full_denylist.py
tests/appsec/test_user_blocking_full_denylist.py
tests/appsec/utils.py

Include protocol test in main function to avoid false positive XPSS

---

tests/appsec/iast/source/test_parameter_value.py

The IAST source test started to fail randomly for the `reasteasy-netty3` weblog ([example](https://github.com/DataDog/system-tests/actions/runs/9808953403/job/27085825030?pr=2683#logs))
This PR marks the test as flaky meanwhile we investigate the underlying reason for the failure.
🛟 …

Mark source test as flaky for the resteasy-netty3 weblog

---

utils/build/virtual_machine/provisions/auto-inject/docker/auto-inject_prepare_docker.yml

Tests failing because of CentOS. As CentOS 7 became EOL on July 1st the repositories have been archived and are not available anymore.
Removes references to mirror.centos.org and replace them by vault.centos.org

fix(centos): Replace dead mirror.centos.org

---

utils/build/docker/golang/chi.Dockerfile
utils/build/docker/golang/echo.Dockerfile
utils/build/docker/golang/gin.Dockerfile
utils/build/docker/golang/gqlgen.Dockerfile
utils/build/docker/golang/graph-gophers.Dockerfile
utils/build/docker/golang/graphql-go.Dockerfile
utils/build/docker/golang/net-http.Dockerfile
utils/build/docker/golang/uds-echo.Dockerfile

We are dropping support for go 1.20 cf. https://github.com/DataDog/dd-trace-go/pull/2705
Upgrade weblog variants base image

[golang] Upgrade base image: 1.20 -> 1.21

---

manifests/java.yml

Header collection was enabled in the java tracer from version 1.35.0
Enable tests for header collection in the java tracer.

[java] Enable header collection related tests

---

tests/appsec/api_security/test_schemas.py

[php] Mark test as flaky for APPSEC-53993

---

.github/workflows/run-end-to-end.yml

Fix egg-chicken-issue
When some base images are build (python, proxy, and soon to come, nodejs #2677), their tag does not exists in docker registry, so the pull step fails. By pulling **after** building base images, `docker compose pull` will ignore them, as they exists locally.
🛟 …

Pull images after building base images

---

manifests/python.yml
tests/appsec/blocking_rule.json
tests/appsec/test_blocking_addresses.py

Suspicious requests tests each tests one address at a time.
`Test_Suspicious_Request_Blocking` class is testing several addresses at once with the new rule `tst-037-012`
- `server.request.method`
- `server.request.uri.raw`
- `server.request.path_params`
- `server.request.query`
- `server.request.headers.no_cookies`
- `server.request.cookies`
They must all match at the same time to trigger the rule. …

add srb test on multiple addresses
