- tests/appsec/test_alpha.py
- utils/_core.py
- utils/build/docker/golang/install_ddtrace.sh
Implement a test suite specifically for the alpha version defined in the feature matrix at https://docs.google.com/spreadsheets/d/1tbDscmonDSa3I2k3QC5Ou_MscbA3CewnqJX3XWgx-gU/edit#gid=0&range=A6
> Alpha version test suite

- tests/appsec/test_reports.py
- tests/appsec/waf/test_addresses.py
- tests/appsec/waf/test_miscs.py
- tests/appsec/waf/test_rules.py
- utils/interfaces/_library/appsec.py
- utils/interfaces/_library/core.py
* Updated PHP test support
* Added support for WAF attack value and patterns
* Updated XSS test to use value instead of pattern
* Added path_params tests
* Reenabled multiple highlights test
* Added test for ndf_000_008
> Miscellaneous changes

- README.md
- docs/architecture/overview.md
- docs/architecture/test_template.py
- tests/template_test.py
Flowchart detailing how tests execute locally and in CI.
Architectural overview document.
> Overview Documentation

- docs/architecture/overview.md
Formatting starts a new numbered list without these spaces.
> Fix nested list

- tests/appsec/waf/test_addresses.py
- tests/appsec/waf/test_rules.py
Cookies will be disabled from rules starting with 1.2.7
> Make tests avoid running on cookies

- .github/workflows/ci.yml
- tests/appsec/test_traces.py
- tests/appsec/waf/test_addresses.py
- utils/build/docker/java/.gitignore
- utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/MyResource.java
- utils/build/docker/java/ratpack.Dockerfile
- utils/build/docker/java/ratpack/src/main/java/com/datadoghq/ratpack/Main.java
- utils/build/docker/java/resteasy-netty3.Dockerfile
- utils/build/docker/java/resteasy-netty3/src/main/java/com/datadoghq/resteasy/MyResource.java
- utils/build/docker/java/spring-boot-jetty.Dockerfile
- utils/build/docker/java/spring-boot-undertow.Dockerfile
- utils/build/docker/java/spring-boot.Dockerfile
- utils/build/docker/java/spring-boot/src/main/java/App.java
- utils/build/docker/java/vertx3.Dockerfile
- utils/build/docker/java/vertx3/pom.xml
- utils/build/docker/java/vertx3/src/main/java/com/datadoghq/vertx3/Main.java
- utils/build/docker/java/vertx3/src/main/resources/logging.properties
Restauration of #277 from @cataphract
> vertx3 app; set max memory on java apps

- tests/appsec/test_identify.py
- utils/build/docker/golang/app/chi.go
- utils/build/docker/golang/app/echo.go
- utils/build/docker/golang/app/gin.go
- utils/build/docker/golang/app/gorilla.go
- utils/build/docker/golang/app/net-http.go
- utils/build/docker/php/apache-mod/php.conf
- utils/build/docker/php/php-fpm/php8.0-fpm.conf
The endpoint call ends with `/`, which messess up with Sinatra and Rack somehow (IIRC slahs and no-slash can be two different HTTP resources)
> Fix identify endpoint

- tests/appsec/test_identify.py
- tests/appsec/waf/test_addresses.py
- tests/appsec/waf/test_reports.py
- tests/appsec/waf/test_rules.py
Also add more precisions on the problems with waf metrics
> Update tests with query keys that now work

- tests/appsec/waf/test_addresses.py
> Skip failing test for traceer nodejs 2.8.0

- docker-compose.yml
- utils/build/docker/agent.Dockerfile
- utils/interfaces/schemas/agent/api/v1/check_run-request.json
- utils/interfaces/schemas/agent/api/v1/discovery-request.json
- utils/interfaces/schemas/agent/api/v1/series-request.json
- utils/interfaces/schemas/agent/api/v1/validate-request.json
- utils/interfaces/schemas/agent/intake/-request.json
- utils/proxy/forwarder.py
> Start the entire agent in agent image

- scenarios/test_library_conf.py
- tests/appsec/test_conf.py
- tests/appsec/waf/test_addresses.py
- tests/appsec/waf/test_miscs.py
- tests/appsec/waf/test_rules.py
- tests/test_standard_tags.py
> Enable some xpassed tests on python

- scenarios/test_library_conf.py
- tests/appsec/test_traces.py
- tests/test_standard_tags.py
> Enable some xpassed tests on java

- .github/workflows/ci.yml
- docs/execute/binaries.md
- utils/scripts/load-binary.sh
> Use branch 1.x for dd-trace-py

- tests/appsec/waf/test_addresses.py
- tests/appsec/waf/test_rules.py
- utils/build/docker/python/flask.py
Features:
- Activate `Test_UrlQuery` for Python, Flask & Django tests.
- Activate `Test_XSS` for Python, Flask & Django tests.
Fixes:
- Update Flask app `/waf/` view which has a required (and unused) parameter which raises an Exception each request
> feat(python): Detect attacks on the server.request.query address

- tests/appsec/test_alpha.py
- tests/appsec/waf/test_addresses.py
Features:
- Activate `Test_Cookies` for Python & Flask tests.
- Activate `test_headers`
> feat(python): Detect attacks on cookies

- tests/test_standard_tags.py
Updating tests after  feature merged https://github.com/DataDog/dd-trace-dotnet/pull/2915/
> Uncomment standard tags tests after merge in dotnet repo

- utils/build/docker/python/pylons/app/app/controllers/waf.py
Fixed tests/appsec/test_traces.py::Test_AppSecEventSpanTags::test_root_span_coherence test
> feat: update test_traces tests

- run.sh
- tests/appsec/waf/test_addresses.py
Enable the system tests for Django body 
Signed-off-by: Juanjo Alvarez <juanjo.alvarezmartinez@datadoghq.com>
> (feat) enable http urlencoded and json body test

- scenarios/remote_config/test_remote_configuration.py
- utils/proxy/forwarder.py
This change adds support for applications that run multiple worker processes, like gunicorn.
> feat: add support for concurrent clients

- tests/appsec/test_docs.py
Signed-off-by: Juanjo Alvarez <juanjo.alvarezmartinez@datadoghq.com>
> asm: update doc pseudotests for Python

- utils/interfaces/_core.py
> Display error on Validation exception at __init__

- tests/appsec/test_traces.py
By fixing a false positive, we accidentally broke a test
> Change the payload used in a test

- run.sh
- scenarios/remote_config/test_remote_configuration.py
- utils/interfaces/_library/core.py
Enable dotnet RCM tests + fix dotnet timeouts
> Enable dotnet RCM tests

- utils/build/build.sh
Solves Mac M1 building docker images
> [DRAFT ARM M1 ] fix build docker images on Mac M1 laptop

- tests/test_standard_tags.py
Making sure obfuscation processing happens not just on the first match.
> Add multi redaction test case

- tests/appsec/iast/test_iast.py
- utils/interfaces/_library/appsec_iast.py
Check for endopint response != 404
Enable test for node: "Strong hash algorithm is not reported as insecure"
> [IAST] Check status != 404 and enable nodejs tests

- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/AppSecIast.java
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/iast/utils/CryptoExamples.java
Current state of tests for dd-trace-java:
https://app.circleci.com/pipelines/github/DataDog/dd-trace-java/16034/workflows/d6228477-e0af-4cc8-a903-63721619031a/jobs/371119/steps
> Fix issues with deduplication and IAST crypto tests

- conftest.py
- pyproject.toml
- utils/interfaces/_core.py
- utils/interfaces/_logs/core.py
- utils/test_the_test/test_stdout_reader.py
Pylint is very close to be happy on utils/
> Make pylint a little bit happier #521

- .github/CODEOWNERS
> Add Kyle to code owners on parametric folder

- utils/build/docker/dotnet/query-versions.fsx
Updated the params passed to CreateWaf function on dot net tests responding to a change on that function signature
> Update CreateWaf params count

- .github/workflows/ci.yml
- scenarios/fuzzer/core.py
- scenarios/fuzzer/corpus.py
- scenarios/fuzzer/html_parser.py
- scenarios/fuzzer/main.py
- scenarios/fuzzer/request_generators.py
- scenarios/fuzzer/request_mutator.py
- scenarios/fuzzer/tools/_data.py
- scenarios/fuzzer/tools/_tools.py
- scenarios/fuzzer/tools/metrics.py
- scenarios/fuzzer/tools/random_strings.py
- scenarios/perfs/main.py
- tests/test_identify.py
Make pylint happy on scenarios/fuuzer folder #521
> Pylint fuzzer

- parametric/apps/golang/main.go
- parametric/conftest.py
- parametric/requirements.txt
- parametric/spec/trace.py
- parametric/test_library_tracestats.py
- parametric/test_tracer.py
The go app was not handling parenting correctly. 
> parametric: fix go app

- scenarios/appsec/test_conf.py
- scenarios/appsec/test_customconf.py
- scenarios/appsec/test_rate_limiter.py
- scenarios/appsec/test_traces.py
- scenarios/appsec/waf/test_addresses.py
- scenarios/appsec/waf/test_reports.py
- scenarios/backend/test_waf.py
- scenarios/perfs/main.py
- scenarios/perfs/process.py
- scenarios/remote_config/test_remote_configuration.py
- scenarios/sampling_rates.py
- scenarios/test_data_integrity.py
- scenarios/test_library_conf.py
- scenarios/test_profiling.py
> pylint scenario folder

- tests/appsec/iast/test_iast.py
- utils/build/docker/nodejs/express4/app.js
Add system tests for IAST weak cipher detection
> Add support for IAST weak cipher system tests

- scenarios/appsec/test_rate_limiter.py
- utils/test_the_test/test_version.py
Support the in operator for one line cleaning for #521 
> Support the in operator for context

- conftest.py
- docker-compose.yml
- pyproject.toml
- pytest.ini
- tests/appsec/iast/test_iast.py
- tests/appsec/test_PII.py
- tests/appsec/test_conf.py
- tests/appsec/test_endpoint_ssrf.py
- tests/appsec/test_identify.py
- tests/appsec/test_logs.py
- tests/appsec/test_reports.py
- tests/appsec/test_traces.py
- tests/appsec/waf/test_miscs.py
- tests/appsec/waf/test_reports.py
- tests/appsec/waf/test_rules.py
- tests/test_library_logs.py
- tests/test_miscs.py
- tests/test_schemas.py
- tests/test_semantic_conventions.py
- tests/test_smoke.py
- tests/test_standard_tags.py
- tests/test_telemetry.py
> Make pylint happy on tests/ folder #521

- parametric/README.md
- parametric/apps/nodejs/servicer.js
- parametric/conftest.py
- parametric/run.sh
- parametric/spec/trace.py
- parametric/test_library_tracestats.py
- parametric/test_span_sampling.py
- parametric/test_tracer.py
Make the tests more accessible by renaming the fixtures and adding some helper functions
> Make parametric tests more accessible

- conftest.py
- utils/interfaces/_agent/core.py
- utils/interfaces/_backend/core.py
- utils/interfaces/_core.py
- utils/interfaces/_library/core.py
- utils/interfaces/_logs/core.py
> Fix cyclic import #521

- tests/appsec/test_identify.py
- tests/appsec/test_traces.py
- tests/appsec/waf/test_reports.py
- tests/test_identify.py
If https://github.com/DataDog/dd-trace-php/pull/1757 is not merged today
> Skip some test due to a regression on PHP tracer

- scenarios/test_no_ip_is_reported.py
- utils/interfaces/_agent/core.py
- utils/interfaces/_core.py
> Chck if TRACE_CLIENT_IP_HEADER_DISABLED is working #569

- lib-injection/run-lib-injection.sh
It wasn't exiting if any of the commands failed.
> Fix lib injection run script

- .github/workflows/ci.yml
- run.sh
- scenarios/remote_config/test_remote_configuration.py
- utils/interfaces/_schemas_validators.py
- utils/interfaces/schemas/library/v0.7/config-request.json
- utils/interfaces/schemas/library/v0.7/misc/config-state.json
Some scenarios were not in the CI.
Needs also to add then in the nightly
> Enable remote backend scenarios #579

- .circleci/config.yml
We were using a fake API key in circle ci
> Add dd-api-key in circle ci

- scenarios/appsec/test_traces.py
- tests/appsec/test_traces.py
> skip obfuscator test for php : bug

- scenarios/appsec/test_ip_blocking.py
Integration bug found by nightly process. CC @ValentinZakharov 
> Bug in ip blocking for "java@0.114.0" for appsec_rules_version == "1.4.2"

- tests/appsec/iast/test_iast.py
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/AppSecIast.java
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/iast/utils/CryptoExamples.java
- New cipher endpoints
- Enable iast cipher tests for java
> java insecure cipher test

- utils/interfaces/schemas/agent/api/v2/profile-request.json
- utils/interfaces/schemas/agent/api/v2/series-request.json
Agent introduced a new request : /agent/api/v2/series
> Add "/agent/api/v2/series schema

- scenarios/appsec/test_client_ip.py
- tests/test_standard_tags.py
Enable IP header collection tests in Java
> Enable IP header collection tests in Java

- scenarios/appsec/test_client_ip.py
- tests/test_standard_tags.py
- utils/build/docker/php/common/install_ddtrace.sh
Enable client ip tests for php
> Enable client ip tests for php

- scenarios/appsec/test_ip_blocking.py
There is a bug with java tracer 0.115.0 and Waf rule 1.4.2
> Declare Bug for Java Tracer Dev (0.115.0) and waf rules 1.4.2

- .github/workflows/ci.yml
> Golang is failing on parametric => remove it for now

- .github/workflows/ci.yml
fix dashboard update condition
> [ci visibility] fix update dashboard condition

- parametric/conftest.py
Create a unique docker network for each parametric test.
This PR is a follow up of #504
Feel free to edit the PR to improve the change.
> Create unique docker network for each parametric test

- requirements.txt
- scenarios/perfs/docker-compose.yml
- scenarios/perfs/main.py
- scenarios/perfs/run.sh
> Fix perfs scenario

- utils/build/docker/cpp/install_ddtrace.sh
- utils/build/docker/cpp/nginx.Dockerfile
> Fixx cpp build step

- scenarios/appsec/test_conf.py
> Skip waf timeout test for spring-boot-openliberty

- .github/workflows/ci.yml
- build.sh
> Retries on build script to reduce failures

- tests/test_telemetry.py
- utils/__init__.py
- utils/interfaces/_core.py
> Fix telemetry test flakyness 

- scenarios/appsec/test_ip_blocking.py
> More agressive skip on a java tracer bug

- parametric/README.md
- parametric/conftest.py
- parametric/run.ps1
Small script and documentation changes to show how to run parametric tests running on Windows. The steps were tested by running some of the `dotnet` tests.
> Get dotnet parametric tests running on Windows

- scenarios/remote_config/test_remote_configuration.py
- tests/appsec/iast/test_iast.py
> Skip some failing tests on java

- scenarios/appsec/test_ip_blocking.py
- scenarios/remote_config/test_remote_configuration.py
- tests/appsec/iast/test_iast.py
> Skip failing test on java

- run.sh
- utils/build/docker/nodejs/express4/iast.js
> Fix UDS test in nodejs

- .github/workflows/ci.yml
- .github/workflows/update-agent-protobuf.yml
- docs/CI/github-actions.md
> Update GH actions from v2 to v3

- tests/appsec/iast/test_iast_command_injection.py
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/AppSecIast.java
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/iast/utils/CmdExamples.java
- utils/build/docker/nodejs/express4/iast.js
Add system tests for the command injection vulnerability
> Add support for IAST command injection system tests

- tests/appsec/iast/test_iast_path_traversal.py
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/AppSecIast.java
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/iast/utils/PathExamples.java
Add system tests for path traversal detection
> Add support for IAST path traversal system tests

- tests/appsec/iast/test_iast_ldap_injection.py
- utils/build/docker/java/spring-boot/pom.xml
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/AppSecIast.java
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/WebSecurityConfig.java
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/iast/utils/LDAPExamples.java
- utils/build/docker/java/spring-boot/src/main/resources/application.properties
- utils/build/docker/java/spring-boot/src/main/resources/test-server.ldif
Add simple ldap injection test and a java springboot endpoint
> JAVA LDAP Injection system test

- tests/appsec/iast/test_iast_path_traversal.py
- utils/build/docker/nodejs/express4/iast.js
Add path traversal test to nodejs test suite.
> Add path traversal test to nodejs.

- tests/appsec/test_runtime_activation.py
> Skip not testable feature in java

- tests/appsec/iast/test_iast_sql_injection.py
> Fix SQLi tests, set all to not released

- conftest.py
- utils/_context/core.py
> Allow method to declare setup code

- tests/integrations/test_cassandra.py
- tests/integrations/test_mongo.py
- tests/integrations/test_sql.py
- tests/test_data_integrity.py
- tests/test_distributed.py
- tests/test_identify.py
- tests/test_sampling_rates.py
> Revamp setup files

- tests/test_sampling_rates.py
- utils/interfaces/_backend/core.py
- utils/interfaces/_deserializer.py
- utils/interfaces/_library/appsec.py
- utils/interfaces/_library/appsec_iast.py
- utils/interfaces/_library/metrics.py
- utils/interfaces/_library/miscs.py
- utils/interfaces/_library/sampling.py
- utils/interfaces/schemas/library/v0.5/traces-request.json
> Support traces v0.5

- tests/appsec/test_client_ip.py
- tests/appsec/test_endpoint_ognl.py
- tests/appsec/test_endpoint_sqli.py
- tests/appsec/test_endpoint_ssrf.py
- tests/appsec/test_identify.py
- tests/appsec/test_logs.py
- tests/appsec/test_rate_limiter.py
- tests/appsec/test_reports.py
- tests/appsec/test_runtime_activation.py
- tests/appsec/test_unsupported.py
> Revamp setup some appsec test files 

- conftest.py
- tests/appsec/waf/test_addresses.py
> Revamp setup of appsec/test_addresses

- parametric/test_trace_distributed.py
Skip parametric failing tests until parametric is adapted to v0.5 traces
> skip parametric test until v0.5 traces fix

- docs/architecture/test_template.py
- docs/edit/iast-validations.md
- docs/weblog/README.md
- tests/appsec/test_customconf.py
- tests/appsec/waf/test_miscs.py
- tests/appsec/waf/test_reports.py
- tests/integrations/test_dbm.py
- utils/build/docker/python/flask.py
> Revamp setup for some appsec files 

- docs/edit/README.md
- tests/appsec/test_alpha.py
- tests/appsec/test_conf.py
- tests/appsec/test_traces.py
> Revamp setup again 

- docs/edit/README.md
- docs/edit/declare-versions.md
- docs/edit/features.md
- tests/appsec/test_PII.py
- tests/appsec/test_versions.py
- tests/remote_config/test_remote_configuration.py
- tests/test_remote_config.py
- tests/test_standard_tags.py
- tests/test_telemetry.py
> Remove useless BaseTestCase inheritances 

- parametric/conftest.py
This should speed up local runs on M1 Macbooks
> Use arm64 compatible image for Python parametric tests

- parametric/README.md
> Add local Python instructions for parametric tests

- docs/edit/README.md
- tests/appsec/test_client_ip.py
- tests/appsec/test_conf.py
- tests/appsec/test_endpoint_ognl.py
- tests/appsec/test_endpoint_sqli.py
- tests/appsec/test_endpoint_ssrf.py
- tests/appsec/test_identify.py
- tests/appsec/test_ip_blocking.py
- tests/appsec/test_rate_limiter.py
- tests/appsec/test_reports.py
- tests/appsec/test_traces.py
- tests/appsec/test_versions.py
- tests/appsec/waf/test_miscs.py
- tests/appsec/waf/test_reports.py
- tests/integrations/test_dbm.py
- tests/remote_config/test_remote_configuration.py
- tests/test_data_integrity.py
- tests/test_distributed.py
- tests/test_identify.py
- tests/test_library_conf.py
- tests/test_no_ip_is_reported.py
- tests/test_remote_config.py
- tests/test_sampling_rates.py
- tests/test_semantic_conventions.py
- tests/test_standard_tags.py
- tests/test_telemetry.py
- utils/interfaces/_agent/core.py
- utils/interfaces/_core.py
- utils/interfaces/_library/core.py
- utils/test_the_test/test_decorators.py
> Remove warnings

- conftest.py
- utils/_context/library_version.py
> Export all known versions

- scenarios/sleep.py
> Fix sleep scenario

- tests/appsec/waf/test_rules.py
> Update a RFI pattern to work with 1.4.3

- .github/workflows/ci.yml
- utils/build/docker/java/spring-boot/pom.xml
- utils/scripts/generate-github-action-file.py
> Added Wildfly to CI matrix

- lib-injection/runner/action.yml
> [lib-injection] fix lib-injection references

- .github/workflows/experimental.yml
Fix experimental workflow (lib injection)
> [lib-injection] Fix lib injection experimental workflow

- tests/appsec/iast/test_iast_command_injection.py
- tests/appsec/iast/test_iast_path_traversal.py
- tests/appsec/iast/test_iast_sql_injection.py
- tests/appsec/iast/test_iast_weak_hash.py
We are changing the vulnerability paths from absolute to relative in nodejs, the iast tests will start to fail if we don't ignore they in nodejs.
Related dd-trace-js PR: https://github.com/DataDog/dd-trace-js/pull/2635
> Change to relative vulnerability path

- utils/build/docker/java/spring-boot-3-native.Dockerfile
- utils/build/docker/java/spring-boot-3-native/pom.xml
- utils/build/docker/java/spring-boot-3-native/src/main/java/com/datadoghq/springbootnative/App.java
This PR fixes the Spring Boot 3 native weblog app.
It patches a PR in review #752 so I don't know the review process.
@robertomonteromiguel you can cherrypick the commit otherwise.
> fix: Fix spring-boot-3-native weblog app

- .github/workflows/experimental.yml
- lib-injection/src/test/shell/functions.sh
After merge dd-trace-py to the main branch, we should enable the lib injection tests
> [lib injection] Enable lib injection for python

- utils/interfaces/_logs.py
> Some logs file was missing on .NET

- conftest.py
> Do not execute setup if test is entirely skipped

- utils/build/docker/python/uds-flask.Dockerfile
- utils/build/docker/python/uwsgi-poc.Dockerfile
Update dependencies in python docker images
> fix(python): update dependencies in python docker images

- docs/weblog/README.md
- tests/appsec/test_event_tracking.py
- utils/build/docker/php/apache-mod/php.conf
- utils/build/docker/php/common/custom_event.php
- utils/build/docker/php/common/user_login_failure_event.php
- utils/build/docker/php/common/user_login_success_event.php
- utils/build/docker/php/php-fpm/php-fpm.conf
AppSec user login and custom event tracking SDK tests.
> Event and user login tracking SDK

- tests/remote_config/test_remote_configuration.py
Unify irrelevant tests in system tests
> feat: unify irrelevant tests in system tests

- utils/scripts/generate-github-action-file.py
Fix docker cache to use rw mode with main branch and use read only cache for other PRs
> Fix docker cache rw for main branch

- utils/build/docker/cpp/nginx.Dockerfile
> Fix cpp build

- utils/build/build.sh
Docker platform is set as parameter of build.sh, instead extra-args
> Fix docker platform param

- utils/build/docker/dotnet/Dependencies/HttpClientWrapper.cs
- utils/build/docker/dotnet/Endpoints/IdentifyEndpoint.cs
- utils/build/docker/dotnet/Endpoints/MakeDistantCallEndpoint.cs
- utils/build/docker/dotnet/Endpoints/SpansEndpoint.cs
Replicating the example at https://github.com/DataDog/system-tests/blob/9d4a61940622b6fa9fb336c0e25f79755915f9d4/utils/build/docker/python/flask/app.py#L72-L86
> Replicate python example for distributed HTTP call

- tests/test_scrubbing.py
Currently its only verifying that a password is properly scrubbed, we also might want to ensure username part is also scrubbed.
> Validate that name is not leaked in url field

- .github/workflows/ci.yml
- utils/scripts/generate-github-action-file.py
Some issues arise with the docker remote cache. This PR disables docker buildx cache. We don't remove code for further analysis
> Disable Docker Buildkit cache

- tests/remote_config/test_remote_configuration.py
> feat(python): enable RCM tests

- tests/appsec/blocking_rule.json
- tests/appsec/test_blocking_addresses.py
Test whether several addresses can drive blocking for a request
> Test which addresses can trigger blocking

- tests/test_scrubbing.py
- tests/test_semantic_conventions.py
> Add version to allow old tracer to pass some tests

- utils/interfaces/schemas/library/telemetry/proxy/api/v2/apmtelemetry-request.json
Update the JSON schema definition for the generate-metrics payload
> Fix issues in GenerateMetrics JSON Schema def

- tests/test_semantic_conventions.py
> add spring controller spans to dict

- tests/appsec/waf/test_rules.py
Update the attack payload to trigger despite upcoming changes
> ASM - Update the attack pattern for crs-921-160

- utils/build/docker/php/common/custom_event.php
- utils/build/docker/php/common/user_login_failure_event.php
- utils/build/docker/php/common/user_login_success_event.php
Update PHP Weblog with new endpoints requirements
> php weblog: update the api to allow changing the events content

- tests/appsec/waf/test_rules.py
A specific request can be detected by several rules. The test was making a wrong assumption about which rule would detect the threat first.
> Christophe papazian/waf rule update

- utils/interfaces/_backend.py
After the refactoring done in https://github.com/DataDog/system-tests/pull/871 I broke the smoke test for E2E tests.
This PR fixes that.
**Confirmed fix**
```
./run.sh APM_TRACING_E2E_SINGLE_SPAN
./run.sh APM_TRACING_E2E
```
> fix backend interface after refactoring

- utils/interfaces/_backend.py
This change will allow us to specify the target API to use for the E2E tests.
You should specify the `DD_SITE` accordingly when running the tests (defaults to `datad0g.com`). For example:
```sh
DD_SITE=datadoghq.com ./run.sh APM_TRACING_E2E
DD_SITE=datadoghq.eu ./run.sh APM_TRACING_E2E
DD_SITE=us3.datadoghq.com ./run.sh APM_TRACING_E2E
```
You also need to make sure that the `DD_API_KEY` and `DD_APPLICATION_KEY` environment variables have correct keys from each of the organisations you are targeting.
```sh
lambros.petrou@COMP-F371T7QC44 system-tests % DD_SITE=datadoghq.com ./run.sh APM_TRACING_E2E
============ Run APM_TRACING_E2E tests ===================
ℹ️  Log folder is ./logs_apm_tracing_e2e
Starting containers in background
[+] Running 5/5
⠿ Network …
```
> Add support for production API in E2E tests

- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/App.java
Add a new endpoint to Java test app for Open Redirect
> ASM - Add endpoint for open redirect

- .github/workflows/ci.yml
> fix PR labels

- tests/appsec/test_ip_blocking.py
> Skip APPSEC_IP_BLOCKING for PHP

- tests/appsec/test_event_tracking.py
- utils/build/docker/java/jersey-grizzly2/pom.xml
- utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/MyResource.java
- utils/build/docker/java/ratpack/pom.xml
- utils/build/docker/java/ratpack/src/main/java/com/datadoghq/ratpack/Main.java
- utils/build/docker/java/resteasy-netty3/pom.xml
- utils/build/docker/java/resteasy-netty3/src/main/java/com/datadoghq/resteasy/MyResource.java
- utils/build/docker/java/spring-boot-3-native/src/main/java/com/datadoghq/springbootnative/WebController.java
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/App.java
- utils/build/docker/java/vertx3/pom.xml
- utils/build/docker/java/vertx3/src/main/java/com/datadoghq/vertx3/Main.java
> Event tracking for Java

- tests/appsec/test_rate_limiter.py
- tests/test_sampling_rates.py
> skip failing test in node

- run.sh
- tests/apm_tracing_e2e/test_single_span.py
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/App.java
- Enable Single Spans end-to-end (E2E) tests for Java in addition to Go (ATI-2419)
The change in `./run.sh` was due to Java tracer failing to parse the `DD_SPAN_SAMPLING_RULES` JSON with the surrounding quotes.
```java
[dd.trace 2023-02-23 14:21:46:542 +0000] [main] ERROR datadog.trace.agent.common.sampling.SpanSamplingRules - Couldn't parse Span Sampling Rules from JSON: '[{"service": "weblog", "name": "*single_span_submitted", "sample_rate": 1.0, "max_per_second": 50}]'
com.squareup.moshi.JsonEncodingException: Use JsonReader.setLenient(true) to accept malformed JSON at path $
at com.squareup.moshi.JsonReader.syntaxError(JsonReader.java:243)
at com.squareup.moshi.JsonUtf8Reader.checkLenient(JsonUtf8Reader.java:1152)
at com.squareup.moshi.JsonUtf8Reader.doPeek(JsonUtf8Reader.java:355)
at …
```
> [apm] Enable APM E2E Single Span tests for Java spring-boot

- conftest.py
- docker-compose.yml
- run.sh
- scenarios/fuzzer/main.py
- tests/test_library_conf.py
- tests/test_sampling_rates.py
- utils/_context/containers.py
- utils/_context/core.py
- utils/proxy/core.py
- utils/scripts/junit_report.py
Move weblog env values from `run.sh` to `context`
> Move weblog env mechanism inside python #783

- utils/interfaces/_agent.py
- utils/interfaces/_core.py
- utils/interfaces/_library/core.py
> Fix get span method #876

- tests/apm_tracing_e2e/test_single_span.py
- utils/interfaces/_backend.py
> [apm-e2e] rewording and improvements to the EvP API

- utils/build/docker/java/app.sh
- utils/build/docker/java/jersey-grizzly2.Dockerfile
- utils/build/docker/java/ratpack.Dockerfile
- utils/build/docker/java/resteasy-netty3.Dockerfile
- utils/build/docker/java/spring-boot-3-native.Dockerfile
- utils/build/docker/java/spring-boot-jetty.Dockerfile
- utils/build/docker/java/spring-boot-native.Dockerfile
- utils/build/docker/java/spring-boot-openliberty.Dockerfile
- utils/build/docker/java/spring-boot-undertow.Dockerfile
- utils/build/docker/java/spring-boot-wildfly.Dockerfile
- utils/build/docker/java/spring-boot.Dockerfile
- utils/build/docker/java/vertx3.Dockerfile
Simplify Java app.sh
Use a plain app.sh script rather than creating it with `echo`. Use environment variables when we need to tweak the tracer.
Once your PR is …
> Simplify Java app.sh

- tests/test_schemas.py
Skip schemas test for node tracer v2 too
> Skip schema test for node tracer v2

- utils/interfaces/_backend.py
Small typo fix for `computeCount`, and remove the deprecated `includeEvents`.
Functionally, nothing change.
> Fix backend typo

- parametric/conftest.py
- parametric/test_headers_b3.py
- parametric/test_headers_b3multi.py
- parametric/test_headers_datadog.py
- parametric/test_headers_none.py
- parametric/test_headers_precedence.py
- parametric/test_headers_tracecontext.py
- parametric/test_headers_tracestate_dd.py
Removes test skips for the header tests that are now passing.
> [parametric] Removes test skips for the header tests that are now passing

- tests/remote_config/test_remote_configuration.py
Fix https://github.com/DataDog/system-tests-dashboard/actions/runs/4350838335/jobs/7601941694
> Skip failing test on ASM RC

- conftest.py
- utils/_context/_scenarios.py
- utils/interfaces/_agent.py
- utils/interfaces/_logs.py
> Minor fixes

- utils/build/docker/php/common/users.php
> Add users endpoint on php

- utils/interfaces/schemas/library/v0.7/config-request.json
> products array on remote config must not be empty

- utils/build/build.sh
This PR adds support for Linux aarch64.
> Support for Linux aarch64

- utils/_context/_scenarios.py
- utils/proxy/core.py
Proper fix for https://github.com/DataDog/system-tests/pull/985
It seems that `mitmproxy` cannot have two proxies in the same process (see [here](https://github.com/mitmproxy/mitmproxy/blob/8e7564e9954f7ec49eab60102abb8db3366d3bc6/mitmproxy/master.py#L43), and [here](https://github.com/mitmproxy/mitmproxy/discussions/5762)), and it was causing issues in some tests.
This PR uses the same proxy with two different modes, since [a single proxy can support multiple ones](https://docs.mitmproxy.org/stable/concepts-options/#mode).
```
./run.sh APM_TRACING_E2E_SINGLE_SPAN
...
runner  | tests/apm_tracing_e2e/test_single_span.py ..                                                                     [100%]
runner  | 
runner  | ------------------------------------ …
```
> fix multiple mitmproxy proxies conflicting

- tests/remote_config/test_remote_configuration.py
- utils/interfaces/_core.py
- utils/interfaces/_deserializer.py
- utils/interfaces/schemas/library/-request.json
- utils/interfaces/schemas/library/info-request.json
> Add a small helper test on remote config

- tests/test_identify.py
- utils/build/docker/dotnet/Endpoints/IdentifyEndpoint.UserDetails.cs
> Activate propagation test for .NET

- parametric/test_headers_tracestate_dd.py
Switch some header tests to check sample override and decision maker drop as well.
> Switch some tests to do sample override and drop decision maker

- parametric/requirements.txt
Building parametric test failed without this.
> Update dependencies for grpc and protobuf

- parametric/test_otel_span_methods.py
- parametric/test_otel_span_with_w3c.py
- parametric/test_otel_tracer.py
Waiting for https://github.com/DataDog/dd-trace-go/pull/1839 to get merged first to unblock PR reviews
Once your PR …
> Skipped OTel parametric tests for Go

- parametric/requirements.txt
Update ddtrace + grpcio + grpcio-tools + protobuf since otherwise parametric tests don't seem to be able to run on recent MacBooks.
Once your PR is reviewed, you …
> update ddtrace + grpcio + grpcio-tools + protobuf

- lib-injection/build/docker/ruby/dd-lib-ruby-init-test-rails-bundle-deploy/Dockerfile
- lib-injection/build/docker/ruby/dd-lib-ruby-init-test-rails-conflict/Dockerfile
- lib-injection/build/docker/ruby/dd-lib-ruby-init-test-rails-explicit/Dockerfile
- lib-injection/build/docker/ruby/dd-lib-ruby-init-test-rails-gemsrb/Dockerfile
- lib-injection/build/docker/ruby/dd-lib-ruby-init-test-rails/Dockerfile
- lib-injection/runner/action.yml
> Pin ruby images with 3.1.3

- tests/appsec/iast/sink/test_iast_sql_injection.py
- tests/appsec/iast/sink/test_iast_weak_hash.py
> skip failing test on python

- utils/build/docker/java/jersey-grizzly2.Dockerfile
- utils/build/docker/java/ratpack.Dockerfile
- utils/build/docker/java/resteasy-netty3.Dockerfile
- utils/build/docker/java/spring-boot-jetty.Dockerfile
- utils/build/docker/java/spring-boot-openliberty.Dockerfile
- utils/build/docker/java/spring-boot-undertow.Dockerfile
- utils/build/docker/java/spring-boot-wildfly.Dockerfile
- utils/build/docker/java/spring-boot.Dockerfile
- utils/build/docker/java/uds-spring-boot.Dockerfile
- utils/build/docker/java/vertx3.Dockerfile
Slightly smaller, upgraded JDK, Maven, and base operating system.
> Upgrade Java builder image to 3.9-eclipse-temurin-11

- utils/build/docker/java/spring-boot-native.Dockerfile
- utils/build/docker/java/spring-boot/pom.xml
Every artifact is on Maven Central. repo.spring.io might just slow things down.
> Remove repo.spring.io

- tests/appsec/test_ip_blocking_maxed.py
> Skip failing test on node (appsec_ip_blocking_maxed)

- tests/appsec/waf/test_rules.py
> [dotnet library] remove some bug tags

- tests/appsec/iast/sink/test_iast_sql_injection.py
- tests/appsec/iast/sink/test_iast_weak_hash.py
- utils/interfaces/_library/appsec_iast.py
> IAST python version fix

- .dockerignore
Fix docker build including logs_* in context
The incorrect exclusion triggers spurious rebuilds and makes things take longer than needed due to transferring a big context.
> **_NOTE:_**  By default in PR only default scenario tests will be launched. Please refer to the [documentation](https://datadoghq.atlassian.net/wiki/spaces/APMINT/pages/2866381467/CI+Workflow+Github+Actions) to run all scenarios in your PR if …
> Fix docker build including logs_* in context

- utils/build/docker/java/spring-boot/pom.xml
Pin version for wildfly-jar-maven-plugin. The build is failing with the new 9.0.0.Final release of this plugin.
> Fix spring-boot-wildfly build

- tests/appsec/iast/source/test_iast_request_body.py
> Fix test name for IAST request body

- tests/appsec/iast/sink/test_iast_command_injection.py
- tests/appsec/iast/sink/test_iast_ldap_injection.py
- tests/appsec/iast/sink/test_iast_path_traversal.py
- tests/appsec/iast/sink/test_iast_sql_injection.py
- tests/appsec/iast/sink/test_iast_weak_cipher.py
- tests/appsec/iast/sink/test_iast_weak_hash.py
- tests/appsec/iast/source/test_iast_request_body.py
- tests/appsec/iast/source/test_iast_request_cookie_name.py
- tests/appsec/iast/source/test_iast_request_cookie_value.py
- tests/appsec/iast/source/test_iast_request_header.py
- tests/appsec/iast/source/test_iast_request_header_name.py
- tests/appsec/iast/source/test_iast_request_parameter.py
- tests/appsec/iast/source/test_iast_request_parameter_name.py
> Enable all supported IAST tests for Java

- utils/build/docker/python/flask/app.py
Fix the Flask "track_custom_event" view that didn't have a return.
Once your PR is reviewed, you can merge it ! …
> Fix Flask view without response

- README.md
- docs/execute/README.md
- docs/execute/requirements.md
> Doc on requirements

- utils/_context/_scenarios.py
- utils/_context/containers.py
> Revamp and clean scenarios/containers

- utils/build/docker/dotnet/install_ddtrace.sh
- utils/scripts/docker_base_image.sh
> fix dotnet docker base images

- utils/_context/_scenarios.py
- utils/_context/containers.py
Bitnami/kafka:latest is not working, stick to an older version
> Fix kafka version

- .github/CODEOWNERS
> Update CODEOWNERS with @DataDog/system-tests-core

- utils/_context/_scenarios.py
> Reduce setup wait time for Java to 10 seconds

- conftest.py
- tests/fuzzer/core.py
- tests/fuzzer/main.py
- tests/fuzzer/request_mutator.py
- utils/_context/_scenarios.py
- utils/_context/containers.py
- utils/_context/core.py
- utils/interfaces/_backend.py
- utils/interfaces/_core.py
- utils/interfaces/_logs.py
- utils/interfaces/_schemas_validators.py
- utils/test_the_test/test_stdout_reader.py
Clean startup sequence to prepare integration of parametric tests
> Clean startup sequence

- .github/workflows/ci.yml
Previously, if a scenario fails, next scneario are not executed, which makes PR involving several scenario painfull to test.
> Launch every relevant scenarios if build is successful

- .gitignore
> Add pyenv .python-version to .gitignore

- tests/appsec/iast/sink/test_ssrf.py
- utils/build/docker/java/iast-common/src/main/java/com/datadoghq/system_tests/iast/utils/SsrfExamples.java
- utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/MyResource.java
- utils/build/docker/java/resteasy-netty3/src/main/java/com/datadoghq/resteasy/IastSinkResource.java
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/AppSecIast.java
- utils/build/docker/java/vertx3/src/main/java/com/datadoghq/vertx3/iast/routes/IastSinkRouteProvider.java
- utils/build/docker/java/vertx4/src/main/java/com/datadoghq/vertx4/iast/routes/IastSinkRouteProvider.java
Adds required enpoints for Java
> Add SSRF endpoints for Java

- tests/appsec/iast/sink/test_ssrf.py
- utils/build/docker/java/iast-common/src/main/java/com/datadoghq/system_tests/iast/utils/SsrfExamples.java
- utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/MyResource.java
- utils/build/docker/java/resteasy-netty3/src/main/java/com/datadoghq/resteasy/IastSinkResource.java
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/AppSecIast.java
- utils/build/docker/java/vertx3/src/main/java/com/datadoghq/vertx3/iast/routes/IastSinkRouteProvider.java
- utils/build/docker/java/vertx4/src/main/java/com/datadoghq/vertx4/iast/routes/IastSinkRouteProvider.java
- utils/build/docker/nodejs/express4/iast.js
> SSRF vulnerabiilty detection system test implemented in nodejs and java

- utils/build/docker/nodejs/express4-typescript.Dockerfile
- utils/build/docker/nodejs/express4.Dockerfile
- utils/build/docker/nodejs/uds-express4.Dockerfile
Update Node.js system tests to use v16.
We're dropping support for Node 14.
> update nodejs system tests to use v16

- tests/appsec/iast/sink/test_weak_cipher.py
Following the same convention as every other IAST sink test.
> Rename TestIastWeakCipher to TestWeakCipher

- tests/appsec/iast/iast_fixtures.py
> Fix SinkFixture.test_secure test

- tests/appsec/waf/test_blocking.py
> Enable test for new block template in Java 1.14.0

- tests/appsec/test_rate_limiter.py
Make tests/appsec/test_rate_limiter.py deterministic (always the same number of requests)
Allow to enable replay mode on this scenario
> Make appsec/test_rate_limiter deterministic

- tests/appsec/test_blocking_addresses.py
- utils/build/docker/golang/app/chi.go
- utils/build/docker/golang/app/echo.go
- utils/build/docker/golang/app/gin.go
- utils/build/docker/golang/app/gorilla.go
- Add go endpoints for SRB testing
- Enable SRB tests for Go
> go: enable SRB tests

- tests/appsec/iast/sink/test_weak_randomness.py
- utils/build/docker/java/iast-common/src/main/java/com/datadoghq/system_tests/iast/utils/WeakRandomnessExamples.java
- utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/MyResource.java
- utils/build/docker/java/resteasy-netty3/src/main/java/com/datadoghq/resteasy/IastSinkResource.java
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/AppSecIast.java
- utils/build/docker/java/vertx3/src/main/java/com/datadoghq/vertx3/iast/routes/IastSinkRouteProvider.java
- utils/build/docker/java/vertx4/src/main/java/com/datadoghq/vertx4/iast/routes/IastSinkRouteProvider.java
Add tests for weak randomness vulnerability detection
> Add weak randomness detection tests

- tests/appsec/iast/sink/test_ssrf.py
> Fix decorators for IAST SSRF test

- tests/appsec/iast/sink/test_insecure_cookie.py
- utils/build/docker/nodejs/express4/iast/index.js
Add test to check that the insecure cookie vulnerability detection in iast is working.
> Add insecure cookie test

- tests/test_telemetry.py
This used to be flaky, but now that telemetry heartbeat is reduced to 2 seconds in the tests, it seems to work properly.
> Enable telemetry heartbeat test

- utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/IastSinkResource.java
- utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/IastSourceResource.java
- utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/MyResource.java
- utils/build/docker/java/resteasy-netty3/src/main/java/com/datadoghq/resteasy/MyResource.java
There was a lot of divergence for code that should be mostly the same.
> Unify jersey-grizzly2 and resteasy-netty3 weblogs

- .github/pull_request_template.md
- tests/appsec/blocking_rule.json
- tests/appsec/test_blocking_addresses.py
Fix scenario APPSEC_BLOCKING
Issue introduced #1225
> Fix appsec blocking scenario

- docs/execute/e2e.md
- tests/apm_tracing_e2e/README.md
Added a short summary of steps necessary to run / update the e2e tests.
Improving the documentation and user experience
> Added a Readme to apm_tracing_e2e with running instructions

- tests/onboarding/test_onboarding_install.py
Make it private class to avoid posible conflicts with pytest
> Rename TestOnboardingInstallBaseTest -> _OnboardingInstallBaseTest

- tests/appsec/iast/sink/test_unvalidated_redirect.py
- utils/build/docker/nodejs/express4/iast/index.js
- Update unvalidated redirect vulnerability sink test with nodejs details
- Add express endpoints to test unvalidated redirect in `response.redirect()` and `response.setHeader()` methods
> Prepare nodejs Unvalidated redirect vulnerability testing

- tests/appsec/test_blocking_addresses.py
- utils/build/docker/java/jersey-grizzly2/pom.xml
- utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/MyResource.java
- utils/build/docker/java/ratpack/pom.xml
- utils/build/docker/java/ratpack/src/main/java/com/datadoghq/ratpack/Main.java
- utils/build/docker/java/ratpack/src/main/java/com/datadoghq/ratpack/WafPostHandler.java
- utils/build/docker/java/resteasy-netty3/src/main/java/com/datadoghq/resteasy/MyResource.java
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/App.java
- utils/build/docker/java/vertx3/src/main/java/com/datadoghq/vertx3/Main.java
- utils/build/docker/java/vertx4/src/main/java/com/datadoghq/vertx4/Main.java
> Suspicious request blocking tests for Java

- tests/integrations/test_dbm.py
- utils/_weblog.py
`npgsql` request seems to be very slow
> Fix small flakyness in .NET

- tests/appsec/test_ip_blocking_full_denylist.py
- tests/appsec/waf/test_blocking.py
- tests/test_the_test/test_decorators.py
- utils/_decorators.py
`@released` declares versions for feature, and must be used only on classes.
> Allow @released only on classes

- tests/appsec/blocking_rule.json
- tests/appsec/test_blocking_addresses.py
- tests/appsec/waf/test_blocking.py
- utils/build/docker/dotnet/Controllers/TagValueController.cs
Activate tests related to WAF addresses.
Activating tests are good.
> [ASM] activate tests for newly minted features

- .github/actions/install_runner/action.yaml
- .github/actions/lint_code/action.yaml
- .github/workflows/ci.yml
> Optimize CI

- tests/appsec/iast/sink/test_unvalidated_redirect_forward.py
- tests/test_semantic_conventions.py
- utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/IastSinkResource.java
- utils/build/docker/java/resteasy-netty3/src/main/java/com/datadoghq/resteasy/IastSinkResource.java
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/AppSecIast.java
- Update sink test for unvalidated redirect vulnerability
- Add jersey and resteasy endpoints to test unvalidated redirect in header and location Response methods
- Add servlet forward test
Test unvalidated redirect vulnerability
> Update IAST unvalidated redirect vulnerability

- .github/workflows/ci.yml
Fuzzer CI is currently broken, probably a typo
> Fix fuzzer CI

- tests/test_telemetry.py
This test is flaky on java. Skipping it waiting for a confirmation/fix
> Skip flaky test on java

- .github/workflows/experimental.yml
The tests disabled until the jira issue fixed
https://datadoghq.atlassian.net/browse/AIT-7722
> Disable experimental tests auto injection

- tests/test_telemetry.py
Ensure that heartbeats are actually received (the previous test validated even if no heartbeats were received at all, but other telemetry messages were).
Check the interval time between heartbeats themselves.
Mark Ruby as `@bug`, since it's not sending heartbeats at all.
> Improve test for telemetry heartbeats

- tests/test_telemetry.py
> Test if telemetry heartbeats are sent too fast

- utils/interfaces/_backend.py
- utils/interfaces/_core.py
The `accept_data` logic is not needed anymore.
> Remove some ingestion leftovers

- utils/build/docker/agent.Dockerfile
> Fix build of old agent versions

- tests/appsec/test_automated_login_events.py
- utils/build/docker/nodejs/express4-typescript.Dockerfile
- utils/build/docker/nodejs/express4-typescript/app.ts
- utils/build/docker/nodejs/express4-typescript/auth.js
- utils/build/docker/nodejs/express4-typescript/auth.ts
- utils/build/docker/nodejs/express4-typescript/package-lock.json
- utils/build/docker/nodejs/express4-typescript/package.json
Enable automatic user events tests for nodejs v4.4.0
> Enable auto user events for nodejs v4.4.0

- utils/build/docker/python/django-poc.base.Dockerfile
- utils/build/docker/python/flask-poc.base.Dockerfile
- utils/build/docker/python/uwsgi-poc.base.Dockerfile
Add `cmake` and `make` Flask, Django and Uwsgi docker files.
Following Python PRs need it:
https://github.com/DataDog/dd-trace-py/pull/6199
https://github.com/DataDog/dd-trace-py/pull/6108
https://github.com/DataDog/dd-trace-py/tree/avara1986/move_cpp_functions
> feat(python): update docker images

- tests/appsec/test_automated_login_events.py
- utils/build/docker/nodejs/express4/auth.js
> Fix id for extended tests as well

- utils/build/docker/java/akka-http/pom.xml
- utils/build/docker/java/iast-common/pom.xml
- utils/build/docker/java/vertx3/pom.xml
- utils/build/docker/java/vertx4/pom.xml
* Fixes #1376
* Fixes #1375
* Fixes #1374
* Fixes #1373
> java: Update deps (bcprov-jdk18on)

- tests/test_telemetry.py
Skip two failing tests.
Massive failure on CI. Can't reproduce yet locally.
> Hotfix telemetry test

- tests/appsec/test_automated_login_events.py
Fix assertion that checks that the 'usr.id' tag is empty for nodejs. These tests will be skipped for all versions util the fix is in dev branch.
> Fix empty 'usr.id' tag.

- .gitlab-ci.yml
Fix gitlab ci pipeline (onboarding)
> Fix onboarding gitlab ci pipeline

- tests/integrations/test_dsm.py
- utils/build/docker/dotnet/Dependencies/RabbitMQHelper.cs
- utils/build/docker/dotnet/Endpoints/DsmEndpoint.cs
- utils/build/docker/dotnet/app.csproj
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/App.java
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/rabbitmq/RabbitmqConnector.java
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/rabbitmq/RabbitmqConnectorForDirectExchange.java
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/rabbitmq/RabbitmqConnectorForFanoutExchange.java
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/rabbitmq/RabbitmqConnectorForTopicExchange.java
> Update rabbit tests in test_dsm.py for both Java and dotnet

- tests/appsec/api_security/test_schemas.py
Activate scenario APPSEC_API_SECURITY for python tracer
The Api Security Feature was privately released in 1.16.0 version of dd-trace-py
> api_security activation for python tracer

- tests/appsec/iast/sink/test_command_injection.py
- tests/appsec/iast/sink/test_ldap_injection.py
- tests/appsec/iast/sink/test_path_traversal.py
- tests/appsec/iast/sink/test_sql_injection.py
- tests/appsec/iast/sink/test_ssrf.py
- tests/appsec/iast/sink/test_unvalidated_redirect.py
- tests/appsec/iast/sink/test_unvalidated_redirect_forward.py
- tests/appsec/iast/sink/test_weak_cipher.py
- tests/appsec/iast/sink/test_weak_hash.py
- tests/appsec/iast/sink/test_weak_randomness.py
- tests/appsec/iast/sink/test_xpath_injection.py
- tests/appsec/iast/source/test_body.py
- tests/appsec/iast/source/test_cookie_name.py
- tests/appsec/iast/source/test_cookie_value.py
- tests/appsec/iast/source/test_header_name.py
- tests/appsec/iast/source/test_header_value.py
- tests/appsec/iast/source/test_parameter_name.py
- tests/appsec/iast/source/test_parameter_value.py
- utils/build/docker/java/akka-http/src/main/scala/com/datadoghq/akka_http/IastRoutes.scala
- utils/build/docker/java/iast-common/src/main/java/com/datadoghq/system_tests/iast/utils/XPathExamples.java
- utils/build/docker/java/jersey-grizzly2/pom.xml
- utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/IastSourceResource.java
- utils/build/docker/java/ratpack.Dockerfile
- utils/build/docker/java/ratpack/pom.xml
- utils/build/docker/java/ratpack/src/main/java/com/datadoghq/ratpack/IastHandlers.java
- utils/build/docker/java/ratpack/src/main/java/com/datadoghq/ratpack/Main.java
- utils/build/docker/java/resteasy-netty3/src/main/java/com/datadoghq/resteasy/IastSourceResource.java
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/AppSecIastSource.java
- utils/build/docker/java/vertx3/src/main/java/com/datadoghq/vertx3/iast/routes/IastSourceRouteProvider.java
- utils/build/docker/java/vertx4/src/main/java/com/datadoghq/vertx4/iast/routes/IastSourceRouteProvider.java
Add more endpoints, update decorators.
> Add missing IAST tests in Java

- tests/test_telemetry.py
Depends on https://github.com/DataDog/dd-trace-java/pull/5476
> Fix telemetry tests decorators for Java

- tests/integrations/test_dsm.py
- utils/build/docker/nodejs/express4.Dockerfile
- utils/build/docker/nodejs/express4/app.js
- utils/build/docker/nodejs/express4/package.json
> Added dsm endpoint in for node.js to support dsm tests

- utils/interfaces/schemas/agent/api/v0.1/configurations-request.json
- utils/interfaces/schemas/agent/api/v0.1/org-request.json
- utils/interfaces/schemas/agent/api/v0.1/status-request.json
New request from agent -> add schema skeleton.
> Add schema for /api/v0.1/org request from agent

- tests/remote_config/test_remote_configuration.py
> Skip schema test on php/RC

- .github/workflows/ci.yml
- tests/apm_tracing_e2e/test_otel.py
- tests/appsec/waf/test_telemetry.py
- tests/test_telemetry.py
- utils/_context/_scenarios.py
- utils/_context/containers.py
- utils/interfaces/_core.py
Investigation for #1380 and #1370
> Investigate flaky tests

- run.sh
> Fix scenario set run

- tests/appsec/test_automated_login_events.py
Add the necessary information on the automated login event in the extended mode for ruby. 
The tests are not yet enabled as the feature has not being release. The test have been tested locally 😄 
> [APPSEC-10347] Add necessary code for automated login events in  extended mode for ruby

- tests/appsec/iast/sink/test_insecure_cookie.py
- tests/appsec/iast/sink/test_no_httponly_cookie.py
- tests/appsec/iast/sink/test_no_samesite_cookie.py
> feat(python): enable IAST cookies vulnerabilities

- tests/parametric/test_otel_span_methods.py
- tests/parametric/test_otel_span_with_w3c.py
- tests/parametric/test_otel_tracer.py
- utils/build/docker/dotnet/parametric/ApmTestClient.csproj
- utils/build/docker/dotnet/parametric/Services/ApmTestClientService.Otel.cs
Unskip and update the parametric tests for OpenTelemetry for .NET.
Required for GA for OpenTelemetry
> Update OpenTelemetry parametric tests for .NET

- tests/appsec/iast/sink/test_trust_boundary_violation.py
- utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/IastSinkResource.java
- utils/build/docker/java/spring-boot/pom.xml
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/AppSecIast.java
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/CookieConfig.java
Added Trust Boundary violation vulnerability detection tests and endpoints
Trust Boundary violation vulnerability detection was added to the java library recently and we need tests for that functionality.
> Added trust boundary violation tests and endpoints

- utils/build/docker/java/ratpack/src/main/java/com/datadoghq/ratpack/Main.java
Use Promises for the block where it makes a request.
> [Java][Ratpack] Avoid blocking in /make_distant_call

- utils/build/docker/java/spring-boot-payara.Dockerfile
> [Java][Payara] Speed up startup by disabling clustering

- tests/appsec/waf/test_blocking.py
Per title, See APPSEC-10798
Feature is flaky
> Skip failing test on ASM/java

- tests/test_telemetry.py
> Disable telemetry v2 required header tests for python

- docs/scenarios/parametric.md
Fix old instructions before parametric tests were merged.
Get the documentation right.
> Update parametric tests documentation

- tests/test_scrubbing.py
The test logic might be slightly confusing. Clarify that it is the client HTTP request that we care about.
> Clarify test_scrubbing::Test_UrlField

- manifests/cpp.yml
- manifests/dotnet.yml
- manifests/golang.yml
- manifests/java.yml
- manifests/nodejs.yml
- manifests/php.yml
- manifests/python.yml
- manifests/ruby.yml
- tests/appsec/iast/sink/test_xss.py
- utils/build/docker/java/iast-common/src/main/java/com/datadoghq/system_tests/iast/utils/XSSExamples.java
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/AppSecIast.java
- Add XSS tests 
- Add Java XSS enpoints in spring-boot
Test XSS vulnerability
Some test are enabled for next dd-java-agent version (1.19.0)
> Add IAST XSS system test

- tests/fuzzer/main.py
- utils/_context/_scenarios.py
- utils/_context/containers.py
- utils/interfaces/__init__.py
- utils/interfaces/_logs.py
Add stdout interface for postgres container
Allow logs assertion on postgres container
> Add stdout interface for postgres DB container

- utils/build/docker/dotnet/install_ddtrace.sh
Fix for the bug when `dotnet` library compiled for x64 used on arm64 platform.
> Support dotnet arm64

- .github/CODEOWNERS
Update ASM team  CODEOWNERS. We have renamed the teams from `appsec-*` to `asm-*`
> update asm teams on CODEOWNERS file

- tests/appsec/test_request_blocking.py
> Skip failing test on ruby

- .github/workflows/ci.yml
- .github/workflows/compute-scenarios.yml
- docs/CI/labels.md
Add support for `run-debugger-scenarios` label.
Reduce waiting time when modifying debugger tests related only.
> Add debugger label

- docs/scenarios/parametric.md
- utils/build/docker/nodejs/parametric/Dockerfile
* Correct path for inserting npm tarball
* Correct CLI args
* Add git to docker image
> Clearer Node.js parametric test instructions

- .gitlab-ci.yml
Fix failures on the pulumi command plugin installation
> Fix pulumi command plugin installation

- conftest.py
- manifests/parser/core.py
- utils/_decorators.py
> Minor fixes on manifest logic

- tests/appsec/waf/test_rules.py
Argument name was missing in `@released`
> Fix typo in golang version declaration

- manifests/cpp.yml
- tests/debugger/test_debugger.py
- tests/integrations/test_dbm.py
- tests/integrations/test_dsm.py
- tests/parametric/test_dynamic_configuration.py
- tests/remote_config/test_remote_configuration.py
- tests/test_distributed.py
- tests/test_telemetry.py
Use manifest files rather than inline declarations
> Use manifest file for C++ versions declarations

- tests/test_standard_tags.py
Tests in https://app.circleci.com/pipelines/github/DataDog/dd-trace-java/28746/workflows/defbc7cf-6d62-4811-8c16-92a08322baa1/jobs/963842
> New query string obfuscation regexp for Java

- tests/appsec/api_security/test_schemas.py
With the integration of the new waf feature to compute type schemas into the libraries, all keys will be lowercase.
> update to lowercase for api_security tests

- .github/workflows/ci.yml
> Remove temporary fix from PHP

- tests/test_the_test/test_decorators.py
- utils/_decorators.py
> Include agent in released decorator

- manifests/python.yml
- tests/appsec/api_security/test_schemas.py
Fix failure found in the test_schemas.py and python release annotation/manifest
> Fix test_schemas and python releases manifest

- manifests/dotnet.yml
- manifests/golang.yml
- manifests/nodejs.yml
- manifests/python.yml
- manifests/ruby.yml
- tests/appsec/api_security/test_schemas.py
Add tests for request cookies for api security schema extraction
Fix typo Reponse -> Response for api security tests
> api security tests for request cookies

- manifests/php.yml
- tests/appsec/test_PII.py
- tests/appsec/test_automated_login_events.py
- tests/appsec/test_client_ip.py
- tests/appsec/test_identify.py
- tests/appsec/test_logs.py
- tests/appsec/test_reports.py
- tests/appsec/test_user_blocking_full_denylist.py
- tests/appsec/waf/test_addresses.py
- tests/appsec/waf/test_telemetry.py
- tests/integrations/test_db_integrations_sql.py
- tests/integrations/test_dbm.py
- tests/integrations/test_dsm.py
- tests/parametric/test_dynamic_configuration.py
- tests/remote_config/test_remote_configuration.py
- tests/test_distributed.py
- tests/test_identify.py
- tests/test_library_conf.py
- tests/test_sampling_rates.py
- tests/test_scrubbing.py
- tests/test_semantic_conventions.py
- tests/test_standard_tags.py
- tests/test_telemetry.py
- tests/test_the_test/test_decorators.py
> Move PHP versions declarations to manifest files

- manifests/python.yml
activate custom blocking reponse test for python
> activate custom blocking reponse test for python

- docs/edit/README.md
- docs/edit/coverage.md
- docs/edit/declare-versions.md
- docs/execute/force-execute.md
- docs/execute/replay.md
- docs/internals/PR-reviews.md
> Update doc to use manifest files

- conftest.py
- manifests/agent.yml
- manifests/dotnet.yml
- manifests/golang.yml
- manifests/java.yml
- manifests/nodejs.yml
- manifests/python.yml
- manifests/ruby.yml
- tests/appsec/test_automated_login_events.py
- tests/appsec/test_reports.py
- tests/integrations/test_db_integrations_sql.py
- tests/integrations/test_dbm.py
- tests/integrations/test_dsm.py
- tests/otel_tracing_e2e/test_e2e.py
- tests/parametric/test_dynamic_configuration.py
- tests/test_standard_tags.py
- tests/test_telemetry.py
- tests/test_the_test/test_decorators.py
- tests/test_the_test/test_json_report.py
- utils/_decorators.py
> Final migration leftovers for version declaration

- manifests/java.yml
- tests/appsec/test_conf.py
- tests/appsec/test_customconf.py
- tests/appsec/test_logs.py
- tests/appsec/test_rate_limiter.py
- tests/appsec/test_runtime_activation.py
- tests/appsec/waf/test_addresses.py
- tests/appsec/waf/test_blocking.py
- tests/appsec/waf/test_exclusions.py
- tests/appsec/waf/test_miscs.py
- tests/appsec/waf/test_reports.py
- tests/appsec/waf/test_rules.py
- tests/appsec/waf/test_telemetry.py
- tests/onboarding/test_onboarding_install.py
> Remove bare pytest import and skips

- tests/debugger/test_debugger.py
- utils/_context/_scenarios.py
- utils/build/docker/dotnet/Controllers/DebuggerController.cs
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/DebuggerController.java
- utils/proxy/rc_mocked_responses_debugger_method_probes_snapshot.json
Add span and span-decoration method probe snapshot tests
> [DEBUGGER] Add span and span-decoration method probe snapshot tests

- docs/weblog/README.md
- manifests/python.yml
- tests/appsec/api_security/test_schemas.py
- utils/_context/_scenarios.py
- utils/build/docker/ruby/sinatra14/app.rb
- utils/build/docker/ruby/sinatra20/app.rb
- utils/build/docker/ruby/sinatra21/app.rb
Update the ENV variables for the API security base on the latest changes in the RFC.
Disable the Python tests. 
Also, update some of the tests to make the assertion more relax
> Api security env variable

- tests/debugger/test_debugger.py
- utils/_context/_scenarios.py
- utils/proxy/rc_mocked_responses_debugger_line_probes_snapshot.json
Add more line probe snapshots tests
> [Debugger] Add more line probe snapshots tests

- manifests/cpp.yml
- tests/appsec/test_versions.py
- tests/debugger/test_debugger.py
- tests/test_library_conf.py
- tests/test_miscs.py
- tests/test_profiling.py
- tests/test_sampling_rates.py
- tests/test_telemetry.py
> Migrate few C++ leftovers in manifest file

- manifests/php.yml
- tests/appsec/test_blocking_addresses.py
- tests/appsec/test_reports.py
- tests/appsec/waf/test_addresses.py
- tests/appsec/waf/test_rules.py
- tests/debugger/test_debugger.py
- tests/remote_config/test_remote_configuration.py
- tests/test_profiling.py
> Migrate  few PHP leftovers in manifest file

- manifests/python.yml
- tests/appsec/iast/_test_iast_fixtures.py
- tests/appsec/iast/sink/test_command_injection.py
- tests/appsec/iast/sink/test_weak_cipher.py
- tests/appsec/iast/sink/test_weak_hash.py
- tests/appsec/iast/sink/test_weak_randomness.py
- utils/build/docker/python/django/django.app.urls.py
- utils/build/docker/python/flask/app.py
- Python weak randomness vulnerability
- Update `test_telemetry_metric_instrumented_sink` function: validate tags case insensitive 
> feat(python): weak randomness vulnerability

- manifests/cpp.yml
- manifests/java.yml
- manifests/nodejs.yml
- manifests/parser/core.py
- manifests/php.yml
- manifests/ruby.yml
- tests/apm_tracing_e2e/test_otel.py
- tests/apm_tracing_e2e/test_single_span.py
- tests/appsec/test_blocking_addresses.py
- tests/appsec/waf/test_miscs.py
- tests/debugger/test_debugger.py
- tests/integrations/test_cassandra.py
- tests/integrations/test_mongo.py
- tests/integrations/test_sql.py
- tests/otel_tracing_e2e/test_e2e.py
- tests/remote_config/test_remote_configuration.py
- tests/test_profiling.py
- tests/test_semantic_conventions.py
- tests/test_telemetry.py
- utils/_decorators.py
> Hopefully, last manifest migration

- .github/workflows/ci.yml
- manifests/cpp.yml
- manifests/dotnet.yml
- manifests/golang.yml
- manifests/java.yml
- manifests/nodejs.yml
- manifests/php.yml
- manifests/python.yml
- manifests/ruby.yml
- tests/integrations/test_db_integrations_sql.py
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/integerations/db/BaseCRUDOperation.java
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/integerations/db/mssql/MssqlCRUDOperation.java
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/integerations/db/postgres/PostgresCRUDOperation.java
- utils/build/docker/nodejs/express4/app.js
- utils/build/docker/nodejs/express4/integrations/db/mssql.js
- utils/build/docker/nodejs/express4/integrations/db/mysql.js
- utils/build/docker/nodejs/express4/integrations/db/postgres.js
- utils/build/docker/nodejs/express4/integrations/db/resources/mysql.sql
- utils/build/docker/nodejs/express4/integrations/db/resources/postgres.sql
- utils/build/docker/python/flask/integrations/db/mssql.py
- utils/build/docker/python/flask/integrations/db/mysqldb.py
- utils/build/docker/python/flask/integrations/db/postgres.py
We have recently added integration tests for databases.
Until now we have done the validations of the library/trace, in this PR we add the validations of the messages that go out from the agent.
We have also added sql query obfuscation tests.
> Db Integrations scenario: add agent interface validations

- manifests/python.yml
- tests/appsec/iast/sink/test_insecure_cookie.py
- tests/appsec/iast/sink/test_no_httponly_cookie.py
- tests/appsec/iast/sink/test_no_samesite_cookie.py
- tests/appsec/iast/sink/test_path_traversal.py
- utils/build/docker/python/django/django.app.urls.py
- utils/build/docker/python/flask/app.py
- Python path traversal vulnerability
> feat(python): path traversal vulnerability

- tests/test_telemetry.py
Per title (See https://datadoghq.atlassian.net/browse/AIT-1717)
> Skip test_seq_id for ruby (flaky)

- tests/test_standard_tags.py
> Enable Java test: Test_StandardTagsClientIp.test_client_ip_with_appsec_event_and_vendor_headers

- manifests/java.yml
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/AppSecIast.java
> Fix XCONTENTTYPE_MISSING_HEADER header and mark Java as bug

- utils/build/docker/ruby/rails60.Dockerfile
Simplify Dockerfile for the rails60 weblog
> simplify rails 6.0 dockerfile

- manifests/java.yml
> [Java] Enable IAST test in Payara

- tests/appsec/waf/test_exclusions.py
> Skip test_input_exclusion_positive_test on nodejs/main

- manifests/python.yml
> Deactivate IAST TestPathTraversal on python3.12 (not supported)

- .github/workflows/ci.yml
- manifests/python.yml
- utils/_context/containers.py
> Python3.12 is now supported on released python library

- tests/parametric/test_headers_b3multi.py
> Mark irrelevant test for legacy b3 propagation style

- tests/appsec/iast/_test_iast_fixtures.py
> Add a warning if agent answered 403 in telemetry/iast tests

- docs/weblog/README.md
> Document IAST source weblog points, clean up formatting

- .github/workflows/ci.yml
- docs/execute/build.md
- manifests/python.yml
- tests/test_semantic_conventions.py
- utils/build/docker/python/fastapi.Dockerfile
- utils/build/docker/python/fastapi.base.Dockerfile
- utils/build/docker/python/fastapi/app.sh
- utils/build/docker/python/fastapi/log_conf.yaml
- utils/build/docker/python/fastapi/main.py
add new FastAPI variant to python
ASM plan to fully support FastAPI.
> chore(python): add new FastAPI variant

- .github/actions/pull_images/action.yml
- tests/appsec/test_blocking_addresses.py
- tests/test_the_test/test_manifest.py
Per title.
Also two minor fixes
> Ensure all items in manifest esists

- manifests/java.yml
> Skip Test_HstsMissingHeader for java (flaky)

- manifests/dotnet.yml
- tests/appsec/iast/sink/test_weak_hash.py
- utils/build/docker/dotnet/Controllers/IastController.cs
This PR contains the IAST weak hash vulnerability tests for .net 
This is the first PR of IAST tests for .net
> [.Net] IAST Weak hash implementation

- manifests/java.yml
- tests/appsec/iast/sink/test_hsts_missing_header.py
Per title, see #1682 and #1638
> Rollback #1682, fix #1638

- manifests/nodejs.yml
Enable GraphQL tests for nodejs.
> Enable GraphQL tests for node tracer v4.16.0.

- manifests/ruby.yml
Enable the schema extraction tests for ruby 1.15.0
> Enable schema extraction test for Ruby

- docs/edit/manifest.md
- utils/_decorators.py
> Improve manifest docs and messages

- manifests/nodejs.yml
Enable node waf telemetry metrics
> [node.js] Test waf telemetry metrics

- logs.sh
- manifests/dotnet.yml
- tests/appsec/iast/sink/test_command_injection.py
- utils/build/docker/dotnet/Controllers/IastController.cs
This PR contains the IAST insecure command vulnerability tests for .net
To increase the coverage of the .net system tests regarding the already implemented features of IAST.
> [.Net] IAST insecure command implementation

- tests/appsec/iast/_test_iast_fixtures.py
- tests/appsec/iast/source/test_body.py
- tests/appsec/iast/source/test_cookie_name.py
- tests/appsec/iast/source/test_cookie_value.py
- tests/appsec/iast/source/test_header_name.py
- tests/appsec/iast/source/test_header_value.py
- tests/appsec/iast/source/test_parameter_name.py
- tests/appsec/iast/source/test_parameter_value.py
Revamp IAST Source Fixture 
1. Remove boilerplate code
2. unblock #1707
3. Follow the style guidelines of this project (See [how to easily lint the code](https://github.com/DataDog/system-tests/blob/main/docs/edit/lint.md))
> Revamp IAST test model

- manifests/python.yml
Per title : https://github.com/DataDog/system-tests-dashboard/actions/runs/6609180626/job/17948945552#step:15:106
> [python] Skip Test_DsmKafka as bug

- manifests/dotnet.yml
- manifests/golang.yml
- manifests/java.yml
- manifests/nodejs.yml
- manifests/php_appsec.yml
- manifests/python.yml
- manifests/ruby.yml
- tests/appsec/iast/_test_iast_fixtures.py
- tests/appsec/iast/sink/test_command_injection.py
- tests/appsec/iast/sink/test_hsts_missing_header.py
- tests/appsec/iast/sink/test_insecure_cookie.py
- tests/appsec/iast/sink/test_ldap_injection.py
- tests/appsec/iast/sink/test_no_httponly_cookie.py
- tests/appsec/iast/sink/test_no_samesite_cookie.py
- tests/appsec/iast/sink/test_nosql_mongodb_injection.py
- tests/appsec/iast/sink/test_path_traversal.py
- tests/appsec/iast/sink/test_sql_injection.py
- tests/appsec/iast/sink/test_ssrf.py
- tests/appsec/iast/sink/test_trust_boundary_violation.py
- tests/appsec/iast/sink/test_unvalidated_redirect.py
- tests/appsec/iast/sink/test_unvalidated_redirect_forward.py
- tests/appsec/iast/sink/test_weak_cipher.py
- tests/appsec/iast/sink/test_weak_hash.py
- tests/appsec/iast/sink/test_weak_randomness.py
- tests/appsec/iast/sink/test_xcontent_sniffing.py
- tests/appsec/iast/sink/test_xpath_injection.py
- tests/appsec/iast/sink/test_xss.py
- utils/_weblog.py
Per title
* remove boilerplate code
* unblock #1707
> [internal] Revamp IAST sink fixture

- tests/onboarding/infra_provision/provision_onboarding_host.yml
> fix onboarding host provision

- manifests/dotnet.yml
- tests/appsec/iast/sink/test_no_samesite_cookie.py
- utils/build/docker/dotnet/Controllers/IastController.cs
Description
IAST NoSamesiteCookie for dotnet
Motivation
> [dotnet] IAST NoSamesiteCookie

- manifests/dotnet.yml
- tests/appsec/iast/sink/test_insecure_cookie.py
- utils/build/docker/dotnet/Controllers/IastController.cs
IAST InsecureCookie for dotnet
> [dotnet] IAST InsecureCookie

- tests/appsec/test_automated_login_events.py
- tests/appsec/test_rate_limiter.py
> Skip Test_Login_Events_Extended on PHP

- manifests/dotnet.yml
- tests/appsec/iast/sink/test_weak_cipher.py
- utils/build/docker/dotnet/Controllers/IastController.cs
> [dotnet] IAST WeakCipher tests

- manifests/dotnet.yml
- tests/appsec/iast/sink/test_path_traversal.py
- utils/build/docker/dotnet/Controllers/IastController.cs
This PR contains the implementation of the IAST path traversal tests
It's a feature that we already support.
> [.Net] IAST PathTraversal tests

- utils/build/docker/cpp/nginx/install_ddtrace.sh
Per title, see opentracing-contrib/nginx-opentracing#527
> Hardcode nginx-opentracing version

- manifests/dotnet.yml
- tests/appsec/iast/sink/test_ssrf.py
- utils/build/docker/dotnet/Controllers/IastController.cs
This PR contains the implementation of the IAST system tests for the SSRF vulnerability
It's a feature that we support but it has no system tests.
> [.Net] SSRF tests

- utils/build/docker/cpp/nginx/install_ddtrace.sh
Issue opentracing-contrib/nginx-opentracing#527 is fixed, revert #1747 
> Revert #1747

- tests/appsec/waf/test_telemetry.py
> Java telemetry API version is now v2

- tests/integrations/test_db_integrations_sql.py
* Better output in case of failure
* iterate over all trace (rather than trace only present in the current payload) to besure to not miss any span (even if I'm pretty sure that iterating on the current trace would be good )
* skip some failing test for java lib `1.23.0`
> Fix integrations scenario on java

- .github/workflows/ci.yml
- .github/workflows/compute-scenarios.yml
> Add label run-integration-scenarios

- tests/integrations/test_db_integrations_sql.py
> Fix integration scenario

- tests/appsec/api_security/test_schemas.py
- utils/_weblog.py
- utils/build/docker/dotnet/Controllers/IastController.cs
- utils/build/docker/dotnet/Controllers/TagValueController.cs
- utils/build/docker/dotnet/Models/ApiSecurity/RequestBodyModel.cs
- utils/build/docker/dotnet/Models/ApiSecurity/ResponseBodyModel.cs
- utils/build/docker/dotnet/app.csproj
- utils/build/docker/dotnet/poc.Dockerfile
- utils/build/docker/dotnet/uds.Dockerfile
- Adapt tests, as payloads are slightly different in dotnet
-  Adapt dotnet weblog
- Fixes : cookies value can't contain whitespaces, actually pass cookies when building the request
> Prepare api security tests for dotnet

- manifests/dotnet.yml
- utils/build/docker/dotnet/Controllers/IastController.WeakRandomness.cs
- utils/build/docker/dotnet/Controllers/IastController.cs
IAST WeakRandomness for dotnet
> [dotnet] WeakRandomness tests and weblog code reorganization

- docs/weblog/README.md
- manifests/cpp.yml
- manifests/dotnet.yml
- manifests/golang.yml
- manifests/java.yml
- manifests/nodejs.yml
- manifests/php.yml
- manifests/php_appsec.yml
- manifests/python.yml
- manifests/ruby.yml
- tests/appsec/test_shell_execution.py
- utils/build/docker/nodejs/express4-typescript/app.ts
- utils/build/docker/nodejs/express4/app.js
Add shell execution tests for the default scenario.
> Shell execution tests

- tests/remote_config/test_remote_configuration.py
> dotnet bug remote configuration

- .github/workflows/ci.yml
- .github/workflows/parametric.yml
- conftest.py
- utils/_context/_scenarios.py
> [WIP] fix parametric scenario

- utils/interfaces/schemas/miscs/telemetry/common/events/apm-onboarding.json
> Add agent.first_trace.sent to possible telemetry event

- manifests/agent.yml
- tests/test_telemetry.py
> [Instrumentation Telemetry] Test that install tags are added to the agent

- utils/build/docker/python/django-poc.Dockerfile
- utils/build/docker/python/fastapi.Dockerfile
- utils/build/docker/python/flask-poc.Dockerfile
- utils/build/docker/python/pylons.Dockerfile
- utils/build/docker/python/python3.12.Dockerfile
- utils/build/docker/python/uds-flask.Dockerfile
- utils/build/docker/python/uwsgi-poc.Dockerfile
`dd-trace-py` IAST feature: Vulnerability Deduplication
Fix Python PR https://github.com/DataDog/dd-trace-py/pull/7582
> feat(python/iast): vulnerability deduplication

- utils/build/docker/nodejs/express4/.eslintrc.json
- utils/build/docker/nodejs/nextjs/.eslintrc.json
Per title
The easier the PR on system tests are, the better :slightly_smiling_face:
> Remove node specific warning in PR

- manifests/dotnet.yml
- tests/appsec/iast/source/test_header_value.py
- utils/build/docker/dotnet/Controllers/IastController.cs
IAST header value test for dotnet
> [dotnet] IAST header value test

- docs/scenarios/parametric.md
Fix for the Python library command.
> docs: update python parametric command

- .gitlab-ci.yml
- tests/onboarding/infra_provision/provision_onboarding_container_ruby.yml
- tests/onboarding/test_onboarding_install.py
- tests/onboarding/weblog/java/test-app-java/test-app-java_docker_compose_run.sh
- tests/onboarding/weblog/nodejs/test-app-nodejs/test-app-nodejs_docker_compose_run.sh
- tests/onboarding/weblog/python/test-app-python-django/test-app-python_docker_compose_run.sh
- tests/onboarding/weblog/ruby/test-app-ruby/test-app-ruby_docker_compose_run.sh
Enable tests related with this fixed issues:
Ruby: https://datadoghq.atlassian.net/browse/AIT-8814
Python: https://datadoghq.atlassian.net/browse/AIT-8581
> Onboarding: Enable Python and Ruby fixed tests

- utils/onboarding/backend_interface.py
> OnBoarding test more verbose

- manifests/java.yml
- tests/appsec/iast/sink/test_hsts_missing_header.py
- tests/appsec/iast/sink/test_insecure_cookie.py
- tests/appsec/iast/sink/test_no_httponly_cookie.py
- tests/appsec/iast/sink/test_no_samesite_cookie.py
- tests/appsec/iast/sink/test_xcontent_sniffing.py
> Enable some Java IAST tests

- tests/parametric/test_headers_tracestate_dd.py
Broke with a bugfix in PHP tracer, there's no dd= data for that specific outcome, hence handling that case.
> If no dd= data is to be propagated, it might be completely missing

- tests/parametric/test_headers_tracestate_dd.py
I hadn't paid enough attention in the last PR, sorry.
> Follow-up to #1864, tracestate itself may also be lacking then

- tests/parametric/test_otel_span_methods.py
- utils/build/docker/golang/parametric/go.mod
- utils/build/docker/golang/parametric/go.sum
> parametric: [golang] unskip the dot notation tests

- .vscode/launch.json
- .vscode/settings.json
- conftest.py
- pyproject.toml
- tests/test_the_test/test_json_report.py
- utils/__init__.py
- utils/_features.py
This new decorator allow to declare that a test class/method belong to a feature. It will be simply used like that : 
```python
from utils import features
@features.awesone
@features.other_one  # allow double declaration
class Test_Stuff:
def test_usecase(self):
...
@features.daddy # allow at method level
def test_usecase(self):
...
```
Before, the model was : 
```js
{
nodeid: string;
outcome: "xfailed" | "xpass" | "fail" | "pass" | "skipped" | "error",
skip_reason: string | null
}
```
I changed it a little bit to integrate the feature id declaration, and being closer to the official format : 
```js
{
nodeid: string;
outcome: "xfailed" | "xpass" | "fail" | "pass" | "skipped" | "error",
lineno: number;  // new property
metadata: {
features: number[],
skip_reason: string | null  // new …
```
> Add feature decorator

- tests/otel_tracing_e2e/_test_validator_trace.py
- utils/interfaces/_backend.py
- Remove validation on a tag that is no longer in use
- Fix a log query
> [opentelemetry] Fix trace and log test

- tests/appsec/test_user_blocking_full_denylist.py
- utils/_features.py
Use `@features` on a simple class
Test the new ingestion mechanism
> First usage of features decorator

- tests/appsec/test_automated_login_events.py
- tests/appsec/test_blocking_addresses.py
- tests/appsec/test_customconf.py
- tests/appsec/test_ip_blocking_full_denylist.py
- tests/appsec/test_rate_limiter.py
- tests/appsec/waf/test_blocking.py
- tests/appsec/waf/test_miscs.py
- tests/integrations/test_crossed_integrations.py
- tests/remote_config/test_remote_configuration.py
- tests/test_sampling_rates.py
- utils/_features.py
Use the new feature association mechanism
Add features decorators
> Add features decorators

- .vscode/launch.json
- pyproject.toml
- tests/appsec/test_blocking_addresses.py
- tests/appsec/test_ip_blocking_full_denylist.py
- tests/appsec/test_user_blocking_full_denylist.py
- tests/appsec/waf/test_addresses.py
- tests/appsec/waf/test_blocking.py
- tests/appsec/waf/test_miscs.py
- utils/_features.py
- utils/scripts/update_features.py
> Report last features aspects to feature decorators

- tests/test_telemetry.py
> Update nodejs bug mark for telemetry heartbeat

- tests/test_the_test/test_version.py
- utils/_context/library_version.py
> Allow custom local version pattern for agent

- tests/onboarding/infra_provision/includes/provision_lib_injection_container_manual.yml
- tests/onboarding/infra_provision/includes/provision_lib_injection_host_manual.yml
> hot fix onboarding

- tests/parametric/test_span_links.py
* ddtrace-py v0.2.4 uses v0.5 trace API, support this in parametric tests
* actually, trace_id are differents, so skipping the test as bug, waiting for a fix on test logic or tracer
> Support span links v0.5 trace API

- utils/onboarding/provision_utils.py
> Onboarding: Add config to exclude amis

- lib-injection/build/docker/nodejs/sample-app/Dockerfile
- utils/build/docker/nodejs/express4-typescript.Dockerfile
- utils/build/docker/nodejs/express4.Dockerfile
- utils/build/docker/nodejs/uds-express4.Dockerfile
- utils/build/docker/nodejs_otel/express4-otel.Dockerfile
Node js v5 release
update node version being used in node system tests. This is in preparation for a major release that will drop support for node 16
> Upgrade node version used for system tests

- tests/parametric/conftest.py
- utils/build/docker/cpp/parametric/http/CMakeLists.txt
- utils/build/docker/cpp/parametric/http/Dockerfile
- utils/build/docker/cpp/parametric/http/developer_noise.cpp
- utils/build/docker/cpp/parametric/http/developer_noise.h
- utils/build/docker/cpp/parametric/http/httplib.h
- utils/build/docker/cpp/parametric/http/json.hpp
- utils/build/docker/cpp/parametric/http/main.cpp
- utils/build/docker/cpp/parametric/http/manual_scheduler.h
- utils/build/docker/cpp/parametric/http/request_handler.cpp
- utils/build/docker/cpp/parametric/http/request_handler.h
- utils/build/docker/cpp/parametric/http/utils.h
Add cpp HTTP server for [the gRPC -> HTTP migration](https://docs.google.com/document/d/1qacYmyyIgMuAo8NxwbyH0paOf7f6bfe89QQUPPFygqA).
- Add a new folder containing the new HTTP server implementation.
- Update parametric `conftest` to use the HTTP server instead of gRPC.
🛟 …
> parametric: Add cpp-http server

- tests/appsec/iast/sink/test_unvalidated_redirect.py
- tests/test_the_test/test_features.py
> Leftover in ASM feature declaration

- utils/build/docker/python/python3.12.base.Dockerfile
python3.12 weblog was using a rc version of python.
bump it to the last stable python 3.12 version
> update python 3.12 version image

- manifests/golang.yml
> Activate Test_LibraryHeaders on golang library

- manifests/nodejs.yml
- tests/appsec/iast/sink/test_weak_randomness.py
- utils/build/docker/nodejs/express4-typescript/app.ts
- utils/build/docker/nodejs/express4-typescript/iast.ts
- utils/build/docker/nodejs/express4/iast/index.js
System test for Weak randomness vulnerability detection in nodejs
Add weak randomness endpoints in express application.
Add vulnerability location in weak randomness test for nodejs. …
> Weak randomness tests for nodejs

- utils/build/docker/nodejs/express4/app.js
This message appears in all PRs, I want to remove it.
> Fix "Unchanged files with check annotations" message

- tests/integrations/crossed_integrations/test_sqs.py
Clean code, check that buddy images has been pushed correctly
Definition of base class properties, to avoid the linter to complain.
> Minor fixes on test_sqs.py

- .github/workflows/ci.yml
> Testing merges

- manifests/nodejs.yml
- tests/appsec/iast/sink/test_trust_boundary_violation.py
To have a more consistent suite test for IAST NodeJS.
Enabling some missing test in NodeJS manifest.
Tidying up some tests.
> IAST NodeJS Fixings

- .gitlab-ci.yml
> Test merge2

- .github/workflows/ci.yml
> Test merge 3

- .gitlab-ci.yml
> test merge 4

- .gitlab-ci.yml
> Test merge 9

- tests/parametric/test_sampling_delegation.py
This PR fixes a typo in some comments that I wrote recently.
> I pasted the wrong link before.

- tests/appsec/waf/test_telemetry.py
We can have counting errors where waf.requests totals do not match the actual number of traced requests ([APPSEC-51509](https://datadoghq.atlassian.net/browse/APPSEC-51509)). Java issue is fixed with https://github.com/DataDog/dd-trace-java/pull/6595
Test that the sum of all waf.requests counter match the number of root spans of kind server.
[APPSEC-51509]: https://datadoghq.atlassian.net/browse/APPSEC-51509?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Test coherence of waf.requests metric and number of traces

- manifests/nodejs.yml
Response body schema extraction for express merged in dd-trace-js master
Enable Test_Schema_Response_Body for express4 and express4-typescript applications.
[APPSEC-47094]
[APPSEC-47094]: …
> [NodeJS] Enable ResponseBody api security tests in node

- pyproject.toml
- tests/parametric/test_otel_span_methods.py
- tests/parametric/test_otel_span_with_w3c.py
- tests/parametric/test_otel_tracer.py
- tests/parametric/test_sampling_span_tags.py
- tests/parametric/test_tracer.py
- utils/_features.py
> Link tests to features

- tests/parametric/test_telemetry.py
> added nodejs telemetry name mapping

- manifests/nodejs.yml
- tests/appsec/iast/sink/test_hardcoded_secrets.py
- tests/appsec/iast/sink/test_nosql_mongodb_injection.py
- tests/appsec/iast/sink/test_sql_injection.py
Increase tests coverage
Enable uds-express4 tests, review metrics tests and others
> nodejs easy wins

- docs/execute/binaries.md
I hard a hard time finding that myself
mentionned getting artifact from azure & added screeshots
> Add screenshots to help find artifacts for dotnet tracer

- .gitlab-ci.yml
- utils/build/virtual_machine/provisions/container-auto-inject-install-script/provision.yml
Fix onboarding tests: container install script scenarios
Fix push results to FPD: ensure the json file exists
> OnBoarding: Fix container install script and push FPD

- manifests/nodejs.yml
> Enable Test_ExternalWafRequestsIdentification for Node.js

- pyproject.toml
- tests/apm_tracing_e2e/test_otel.py
- tests/parametric/test_headers_none.py
- tests/parametric/test_headers_precedence.py
- tests/parametric/test_headers_tracecontext.py
- tests/parametric/test_headers_tracestate_dd.py
More feature ids!
More feature ids!
> Add some missing feature ids

- utils/k8s_lib_injection/k8s_datadog_cluster_agent.py
- utils/k8s_lib_injection/k8s_weblog.py
Add more traces for the weblog deployment.
> K8s Lib Injection: Add debug traces

- .github/workflows/run-lib-injection.yml
- tests/k8s_lib_injection/test_k8s_configmap_auto_inject.py
> K8s Lib Injection: add dotnet tests

- tests/k8s_lib_injection/conftest.py
- tests/k8s_lib_injection/test_k8s_configmap_auto_inject.py
- utils/k8s_lib_injection/k8s_command_utils.py
- utils/k8s_lib_injection/k8s_datadog_cluster_agent.py
- utils/k8s_lib_injection/k8s_weblog.py
> K8s Lib Injection: Fixes

- manifests/golang.yml
Version was too early for the tests to succeed on release branches
> go: bump custom blocking test version

- tests/appsec/iast/sink/test_nosql_mongodb_injection.py
> Fix left over on IAST test/.NET

- docs/scenarios/k8s_lib_injection.md
> k8s lib injection: update doc

- tests/appsec/iast/sink/test_nosql_mongodb_injection.py
- utils/build/docker/dotnet/Controllers/IastController.cs
> [dotnet][ASM][IAST] Fix the left over test

- tests/test_data_integrity.py
more easy wins
we want more green on the parity feature dashboard
> python: enable one more test

- docs/README.md
> black box update

- .github/workflows/run-lib-injection.yml
The artifact name should be changed, in order to be processed from system-tests-dashboard
> K8s Lib Injection: Artifact Name

- .github/CODEOWNERS
Go manifest changes should be reviewable by anyone from the Go guild team https://github.com/orgs/DataDog/teams/dd-trace-go-guild
> CODEOWNERS: update dd-trace-go reviewers

- .github/workflows/run-lib-injection.yml
Add new weblog python variants for K8s lib injection tests
> K8s lib injection: new python variants

- manifests/php.yml
> PHP: Ignore test Test_Schema_Response_Body

- utils/build/docker/dotnet/Controllers/DebuggerController.cs
- utils/build/docker/dotnet/Controllers/IastController.cs
- utils/build/docker/dotnet/Controllers/TagValueController.cs
- utils/build/docker/dotnet/Dependencies/KafkaHelper.cs
- utils/build/docker/dotnet/EndpointRegistry.cs
- utils/build/docker/dotnet/Endpoints/MakeDistantCallEndpoint.cs
- utils/build/docker/dotnet/Endpoints/ReadFileEndpoint.cs
- utils/build/docker/dotnet/Endpoints/SpansEndpoint.cs
- utils/build/docker/dotnet/Endpoints/StatusEndpoint.cs
- utils/build/docker/dotnet/Helper.cs
- utils/build/docker/dotnet/IdentityStores/UserStoreMemory.cs
- utils/build/docker/dotnet/ModelBinderSwitchProvider.cs
- utils/build/docker/dotnet/Models/ApiSecurity/RequestBodyModel.cs
- utils/build/docker/dotnet/Models/ApiSecurity/ResponseBodyModel.cs
- utils/build/docker/dotnet/Models/LoginModel.cs
- utils/build/docker/dotnet/app.csproj
In .NET project `utils/build/docker/dotnet`:
- fix errors that prevent building locally (outside of docker)
- fix (or suppress) build warnings
- exclude directory `parametric/` from build
- fix target framework
- add missing null checks and nullability annotations
- remove some unused declarations
- fix some instances of string interpolation
- other miscellaneous fixes: typos, code formatting, etc
- suppress warnings for known issues (`NU1902`, `NU1903`, and `CA1416`)
* Framework is modified, or non obvious …
> [dotnet] fix build warnings

- tests/parametric/test_headers_b3.py
- tests/parametric/test_headers_b3multi.py
- tests/parametric/test_headers_datadog.py
- tests/parametric/test_headers_none.py
- tests/parametric/test_headers_precedence.py
Revert #2318, as underlying issue was fixed in #2240
> Revert #2318

- manifests/python.yml
Reverts DataDog/system-tests#2335
Re-enables Python test
> Revert "Revert "chore(python): add one more test""

- tests/appsec/test_blocking_addresses.py
- remove deprecated decorator (django was fixed)
- remove test for a feature that is currently not planned for the tracers
> update test file for blocking addresses

- .github/pull_request_template.md
- .github/workflows/ci.yml
- .github/workflows/compute-impacted-languages.yml
- .github/workflows/compute-impacted-libraries.yml
- .github/workflows/run-end-to-end.yml
- .github/workflows/run-graphql.yml
- .github/workflows/run-lib-injection.yml
- .github/workflows/run-open-telemetry.yml
- .github/workflows/run-parametric.yml
- .github/workflows/system-tests.yml
> Compute dynamically the matrix

- utils/build/virtual_machine/provisions/host-auto-inject/auto-inject_host_manual.yml
There was a problem with package signature verification, this Pr avoid these problems
> OnBoarging: Fix package signature verification

- utils/build/virtual_machine/provisions/host-auto-inject/auto-inject_host_manual.yml
> Onboarding test minor fix

- utils/interfaces/_schemas_validators.py
- utils/interfaces/schemas/library/debugger/v1/diagnostics-request.json
- utils/interfaces/schemas/library/debugger/v1/input-request.json
- utils/proxy/_deserializer.py
> POC : debugger schemas

- .github/workflows/run-end-to-end.yml
- tests/appsec/waf/test_addresses.py
- utils/build/build_python_base_images.sh
- utils/build/docker/python/flask-poc.Dockerfile
- utils/build/docker/python/flask-poc.base.Dockerfile
- utils/build/docker/python/python3.12.Dockerfile
- utils/build/docker/python/python3.12.base.Dockerfile
- utils/build/docker/python/uds-flask.Dockerfile
https://datadoghq.atlassian.net/browse/APPSEC-52915
* publish updated base images for python weblog using gunicorn
* skip failing bug
> Skip failing test on gunicorn 22.0

- .github/workflows/run-lib-injection.yml
- docs/scenarios/k8s_lib_injection.md
- lib-injection/runner/action.yml
Clean CI !
Fix warnings in lib-injection 
> Fix warnings in lib-injection 

- manifests/ruby.yml
Unlock tests that are fixed by this PR: https://github.com/DataDog/dd-trace-rb/pull/3616
> Unskip tests for Ruby 2.0 sampling

- tests/integrations/test_dbm.py
> Fix typo in error message

- manifests/python.yml
Those PRs are failing due to this error:
https://github.com/DataDog/system-tests/pull/2434
https://github.com/DataDog/system-tests/pull/2433
> [python] Test_UserLoginSuccessEvent fails on 3.12

- utils/build/docker/python/django/django.app.urls.py
- utils/build/docker/python/flask/app.py
Some Python endpoints check Code Security (IAST) vulnerabilities sources against SQL injection sink points. That PR
https://github.com/DataDog/dd-trace-py/pull/9163 raises a problem: that sink points should be redacted and the system test validation fails. We need to report a vulnerability but with no redaction
Extra: I added header injection endpoints 
:rocket: Once your …
> [python] fix cookies report

- tests/integrations/test_dbm.py
> Avoid false xpass in Test_Dbm

- tests/appsec/test_traces.py
* `test_root_span_coherence` had false XPASS positive on Java with native-image (no appsec support at all).
* Ensure `test_root_span_coherence` fails if there are no spans to validate on.
* Use more pytest-friendly asserts in Test_AppSecEventSpanTags to provide clearer errors.
* ~[ ] If PR title starts with `[<language>]`, double-check that only `<language>` is impacted by the change~
> Avoid false xpass in Test_AppSecEventSpanTags and use informative asserts

- manifests/java.yml
> [java] Enable system tests for Java sampling RC

- manifests/python.yml
- utils/build/docker/python/django/django.app.urls.py
Enable header injection test for python. Merge after this PR: https://github.com/DataDog/dd-trace-py/pull/9198
> [python] header injection vulnerability

- manifests/python.yml
Disable path traversal for python in 2.9.0 https://github.com/DataDog/dd-trace-py/pull/9247
> [python] disable path traversal

- manifests/python.yml
Second part of https://github.com/DataDog/system-tests/pull/2448
> [python] disable path traversal II

- manifests/python.yml
Third part of https://github.com/DataDog/system-tests/pull/2448 due to cookies tests implements path traversal to report the source https://github.com/DataDog/system-tests/pull/2433/ and https://github.com/DataDog/system-tests/pull/2449
> feat(python): disable path traversal III

- tests/parametric/test_dynamic_configuration.py
- utils/build/docker/java/parametric/src/main/java/com/datadoghq/OpenTracingClient.java
- utils/parametric/_library_client.py
> Testing remote sampling rules with tags.

- manifests/cpp.yml
- manifests/dotnet.yml
- manifests/golang.yml
- manifests/java.yml
- manifests/nodejs.yml
- manifests/php.yml
- manifests/python.yml
- manifests/ruby.yml
- tests/appsec/rasp/test_span_tags.py
- tests/appsec/rasp/test_stack_traces.py
- utils/_features.py
This PR introduces new RASP tests:
- Stack trace validation: these tests validate that stack traces are generated on RASP events, that the top level schema contains the minimum set of tags and that the stack ID of each appsec event is present in a stack trace.
- Span tag validation: these tests validate mandatory span metrics (`appsec.rasp.duration`) and optional span metrics (`appsec.rasp.duration_ext`, `appsec.rasp.rule.eval`).  …
> [ASM][RASP] Test stack traces and span tags

- utils/build/docker/ruby/install_ddtrace.sh
Syntax error invoked from https://github.com/DataDog/appsec-event-rules/blob/main/.github/workflows/system-tests.yaml
```ruby
gem 'datadog' ~> '~> 2.0.0.beta2'
```
to 
```ruby
gem 'datadog', '~> 2.0.0.beta2'
```
> Fix latest released gem version install

- tests/integrations/test_dbm.py
> Fix _Test_Dbm_Comment

- manifests/python.yml
- tests/appsec/iast/sink/test_command_injection.py
> [python] easy wins for python (iast)

- .gitlab-ci.yml
- utils/build/virtual_machine/weblogs/dotnet/test-app-dotnet/test-app-dotnet_run.sh
Debug onboarding tests, dotnet host injection scenario
> OnBoarding debug dotnet

- tests/debugger/test_debugger_pii.py
- utils/_context/_scenarios.py
- utils/build/docker/dotnet/Controllers/DebuggerController.cs
- utils/build/docker/dotnet/Models/Debugger/Pii.cs
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/debugger/CustomPii.java
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/debugger/DebuggerController.java
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/debugger/Pii.java
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/debugger/PiiBase.java
The debugger can redact values based on setting environment variables. This PR tests this feature.
Add Test custom PII redacted type and identifiers
> [DEBUGGER] Test custom PII redacted type and identifiers

- tests/debugger/test_debugger.py
- tests/debugger/test_debugger_pii.py
- tests/debugger/utils.py
Refactor weblog requests validation.
Move weblog requests validation to the base class.
> [Debugger] Weblog requests refactoring

- tests/test_the_test/test_version.py
- utils/_context/_scenarios.py
- utils/_context/containers.py
- utils/_context/library_version.py
> Use semver for version parser

- utils/build/virtual_machine/provisions/installer-auto-inject/provision.yml
- utils/build/virtual_machine/weblogs/nodejs/test-app-nodejs-alpine/test-app-nodejs_docker_compose_run.sh
- utils/build/virtual_machine/weblogs/nodejs/test-app-nodejs-container/test-app-nodejs_docker_compose_run.sh
- utils/build/virtual_machine/weblogs/ruby/test-app-ruby-container/test-app-ruby_docker_compose_run.sh
Support installer-based nodejs & ruby containers like we do for other languages
> upgrade(installer): Support nodejs & ruby containers

- tests/auto_inject/test_auto_inject_install.py
Making `SIMPLE_CONTAINER_AUTO_INJECTION` work again
Rename a test that was named the same as the single `SIMPLE_CONTAINER_AUTO_INJECTION` test. Because the name was duplicated and overridden the `SIMPLE_CONTAINER_AUTO_INJECTION` scenario had no test and thus failed.
🛟 …
> fix(injection): Fix simple container injection

- .github/workflows/run-end-to-end.yml
- utils/build/docker/cpp/nginx/install_ddtrace.sh
[v1.2.0](https://github.com/DataDog/nginx-datadog/releases/tag/v1.2.0) release broke system tests
Build the good artifact name
> [cpp] fix weblog build

- manifests/python.yml
- tests/appsec/test_event_tracking.py
> [python] enable more easy wins

- utils/build/docker/cpp/nginx.Dockerfile
- utils/build/docker/cpp/nginx/install_ddtrace.sh
> [cpp] Extract version for C++ library

- tests/parametric/test_tracer_flare.py
The Node tracer will send text files directly for now, and eventually will use gzip anyway and not zip, so this check will never make sense for Node.
Add exception for zip check for Node. For now this is only runnable locally as no releases of the Node tracer has the feature. I will make a follow-up PR to add the version once the feature is released. …
> add exception for zip check for node

- manifests/java.yml
> [java] Mark some telemetry parametric tests as supported

- utils/_context/_scenarios.py
- utils/_context/virtual_machines.py
- utils/build/virtual_machine/provisions/auto-inject/docker/auto-inject_prepare_docker.yml
- utils/build/virtual_machine/weblogs/dotnet/provision_test-app-dotnet.yml
- utils/build/virtual_machine/weblogs/dotnet/provision_test-shell-script.yml
- utils/build/virtual_machine/weblogs/nodejs/provision_test-app-nodejs.yml
- utils/build/virtual_machine/weblogs/nodejs/provision_test-shell-script.yml
- utils/build/virtual_machine/weblogs/ruby/provision_test-app-ruby.yml
- utils/build/virtual_machine/weblogs/ruby/provision_test-shell-script.yml
Testing the injector on our oldest supported platform (installer only)
[Successful pipeline for installer jobs](https://gitlab.ddbuild.io/DataDog/system-tests/-/pipelines/36237257)
Adds a CentOS VM and adds it to the installer tests
> feat(system-tests): Add CentOS VM

- .github/workflows/run-end-to-end.yml
- manifests/cpp.yml
- manifests/dotnet.yml
- manifests/golang.yml
- manifests/java.yml
- manifests/nodejs.yml
- manifests/php.yml
- manifests/python.yml
- manifests/ruby.yml
- scenario_groups.yml
- tests/appsec/test_asm_standalone.py
- utils/_context/_scenarios.py
- utils/_features.py
New feature ASM Standalone billing tests
RFC: https://docs.google.com/document/d/12NBx-nD-IoQEMiCRnJXneq4Be7cbtSc6pJLOFUWTpNE/edit
- A new scenario
- A new feature
- Some basic tests (we'd need a multi-service setup to test everything properly)
🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X) …
> asm standalone billing tests

- manifests/nodejs.yml
- tests/appsec/rasp/test_span_tags.py
- tests/appsec/rasp/test_stack_traces.py
- utils/build/docker/nodejs/express4-typescript/app.ts
- utils/build/docker/nodejs/express4-typescript/rasp.ts
- utils/build/docker/nodejs/express4/app.js
- utils/build/docker/nodejs/express4/rasp.js
- utils/build/docker/nodejs/nextjs/src/app/rasp/ssrf/route.js
Exploit prevention is being detected in nodejs tracer, and the PR with the metrics have been merged, we should update the system tests.
Adds endpoints in the 3 variants and enables the ssrf system tests
> [nodejs] Enable rasp ssrf metrics system tests in nodejs

- .gitlab-ci.yml
- utils/build/virtual_machine/weblogs/python/test-app-python/python_install.sh
Last merge related with krunvm broke python host installation. This Pr should fix it
> Fix onboarding python

- tests/appsec/test_user_blocking_full_denylist.py
* More understandeable test and errors.
* Ensure that the span we validate is the root span.
* More "natural" flow.
> Simplify test_user_blocking_full_denylist.py asserts

- manifests/golang.yml
RASP for SSRF has been released already
Enable RASP SSRF tests
> [golang] Enable RASP SSRF tests

- utils/onboarding/weblog_interface.py
Making tests pass first try.
To make sure we're not losing traces to sampling we set the priority explicitly in the test.
> fix(installer_tests): Fix flakiness

- manifests/nodejs.yml
Tracer flare has landed in dd-trace-js 5.15.0 and tests should be enabled for that version and later.
Add Node.js support for tracer flare tests.
> add nodejs support for tracer flare tests

- tests/auto_inject/test_auto_inject_install.py
Flakey tests:
- https://gitlab.ddbuild.io/DataDog/auto_inject/-/jobs/550946654
- https://gitlab.ddbuild.io/DataDog/auto_inject/-/jobs/550946644
- https://gitlab.ddbuild.io/DataDog/auto_inject/-/jobs/550946643
- Bumps execute_command timeout to 5min instead of 2min
- Retrieve command output in a streaming fashion to have partial data if the timeout persists
:rocket: Once …
> fix(flake): Bump execute_command timeout

- manifests/java.yml
- tests/debugger/test_debugger_expression_language.py
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/debugger/DebuggerController.java
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/debugger/ExpressionTestStruct.java
- utils/proxy/rc_mocked_responses_debugger_expression_language.json
Enable expression language tests for java
Enable expression language tests for java
> [Debugger] Enable expression language tests for java

- format.sh
- manifests/cpp.yml
- manifests/golang.yml
- manifests/java.yml
- manifests/python.yml
- manifests/ruby.yml
> Strip trailing spaces from manifests

- format.sh
> Fix format.sh trailing space removal in Linux

- .github/actions/pull_images/action.yml
- .github/workflows/run-end-to-end.yml
- utils/_context/_scenarios.py
- utils/_context/containers.py
- utils/scripts/get-image-list.py
- utils/tools.py
Before :
* simple run (only default scenario) : 12s https://github.com/DataDog/system-tests/actions/runs/9680233476/job/26708097007#step:4:1
* full run (all scenario) : 219s https://github.com/DataDog/system-tests/actions/runs/9680330556/job/26713339712#step:4:1
After : 
* simple run (only default scenario) : 13s https://github.com/DataDog/system-tests/actions/runs/9684405073/job/26722150197?pr=2611
* full run (all scenarios): 97s https://github.com/DataDog/system-tests/actions/runs/9684470124/job/26722530700#step:4:1
These figures are collected the exact same list.
Turns out we misses two images : 
* localstack/localstack:3.1.0                   1.09GB   CROSSED_TRACING_LIBRARIES
* otel/opentelemetry-collector-contrib:latest   255MB (OpenTelemetryScenarios)
With those two images, we add …
> [cpp] Optimize docker pull by using docker compose

- utils/build/docker/nodejs/express4-typescript/app.ts
- utils/build/docker/nodejs/express4/app.js
- utils/build/docker/nodejs/nextjs/src/app/requestdownstream/route.js
- utils/build/docker/nodejs/nextjs/src/app/returnheaders/route.js
Implement different nodejs variant endpoints for Standalone ASM testing
> [nodejs] express4, express4-typescript and nextjs endpoints for Standalone ASM testing

- utils/build/docker/dotnet/Controllers/IastController.cs
- utils/build/docker/dotnet/Controllers/LoginController.cs
- utils/build/docker/dotnet/IdentityStores/RoleStore.cs
- utils/build/docker/dotnet/IdentityStores/UserStoreMemory.cs
- utils/build/docker/dotnet/ModelBinderSwitchProvider.cs
- utils/build/docker/dotnet/Models/Debugger/ExpressionTestStruct.cs
- utils/build/docker/dotnet/Models/Debugger/Pii.cs
- utils/build/docker/dotnet/Models/IValidable.cs
- utils/build/docker/dotnet/Models/LoginModel.cs
- utils/build/docker/dotnet/Models/String.cs
- utils/build/docker/dotnet/app.csproj
- utils/build/docker/dotnet/parametric/Endpoints/ApmTestApi.cs
- utils/build/docker/dotnet/parametric/Endpoints/ApmTestApiOtel.cs
- CI linter found trailing whitespace (either missed in #2598 or new)
- Solve more issues with line endings differences between Windows and other OSes
- Remove trailing whitespace
- Remove the byte-order mark (BOM) from UT8-F text files to help git identify them correctly so it can switch between LF and CRLF line endings automatically on checkout …
> [.NET] remove trailing whitespace and UTF-8 BOM

- utils/build/docker/dotnet/app.sh
Caught by the linter: https://www.shellcheck.net/wiki/SC1083
Quote the env var string.
> [.NET] quote curly braces in bash script

- format.sh
- utils/_context/_scenarios.py
- utils/_context/containers.py
- utils/build/build_python_base_images.sh
- utils/build/docker/python/django-poc.Dockerfile
- utils/build/docker/python/django-poc.base.Dockerfile
- utils/build/docker/python/fastapi.Dockerfile
- utils/build/docker/python/fastapi.base.Dockerfile
- utils/build/docker/python/flask-poc.Dockerfile
- utils/build/docker/python/flask-poc.base.Dockerfile
- utils/build/docker/python/flask/app.sh
- utils/build/docker/python/install_ddtrace.sh
- utils/build/docker/python/python3.12.Dockerfile
- utils/build/docker/python/python3.12.base.Dockerfile
- utils/build/docker/python/uds-flask.Dockerfile
- utils/build/docker/python/uwsgi-poc.Dockerfile
- utils/build/docker/python/uwsgi-poc.base.Dockerfile
* faster build
* easier debug
* install rsut toolchain on base images
* print stdout/stderr when a container healthcheck fails
> [python] Debug message, install rust on base images

- tests/parametric/test_tracer_flare.py
Update tracer flare test, the tracers don't rely on the config ID, and only rely on the config content
> [FA] Update tracer flare test

- utils/build/virtual_machine/weblogs/dotnet/provision_test-app-dotnet.yml
Disabled tests:
- Amazon Linux 2 Dotnet 6
Due to: https://datadoghq.atlassian.net/browse/AIT-10335
> Onboarding: Disable amazon linux 2 dotnet6

- manifests/java.yml
- tests/appsec/iast/sink/test_no_httponly_cookie.py
- tests/appsec/iast/source/test_header_value.py
- tests/appsec/iast/source/test_parameter_value.py
- tests/test_semantic_conventions.py
- utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/IastSinkResource.java
- utils/build/docker/java/resteasy-netty3/src/main/java/com/datadoghq/resteasy/IastSinkResource.java
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/AppSecIast.java
> [java] Enable more XPASS tests

- tests/auto_inject/test_auto_inject_blocklist.py
> Propagate env vars

- utils/build/docker/python/django-poc.base.Dockerfile
Fix the failing test for Python [Test_Headers.test_specific_key2](https://github.com/DataDog/system-tests/actions/runs/9759669166/job/26937085012?pr=2653#step:12:169)
> [python] pin gunicorn version to 21.2.0

- tests/debugger/test_debugger_expression_language.py
- tests/debugger/test_debugger_pii.py
- tests/debugger/test_debugger_probe_snapshot.py
- tests/debugger/test_debugger_probe_status.py
- tests/debugger/utils.py
RC API allows to receive response from agent and validate it.
This PR add test, that all configs have no errors.
Assert RC requests have no errors.
> [Debugger] Assert RC requests have no errors

- utils/build/docker/dotnet/parametric/Endpoints/ApmTestApi.cs
- utils/build/docker/dotnet/parametric/Endpoints/ApmTestApiOtel.cs
- utils/build/docker/dotnet/weblog/Controllers/IastController.cs
- utils/build/docker/dotnet/weblog/Controllers/LoginController.cs
- utils/build/docker/dotnet/weblog/Controllers/TagValueController.cs
- utils/build/docker/dotnet/weblog/Endpoints/DsmEndpoint.cs
- utils/build/docker/dotnet/weblog/Endpoints/HeadersEndpoint.cs
- utils/build/docker/dotnet/weblog/IdentityStores/RoleStore.cs
- utils/build/docker/dotnet/weblog/IdentityStores/UserStoreMemory.cs
- utils/build/docker/dotnet/weblog/Models/ApiSecurity/RequestBodyModel.cs
NOTE: this PR is stacked on #2606. Make sure that one is merged first before merging this one.
Building the .NET `weblog` app produces a lot of compiler warnings.
Mostly adding missing nullability annotations (`?`), suppressing nullability warnings (`!`), and fixing other compiler and Roslyn analyzer warnings.
🛟 …
> [.NET] fix compiler warnings in `weblog` app

- tests/integrations/utils.py
> Fix nodejs otel mssql

- tests/debugger/probes/expression_language_comparison_operators.json
- tests/debugger/test_debugger_expression_language.py
- tests/debugger/utils.py
- utils/build/docker/dotnet/weblog/Controllers/DebuggerController.cs
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/debugger/DebuggerController.java
Test expression language comparison operators
> [Debugger] Expression Language - comparison operators

- utils/build/virtual_machine/weblogs/ruby/test-app-ruby/test-app-ruby_run.sh
> Change using `bin/rails` for rails app start command

- manifests/nodejs.yml
- utils/build/docker/nodejs/express4-typescript/app.ts
- utils/build/docker/nodejs/express4/app.js
- utils/build/docker/nodejs/nextjs/src/app/requestdownstream/route.js
Enable appsec standalone tests for node
> [nodejs] Enable Standalone ASM tests for node

- manifests/nodejs.yml
Fix the XPASS created on Friday
Set version in node.yml
> [nodejs] Fix XPASS in Test_MissingRules

- .github/actions/pull_images/action.yml
- .github/workflows/run-end-to-end.yml
- utils/_context/_scenarios/__init__.py
- utils/_context/containers.py
- utils/build/docker/agent.Dockerfile
- utils/scripts/get-image-list.py
Faster CI time
Pre-load base images for agent and weblog
> Preload docker image for agent and weblog

- manifests/python.yml
add `test_rate_limiter.py` to manifest.
> [python] add missing file into manifest

- tests/debugger/probes/expression_language_instance_of.json
- tests/debugger/test_debugger_expression_language.py
- tests/debugger/utils.py
Add expression language `instanceof` tests
> [Debugger] Add expression language `instanceof` tests

- manifests/java.yml
- tests/appsec/test_blocking_addresses.py
> [java] Enable more request blocking tests

- tests/appsec/api_security/test_schemas.py
> [php] flag another flaky test for APPSEC-53993

- utils/build/docker/golang/net-http.Dockerfile
Go doesn't need the source code of the application and its dependencies to be in the container to run. Having these present meant that the buddy image generated for Go was 1.68GB. It's not a more reasonable (although still pretty large) 852MB, which is ~50% reduction.
I only did `net-http` for now since it's the variant that is used by the Go buddy image, meaning that its size impacts all other languages, but additional variants could also be updated later.
Update net-http variant of golang to use multi-stage build.
* Test logic is modified? -> Get a review from RFC owner. We're working on refining the `codeowners` file …
> [golang] update net-http variant of golang to use multi-stage build

- utils/build/docker/nodejs/express4-typescript.Dockerfile
- utils/build/docker/nodejs/express4-typescript/app.ts
- utils/build/docker/nodejs/express4.Dockerfile
- utils/build/docker/nodejs/express4/app.js
- utils/build/docker/nodejs/nextjs.Dockerfile
- utils/build/docker/nodejs/nextjs/src/app/requestdownstream/route.js
- utils/build/docker/nodejs/uds-express4.Dockerfile
- utils/build/docker/nodejs_otel/express4-otel.Dockerfile
Alpine is a lot smaller which will make pulling the images much faster.
Switch Node.js weblog images to alpine.
> [nodejs] switch nodejs weblog images to alpine

- tests/appsec/api_security/test_schemas.py
> [php] skip another flaky test for APPSEC-53993

- tests/appsec/iast/sink/test_unvalidated_redirect.py
- tests/appsec/iast/sink/test_weak_hash.py
- tests/appsec/iast/sink/test_weak_randomness.py
- tests/appsec/iast/sink/test_xpath_injection.py
- tests/integrations/test_dbm.py
> [dotnet] Skip flaky test APPSEC-54151

- scenario_groups.yml
> Add APPSEC_RASP to APPSEC_SCENARIOS

- .github/workflows/run-parametric.yml
- utils/scripts/compute_impacted_scenario.py
> Do not run parametric on java/dev (not supported)

- tests/debugger/test_debugger_expression_language.py
- utils/build/docker/dotnet/weblog/Controllers/DebuggerController.cs
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/debugger/DebuggerController.java
> [Debugger] Add string operations tests

- manifests/cpp.yml
- manifests/dotnet.yml
- manifests/golang.yml
- manifests/java.yml
- manifests/nodejs.yml
- manifests/php.yml
- manifests/python.yml
- manifests/ruby.yml
- tests/appsec/test_remote_config_rule_changes.py
- tests/appsec/test_runtime_activation.py
- utils/_features.py
- utils/_remote_config.py
RC may be used to change the definition of the block action at the org level. Test for that feature was missing.
Add a new test checking for the block action redefinition in RC.
- enable ASM with default settings
- use code 405 with json response
- use code 505 with html response
- use code 302 with redirect response
- get back to ASM disabled
Also: 
- fix a small error in the remote_config api while waiting for confirmation that the state was applied with several files from different products at once.
- add a small additional wait after confirmation to give time for subprocesses to be updated.
- use `reset`  for the rc state in `utils/_features.py` as it's not the only tests in this scenario anymore.
- pass the two test files in bug state for python, as the python tracer is unexpectedly …
> add new RC test for changing the block action

- tests/k8s_lib_injection/test_k8s_init_image_validator.py
> [java] Skip failiong test on k8 injection

- utils/build/docker/java/app-payara.sh
- utils/build/docker/java/spring-boot-payara.Dockerfile
New RASP tests are not working due the problem with xml parser
Fixed xml parser in Java Springboot Payara weblog
> [java] Fixed xml parsing for Springboot Payara

- manifests/nodejs.yml
Remove 4 XPASS
Enable test_remote_config_rule_changes for >=4.1.0 versions
> [nodejs] Enable test_remote_config_rule_changes for >=4.1.0 versions

- manifests/java.yml
Tracer was updated to V2 of the login events RFC
> [java] Update manifest for java login events V2

- tests/debugger/test_debugger_expression_language.py
- utils/build/docker/dotnet/weblog/Controllers/DebuggerController.cs
- utils/build/docker/dotnet/weblog/Models/Debugger/CollectionFactory.cs
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/debugger/CollectionFactory.java
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/debugger/DebuggerController.java
Add expression language collection operations system tests
> [Debugger] Expression language collection operations

- .github/workflows/ci.yml
- utils/_context/containers.py
#2750 use alternative images for DB container. The image used for mysql (`mariadb:latest`) turns out to be flaky 
* https://github.com/DataDog/system-tests-dashboard/actions/runs/10088428133/job/27894294741#step:16:22
* https://github.com/DataDog/system-tests-dashboard/actions/runs/10088428133/job/27894318407#step:16:22
* https://github.com/DataDog/system-tests-dashboard/actions/runs/10088428133/job/27894311097#step:16:22
Use back `mysql/mysql-server:latest`
* Framework is modified, or non obvious usage of …
> Use back mysql/mysql-server:latest for mysql

- docs/scenarios/parametric.md
- utils/parametric/_library_client.py
- utils/scripts/compute_impacted_scenario.py
- utils/scripts/parametric/run_reference_http.sh
> Fix parametric doc and tools

- tests/parametric/test_otel_span_methods.py
- tests/parametric/test_otel_span_with_w3c.py
- tests/parametric/test_otel_tracer.py
> [python] skip failing test for APMAPI-180

- tests/debugger/test_debugger_expression_language.py
- utils/build/docker/dotnet/weblog/Controllers/DebuggerController.cs
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/debugger/DebuggerController.java
Expression language add `check for null` tests
> [Debugger] Expression language add `check for null` tests

- manifests/php.yml
- tests/appsec/test_event_tracking.py
- tests/appsec/test_shell_execution.py
- utils/build/docker/php/php-fpm/build.sh
A number of features have been introduced in php-appsec, however relevant tests had not been enabled so far, which is what this PR does.
Enabled the following tests:
- `tests/appsec/test_event_tracking.py::Test_UserLoginSuccessEvent::test_user_login_success_header_collection `
- `tests/appsec/test_event_tracking.py::Test_UserLoginFailureEvent::test_user_login_failure_header_collection`
- `tests/appsec/test_shell_execution.py::Test_ShellExecution::test_truncate_blank_2nd_argument`
- `tests/appsec/test_traces.py::Test_CollectDefaultRequestHeader::test_collect_default_request_headers` 
- `tests/appsec/test_traces.py::Test_ExternalWafRequestsIdentification::test_external_wafs_header_collection`
- `tests/appsec/waf/test_addresses.py::Test_BodyXml::test_xml_attr_value`
- …
> Update php/appsec XPASS tests

- .gitlab-ci.yml
> Add manual trigger to onboarding jobs

- docs/weblog/README.md
- manifests/cpp.yml
- manifests/dotnet.yml
- manifests/golang.yml
- manifests/java.yml
- manifests/nodejs.yml
- manifests/php.yml
- manifests/python.yml
- manifests/ruby.yml
- tests/appsec/rasp/rasp_ruleset.json
- tests/appsec/rasp/test_shi.py
- utils/_features.py
This PR introduces a new set of tests to validate the new Shell Injection Detection feature for exploit prevention  / RASP.
The following new tests have been introduced:
- `tests/appsec/rasp/test_shi.py`:
- `Test_Shi_UrlQuery`
- `Test_Shi_BodyUrlEncoded`
- `Test_Shi_BodyXml`
- `Test_Shi_BodyJson`
These new tests are specifically included in the new `APPSEC_RASP` scenario.
The following new features  have also been introduced to the feature parity dashboard:
- `rasp_shell_injection`
* Framework is modified, …
> [ASM][RASP] Shell Injection Tests

- manifests/nodejs.yml
- tests/appsec/rasp/test_ssrf.py
- tests/appsec/rasp/test_stack_traces.py
- utils/build/docker/nodejs/express4-typescript/rasp.ts
- utils/build/docker/nodejs/express4/rasp.js
Blocking for rasp ssrf rules has been merged in dd-trace-js, we should enable the system tests
Enable the system tests for next dd-trace-js version. 
As in nodejs we get url with trailing `/`, we are modifying the test to add it in nodejs tests.
🛟 [#apm-shared-testing](https://dd.enterprise.slack.com/archives/C025TJ4RZ8X …
> Enable rasp blocking tests

- manifests/cpp.yml
- manifests/dotnet.yml
- manifests/golang.yml
- manifests/java.yml
- manifests/nodejs.yml
- manifests/php.yml
- manifests/python.yml
- manifests/ruby.yml
- tests/appsec/test_remote_config_rule_changes.py
- tests/appsec/test_suspicious_attacker_blocking.py
- utils/_features.py
New feature "Suspicious attacker blocking" requires tests
- add a new test file and a new feature
- add a new test with several consecutive RC changes
- improve reset at the end of another RC test (`test_remote_config_rule_changes.py`) in the same scenario
APPSEC-54105
APPSEC-54412
🛟 …
> new suspicious attacker blocking test

- manifests/python.yml
Enable more tests following fix merged https://github.com/DataDog/dd-trace-py/pull/10030
APPSEC-54105
> [python] manifest update

- tests/appsec/test_automated_login_events.py
- utils/_features.py
Add 2 new features:
- Threats: User ID collection modes
- Threats: Requests Fingerprinting
Add existing tests to the first features. More tests to come.
> add 2 new features

- tests/appsec/iast/source/test_kafka_key.py
- tests/appsec/iast/source/test_kafka_value.py
> [nodejs] Skip test failing on APPSEC-54445

- tests/k8s_lib_injection/test_k8s_configmap_auto_inject.py
- tests/k8s_lib_injection/test_k8s_init_image_validator.py
- tests/k8s_lib_injection/test_k8s_manual_inject.py
> Skip failing test for APMRP-359

- tests/appsec/waf/test_reports.py
Although span tags are correct some times rasp is not blocking du to timing issue
https://datadoghq.atlassian.net/browse/APPSEC-54465
> Set @flaky to APPSEC_RASP java vertx4 

- tests/appsec/iast/sink/test_weak_cipher.py
> [python] weak cipher flakyness investigation

- tests/appsec/waf/test_reports.py
Although span tags are correct some times rasp is not blocking due to timing issue
https://datadoghq.atlassian.net/browse/APPSEC-54465
> Set @flaky to APPSEC_RASP java vertx3

- tests/appsec/test_traces.py
> Avoid false XPASS on Test_AppSecEventSpanTags

- tests/debugger/probes/pii.json
- tests/debugger/probes/probe_snapshot_line.json
- tests/debugger/probes/probe_snapshot_method.json
- tests/debugger/probes/probe_snapshot_mix_log.json
- tests/debugger/probes/probe_status_log.json
- tests/debugger/probes/probe_status_metric.json
- tests/debugger/probes/probe_status_span.json
- tests/debugger/probes/probe_status_spandecoration.json
- tests/debugger/test_debugger_pii.py
- tests/debugger/test_debugger_probe_snapshot.py
- tests/debugger/test_debugger_probe_status.py
- tests/debugger/utils.py
- utils/_context/_scenarios/__init__.py
Refactor tests + enable line probe status tests
> [Debugger] Refactor tests + enable line probe status tests

- manifests/dotnet.yml
- tests/appsec/test_automated_login_events.py
Deactivates old tests for usr.id collection and activates the new versions to align with changes implemented in the dotnet library.
> [dotnet][asm] update now new v2 login events are implemented

- manifests/java.yml
> [java] Enable AppSecRequestBlocking in all variants

- tests/auto_inject/utils.py
Flaky tests are a no no
- Add a smaller timeout to close the stdout channel so we can have partial logs of the command if it times out
- Only restart the docker compose instead of rebuilding the whole app on container scenarios
- Restart docker before the `docker-compose up` in the `uninstall` test to make sure Docker doesn't get stuck on network recreation
Pipeline: https://gitlab.ddbuild.io/DataDog/system-tests/-/pipelines/41597777
* Framework is modified, or non obvious usage of it -> get a review from …
> fix(APMON): Fix flaky tests

- utils/virtual_machine/aws_provider.py
DevX when debugging tests locally
Adds an env var to keep VMs instead of destroying them
> upgrade(onboarding): Add option to keep VMs

- tests/parametric/test_tracer.py
> fix(php): SCI Tagging tests

- tests/test_telemetry.py
> [nodejs] Revert #2893

- .github/workflows/run-lib-injection.yml
- .github/workflows/system-tests.yml
- tests/k8s_lib_injection/test_k8s_init_image_validator.py
- utils/_context/containers.py
https://datadoghq.atlassian.net/browse/APMRP-359
> Fix lib injection validator

- tests/k8s_lib_injection/test_k8s_manual_inject.py
- utils/_context/_scenarios/__init__.py
> lib injection remove deprecated code

- .github/workflows/ci.yml
- .github/workflows/run-docker-mode.yml
- .github/workflows/run-end-to-end.yml
- .github/workflows/run-graphql.yml
- .github/workflows/run-parametric.yml
- utils/scripts/get-workflow-summary.py
The current workflow summary does not provide any usefull info, and is very verbose.
Replace old workflow sumnary with a new one, with recap of failing steps. To be improved later to be able to publish in slack/PR comment
> Better workflow summary

- manifests/java.yml
> [java] Skip failing tests for DEBUG-2784

- manifests/java.yml
Tests for fingerprints are already [passing](https://feature-parity.us1.prod.dog/#/easy-wins) with the current unreleased version of the tracer.
Set the java tracer version 1.39.0 in the manifest for fingerprint support.
> [java] enable fingerprint tests in v1.39.0

- utils/_context/containers.py
- utils/proxy/core.py
> Remove unwanted string from logs

- utils/build/docker/python_otel/flask-poc-otel.Dockerfile
> Fix otel automatic python

- manifests/dotnet.yml
- manifests/golang.yml
- manifests/java.yml
- manifests/nodejs.yml
- manifests/python.yml
- tests/appsec/rasp/test_lfi.py
- tests/appsec/rasp/test_shi.py
- tests/appsec/rasp/test_sqli.py
- tests/appsec/rasp/test_ssrf.py
- tests/appsec/rasp/utils.py
Telemetry data is an important part of rasp feature
Add telemetry tests for each vulnerability for rasp
> add telemetry tests for rasp

- tests/test_telemetry.py
> Telemetry heartbeats : only check average delays

- .github/workflows/update-agent-protobuf.yml
> VULN-8227: Set write PR permission for protobuf job

- tests/debugger/approvals/exception_replay_simple_dotnet_tags_expected.json
- tests/debugger/approvals/exception_replay_simple_java_tags_expected.json
- tests/debugger/test_debugger_exception_replay.py
Validate exception replay tags
> [Debugger] Validate exception replay tags

- .github/CODEOWNERS
Add debugger team as code owners
> [Debugger] Add debugger team as code owners

- manifests/python.yml
- utils/build/docker/python/django/app/urls.py
- utils/build/docker/python/flask/app.py
> [python] Code Security: path source

- manifests/nodejs.yml
Enable Test_Ssrf_Telemetry for nodejs
> [nodejs] Enable Test_Ssrf_Telemetry

- manifests/java.yml
> [java] Enable e2e tests on all spring-boot variants

- docs/weblog/README.md
- utils/build/docker/dotnet/weblog/Controllers/IastController.cs
- utils/build/docker/dotnet/weblog/Endpoints/SetCookieEndpoint.cs
- utils/build/docker/java/akka-http/src/main/scala/com/datadoghq/akka_http/AppSecRoutes.scala
- utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/MyResource.java
- utils/build/docker/java/play/app/controllers/AppSecController.scala
- utils/build/docker/java/ratpack/src/main/java/com/datadoghq/ratpack/Main.java
- utils/build/docker/java/resteasy-netty3/src/main/java/com/datadoghq/resteasy/MyResource.java
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/App.java
- utils/build/docker/java/vertx3/src/main/java/com/datadoghq/vertx3/Main.java
- utils/build/docker/java/vertx4/src/main/java/com/datadoghq/vertx4/Main.java
- utils/build/docker/nodejs/express4-typescript/app.ts
- utils/build/docker/nodejs/express4/app.js
- utils/build/docker/python/django/app/urls.py
- utils/build/docker/python/fastapi/main.py
- utils/build/docker/python/flask/app.py
> Add a /set-cookie endpoint on flask and .NET weblog

- manifests/java.yml
- utils/build/docker/java/akka-http/src/main/scala/com/datadoghq/akka_http/AppSecRoutes.scala
- utils/build/docker/java/jersey-grizzly2/src/main/java/com/datadoghq/jersey/MyResource.java
- utils/build/docker/java/play/app/controllers/AppSecController.scala
- utils/build/docker/java/play/conf/routes
- utils/build/docker/java/ratpack/src/main/java/com/datadoghq/ratpack/Main.java
- utils/build/docker/java/resteasy-netty3/src/main/java/com/datadoghq/resteasy/MyResource.java
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/App.java
- utils/build/docker/java/vertx3/src/main/java/com/datadoghq/vertx3/Main.java
- utils/build/docker/java/vertx4/src/main/java/com/datadoghq/vertx4/Main.java
> [java] Enable Test_RemoteConfigurationExtraServices

- .dockerignore
Leaking in `binaries/**/.git/config`.
Don't copy `binaries/**/.git/config`
> Ignore binaries .git/config for docker image building

- utils/scripts/compute_impacted_scenario.py
- utils/scripts/get-nightly-logs.py
> Add script that get nightly logs

- manifests/java.yml
Original Java W3C Sampling Tag test was an XPass and needed to be enabled for full testing.
Enables the following test for Java:
`tests/parametric/test_trace_sampling.py::Test_Trace_Sampling_With_W3C::test_trace_sampled_by_trace_sampling_rule_tags`
Ticket Link: [APMAPI-651](https://datadoghq.atlassian.net/browse/APMAPI-651)
:rocket: Once your PR is reviewed, you can merge …
> [Java] Setting version for W3C Sampling Tag Test

- tests/parametric/test_dynamic_configuration.py
- utils/_context/_scenarios/parametric.py
- utils/build/docker/dotnet/parametric/ApmTestApi.csproj
- utils/build/docker/dotnet/parametric/Endpoints/ApmTestApi.cs
- utils/build/docker/dotnet/parametric/Endpoints/ApmTestApiOtel.cs
- utils/build/docker/dotnet/weblog/app.csproj
> [dotnet] Adapt weblog/parametric to 3.2 release

- manifests/python.yml
- tests/appsec/iast/source/test_body.py
- utils/build/docker/python/django/app/urls.py
- utils/build/docker/python/flask/app.py
> [python] Code Security: body source

- conftest.py
- docs/edit/from-scratch.md
- tests/appsec/test_automated_login_events.py
- tests/auto_inject/utils.py
- tests/test_the_test/test_docker_scenario.py
- utils/_context/_scenarios/__init__.py
- utils/_context/_scenarios/auto_injection.py
- utils/_context/_scenarios/core.py
- utils/_context/_scenarios/endtoend.py
- utils/_context/_scenarios/k8s_lib_injection.py
- utils/_context/_scenarios/open_telemetry.py
- utils/_context/_scenarios/parametric.py
- utils/_context/_scenarios/performance.py
- utils/_context/containers.py
- utils/_context/core.py
> Clean a little bit Scenario API

- tests/parametric/test_otel_span_methods.py
Appendix to #2841 skip this test as it's failing on .NET
> [dotnet] Skip test_otel_record_exception_sets_all_error_tracking_tags

- tests/debugger/test_debugger_expression_language.py
- tests/debugger/test_debugger_probe_snapshot.py
> [Debugger] Release some bugs

- manifests/java.yml
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/App.java
- utils/build/docker/java/spring-boot/src/main/java/com/datadoghq/system_tests/springboot/rasp/RaspController.java
We need enabled all Exploit prevention tests
Missing RRASP SSRF tests for Java in Springboot
> [Java] SSRF tests for Springboot

- utils/build/docker/python_otel/flask-poc-otel.Dockerfile
> Fix python otel integrations

- conftest.py
- docs/execute/strict-missing-features.md
- tests/test_the_test/test_force_option.py
- tests/test_the_test/test_strict.py
- tests/test_the_test/utils.py
- utils/_decorators.py
> Add --strict-missing-features option

- docs/execute/run.md
Found some path that could show the new directory so it can be easily copy pastable.
Adding the new folder on the path.
> Update run.md based on new directory

- utils/build/docker/java/spring-boot/pom.xml
> [java] Pin the OpenTelemetry version to 1.41.0

- utils/_context/containers.py
- utils/build/build.sh
Fix spelling and grammar in the text/messages.
Fix spelling and grammar in the text/messages.
> Spelling & grammar fixes

- .github/CODEOWNERS
- utils/scripts/compute_impacted_scenario.py
> Removes system-tests-core form owners of manifests

- .github/workflows/run-docker-ssi.yml
- utils/docker_ssi/docker_ssi_matrix_builder.py
Current arm runner is deprecated. Update it
> Update arm runner

- tests/integrations/crossed_integrations/test_kinesis.py
- tests/integrations/crossed_integrations/test_sns_to_sqs.py
- tests/integrations/crossed_integrations/test_sqs.py
- tests/integrations/test_dsm.py
Secrets has not been populated to all repos, everything is brokken.
skipping the test.
> Temporary skip AWS tests

- manifests/dotnet.yml
- manifests/python.yml
- tests/appsec/rasp/test_lfi.py
- tests/appsec/rasp/utils.py
There is no coverage until now for RASP + RC + action customisation.
Add a test to check for this combination of features.
> new test for RASP + Remote Configuration + action customization

- tests/debugger/utils.py
- tests/test_schemas.py
> [nodejs] Skip failing debugger test

- tests/parametric/test_config_consistency.py
- utils/_context/_scenarios/parametric.py
Green CI
Per title
cc @zacharycmontoya 
> [php] Partial revert of #3012

- manifests/php.yml
- tests/parametric/test_sampling_span_tags.py
- tests/parametric/test_span_sampling.py
- tests/parametric/test_tracer_flare.py
- tests/test_sampling_rates.py
- tests/test_semantic_conventions.py
- utils/build/docker/php/parametric/server.php
> [php] Update tests

- .github/workflows/run-docker-ssi.yml
- utils/scripts/compute_impacted_scenario.py
Stop on the failing step
per title
> [SSI] Do not run if some build step fails

- docs/scenarios/parametric.md
adding instructions on how to update proto files in parametric readme
> update readme to add proto steps

- docs/scenarios/parametric.md
Fixed small typo and improve wording in our instructions.
Fixed typo in "git checkout" command
Minor improvement to wording
> Fix typo in parametric.md

- tests/test_telemetry.py
> [java] skip failing test for APMAPI-723

- manifests/java.yml
- pyproject.toml
Following #3034, get ticket for bug declaration
Per title
> [java] Flag bug declaration with ticket APPSEC-54966

- tests/parametric/test_crashtracking.py
> Skip test for APMAPI-727, slightly better test logic

- tests/integrations/test_dbm.py
> [python] skip other test failing because of APMAPI-724

- .github/workflows/run-lib-injection.yml
> Slightly better workflow for lib-injection

- .github/actions/install_runner/action.yaml
- .github/workflows/ci.yml
> Remove legacy check on python 3.9

- manifests/python.yml
- manifests/ruby.yml
- pyproject.toml
> [python] report bug declaration to JIRA

- .github/actions/pull_images/action.yml
- .github/workflows/run-end-to-end.yml
> Log to docker hub to prevent reaching limits

- manifests/golang.yml
- tests/appsec/test_remote_config_rule_changes.py
- tests/test_schemas.py
- utils/build/docker/golang/app/chi/main.go
- utils/build/docker/golang/app/echo/main.go
- utils/build/docker/golang/app/gin/main.go
- utils/build/docker/golang/app/internal/common/common.go
- utils/build/docker/golang/app/net-http/main.go
Enable more APPSEC_RUNTIME_ACTIVATION tests
> [golang] Enable more RC tests
